### ISSUE TITLE
Protobuf parsing failed - model fails

### ISSUE THREAD

**Issue by Jordan-Bowman-Davis** [hacksider/Deep-Live-Cam#10]
The `inswapper_128_fp16.onnx` model is invalid. This can be checked with 
```
import onnx
onnx_model = onnx.load("inswapper_128_fp16.onnx")
onnx.checker.check_model(onnx_model)
```
I solved this by adjusting `faceswapper.py` and just using the standard `inswapper_128.onnx` model [here](https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128.onnx?download=true)

**Comment by hacksider** [comment]
Let me check on this, the inswapper_128_fp16.onnx should be faster than the old one but I believe it's not downloading on your end (you can manually download it as well based on the instruction)

Thanks for the report though! Will check on this later when I get home.

**Comment by Jordan-Bowman-Davis** [comment]
I managed to get it working. Re-downloaded [from here](https://github.com/Hillobar/Rope/releases/download/Crystal_Shard/models.zip). Seems to be working, even though it does not pass the onnx check
