### ISSUE TITLE
Segmentation fault on M1 Mac

### ISSUE THREAD

**Issue by ivdorelian** [hacksider/Deep-Live-Cam#103]
<img width="197" alt="image" src="https://github.com/user-attachments/assets/94191725-124c-4549-9fd9-0974af73a75e">

After a few seconds a segmentation fault error shows up.

```
% python run.py --execution-provider coreml

zsh: segmentation fault  python run.py --execution-provider coreml
```

The same happens with just `python run.py`

Due to the fact that I was getting an `illegal hardware instruction` error with tensorflow installed by `pip install tensorflow`, I had to replace that with `pip install tensorflow-macos`.

**Comment by peterzyk** [comment]
你解决这个问题了嘛，我也是 m1

**Comment by peterzyk** [comment]
我的程序已经成功跑起来了，没有遇到你这个问题

**Comment by olololoe110399** [comment]
@peterzyk Hi, how can you fix it?

**Comment by adamzachyang** [comment]
@olololoe110399 I ran into the same issue of `illegal hardware instruction`. Fixed by a `python3 -m pip install --upgrade pip` followed by `pip install tensorflow-macos`.

**Comment by jasonkneen** [comment]
https://github.com/jasonkneen/Deep-Live-Cam.git updated with optimisations -- will submit a PR
