### ISSUE TITLE
Created Installation Video of Deep Live Cam for Windows

### ISSUE THREAD

**Issue by fahdmirza** [hacksider/Deep-Live-Cam#106]
Hi Team,
   I hope you don't mind me sharing as I am very excited to share this step-by-step installation video of your awesome tool :

https://youtu.be/MICScLVM1x8?si=gRMEyB26CYrKat9r

Thanks.

Fahd

**Comment by hacksider** [comment]
I really appreciated the installation video but please put this in the discussion as this is not an issue. Thanks!
