### ISSUE TITLE
ERROR: Cannot install -r requirements.txt (line 13), -r requirements.txt (line 17), -r requirements.txt (line 4), -r requirements.txt (line 5), -r requirements.txt (line 6) and numpy==1.23.5 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by marsonal2023** [hacksider/Deep-Live-Cam#107]
ERROR: Cannot install -r requirements.txt (line 13), -r requirements.txt (line 17), -r requirements.txt (line 4), -r requirements.txt (line 5), -r requirements.txt (line 6) and numpy==1.23.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.23.5
    opencv-python 4.8.1.78 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python 4.8.1.78 depends on numpy>=1.23.5; python_version >= "3.11"
    opencv-python 4.8.1.78 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python 4.8.1.78 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python 4.8.1.78 depends on numpy>=1.19.3; python_version >= "3.9"
    onnx 1.16.0 depends on numpy>=1.20
    insightface 0.7.3 depends on numpy
    torchvision 0.15.2+cu118 depends on numpy
    onnxruntime-gpu 1.18.0 depends on numpy>=1.26.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by JuanTamadski** [comment]
I changed the onnxruntime-gpu from 1.18 to 1.17 and it proceeded

**Comment by d-hain** [comment]
> I changed the onnxruntime-gpu from 1.18 to 1.17 and it proceeded

sadly that fix didn't work for me
removing the numpy version also didn't change anything.

I am running Windows 10 22H2 19045.4651
I am not a python dev sadly so i have no idea how to fix this

**Comment by marsonal2023** [comment]
i managed to install it using claude it fixed the requirements.txt versions for me but after i opened the app i cant get it to use cuda on my gpu it gives error

**Comment by Man-Dark** [comment]
I am using Windows 11. I solved it by editing the requirements file in the folder. just replace these specific two lines of "numpy" and "onnxruntime-gpu" with the following lines and save the document and try installing the requirements again:

numpy>=1.23.5,<1.27

onnxruntime-gpu>=1.18.0,<1.27; sys_platform != 'darwin'

**Comment by Lorban90** [comment]
after i edited the requirements  it dosent gave me the error with numpy
but now at the end he is not loading through the last step in the attached code
need help :x

` Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow: markers 'sys_platform == "darwin"' don't match your environment
Collecting numpy<1.27,>=1.23.5 (from -r requirements.txt (line 3))
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Collecting opencv-python==4.8.1.78 (from -r requirements.txt (line 4))
  Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting onnx==1.16.0 (from -r requirements.txt (line 5))
  Using cached onnx-1.16.0-cp311-cp311-win_amd64.whl.metadata (16 kB)
Collecting insightface==0.7.3 (from -r requirements.txt (line 6))
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting psutil==5.9.8 (from -r requirements.txt (line 7))
  Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl.metadata (22 kB)
Collecting tk==0.1.0 (from -r requirements.txt (line 8))
  Using cached tk-0.1.0-py3-none-any.whl.metadata (693 bytes)
Collecting customtkinter==5.2.2 (from -r requirements.txt (line 9))
  Using cached customtkinter-5.2.2-py3-none-any.whl.metadata (677 bytes)
Collecting pillow==9.5.0 (from -r requirements.txt (line 10))
  Using cached Pillow-9.5.0-cp311-cp311-win_amd64.whl.metadata (9.7 kB)
Collecting torch==2.0.1+cu118 (from -r requirements.txt (line 11))
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp311-cp311-win_amd64.whl (2619.2 MB)
Collecting torchvision==0.15.2+cu118 (from -r requirements.txt (line 13))
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp311-cp311-win_amd64.whl (4.9 MB)
Collecting onnxruntime-gpu<1.27,>=1.18.0 (from -r requirements.txt (line 17))
  Using cached onnxruntime_gpu-1.19.0-cp311-cp311-win_amd64.whl.metadata (4.5 kB)
Collecting tensorflow==2.12.1 (from -r requirements.txt (line 19))
  Using cached tensorflow-2.12.1-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting opennsfw2==0.10.2 (from -r requirements.txt (line 20))
  Using cached opennsfw2-0.10.2-py3-none-any.whl.metadata (11 kB)
Collecting protobuf==4.23.2 (from -r requirements.txt (line 21))
  Using cached protobuf-4.23.2-cp310-abi3-win_amd64.whl.metadata (540 bytes)
Collecting tqdm==4.66.4 (from -r requirements.txt (line 22))
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
Collecting gfpgan==1.3.8 (from -r requirements.txt (line 23))
  Using cached gfpgan-1.3.8-py3-none-any.whl.metadata (12 kB)
Collecting requests (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting matplotlib (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached matplotlib-3.9.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting scipy (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached scipy-1.14.0-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting scikit-learn (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached scikit_learn-1.5.1-cp311-cp311-win_amd64.whl.metadata (12 kB)
Collecting scikit-image (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached scikit_image-0.24.0-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting easydict (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached easydict-1.13-py3-none-any.whl.metadata (4.2 kB)
Collecting cython (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached Cython-3.0.11-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
Collecting albumentations (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached albumentations-1.4.14-py3-none-any.whl.metadata (38 kB)
Collecting prettytable (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached prettytable-3.11.0-py3-none-any.whl.metadata (30 kB)
Collecting darkdetect (from customtkinter==5.2.2->-r requirements.txt (line 9))
  Using cached darkdetect-0.8.0-py3-none-any.whl.metadata (3.6 kB)
Collecting packaging (from customtkinter==5.2.2->-r requirements.txt (line 9))
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting filelock (from torch==2.0.1+cu118->-r requirements.txt (line 11))
  Using cached filelock-3.15.4-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions (from torch==2.0.1+cu118->-r requirements.txt (line 11))
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch==2.0.1+cu118->-r requirements.txt (line 11))
  Using cached sympy-1.13.2-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.0.1+cu118->-r requirements.txt (line 11))
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Collecting jinja2 (from torch==2.0.1+cu118->-r requirements.txt (line 11))
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting tensorflow-intel==2.12.1 (from tensorflow==2.12.1->-r requirements.txt (line 19))
  Using cached tensorflow_intel-2.12.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting gdown>=4.2.0 (from opennsfw2==0.10.2->-r requirements.txt (line 20))
  Using cached gdown-5.2.0-py3-none-any.whl.metadata (5.8 kB)
Collecting colorama (from tqdm==4.66.4->-r requirements.txt (line 22))
  Using cached https://download.pytorch.org/whl/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting basicsr>=1.4.2 (from gfpgan==1.3.8->-r requirements.txt (line 23))
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... \ `

**Comment by silence-tang** [comment]
Hi 

> after i edited the requirements it dosent gave me the error with numpy but now at the end he is not loading through the last step in the attached code need help :x
> 
> > Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
> > Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
> > Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
> > Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
> > Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
> > Ignoring tensorflow: markers 'sys_platform == "darwin"' don't match your environment
> > Collecting numpy<1.27,>=1.23.5 (from -r requirements.txt (line 3))
> > Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
> > Collecting opencv-python==4.8.1.78 (from -r requirements.txt (line 4))
> > Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
> > Collecting onnx==1.16.0 (from -r requirements.txt (line 5))
> > Using cached onnx-1.16.0-cp311-cp311-win_amd64.whl.metadata (16 kB)
> > Collecting insightface==0.7.3 (from -r requirements.txt (line 6))
> > Using cached insightface-0.7.3.tar.gz (439 kB)
> > Installing build dependencies ... done
> > Getting requirements to build wheel ... done
> > Preparing metadata (pyproject.toml) ... done
> > Collecting psutil==5.9.8 (from -r requirements.txt (line 7))
> > Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl.metadata (22 kB)
> > Collecting tk==0.1.0 (from -r requirements.txt (line 8))
> > Using cached tk-0.1.0-py3-none-any.whl.metadata (693 bytes)
> > Collecting customtkinter==5.2.2 (from -r requirements.txt (line 9))
> > Using cached customtkinter-5.2.2-py3-none-any.whl.metadata (677 bytes)
> > Collecting pillow==9.5.0 (from -r requirements.txt (line 10))
> > Using cached Pillow-9.5.0-cp311-cp311-win_amd64.whl.metadata (9.7 kB)
> > Collecting torch==2.0.1+cu118 (from -r requirements.txt (line 11))
> > Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp311-cp311-win_amd64.whl (2619.2 MB)
> > Collecting torchvision==0.15.2+cu118 (from -r requirements.txt (line 13))
> > Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp311-cp311-win_amd64.whl (4.9 MB)
> > Collecting onnxruntime-gpu<1.27,>=1.18.0 (from -r requirements.txt (line 17))
> > Using cached onnxruntime_gpu-1.19.0-cp311-cp311-win_amd64.whl.metadata (4.5 kB)
> > Collecting tensorflow==2.12.1 (from -r requirements.txt (line 19))
> > Using cached tensorflow-2.12.1-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
> > Collecting opennsfw2==0.10.2 (from -r requirements.txt (line 20))
> > Using cached opennsfw2-0.10.2-py3-none-any.whl.metadata (11 kB)
> > Collecting protobuf==4.23.2 (from -r requirements.txt (line 21))
> > Using cached protobuf-4.23.2-cp310-abi3-win_amd64.whl.metadata (540 bytes)
> > Collecting tqdm==4.66.4 (from -r requirements.txt (line 22))
> > Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
> > Collecting gfpgan==1.3.8 (from -r requirements.txt (line 23))
> > Using cached gfpgan-1.3.8-py3-none-any.whl.metadata (12 kB)
> > Collecting requests (from insightface==0.7.3->-r requirements.txt (line 6))
> > Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
> > Collecting matplotlib (from insightface==0.7.3->-r requirements.txt (line 6))
> > Using cached matplotlib-3.9.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
> > Collecting scipy (from insightface==0.7.3->-r requirements.txt (line 6))
> > Using cached scipy-1.14.0-cp311-cp311-win_amd64.whl.metadata (60 kB)
> > Collecting scikit-learn (from insightface==0.7.3->-r requirements.txt (line 6))
> > Using cached scikit_learn-1.5.1-cp311-cp311-win_amd64.whl.metadata (12 kB)
> > Collecting scikit-image (from insightface==0.7.3->-r requirements.txt (line 6))
> > Using cached scikit_image-0.24.0-cp311-cp311-win_amd64.whl.metadata (14 kB)
> > Collecting easydict (from insightface==0.7.3->-r requirements.txt (line 6))
> > Using cached easydict-1.13-py3-none-any.whl.metadata (4.2 kB)
> > Collecting cython (from insightface==0.7.3->-r requirements.txt (line 6))
> > Using cached Cython-3.0.11-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
> > Collecting albumentations (from insightface==0.7.3->-r requirements.txt (line 6))
> > Using cached albumentations-1.4.14-py3-none-any.whl.metadata (38 kB)
> > Collecting prettytable (from insightface==0.7.3->-r requirements.txt (line 6))
> > Using cached prettytable-3.11.0-py3-none-any.whl.metadata (30 kB)
> > Collecting darkdetect (from customtkinter==5.2.2->-r requirements.txt (line 9))
> > Using cached darkdetect-0.8.0-py3-none-any.whl.metadata (3.6 kB)
> > Collecting packaging (from customtkinter==5.2.2->-r requirements.txt (line 9))
> > Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
> > Collecting filelock (from torch==2.0.1+cu118->-r requirements.txt (line 11))
> > Using cached filelock-3.15.4-py3-none-any.whl.metadata (2.9 kB)
> > Collecting typing-extensions (from torch==2.0.1+cu118->-r requirements.txt (line 11))
> > Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
> > Collecting sympy (from torch==2.0.1+cu118->-r requirements.txt (line 11))
> > Using cached sympy-1.13.2-py3-none-any.whl.metadata (12 kB)
> > Collecting networkx (from torch==2.0.1+cu118->-r requirements.txt (line 11))
> > Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
> > Collecting jinja2 (from torch==2.0.1+cu118->-r requirements.txt (line 11))
> > Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
> > Collecting tensorflow-intel==2.12.1 (from tensorflow==2.12.1->-r requirements.txt (line 19))
> > Using cached tensorflow_intel-2.12.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
> > Collecting gdown>=4.2.0 (from opennsfw2==0.10.2->-r requirements.txt (line 20))
> > Using cached gdown-5.2.0-py3-none-any.whl.metadata (5.8 kB)
> > Collecting colorama (from tqdm==4.66.4->-r requirements.txt (line 22))
> > Using cached https://download.pytorch.org/whl/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
> > Collecting basicsr>=1.4.2 (from gfpgan==1.3.8->-r requirements.txt (line 23))
> > Using cached basicsr-1.4.2.tar.gz (172 kB)
> > Installing build dependencies ... done
> > Getting requirements to build wheel ... done
> > Installing backend dependencies ... \

Hi, did you solve it? I am also stuck there, need help!
