### ISSUE TITLE
Please Share Hardware and Sample Image Specs used to produce the Demo Live Stream Quality Results

### ISSUE THREAD

**Issue by shaneholloman** [hacksider/Deep-Live-Cam#109]
I have this working fine on Windows 11

```powershell
  shane @ moa ❯ ~ nvidia-smi
Sat Aug 10 14:09:33 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti   WDDM  |   00000000:21:00.0  On |                  N/A |
| 41%   47C    P2             78W /  260W |    4771MiB /  11264MiB |     36%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

However, nothing remotely close your wonderful results. you have a great framerate, resolution, smile with teeth works (not near as good for me)

What: 
- GPU
- Camera
- sample image specs:
    - codec
    - size
    - any other pertinent specs
- command flags used as runtime

**Comment by Fakamoto** [comment]
This!

I tried on my m3 macbook, super slow, and very low fps. Guess you need a super GPU

**Comment by Rolandjg** [comment]
It is very slow on a 3060 with 12gb vram, would like to know the hardware used for the demo vid

**Comment by theoldsong** [comment]
> It is very slow on a 3060 with 12gb vram, would like to know the hardware used for the demo vid

My 3090 and 4080s are both very slow.

**Comment by hacksider** [comment]
For my demo, I am using Windows. I'm using 3080. But I believe you only need 6GB VRAM to use it properly
![image](https://github.com/user-attachments/assets/f66e39cd-5909-4629-ba53-710518d3b2b5)

For the CPU, it's not really taking much toll on my end.
![image](https://github.com/user-attachments/assets/319d551e-e52c-466f-bbcc-a0285c00aaf5)


I am also not using the face enhancer during live.

**Comment by hacksider** [comment]
Please don't use face enhancer during live as it is not necessary as of this moment (it's post processing the image AFTER it is rendered thus giving more time to output). Performance will drop significantly. I just leave it there for future development (maybe with frame generation)

**Comment by Rolandjg** [comment]
interesting... my hardware is Intel i7-9700F with a rtx 3060 on fedora linux and the cpu is at 99%, no face enhancer. The camera is 720x512

**Comment by hacksider** [comment]
You might not be using the gpu version, please follow the other instructions as well
![image](https://github.com/user-attachments/assets/fb3562c1-61bf-4ec8-ba86-52d991b7736d)
