### ISSUE TITLE
OpenCV: camera failed to properly initialize!

### ISSUE THREAD

**Issue by wangbooth** [hacksider/Deep-Live-Cam#112]
MacBook M1 Pro
macOS Sonoma 14.5

When using Live mode, errors may occur:

```
OpenCV: not authorized to capture video (status 0), requesting...
OpenCV: camera failed to properly initialize!
```

If you are using Termius or another terminal to run run.py, it is possible to encounter this issue. Please switch to using macOS’s native Terminal.app to run it.

**Comment by RoversX** [comment]
> MacBook M1 Pro macOS Sonoma 14.5
> 
> When using Live mode, errors may occur:
> 
> ```
> OpenCV: not authorized to capture video (status 0), requesting...
> OpenCV: camera failed to properly initialize!
> ```
> 
> If you are using Termius or another terminal to run run.py, it is possible to encounter this issue. Please switch to using macOS’s native Terminal.app to run it.

Using native Terminal.app, still have the problem.

```bash
2024-08-10 15:49:40.844 Python[5375:81665] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
OpenCV: out device of bound (0-2): 3
OpenCV: camera failed to properly initialize!

```

<img width="682" alt="Screenshot 2024-08-10 at 3 49 54 PM" src="https://github.com/user-attachments/assets/d7fcbb12-9913-49f6-b9c6-07c63fa7fe32">

M1 Pro 
14.6.1

**Comment by laloe74** [comment]
> > MacBook M1 Pro macOS Sonoma 14.5
> > When using Live mode, errors may occur:
> > ```
> > OpenCV: not authorized to capture video (status 0), requesting...
> > OpenCV: camera failed to properly initialize!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you are using Termius or another terminal to run run.py, it is possible to encounter this issue. Please switch to using macOS’s native Terminal.app to run it.
> 
> Using native Terminal.app, still have the problem.
> 
> ```shell
> 2024-08-10 15:49:40.844 Python[5375:81665] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
> OpenCV: out device of bound (0-2): 3
> OpenCV: camera failed to properly initialize!
> ```
> 
> <img alt="Screenshot 2024-08-10 at 3 49 54 PM" width="682" src="https://private-user-images.githubusercontent.com/85817538/356791778-d7fcbb12-9913-49f6-b9c6-07c63fa7fe32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjk0NDIsIm5iZiI6MTcyMzI2OTE0MiwicGF0aCI6Ii84NTgxNzUzOC8zNTY3OTE3NzgtZDdmY2JiMTItOTkxMy00OWY2LWI5YzYtMDdjNjNmYTdmZTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA1NTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDAyZGE5NjJiNjg0YWVjNTRkNmIxOGRiMDdiY2EzYjI3YzBmMzllMDk0NDJmN2RkYWVjNTFhODJmZjNiMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0euYrRbsJjlrQHRElOCmmLdjncBHrVTqawyxewrel6A">
> M1 Pro 14.6.1

same

**Comment by RoversX** [comment]
> > > MacBook M1 Pro macOS Sonoma 14.5
> > > When using Live mode, errors may occur:
> > > ```
> > > OpenCV: not authorized to capture video (status 0), requesting...
> > > OpenCV: camera failed to properly initialize!
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If you are using Termius or another terminal to run run.py, it is possible to encounter this issue. Please switch to using macOS’s native Terminal.app to run it.
> > 
> > 
> > Using native Terminal.app, still have the problem.
> > ```shell
> > 2024-08-10 15:49:40.844 Python[5375:81665] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
> > OpenCV: out device of bound (0-2): 3
> > OpenCV: camera failed to properly initialize!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="Screenshot 2024-08-10 at 3 49 54 PM" width="682" src="https://private-user-images.githubusercontent.com/85817538/356791778-d7fcbb12-9913-49f6-b9c6-07c63fa7fe32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjk0NDIsIm5iZiI6MTcyMzI2OTE0MiwicGF0aCI6Ii84NTgxNzUzOC8zNTY3OTE3NzgtZDdmY2JiMTItOTkxMy00OWY2LWI5YzYtMDdjNjNmYTdmZTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA1NTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDAyZGE5NjJiNjg0YWVjNTRkNmIxOGRiMDdiY2EzYjI3YzBmMzllMDk0NDJmN2RkYWVjNTFhODJmZjNiMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0euYrRbsJjlrQHRElOCmmLdjncBHrVTqawyxewrel6A">
> > M1 Pro 14.6.1
> 
> same

Solved, you may need to change this
<img width="522" alt="Screenshot 2024-08-10 at 3 56 18 PM" src="https://github.com/user-attachments/assets/897fcda8-914e-4700-9a16-482aaf0703ef">

**Comment by laloe74** [comment]
> > > > MacBook M1 Pro macOS Sonoma 14.5
> > > > When using Live mode, errors may occur:
> > > > ```
> > > > OpenCV: not authorized to capture video (status 0), requesting...
> > > > OpenCV: camera failed to properly initialize!
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > If you are using Termius or another terminal to run run.py, it is possible to encounter this issue. Please switch to using macOS’s native Terminal.app to run it.
> > > 
> > > 
> > > Using native Terminal.app, still have the problem.
> > > ```shell
> > > 2024-08-10 15:49:40.844 Python[5375:81665] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
> > > OpenCV: out device of bound (0-2): 3
> > > OpenCV: camera failed to properly initialize!
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > <img alt="Screenshot 2024-08-10 at 3 49 54 PM" width="682" src="https://private-user-images.githubusercontent.com/85817538/356791778-d7fcbb12-9913-49f6-b9c6-07c63fa7fe32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjk0NDIsIm5iZiI6MTcyMzI2OTE0MiwicGF0aCI6Ii84NTgxNzUzOC8zNTY3OTE3NzgtZDdmY2JiMTItOTkxMy00OWY2LWI5YzYtMDdjNjNmYTdmZTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA1NTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDAyZGE5NjJiNjg0YWVjNTRkNmIxOGRiMDdiY2EzYjI3YzBmMzllMDk0NDJmN2RkYWVjNTFhODJmZjNiMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0euYrRbsJjlrQHRElOCmmLdjncBHrVTqawyxewrel6A">
> > > M1 Pro 14.6.1
> > 
> > 
> > same
> 
> Solved, you may need to change this <img alt="Screenshot 2024-08-10 at 3 56 18 PM" width="522" src="https://private-user-images.githubusercontent.com/85817538/356792046-897fcda8-914e-4700-9a16-482aaf0703ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjk3ODQsIm5iZiI6MTcyMzI2OTQ4NCwicGF0aCI6Ii84NTgxNzUzOC8zNTY3OTIwNDYtODk3ZmNkYTgtOTE0ZS00NzAwLTlhMTYtNDgyYWFmMDcwM2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA1NTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2M2Y1MDFmNWVjYzIxYjQzZTI5MjlhYzFlYTY5ZmJiNGRiMzBlYjBmOWY2ZjczOGUzNDVkY2NhNTJhNzk1NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u15CXD1a9ifEaqDw5lHKrRYZfRdAksONkdJufk1KKQM">
> 
> Super low fps lol

After reporting the error, there is just a blank window with nothing.

**Comment by wangbooth** [comment]
> > > > > MacBook M1 Pro macOS Sonoma 14.5
> > > > > When using Live mode, errors may occur:
> > > > > ```
> > > > > OpenCV: not authorized to capture video (status 0), requesting...
> > > > > OpenCV: camera failed to properly initialize!
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > If you are using Termius or another terminal to run run.py, it is possible to encounter this issue. Please switch to using macOS’s native Terminal.app to run it.
> > > > 
> > > > 
> > > > Using native Terminal.app, still have the problem.
> > > > ```shell
> > > > 2024-08-10 15:49:40.844 Python[5375:81665] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
> > > > OpenCV: out device of bound (0-2): 3
> > > > OpenCV: camera failed to properly initialize!
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > <img alt="Screenshot 2024-08-10 at 3 49 54 PM" width="682" src="https://private-user-images.githubusercontent.com/85817538/356791778-d7fcbb12-9913-49f6-b9c6-07c63fa7fe32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjk0NDIsIm5iZiI6MTcyMzI2OTE0MiwicGF0aCI6Ii84NTgxNzUzOC8zNTY3OTE3NzgtZDdmY2JiMTItOTkxMy00OWY2LWI5YzYtMDdjNjNmYTdmZTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA1NTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDAyZGE5NjJiNjg0YWVjNTRkNmIxOGRiMDdiY2EzYjI3YzBmMzllMDk0NDJmN2RkYWVjNTFhODJmZjNiMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0euYrRbsJjlrQHRElOCmmLdjncBHrVTqawyxewrel6A">
> > > > M1 Pro 14.6.1
> > > 
> > > 
> > > same
> > 
> > 
> > Solved, you may need to change this <img alt="Screenshot 2024-08-10 at 3 56 18 PM" width="522" src="https://private-user-images.githubusercontent.com/85817538/356792046-897fcda8-914e-4700-9a16-482aaf0703ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjk3ODQsIm5iZiI6MTcyMzI2OTQ4NCwicGF0aCI6Ii84NTgxNzUzOC8zNTY3OTIwNDYtODk3ZmNkYTgtOTE0ZS00NzAwLTlhMTYtNDgyYWFmMDcwM2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA1NTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2M2Y1MDFmNWVjYzIxYjQzZTI5MjlhYzFlYTY5ZmJiNGRiMzBlYjBmOWY2ZjczOGUzNDVkY2NhNTJhNzk1NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u15CXD1a9ifEaqDw5lHKrRYZfRdAksONkdJufk1KKQM">
> > Super low fps lol
> 
> After reporting the error, there is just a blank window with nothing.

restart

**Comment by MazenQ88** [comment]
for macOS 14.5 using M3 MacBook Pro I had to change the index for camera in ui.py and chose 1 for the index in line ~259 ==> "cap = cv2.VideoCapture(1)"

**Comment by laloe74** [comment]
I fix it

1. https://github.com/hacksider/Deep-Live-Cam/issues/80#issuecomment-2278248039
2. https://stackoverflow.com/questions/60469202/unable-to-install-tkinter-with-pyenv-pythons-on-macos/61879759#61879759
