### ISSUE TITLE
Blurry output

### ISSUE THREAD

**Issue by zennomi** [hacksider/Deep-Live-Cam#116]
<img width="409" alt="Screenshot 2024-08-10 130713" src="https://github.com/user-attachments/assets/b3db2099-0a36-45b4-9137-0687b3915c4d">

![output](https://github.com/user-attachments/assets/9bd7fa28-e508-4635-92d4-dd1692d1ada1)

The output's face area is blurry.
I tried with cpu, cuda providers, still got same issue.

On Windows 11, python 3.10.6.

**Comment by hacksider** [comment]
the face maximum size is just 128x128 which is the limit of the model. You can use "face enhancer" to improve it.

**Comment by zennomi** [comment]
> the face maximum size is just 128x128 which is the limit of the model. You can use "face enhancer" to improve it.

Same for the face image and target? Or just the face image?
