### ISSUE TITLE
error pip install -r requeriments.txt

### ISSUE THREAD

**Issue by xzy71** [hacksider/Deep-Live-Cam#122]
error: subprocess-exited-with-error    × pip subprocess to install backend dependencies did not run successfully.   │ exit code: 2   ╰─> [80 lines of output]       Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118       Collecting torch         Downloading https://download.pytorch.org/whl/cu118/torch-2.4.0%2Bcu118-cp310-cp310-win_amd64.whl (2692.5 MB)            -----------------------------            2.0/2.7 GB 2.4 MB/s eta 0:04:50       ERROR: Exception:       Traceback (most recent call last):         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher           yield         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read           data = self._fp_read(amt) if not fp_closed else b""         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read           return self._fp.read(amt) if amt is not None else self._fp.read()         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 102, in read           self.__buf.write(data)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 483, in func_wrapper           return func(*args, **kwargs)       OSError: [Errno 28] No space left on device        During handling of the above exception, another exception occurred:        Traceback (most recent call last):         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper           status = _inner_run()         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run           return self.run(options, args)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper           return func(self, options, args)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\commands\install.py", line 379, in run           requirement_set = resolver.resolve(         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve           result = self._result = resolver.resolve(         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve           state = resolution.resolve(requirements, max_rounds=max_rounds)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve           self._add_to_criteria(self.state.criteria, r, parent=None)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria           if not criterion.candidates:         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__           return bool(self._sequence)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__           return any(self)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>           return (c for c in iterator if id(c) not in self._incompatible_ids)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built           candidate = func()         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 186, in _make_candidate_from_link           base: Optional[BaseCandidate] = self._make_base_candidate_from_link(         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 232, in _make_base_candidate_from_link           self._link_candidate_cache[link] = LinkCandidate(         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__           super().__init__(         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__           self.dist = self._prepare()         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare           dist = self._prepare_distribution()         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution           return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement           return self._prepare_linked_requirement(req, parallel_builds)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\operations\prepare.py", line 598, in _prepare_linked_requirement           local_file = unpack_url(         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\operations\prepare.py", line 170, in unpack_url           file = get_http_url(         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\operations\prepare.py", line 111, in get_http_url           from_path, content_type = download(link, temp_dir.path)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\network\download.py", line 148, in __call__           for chunk in chunks:         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 55, in _rich_progress_bar           for chunk in iterable:         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_internal\network\utils.py", line 65, in response_chunks           for chunk in response.raw.stream(         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream           data = self.read(amt=amt, decode_content=decode_content)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read           with self._error_catcher():         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__           self.gen.throw(typ, value, traceback)         File "C:\Users\~~\AppData\Local\Programs\Python\Python310\Lib\site-packages\pip\_vendor\urllib3\response.py", line 455, in _error_catcher           raise ProtocolError("Connection broken: %r" % e, e)       pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: OSError(28, 'No space left on device')", OSError(28, 'No space left on device'))       [end of output]    note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error  × pip subprocess to install backend dependencies did not run successfully. │ exit code: 2 ╰─> See above for output.  note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by jasonkneen** [comment]
Same issue -- frustrating when readme instructions don't work and it's a new venv setup too!

**Comment by steinathan** [comment]
same issue 

```sh
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.18.0 (from -r requirements.txt (line 17)) (from versions: 1.10.0, 1.11.0, 1.11.1, 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime-gpu==1.18.0 (from -r requirements.txt (line 17))
```

**Comment by lbltavares** [comment]
> OSError(28, 'No space left on device')

It looks like your disk is full

**Comment by lbltavares** [comment]
I was having issues when I tried with python 3.11+
3.10 worked for me (I'm using [conda](https://conda.io/projects/conda/en/latest/user-guide/getting-started.html))

**Comment by xzy71** [comment]
I'll try, it went unnoticed in my eyes lol

**Comment by xzy71** [comment]
The problem is that I use an AMD card, so I don't know how I would do this

**Comment by JackySu** [comment]
it indicates I have no space left on my device though I pretty sure that I have 100gb+ free space, so you need to install dependencies manually like 
```shell
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
```

**Comment by xiaopang10** [comment]
> it indicates I have no space left on my device though I pretty sure that I have 100gb+ free space, so you need to install dependencies manually like
> 
> ```shell
> pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
> ```



> The problem is that I use an AMD card, so I don't know how I would do this



> it indicates I have no space left on my device though I pretty sure that I have 100gb+ free space, so you need to install dependencies manually like
> 
> ```shell
> pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
> ```

comrades help me!! how do i install all manualy? cant be with only that one long line @JackySu can it?

**Comment by mozillo** [comment]
```
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.18.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.18.0
```
on MacMini 2018

**Comment by mozillo** [comment]
> same issue
> 
> ```shell
> ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.18.0 (from -r requirements.txt (line 17)) (from versions: 1.10.0, 1.11.0, 1.11.1, 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
> ERROR: No matching distribution found for onnxruntime-gpu==1.18.0 (from -r requirements.txt (line 17))
> ```

try
```bash
conda install onnxruntime -c conda-forge
```

**Comment by TheZuna** [comment]
I was having issues. Despite being in venv default pip cache directory was on main full drive.
`set PIP_CACHE_DIR=D:\path\to\new\cache\dir`

**Comment by danloman** [comment]
I fixed my initial issue of it giving me a lengthy exception error by changing the venv to python 3.10 instead of 3.12 in the `pyvenv.cfg,` but then while running the pip install, it gave me an error saying my disk was full, which it isnt. `ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device`

**Comment by danloman** [comment]
> it indicates I have no space left on my device though I pretty sure that I have 100gb+ free space, so you need to install dependencies manually like
> 
> ```shell
> pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
> ```

If you initially run this, and run 'python run.py' a few times, you can do pip install [program] to whatever it says is missing
