### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'configure'

### ISSUE THREAD

**Issue by uicodee** [hacksider/Deep-Live-Cam#123]
status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'

**Comment by minisailboat** [comment]
You may need to install FFmpeg
![image](https://github.com/user-attachments/assets/5e538184-4e2f-4389-bd71-0699ca31779e)

**Comment by AlphaKh** [comment]
@uicodee Have you found a solution to the error?
I'm facing the same issue

**Comment by Jaie55** [comment]
If you're using Linux you should add ffmpeg to path.
If you're on Windows install it following this guide: https://phoenixnap.com/kb/ffmpeg-windows

**Comment by klssland** [comment]
I'm on macOS, which path? @Jaie55

**Comment by Jaie55** [comment]
Use `echo "$PATH"` and check if ffmpeg is there.
If not add the bin to it, for example, if the FFmpeg binary is in /Users/test/local, type:`export PATH=$PATH:/Users/test/Local`

**Comment by klssland** [comment]
when i install via pip3 it shows ffmpeg is in
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ffmpeg @Jaie55

**Comment by wowker** [comment]
install ffmpeg,i use homebrew install,brew install ffmpeg,fixed it

**Comment by 1574300748** [comment]
在core.py修改一下def pre_check() -> bool:
    if sys.version_info < (3, 9):
        update_status('Python version is not supported - please upgrade to 3.9 or higher.')
        return False
    # 手动指定ffmpeg的路径
    ffmpeg_path = "C:\\ffmpeg\\bin\\ffmpeg.exe"
    if not os.path.isfile(ffmpeg_path):
        update_status('ffmpeg is not installed.')
        return False
    return True
