### ISSUE TITLE
Core dependencies error for mac silicon

### ISSUE THREAD

**Issue by jasonkneen** [hacksider/Deep-Live-Cam#125]
Another issue, trying to uninstall the onnx runtime for Silicon Macs

```
pip install onnxruntime-silicon==1.13.1
WARNING: Skipping onnxruntime as it is not installed.
WARNING: Skipping onnxruntime-silicon as it is not installed.
ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon==1.13.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime-silicon==1.13.1
```

**Comment by jasonkneen** [comment]
installed with ` brew install onnxruntime` -- will see if this works...

**Comment by RoversX** [comment]
> Another issue, trying to uninstall the onnx runtime for Silicon Macs
> 
> ```
> pip install onnxruntime-silicon==1.13.1
> WARNING: Skipping onnxruntime as it is not installed.
> WARNING: Skipping onnxruntime-silicon as it is not installed.
> ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon==1.13.1 (from versions: none)
> ERROR: No matching distribution found for onnxruntime-silicon==1.13.1
> ```
try python3.10

**Comment by tad-swift** [comment]
> try python3.10

Yep, 3.10 worked for me.

**Comment by varna9000** [comment]
Do you have good performance on apple silicon? I have M1 and it's horribly choppy as if no acceleration is applied. I'm running it with `--execution-provider coreml`

**Comment by tad-swift** [comment]
> Do you have good performance on apple silicon? I have M1 and it's horribly choppy as if no acceleration is applied. I'm running it with `--execution-provider coreml`

I'm using M3 Pro with 18GB ram and I'm getting like 3fps in the camera

**Comment by RoversX** [comment]
> > Do you have good performance on apple silicon? I have M1 and it's horribly choppy as if no acceleration is applied. I'm running it with `--execution-provider coreml`
> 
> I'm using M3 Pro with 18GB ram and I'm getting like 3fps in the camera

That's fast, my M1 Pro is running less than 1fps...
