### ISSUE TITLE
How to increse fps if I have a GPU like 4090?

### ISSUE THREAD

**Issue by YanXiaoAI** [hacksider/Deep-Live-Cam#126]
how to set the code to increse fps? or there is a limitation? my 4090 only cost 60% to run this program

**Comment by WillHemmens** [comment]
Would love to know this too, I'm getting around 3 FPS with a 3090 Ti. When there is no face in shot, FPS increases alot.

**Comment by hacksider** [comment]
Don't use face enhancer, it'll improve a lot. And make sure you install the requirements for nvidia.
![image](https://github.com/user-attachments/assets/761f7de4-0996-4d37-8e96-408f18a5ce9c)
You only need 1 if there's multiple person in the video (same faces apply)
You only need 2 if you want to get NSFW

**Comment by WillHemmens** [comment]
Even without face enhancer I get low frames. I can see GPU memory and GPU usage when it's running and the CPU usage is far lower than on CPU only mode.

I just set the project up again from scratch and I get the same results, very low frames without face enhancer.

**Comment by hacksider** [comment]
I'm still finding ways to increase the fps but since this is post processing, the highest I can get is 13/15fps which is half of my webcam speed.

**Comment by WillHemmens** [comment]
Could you please advise what kind of system you are running it on?

Thanks and love the project. I have been waiting for something like this for a long time.

**Comment by hacksider** [comment]
my previous system where I created the demo is 8700k/1080ti/16GB RAM. What I'm currently using now have is 13700k/3080/32GB RAM.

So I can confidently say it runs good on my 6 years old hardware.

**Comment by WillHemmens** [comment]
I changed from using Camo to a real webcam and this resolved my issue.
