### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by GilgameshH0** [hacksider/Deep-Live-Cam#129]
when i click start, after selected input and output, i got error in console: site-packages\insightface\model_zoo\retinaface.py", line 211, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by GilgameshH0** [comment]
All good now, you just need to copy your photo/video and git folder into folder without unicode symbols, for example on C://myfolder

**Comment by ilanreuben** [comment]
Same problem, but I don't have unicode symbols in the path for the photo / video. Any clues on how to fix?

**Comment by ne1i** [comment]
same problem, even if every directory has no unicode symbols
