### ISSUE TITLE
Trouble with installing in MacOS

### ISSUE THREAD

**Issue by heliumsoft** [hacksider/Deep-Live-Cam#13]
Hello @hacksider 

I'm installing this App on my Macbook and have issues with installing GPU libraries (onnxruntime).  Tried installing dependencies for **CoreML Execution Provider (Apple Legacy)** and got this error message: 

```
ERROR: Could not find a version that satisfies the requirement onnxruntime-coreml==1.13.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime-coreml==1.13.1
```

Platform: 
CPU: 6-Core Intel Core i7
Firmware Date: 2020
2 GPUs:   
      1. AMD Radeon Pro 5300M (PCIe)
      2. Intel UHD Graphics 630 (built-in)
      
 Please let me know the solution for running the App via GPU.
 
 Thanks

**Comment by hacksider** [comment]
try this
`pip uninstall onnxruntime onnxruntime-coreml
pip install onnxruntime-coreml==1.13.1`

**Comment by sidsarasvati** [comment]
worked with ` python3 -m pip install onnxruntime`
