### ISSUE TITLE
HERE'S HOW TO FIX BLACK SQUARES IN PHOTOS AND VIDEOS

### ISSUE THREAD

**Issue by letho1608** [hacksider/Deep-Live-Cam#133]
Yeah, I run in virtual environment with below command and it works with my cpu.

pip uninstall onnxruntime 
pip uninstall onnxruntime-gpu 
pip uninstall onnxruntime-directml
pip install onnxruntime-directml==1.15.1
python run.py --execution-provider cpu

Good luck

**Comment by sonnguyenHT** [comment]
It didn't work with Mac M2

**Comment by letho1608** [comment]
> It didn't work with Mac M2

This method only applies on windows

**Comment by omathurin** [comment]
This worked. Thank you letho1608!

**Comment by letho1608** [comment]
> It didn't work with Mac M2

Mac M2 thì t không biết fix sao vì không có máy đó :V, t sửa trên window cách trên thì được

**Comment by minussign** [comment]
It's worked !!!! Thank you very much.

**Comment by purifluff** [comment]
it worked for me too!! thank you

**Comment by AquiGorka** [comment]
Because you are asking it to run with the cpu: `python run.py --execution-provider cpu` <- `--execution-provider cpu`, try a different provider.

**Comment by ANK789** [comment]
> onnxruntime-directml

Thanks，solved this problem!

**Comment by alexvndre0day** [comment]
thanks
