### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by SSalvadoRR-official** [hacksider/Deep-Live-Cam#137]
`RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

`

How can I fix that?

**Comment by hacksider** [comment]
It's really hard to answer this question without your hardware specs
