### ISSUE TITLE
Preview show nothing

### ISSUE THREAD

**Issue by Hotjeese** [hacksider/Deep-Live-Cam#14]
Hi,
First thanks for you project. 
I select a face then click live a popup show preview but there is nothing on it as you can see below. My webcam is working as i have tested it. Could you help me to resolve it ?

![Capture](https://github.com/hacksider/Deep-Live-Cam/assets/153913050/69253e6b-b2b5-478e-bea3-a799cf021fe8)

**Comment by hacksider** [comment]
Can you send the screenshot of the console? I believe it's more of the CUDA version issue

**Comment by CalvinKluk** [comment]
Same Here, how did you fix it?
