### ISSUE TITLE
Replacing only one face in the video

### ISSUE THREAD

**Issue by iDenisOK** [hacksider/Deep-Live-Cam#143]
Hi, can you give me a hint? 
I have 2 faces in my video, I want to change only one of them, how do I do it, because the many faces function has no effect whatsoever, both faces are changed with or without it.

**Comment by vic4key** [comment]
I have plan to contribute/improve the many faces function that users can assign the source face to target faces. It might satisfy your expectation.

**Comment by xiaoqdu** [comment]
Is this feature implemented in the latest version?

**Comment by hacksider** [comment]
Check face mapping feature
