### ISSUE TITLE
How should I "work with a venv to avoid issues"?

### ISSUE THREAD

**Issue by SSalvadoRR-official** [hacksider/Deep-Live-Cam#145]
Where can I launch it or download it or something? Previously I worked with PowerShell and cmd. I really want to aviod issues this time

**Comment by phattran1023** [comment]
I will assume that you are using Windows.
First you need to go to the root directory of the folder (after cloned it). Then run the command `python -m venv .venv` .
Then you active the venv by running `.venv\scripts/active`. 
![image](https://github.com/user-attachments/assets/583f4947-90f7-41bd-8002-26c85405c8d1)

If successful, it should show (venv) in the console.
And there you go, run the command to install requirements again.

**Comment by SSalvadoRR-official** [comment]
Thank yo uso much! It worked! You have a typo in second script, it should be  `venv\scripts\active`

You're my saviour. It finally works!
