### ISSUE TITLE
Why is this repo suddenly popular?

### ISSUE THREAD

**Issue by harrywenjie** [hacksider/Deep-Live-Cam#148]
As far as I understand this is just roop with live cam.     
What I don't understand is how can this repo get so popular today?     
It has been out for at least half a year. Can someone tell me why?

**Comment by noteMASTER11** [comment]
It's because of the Medium news hype I suppose. I'm here because of them. Lots of another websites copypasted this repo ~ 20 h ago.

**Comment by SSalvadoRR-official** [comment]
You can spot a lot of russians here because some popular telegram channels (like Pekarnya - 720k subs and CyberTopor - 1.6 mil subs) found this repo and decided to share

Now everybody is struggling to install it

**Comment by varna9000** [comment]
twitter

**Comment by RoversX** [comment]
𝕏

**Comment by MAFiA303** [comment]
I'm here from reddit

**Comment by hacksider** [comment]
I don't know myself, but then again, will close this as this is not an issue. You can continue this on the discussion :)
