### ISSUE TITLE
openvino not working

### ISSUE THREAD

**Issue by Kitopvibe1** [hacksider/Deep-Live-Cam#15]
(base) (venv) C:\Users\DELL\Deep-Live-Cam>python run.py --execution-provider openvino
usage: run.py [-h] [-s SOURCE_PATH] [-t TARGET_PATH] [-o OUTPUT_PATH]
              [--frame-processor {face_swapper,face_enhancer} [{face_swapper,face_enhancer} ...]] [--keep-fps] [--keep-audio] [--keep-frames]
              [--many-faces] [--video-encoder {libx264,libx265,libvpx-vp9}] [--video-quality [0-51]] [--max-memory MAX_MEMORY]
              [--execution-provider {azure,cpu} [{azure,cpu} ...]] [--execution-threads EXECUTION_THREADS] [-v]
run.py: error: argument --execution-provider: invalid choice: 'openvino' (choose from 'azure', 'cpu')

**Comment by hacksider** [comment]
try using cpu on the argument
