### ISSUE TITLE
Frame processor face_enhancer not found

### ISSUE THREAD

**Issue by TrustAI-laboratory** [hacksider/Deep-Live-Cam#154]
<img width="338" alt="image" src="https://github.com/user-attachments/assets/89883d52-60d0-4bf7-8279-d5673143e007">
![image](https://github.com/user-attachments/assets/21a3bc21-67ed-490b-a168-561926e242fa)
something wrong?

**Comment by vlednerk** [comment]
same "Frame processor face_enhancer not found"

**Comment by Joeycan2** [comment]
same here having black box on webcam, with face_enhancer not found.

**Comment by Joeycan2** [comment]
same here having black box on webcam, with face_enhancer not found.
I tried python run.py --execution-provider dml
and python run.py --execution-provider cpu
just a black box around my face. Also the convert option not working either. 

So what's the face_enhancer module?

**Comment by davideuler** [comment]
It show "Frame processor face_enhancer not found" when running on mac silicon. And an empty interface shows on the GUI.

```
python run.py --execution-provider coreml
```

**Comment by andreashen** [comment]
In my case, i didn't install **gfpgan** properly at first.

> pip install gfpgan==1.3.8
 
and if you cannot find **tb-nightly**, (some college mirror sites would not include this lib)
Just change your pypi mirror (e.g. aliyun)

**Comment by Samwellwang** [comment]
https://github.com/hacksider/Deep-Live-Cam/issues/162#issuecomment-2282640935  can help you

**Comment by TrustAI-laboratory** [comment]
Thanks all.

And I finally found that it occurred by inswapper_128_fp16.onnx file in models. When I changed it to another model file in a different resource (https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx), It resolved!
