### ISSUE TITLE
dont running

### ISSUE THREAD

**Issue by leamow51** [hacksider/Deep-Live-Cam#158]
Guys, I need help
PS C:\Windows\system32\Deep-Live-Cam> python run.py
Python
PS C:\Windows\system32\Deep-Live-Cam>
PS C:\Windows\system32\Deep-Live-Cam> python run.py
Python
PS C:\Windows\system32\Deep-Live-Cam>
shell constantly outputs "Python"

**Comment by hacksider** [comment]
Have you followed all the installation procedure?

**Comment by burdukow** [comment]
This is default placeholder for python package in MS CMD/PS. you need to install/reinstall python and make sure that you add python to PATH.

**Comment by leamow51** [comment]
> Have you followed all the installation procedure?

absolutely

**Comment by leamow51** [comment]
> This is default placeholder for python package in MS CMD/PS. you need to install/reinstall python and make sure that you add python to PATH.
i added python to path

**Comment by IrfanKpm** [comment]
> > This is default placeholder for python package in MS CMD/PS. you need to install/reinstall python and make sure that you add python to PATH.
> > i added python to path
Could you please paste or upload a screenshot of the issue you're facing? It will help to understand the problem better

**Comment by burdukow** [comment]
> i added python to path

Please make sure, that python is in PATH, if not add it manualy OR reinstall python OR install it from MS Store, if possible
