### ISSUE TITLE
'Nonetype' object has no attribute 'configure'/ffmpeg not installed but IS installed

### ISSUE THREAD

**Issue by vomitwolf** [hacksider/Deep-Live-Cam#159]
warnings.warn(msg, RuntimeWarning)
[DLC.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "/Users/vomitwolf/Deep-Live-Cam/run.py", line 6, in <module>
    core.run()
  File "/Users/vomitwolf/Deep-Live-Cam/modules/core.py", line 237, in run
    if not pre_check():
           ^^^^^^^^^^^
  File "/Users/vomitwolf/Deep-Live-Cam/modules/core.py", line 158, in pre_check
    update_status('ffmpeg is not installed.')
  File "/Users/vomitwolf/Deep-Live-Cam/modules/core.py", line 166, in update_status
    ui.update_status(message)
  File "/Users/vomitwolf/Deep-Live-Cam/modules/ui.py", line 137, in update_status
    status_label.configure(text=text)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'configure'

**Comment by WillHemmens** [comment]
ffmpeg is not installed.

**Comment by grizzzlyzzzombie** [comment]
same issue
![image](https://github.com/user-attachments/assets/ddedace5-6dbe-42b4-9606-6ab18e081b26)

**Comment by vomitwolf** [comment]
> ffmpeg is not installed.

![Screenshot 2024-08-11 at 1 08 20 PM](https://github.com/user-attachments/assets/70a0f645-c8b3-4b11-9046-b2ecf154aaa2)

**Comment by Dimarom4** [comment]
Yes, I have this problem too. I tried to install it here `https://www.youtube.com/watch?v=OlNWCpFdVMA` and here `https://phoenixnap.com/kb/ffmpeg-windows` 
![изображение_2024-08-11_164816565](https://github.com/user-attachments/assets/4ff59c9b-5744-4d61-91b6-6284ddbadb27)

![изображение_2024-08-11_164759315](https://github.com/user-attachments/assets/508e5de0-b34f-4b43-831a-078c8b59fbc9)

**Comment by Samwellwang** [comment]
execute "iex (irm ffmpeg.tc.ht)" in your powershell and install ffmpeg ，then restart your ide ，it will work

**Comment by Dimarom4** [comment]
> execute "iex (irm ffmpeg.tc.ht)" in your powershell and install ffmpeg ，then restart your ide ，it will work

what type of ffmpeg i need to install?
![image](https://github.com/user-attachments/assets/bfaf3da5-67c2-4ede-ab1f-00929301d3aa)

**Comment by Dimarom4** [comment]
nothing has changed 
![image](https://github.com/user-attachments/assets/75086d9a-f224-49d7-899f-8ee9ba1f7778)

**Comment by Dimarom4** [comment]
i dont know what i do, but now app starts. I changed PATH. Now its not `C:\ProgramData\chocolatey\bin\ffmpeg.exe`, its `C:\ProgramData\chocolatey\bin`

**Comment by RitikJ06** [comment]
I had the same issue, i installed ffmpeg from here: https://www.ffmpeg.org/download.html#build-windows and added the ffmpeg.exe file to the PATH environment variable and it worked.

**Comment by Samwellwang** [comment]
> i dont know what i do, but now app starts. I changed PATH. Now its not `C:\ProgramData\chocolatey\bin\ffmpeg.exe`, its `C:\ProgramData\chocolatey\bin`

You have to ensure than ffmpeg in your enviroment path and that it response when executed 'ffmpeg' in your powershell

**Comment by cyc-hahaha** [comment]
![show1](https://github.com/user-attachments/assets/133928fd-348e-4097-9514-4f40f1dd6695)  I had the  same issue.

**Comment by cyc-hahaha** [comment]
> > i dont know what i do, but now app starts. I changed PATH. Now its not `C:\ProgramData\chocolatey\bin\ffmpeg.exe`, its `C:\ProgramData\chocolatey\bin`
> 
> You have to ensure than ffmpeg in your enviroment path and that it response when executed 'ffmpeg' in your powershell

yes, It worked   !!!!!!!!!!
