### ISSUE TITLE
Corrupt results

### ISSUE THREAD

**Issue by helgster77** [hacksider/Deep-Live-Cam#160]
I get corrupt results, any idea what I need to fix?

![image](https://github.com/user-attachments/assets/db1a1993-411e-4e82-aea7-2161d72f5522)

**Comment by WillHemmens** [comment]
Can you show the input image?

**Comment by helgster77** [comment]
Was just trying to replicate what was in the demo:
![image](https://github.com/user-attachments/assets/1017ad52-63bf-4a67-8875-2d5fcdbbdf0c)

**Comment by helgster77** [comment]
I have tried more images but they all give results like this

**Comment by helgster77** [comment]
This fixed it:

pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3
