### ISSUE TITLE
Ubuntu 22.04 WSL 2 error: getStreamChannelGroup Camera index out of range

### ISSUE THREAD

**Issue by kirahman2** [hacksider/Deep-Live-Cam#161]
I ran 

`python run.py --execution-provider cuda`

I got the error 
`2024-08-10 17:02:31.479672: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[ WARN:0@15.562] global cap_v4l.cpp:982 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@15.563] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range`

Will there be support to detect a webcam from WSL linux? I am on a Windows 11 desktop.

**Comment by MartinsKMickus** [comment]
I haven't followed a guide I will provide but it seems that Microsoft has excluded some drivers from WSL. To make the camera available within WSL you have to rebuild the WSL kernel with the necessary drivers (and also follow USB device sharing steps).
Here is the tutorial: https://youtu.be/t_YnACEPmrM?si=1pJEIHi0JplAPMUE

I hope it works.

**Comment by elixsmax** [comment]
> I haven't followed a guide I will provide but it seems that Microsoft has excluded some drivers from WSL. To make the camera available within WSL you have to rebuild the WSL kernel with the necessary drivers (and also follow USB device sharing steps). Here is the tutorial: https://youtu.be/t_YnACEPmrM?si=1pJEIHi0JplAPMUE
> 
> I hope it works.

I had the same issue as the user above but the video you linked fixed it! thank you so much!!

**Comment by thepromptninjaneer** [comment]
Did you end up getting this full work in WSL?
