### ISSUE TITLE
The face area is a back square 

### ISSUE THREAD

**Issue by david-dong828** [hacksider/Deep-Live-Cam#162]
OS: window10
python 3.10
CPU no CUDA

----- Please find the below screenshots as more info, and is any idea why there's only black square on my face area ?

Thanks

![image](https://github.com/user-attachments/assets/ceeaf331-bb30-423b-ae8e-c596f2ba145e)

![image](https://github.com/user-attachments/assets/e1180326-bb75-4aa6-b705-253523b0c41a)

**Comment by a1667834841** [comment]
haha

**Comment by johnnestebann** [comment]
same problem here! from Ubuntu 22.04 without GPU, this output:
```
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/johnnestebann/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/johnnestebann/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/johnnestebann/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/johnnestebann/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/johnnestebann/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
```

**Comment by ShinSeongJin2** [comment]
Hi. I had the same problem. And I finally found that it occurred by inswapper_128_fp16.onnx file in models. When I changed it to another model file in a different resource (https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx), It resolved!

**Comment by RuifengFu** [comment]
> Hi. I had the same problem. And I finally found that it occurred by inswapper_128_fp16.onnx file in models. When I changed it to another model file in a different resource (https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx), It resolved!

Thanks, this way do work.

**Comment by ercanezin** [comment]
I can also confirm it worked on my macOS with Intel CPU.

**Comment by david-dong828** [comment]
> Hi. I had the same problem. And I finally found that it occurred by inswapper_128_fp16.onnx file in models. When I changed it to another model file in a different resource (https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx), It resolved!

This works. Thanks bro

**Comment by blessingmwiti** [comment]
> Hi. I had the same problem. And I finally found that it occurred by inswapper_128_fp16.onnx file in models. When I changed it to another model file in a different resource (https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx), It resolved!

Thanks brother

**Comment by david-dong828** [comment]
solved

**Comment by imyideas** [comment]
> > Hi. I had the same problem. And I finally found that it occurred by inswapper_128_fp16.onnx file in models. When I changed it to another model file in a different resource (https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx), It resolved!
> 
> Thanks brother

Thanks it worked !!

**Comment by li-yong** [comment]
> inswapper_128_fp16.onnx

The link is changed, https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/inswapper_128_fp16.onnx

**Comment by timfocus6** [comment]
Same
