### ISSUE TITLE
The program does not use GPU acceleration. 

### ISSUE THREAD

**Issue by Phill526** [hacksider/Deep-Live-Cam#163]
Hello! The program is work but dont use my rtx 3080 cause i checked it load its idling. The fps is very baad... I installed nvidia toolkit and pip install onnxruntime-gpu==1.16.3

**Comment by lelelol** [comment]
run these commands: 
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3
and start the app with this one:
python run.py --execution-provider cuda

**Comment by Phill526** [comment]
> run these commands: pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3 and start the app with this one: python run.py --execution-provider cuda

I started python run.py --execution-provider cuda it doesnt work and shows error error: argument --execution-provider: invalid choice: 'cuda' (choose from 'dml', 'cpu')

**Comment by Phill526** [comment]
> run these commands: pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3 and start the app with this one: python run.py --execution-provider cuda

Made as you write exactly the same result.

**Comment by Phill526** [comment]
> run these commands: pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3 and start the app with this one: python run.py --execution-provider cuda

oh shit its worked!! But i cash black square, u know something about it??

**Comment by burdukow** [comment]
> But i cach black square often, u know something about it??

Try to download models from #70
[inswapper_128_fp16.onnx](https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx) 
[GFPGANv1.4.pth](https://huggingface.co/gmk123/GFPGAN/resolve/main/GFPGANv1.4.pth?download=true)

**Comment by Phill526** [comment]
> > But i cach black square often, u know something about it??
> 
> Try to download models from #70 [inswapper_128_fp16.onnx](https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx) [GFPGANv1.4.pth](https://huggingface.co/gmk123/GFPGAN/resolve/main/GFPGANv1.4.pth?download=true)

okay! any more model u can advice?

**Comment by Phill526** [comment]
> pip uninstall onnxruntime onnxruntime-gpu
> pip install onnxruntime-gpu==1.16.3
> and start the app with this one:
> python run.py --execution-provider cuda

i had this model already by the way

**Comment by leokovaski** [comment]
I have the same problem or it is similar.
"error: argument --execution-provider: invalid choice: 'coreml' (choose from 'azure', 'cpu')"
Apple Intel
