### ISSUE TITLE
support python other than 3.10

### ISSUE THREAD

**Issue by carefulcomputer** [hacksider/Deep-Live-Cam#169]
Currently recommended version is python 3.10. I have python 3.13 and it has issues running this code. 
However, python 3.10 binaries is not available for mac (because of issues??) https://www.python.org/downloads/macos/ . Can you please support other python versions ?

**Comment by VaibhavCodes01** [comment]
Use Pyenv to Install Python 3.10 on macOS

**Comment by hacksider** [comment]
You can use 3.11 as well

**Comment by diegoasua** [comment]
python 3.13 is not even released. You are running on beta code which no library guarantee it works with. Downgrade to 3.11 or 3.10. They are available for MacOS with Pyenv
