### ISSUE TITLE
Please add gradio or any other web based UI support

### ISSUE THREAD

**Issue by mkasajim** [hacksider/Deep-Live-Cam#172]
I attempted to run this on an Ubuntu server that lacks a GUI, but encountered a 'no display' error. Could you please add a feature to launch the UI through a web browser, using tools like Gradio, Taipy, or any other web-based interface?

**Comment by Zhuangvictor0** [comment]
I WANT THIS TOOOO!!!!

**Comment by ANK789** [comment]
me too
