### ISSUE TITLE
Freezing issues

### ISSUE THREAD

**Issue by success555** [hacksider/Deep-Live-Cam#18]
Hello mine is running but freezing on RTX3060 16gb dedicated, please how can I fix it and also how can I make display very clear and efficient.

thanks

**Comment by hacksider** [comment]
What's the error on the console?

**Comment by Tahabz** [comment]
Mine's keep freezing too but I'm not sure if it's just the max performance I can get out of my gpu/cpu or I could do something to make it smoother.
I'm running on Mac M1 Air.

I'm using python3.10 run.py --execution-provider coreml to run the program.

**Comment by hacksider** [comment]
@Tahabz for the freezes, I'm very sure it's the hardware overheating (specially as you have said you're on macbook air)

**Comment by Tahabz** [comment]
> @Tahabz for the freezes, I'm very sure it's the hardware overheating (specially as you have said you're on macbook air)

Can you please recommend a pc where this would run smoothly (a performance similar to the GIF shown in the readme)

**Comment by hacksider** [comment]
@Tahabz 3060 or 4060 would do good but if you want the same as the one in the demo, then 4070 or 3080 will be better. It should be enough to do stable diffusion as well really fast (image manipulation using AI). The performance on 3080/4070 is just a delay of 2 to 3 frames (processing) on HD quality.
