### ISSUE TITLE
No module found while running

### ISSUE THREAD

**Issue by jwangb7111** [hacksider/Deep-Live-Cam#183]
After installing all requirements, I tried to run this project but received below error:

import torch  ModuleNotFoundError: No module named 'torch'

How can I fix this issue?

Thx
James

**Comment by tearsbear** [comment]
try to run with python3 run.py

**Comment by Gal0ee** [comment]
Hey, got the same issue, python3 run.py doesn't work either
![image](https://github.com/user-attachments/assets/444977a9-db57-4453-9cb1-a6cc34401d95)

**Comment by Gal0ee** [comment]
> Hey, got the same issue, python3 run.py doesn't work either 
Nvm, I got errors when running pip install, so I have to manually install all the requirements it request, and it got fixed
