### ISSUE TITLE
Frame processor face_enhancer not found

### ISSUE THREAD

**Issue by Dimarom4** [hacksider/Deep-Live-Cam#184]
I use it without CUDA. I pressed  `START` or `LIVE`, nothing happened, only in the console. The camera is connected and working correctly
```
[ WARN:0@99.236] global cap.cpp:323 cv::VideoCapture::open VIDEOIO(DSHOW): raised unknown C++ exception!

[ERROR:0@99.241] global obsensor_uvc_stream_channel.cpp:158 cv::obsensor::getStreamChannelGroup Camera index out of range
Frame processor face_enhancer not found`
```

**Comment by Ku-Tadao** [comment]
This **_should_** resolve the face_enhancer issue:

 uninstall the current version of basicsr:
`pip uninstall basicsr -y`

install basicsr directly from its GitHub repository:
`pip install git+https://github.com/xinntao/BasicSR.git@master`

After installation is complete, also reinstall gfpgan:
`pip uninstall gfpgan -y`
`pip install git+https://github.com/TencentARC/GFPGAN.git@master`

this fixed it for me.

you're having another issue which i can't help you with though, the above only fixes the face_enhancer part.

**Comment by Dimarom4** [comment]
Thanks, this helped me and now everything works well, but without CUDA. And when I try with CUDA I get completely different errors
