### ISSUE TITLE
 App crashes during video processing on AMD Radeon Instinct MI25 MXGPU

### ISSUE THREAD

**Issue by drgom1** [hacksider/Deep-Live-Cam#188]
Hey there, Deep-Live-Cam team!

I'm having a bit of trouble with your app and could really use some help. I'm running this on a Windows 10 VM in Azure with an AMD Radeon Instinct MI25 MXGPU. 

Here's what's happening:
The app starts up fine, and I can see the GUI. The preview feature works great, but when I try to create the actual video, it crashes. It gets through extracting the frames, but as soon as it starts the face-swapping part, it just shuts down.

I've tried a bunch of things to fix it:
- Running with different execution threads
- Limiting memory usage
- Using just the CPU
- Updating everything I could think of
- Even tried different videos

But no luck so far. The crash always happens at the same point, right after it says it's extracting frames and starting the face-swapping.

Here's the last bit of output I see before it crashes:
[DLC.CORE] Creating temp resources...
[DLC.CORE] Extracting frames...
[DLC.FACE-SWAPPER] Progressing...
Processing:   0%| | 0/296 [00:00<?, ?frame/s, execution_providers=['DmlExecutionProvider'], execution_threads=8, max_me
Copy
After that, the app just closes.

I'm wondering if there might be some issue with AMD GPUs, or maybe something specific to running in a VM? Any ideas on what else I could try?

Thanks a ton for any help you can give!

**Comment by MegaTheLEGEND** [comment]
+1

**Comment by Jianxff** [comment]
same.

**Comment by vlednerk** [comment]
Log says u use dml , dml not supported by tensorflow anymore 
So amd on windows not supported 😕

**Comment by nicolasxbx** [comment]
+1. Using `--execution-threads 1` works though. But not optimal..
