### ISSUE TITLE
Dont starting

### ISSUE THREAD

**Issue by markenoid** [hacksider/Deep-Live-Cam#19]
Hello, I installed the program as written in the instructions, but ultimately the program starts, it says "WARNING:tensorflow:From C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\ losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.", then two empty lines and stops working after a few seconds. What should I do? I have Windows 10 and I installed python 3.10.6, pip, git, ffmpeg, visual studio 2022 runtimes and downloaded the models, created a models folder and added them there.

![image](https://github.com/hacksider/Deep-Live-Cam/assets/69259896/fe0e6c78-7954-4d3c-9172-78e5f94e158b)

**Comment by hacksider** [comment]
have you installed everything on the requirements.txt?

**Comment by markenoid** [comment]
yes I also installed full list of requirements.txt

**Comment by markenoid** [comment]
I reinstalled each requirement manually and it helped to launch the program, thank you very much

**Comment by pablo1794** [comment]
Facing the same thing. All requirements satisfied but still app won't lunch

**Comment by hacksider** [comment]
I suggest creating a new ticket with your screenshot will help 😊
