### ISSUE TITLE
M2 Mac Studio: no faces to select from

### ISSUE THREAD

**Issue by indieshack** [hacksider/Deep-Live-Cam#192]
![Screenshot 2024-08-11 at 1 59 22 PM](https://github.com/user-attachments/assets/4837a86c-3645-49b0-af91-a20c37f080f6)

The install went fine, but when I start the app (either with or without Apple Silicon GPU set up) this is what I see - missing face images. When I tap on "select a face" a finder dialog opens. Any suggestions?

**Comment by AkdM** [comment]
In the Finder dialog, simply select a face you want to swap from, then select a target if you want to swap a face from a picture or video, then click Start. Or you can just click on Live after selecting the face.
Did you read the README?

**Comment by indieshack** [comment]
> Did you read the README?

Yes I did - select a face from where?

**Comment by AkdM** [comment]
What do you mean from where? You download a picture of someone from the Internet and select the image?

**Comment by indieshack** [comment]
Duh ... OK I understand now - thanks

**Comment by indieshack** [comment]
Misunderstanding of the way the software works
