### ISSUE TITLE
The FPS is low when enabling "Face Enhancer"

### ISSUE THREAD

**Issue by TomiTom1234** [hacksider/Deep-Live-Cam#193]
As the title says, when I enable the "Face Enhancer" for the Live Web Camera, the fps is low, and the movements is slow.
Is there a way to improve the fps?

My Card is 3070Ti with 8gb vRams.

**Comment by giusparsifal** [comment]
Hi, so face enhancer works? It doesn't for me, the face is swapped good, but "Frame processor face_enhancer not found".
How you did it working?
Thanks

**Comment by luxclinic** [comment]
hi

**Comment by TomiTom1234** [comment]
> Hi, so face enhancer works? It doesn't for me, the face is swapped good, but "Frame processor face_enhancer not found". How you did it working? Thanks

Yep it works pretty well, but as I mentioned the fps drops like 5 fps.

I just installed the tool following the installation guide on this page. I assume you have Windows, right?

**Comment by giusparsifal** [comment]
> > Hi, so face enhancer works? It doesn't for me, the face is swapped good, but "Frame processor face_enhancer not found". How you did it working? Thanks
> 
> Yep it works pretty well, but as I mentioned the fps drops like 5 fps.
> 
> I just installed the tool following the installation guide on this page. I assume you have Windows, right?

Yes I have Windows, but even if the face is ok, it keeps on telling me can't fìnd it.
Anyway it is also slow for me when I start it with CPU, with CUDA works fast, only problem is face enahncer.

**Comment by TomiTom1234** [comment]
> i have the same issue with the FPS, still trying to figure out why it's happening.
> 
> do you know if it's a CUDA only thing? or did you run it in a diff way.

I tried Cuda (which is the best way to run the tool) and the CPU, both have problem with FPS when I enable face enhancer.
It seems the developer himself suggests not to enable it at this moment, because (as he says) it is not good right now.
But enabling it gives really a very good and sharp image.

**Comment by walkingwithGod123** [comment]
> > i have the same issue with the FPS, still trying to figure out why it's happening.我的 FPS 也有同样的问题，仍在尝试找出发生这种情况的原因。
> > do you know if it's a CUDA only thing? or did you run it in a diff way.你知道这是否只是 CUDA 的事情吗？或者你是否以不同的方式运行它。
> 
> I tried Cuda (which is the best way to run the tool) and the CPU, both have problem with FPS when I enable face enhancer.我尝试了 Cuda（这是运行该工具的最佳方式）和 CPU，当我启用面部增强器时，两者都出现 FPS 问题。 It seems the developer himself suggests not to enable it at this moment, because (as he says) it is not good right now.开发人员本人似乎建议此时不要启用它，因为（正如他所说）现在不好。 But enabling it gives really a very good and sharp image.但启用它确实可以提供非常好的清晰图像。

The same problem
