### ISSUE TITLE
[ WARN:0@374.880] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638

### ISSUE THREAD

**Issue by Silhouteee** [hacksider/Deep-Live-Cam#194]
after running with python run.py and try to go live for webcam i am encountered with this error code. 

[ WARN:0@374.880] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638

**Comment by Silhouteee** [comment]
fixed

**Comment by am1ntn** [comment]
I'm facing the same problem, how did you fix it?

**Comment by OKSoda** [comment]
Same issue here. What was the fix?

**Comment by HazAT** [comment]
On Windows, you need to tinker with the camera settings to ensure no other app is using the camera. This is how I got it to work.

**Comment by spullara** [comment]
my camera flickers on for a second and then get an error similar to this one.

[ WARN:1@20.419] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147024809

**Comment by emmatrice** [comment]
Give directions on how to go about it
