### ISSUE TITLE
Model Optimization

### ISSUE THREAD

**Issue by inisis** [hacksider/Deep-Live-Cam#198]
Hi, thanks for providing this great project, I find the [inswapper_128_fp16.onnx](https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128_fp16.onnx) that attached can be futher optimized by using [onnxslim ](https://github.com/inisis/OnnxSlim) without lose of accuracy, here are the results.
```
pip install onnxslim
onnxslim inswapper_128_fp16.onnx slim.onnx
```
![image](https://github.com/user-attachments/assets/1cdb51f5-df05-46c5-bbfd-2d6bf067b049)

**Comment by hacksider** [comment]
Awesome! Can you commit this on the experimental as well?

**Comment by inisis** [comment]
Sure, but I only forked the main branch, maybe after https://github.com/hacksider/Deep-Live-Cam/pull/199 is merged, I can create another pr to experimental branch, right now, there are many conflicts.

**Comment by inisis** [comment]
@hacksider pr for experimental branch https://github.com/hacksider/Deep-Live-Cam/pull/215

**Comment by inisis** [comment]
> @hacksider pr for experimental branch #215

Hi @hacksider , can this be merged into experimental branch?
