### ISSUE TITLE
Petition: Opacity slider

### ISSUE THREAD

**Issue by aroca69** [hacksider/Deep-Live-Cam#2]
Your aplication is Awesome. Could you include a Slider with the opacity from 0 to 100 in the face, like in Deepfacelive?. And if is posible to mantain the original colors from the original photo instead to adapt the colors in the target. In photos with makeup don´t take the makeup from the original photo.
Sorry for my english, i´m not native.

**Comment by hacksider** [comment]
No worries, I'll include this on the wishlist but I can't promise anything soon as there are other priorities (but I'm open to any push/commit on the code if someone wants to contribute as well).
