### ISSUE TITLE
Can't install on M1 pro

### ISSUE THREAD

**Issue by success555** [hacksider/Deep-Live-Cam#20]
![Screenshot 2024-02-13 at 11 05 19 AM](https://github.com/hacksider/Deep-Live-Cam/assets/81899125/2deb8cac-03de-4dc3-94e5-9baa8b5ba78e)
![Screenshot 2024-02-13 at 11 05 59 AM](https://github.com/hacksider/Deep-Live-Cam/assets/81899125/cab47565-6d5e-459a-9811-a0b7930d7155)

**Comment by cserpellZF** [comment]
If you look at the error you will see it says ffmpeg is not installed. Go ahead and install it:
```bash
brew install ffmpeg
```
