### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by Ming-gi** [hacksider/Deep-Live-Cam#204]
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement tb-nightly (from gfpgan) (from versions: none)
ERROR: No matching distribution found for tb-nightly

**Comment by Ming-gi** [comment]
i use python3.10(conda)

**Comment by qqizhao** [comment]
I have the same question. And I don't install gfpgan (the last one of requirement.txt).
And the project can work.

**Comment by Of-qinhai** [comment]
``` bash 
pip install tb-nightly --index-url https://pypi.org/simple  
```

**Comment by Of-qinhai** [comment]
``` bash 
pip install tb-nightly --index-url https://pypi.org/simple  
```

**Comment by SeanDCao** [comment]
> ```shell
> pip install tb-nightly --index-url https://pypi.org/simple  
> ```

it's work！tks

**Comment by Ming-gi** [comment]
> ```shell
> pip install tb-nightly --index-url https://pypi.org/simple  
> ```
tks！！
