### ISSUE TITLE
i want a  usb cam

### ISSUE THREAD

**Issue by 3DKIDS** [hacksider/Deep-Live-Cam#207]
I have a default cam on my laptop but if I want to test it with usb cam how can I change the camera selection I would appreciate it if anyone knows.

**Comment by ByerRA** [comment]
I'm in a similar boat. I have a USB cam and would like to know how to select it.

**Comment by NXTler** [comment]
The experimental build has a build in selector. Just go into your folder and switch to experimental with git, pull all the changes and rerun the requirements.
