### ISSUE TITLE
very slow, how to set less ressolution?

### ISSUE THREAD

**Issue by bitcoin5000** [hacksider/Deep-Live-Cam#209]
I have 4090 and it very slow few fps in sec, how to  set lover resolution to make atleast 15 stable fps?

**Comment by orkunisitmak** [comment]
same here with the 4090, even though keep fps,keep frame and face enchance settings are off

**Comment by TomiTom1234** [comment]
It is fine here without Face Enhancer, but only when I turn on the Enhancer, the FPS drops to like 5 fps

**Comment by leetraman822** [comment]
I have an RTX3060 graphics card with 12GB of VRAM. When I enable the face enhancer, it only utilizes 4GB of VRAM, yet the FPS is very slow. I don't know how to improve this.

**Comment by hacksider** [comment]
Currently the size is optimized for 10gb or higher gpu. And yes, it's usually 12 to 15fps as it is doing some processing every other frame. You can make it smaller but there's a very little chance you can do more than 30fps because of the post processing. ☺️

**Comment by FxVenix** [comment]
> Change the numbers in the image. I added a UI to allow you to switch between them.
> 
> /Deep-Live-Cam/modules/ui.py ![2024-08-24_17h41_44](https://private-user-images.githubusercontent.com/125081727/361127924-a2360894-2d66-4ef8-8c54-a1bee9e52684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3Mjc1OTQsIm5iZiI6MTcyOTcyNzI5NCwicGF0aCI6Ii8xMjUwODE3MjcvMzYxMTI3OTI0LWEyMzYwODk0LTJkNjYtNGVmOC04YzU0LWExYmVlOWU1MjY4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QyMzQ4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGRjZjFkMjBmZDFiYmMzOTczMzQwZGMwM2RmNGUwZjk4ODA4NmE2M2QwZjc3MTM2ZGJkODNlNWQ2NDJkZWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fUPYWp0RvdTQFDAu8dS3NPHCEERS10E2DIB34y5aCMQ)


hate to bug and be the one to reopen this but I’m pretty much new to this can someone explain how to add the Ui to make the adjustments

**Comment by hacksider** [comment]
> I don't think this is necessary anymore since the --live-resizable feature has been added.
> 
> It seems that development has progressed since then.

This is basically the answer.

**Comment by hacksider** [comment]
You can resize the preview to make it smaller and faster.

**Comment by mike3wjsk** [comment]
> You can resize the preview to make it smaller and faster.

Thanks for your response. Actually it works perfectly without the face enhancer enabled. With the face enhancer enabled it becomes very slow even if the window is realized to the minimum. I'm currently on a rtx 4070 8gb ded. I'm thinking if there's a way to reduce the quality if the face enhancer so it doesn't have a low fps when it's enabled.

**Comment by ct-03** [comment]
> I have an RTX3060 graphics card with 12GB of VRAM. When I enable the face enhancer, it only utilizes 4GB of VRAM, yet the FPS is very slow. I don't know how to improve this.

me too, can not load all GPU power

**Comment by LE007X** [comment]
> Change the numbers in the image.
> 
> I added a UI to allow you to switch between them.
> 
> 
> 
> /Deep-Live-Cam/modules/ui.py
> 
> ![2024-08-24_17h41_44](https://github.com/user-attachments/assets/a2360894-2d66-4ef8-8c54-a1bee9e52684)
> 
> 

Please how can I write this Command in windows shell

**Comment by xx7Ahmed7xx** [comment]
It is not working for me, resizing the preview box that appears after pressing live doesn't increase fps (so i could preview correctly) it stays quite low...
I have GTX 1660 Ti 6GB on i7-9750H
