### ISSUE TITLE
colab version

### ISSUE THREAD

**Issue by MadeByKit** [hacksider/Deep-Live-Cam#21]
hey hacksider, can you make a colab version for pc without gpu?

i've tried making it but im running into some issues

this was the one made by the creator of roop @s0md3v but it doesnt have the "live" feature like yours
[https://colab.research.google.com/drive/1NG9AoH3QDtC7h97z1Yodmn_CiiGh8Y1T?usp=sharing#scrollTo=lDYdfL3L71i1](url)

**Comment by hacksider** [comment]
I don't know how it will work using a remote location as well 😅

Sorry, can't help you with it.

**Comment by Thankgod20** [comment]
Check my fork> https://github.com/Thankgod20/Deep-Live-Cam-Google-Colab
