### ISSUE TITLE
Empty application window on Mac OS Sonoma, M1

### ISSUE THREAD

**Issue by sintezcs** [hacksider/Deep-Live-Cam#211]
Getting an empty application window, no errors in the console.
Mac OS Sonoma, M1
Python 3.10.2

<img width="972" alt="image" src="https://github.com/user-attachments/assets/569b21d5-36d0-4aa0-95cd-7b6bc4a17625">

**Comment by toitzi** [comment]
Same issue has anyone resolved this?

**Comment by KitsonBroadhurst** [comment]
Same issue here on Mac OS Sonoma, M1

**Comment by grahamj** [comment]
Same with both M1P and M2P MBPs. Sonoma, pyenv 3.10

**Comment by Izzetee** [comment]
same for me M2 Max Sonoma pyenv 3.10

**Comment by hvsw** [comment]
+1

**Comment by hvsw** [comment]
Fixed when using Python `3.10.14`. ✅

**Comment by claude89757** [comment]
> Fixed when using Python `3.10.14`. ✅

it works！thanks
