### ISSUE TITLE
Hey, I can't launch it MacOS Sillicon

### ISSUE THREAD

**Issue by MathisZerbib** [hacksider/Deep-Live-Cam#214]
I've made a conda env 3.10.9

```
conda create --name deep-live-cam
conda activate deep-live-cam   
```

and 

I followed along the installation with 

`pip install -r requirements.txt  

pip uninstall onnxruntime onnxruntime-silicon
pip install onnxruntime-silicon==1.13.1

`

`python run.py --execution-provider coreml`

```

Traceback (most recent call last):
  File "/Users/zer/Documents/lab/perso/Deep-Live-Cam/run.py", line 6, in <module>
    core.run()
  File "/Users/zer/Documents/lab/perso/Deep-Live-Cam/modules/core.py", line 242, in run
    limit_resources()
  File "/Users/zer/Documents/lab/perso/Deep-Live-Cam/modules/core.py", line 131, in limit_resources
    gpus = tensorflow.config.experimental.list_physical_devices('GPU')
AttributeError: module 'tensorflow' has no attribute 'config'

```

and 

`python run.py` 

give me the same output

my dependencies 

`pip list | grep -E "numpy|opencv-python|onnx|insightface|psutil|tk|customtkinter|pillow|torch|torchvision|onnxruntime|tensorflow|opennsfw2|protobuf|tqdm|gfpgan"`
```
numpy                                           1.23.5
opencv-python                                   4.8.1.78
opencv-python-headless                          4.9.0.80
onnx                                            1.16.0
insightface                                     0.7.3
psutil                                          5.9.8
tk                                              0.1.0
customtkinter                                   5.2.2
gfpgan                                          1.3.8
pillow                                          9.5.0
onnxruntime-silicon                             1.16.3
opennsfw2                                       0.10.2
tensorflow                                      2.13.0rc1
tensorflow-estimator                            2.13.0
tensorflow-io-gcs-filesystem                    0.37.0
tensorflow-macos                                2.13.0rc1
torch                                           2.0.1
torchvision                                     0.15.2
tqdm                                            4.66.4
protobuf                                        4.23.2
```

Help would be appreciated ! cheers

**Comment by amanaknows** [comment]
<a href="https://github.com/iAngelica/dark-side-repo" target="_blank">
    <img src="https://img.shields.io/badge/Sith%20Lord%20S5-AI%20Automation%20Dark%20Side%20Control-black?style=for-the-badge&logo=dark-mode&logoColor=white&labelColor=black" alt="AI Automation Dark Side Control Badge">
</a>

**Comment by YetHowTolove** [comment]
me2 bro , wait for the chef answer your question , cheers

**Comment by YetHowTolove** [comment]
hi bro i think i deal with this issue, you just go to your venv and delete all tensorflow named package,then pip install -r requirements.txt,and it can work

may this help you bro

**Comment by MathisZerbib** [comment]
I tried that thank's but not working, I also tried a 
`pip install --upgrade tensorflow 
python run.py --execution-provider coreml 

   
Traceback (most recent call last):
  File "/Users/zer/Documents/lab/perso/Deep-Live-Cam/run.py", line 6, in <module>
    core.run()
  File "/Users/zer/Documents/lab/perso/Deep-Live-Cam/modules/core.py", line 246, in run
    window = ui.init(start, destroy)
  File "/Users/zer/Documents/lab/perso/Deep-Live-Cam/modules/ui.py", line 39, in init
    ROOT = create_root(start, destroy)
  File "/Users/zer/Documents/lab/perso/Deep-Live-Cam/modules/ui.py", line 52, in create_root
    root = ctk.CTk()
  File "/Users/zer/.pyenv/versions/3.10.9/lib/python3.10/site-packages/customtkinter/windows/ctk_tk.py", line 40, in __init__
    CTK_PARENT_CLASS.__init__(self, **pop_from_dict_by_set(kwargs, self._valid_tk_constructor_arguments))
  File "/Users/zer/.pyenv/versions/3.10.9/lib/python3.10/tkinter/__init__.py", line 2301, in __init__
    self._loadtk()
  File "/Users/zer/.pyenv/versions/3.10.9/lib/python3.10/tkinter/__init__.py", line 2317, in _loadtk
    raise RuntimeError("tk.h version (%s) doesn't match libtk.a version (%s)"
RuntimeError: tk.h version (8.5) doesn't match libtk.a version (8.6)


`

**Comment by AlexUrrutia** [comment]
Tried Python **3.11** and it works,  **3.12** does not work at the moment
