### ISSUE TITLE
keep having errors in final step

### ISSUE THREAD

**Issue by Leehonard** [hacksider/Deep-Live-Cam#22]

**Comment by hacksider** [comment]
Seems like you're not on the folder where you pull the github repo. You're on FETTY folder.

**Comment by Leehonard** [comment]
The repo wouldn't clone for whatever reason. I'm new to this, so sorry if I am having basic silly errors.
![error 1](https://github.com/hacksider/Deep-Live-Cam/assets/159996317/3b1c802c-0d48-4217-9d8d-02b330359599)

**Comment by Leehonard** [comment]
But I did download the zip file and extracted it all and Idk if that would make it work or not.

**Comment by Leehonard** [comment]
this is what it shows when I use the cmd from the folder 
![pypypy](https://github.com/hacksider/Deep-Live-Cam/assets/159996317/4e4610b2-eed0-454b-b6f9-3bb6723c5a50)

**Comment by Leehonard** [comment]
every other steps worked up until the last step

**Comment by Leehonard** [comment]
okay so I started the whole process again from scratch using the cmd in the folder, then this is the error I see whn I install requirements.
![py error](https://github.com/hacksider/Deep-Live-Cam/assets/159996317/3f57060a-fd43-440e-bc76-afc4b92ff5df)

**Comment by Leehonard** [comment]
working now, thank you
