### ISSUE TITLE
Low FPS on MacBook Pro M3 Pro

### ISSUE THREAD

**Issue by AlexUrrutia** [hacksider/Deep-Live-Cam#224]
Apple MacBook Pro M3, how to improve fps?

https://github.com/user-attachments/assets/0a6ebebb-e208-4266-98ae-005fe7ad6e3c

**Comment by EnVoY123** [comment]
same problem on M1 Pro

**Comment by jasonkneen** [comment]
Same -- terrible frame rate

**Comment by EnVoY123** [comment]
https://github.com/gongzhang/Deep-Live-Cam/blob/main/README.macos.md

try this

**Comment by AlexUrrutia** [comment]
> https://github.com/gongzhang/Deep-Live-Cam/blob/main/README.macos.md
> 
> try this

I did, same result...

**Comment by Wind010** [comment]
Try playing around with the command line parameters for `--execution-provider` and `--execution-threads`:

I seem to have better luck with using the CPU than coreML.  Also try `keep FPS`.
```
python run.py --execution-provider cpu --execution-threads 4
```

**Comment by jasonkneen** [comment]
managed to get my version working

https://github.com/jasonkneen/Deep-Live-Cam.git

faster and now uses the GPU on Apple Silicon

**Comment by AlexUrrutia** [comment]
> managed to get my version working
> 
> https://github.com/jasonkneen/Deep-Live-Cam.git
> 
> faster and now uses the GPU on Apple Silicon

Can you post the steps needed to make it work with your forked code? Thanks!

**Comment by binglord** [comment]
same on M3 PRO 512+36GB RAM

**Comment by grahamj** [comment]
At least you got it working 😬

I just got a blank window on both M1P and M2P MBPs. Using pyenv with 3.10.14.

**Comment by Wind010** [comment]
> At least you got it working 😬
> 
> 
> 
> I just got a blank window on both M1P and M2P MBPs. Using pyenv with 3.10.14.

Try Python 3.11.  It's what I am using.  Via MiniConda.

**Comment by grahamj** [comment]
> > At least you got it working 😬
> > I just got a blank window on both M1P and M2P MBPs. Using pyenv with 3.10.14.
> 
> Try Python 3.11. It's what I am using. Via MiniConda.

I'll give it a try but both the main and the Mac instructions here say 3.10

**Comment by kr3kls** [comment]
> managed to get my version working
> 
> https://github.com/jasonkneen/Deep-Live-Cam.git
> 
> faster and now uses the GPU on Apple Silicon

It appears your requirements.txt is missing customtkinter and it won't run without it. I tried adding customtkinter==5.2.2 from the original repo to your requirements.txt and it doesn't run.  It fails to load the model with an INVALID_PROTOBUF error.

**Comment by MillionaireChen** [comment]
> > managed to get my version working
> > https://github.com/jasonkneen/Deep-Live-Cam.git
> > faster and now uses the GPU on Apple Silicon
> 
> It appears your requirements.txt is missing customtkinter and it won't run without it. I tried adding customtkinter==5.2.2 from the original repo to your requirements.txt and it runs but won't load the model in live view. It fails to load the model with an INVALID_PROTOBUF error.


<img width="827" alt="image" src="https://github.com/user-attachments/assets/fa70b497-c130-4534-8b61-811abd228c96">

mine is workingworking. But still a lower rate of GPU.

**Comment by ChristianWeyer** [comment]
> managed to get my version working
> 
> https://github.com/jasonkneen/Deep-Live-Cam.git
> 
> faster and now uses the GPU on Apple Silicon

Can't get you version working @jasonkneen

**Comment by poncion** [comment]
Using the M3 version, I attempted the following: 
- Updated `tensorflow-macos` and `tensorflow-metal`. 
- Ran with `python run.py --execution-provider coreml --video-quality 0 --live-resizable`. 

The performance improved, but it can be better because I'm not using my graphic card.
