### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by SomeoneIDKK** [hacksider/Deep-Live-Cam#225]
Finally managed to install TORCH after it not working, but now when typing ¨python run.py´´ this appears:

Traceback (most recent call last):
  File "C:\Users\USER\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\USER\Deep-Live-Cam\modules\core.py", line 14, in <module>
    import torch
  File "D:\Users\USER\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "D:\Users\USER\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

I have tried to install the dependencies multiple times and it still fails for some reason.

**Comment by amanaknows** [comment]
<a href="https://app.commanddash.io/agent?github=https://github.com/amanaknows/intelligent-things" target="_blank">
    <img src="https://img.shields.io/badge/Sith%20Lord%20S5-AI%20Automation%20Dark%20Side%20Control-black?style=for-the-badge&logo=dark-mode&logoColor=white&labelColor=black" alt="AI Automation Dark Side Control Badge">
</a>

**Comment by gilotyna815** [comment]
Same problem.

**Comment by gilotyna815** [comment]
Here's what worked for me: I installed python 3.10, but had 3.12 already without knowing, installed with some visual studio package earlier. Make sure your python commands are using 3.10, you can check in terminal with python --version command.
