### ISSUE TITLE
Timeout on MacBook

### ISSUE THREAD

**Issue by Deep1738** [hacksider/Deep-Live-Cam#23]
I keep having this timeout error when I click live on my MacBook,
<img width="1512" alt="Screenshot 2024-02-26 at 00 13 18" src="https://github.com/hacksider/Deep-Live-Cam/assets/161259828/92ac5355-ae33-4620-9bc2-59746cfb43ff">
<img width="1511" alt="Screenshot 2024-02-26 at 00 13 02" src="https://github.com/hacksider/Deep-Live-Cam/assets/161259828/4d75d1f6-46e3-4840-9993-d549553329d6">

**Comment by cserpellZF** [comment]
It is timing out when downloading the file. Can you try downloading it manually by yourself to check your connection to that site?
