### ISSUE TITLE
你好，我是小白。我想问下要如何运行？我找不到exe文件

### ISSUE THREAD

**Issue by damaomao2** [hacksider/Deep-Live-Cam#230]
你好，我是小白。我想问下要如何运行？我找不到exe文件
只有一个run.py文件。
请问该如何运行？我点击run.py也无法启动。

**Comment by awm-rzhang** [comment]
you need to follow the readme file and install all the dependencies

**Comment by bamjun** [comment]
首先学习Python

**Comment by mokerbay** [comment]
首页有操作指导，挺详细的
这个不是exe程序

**Comment by yang208115** [comment]
运行setup_deep_live_cam.bat就行了
