### ISSUE TITLE
Getting a black square instead of selected image on my face when running the app

### ISSUE THREAD

**Issue by faizanakheel24g** [hacksider/Deep-Live-Cam#231]
![image](https://github.com/user-attachments/assets/e24f26bc-25fc-44ed-a1ba-65f810047025)
Above is the attached image of the issue that i am facing. I was able to download all the packages from the requirements file by running the appropriate command. When i run the `python run.py` command, i get no errors in the console but when i select a face and hit live, i get this issue. Can anyone help me out with this?

**Comment by faizanakheel24g** [comment]
Running the following commands worked:

`pip uninstall onnxruntime onnxruntime-gpu`
`pip install onnxruntime-gpu==1.16.3`

**Comment by barats** [comment]
> Running the following commands worked:
> 
> `pip uninstall onnxruntime onnxruntime-gpu` `pip install onnxruntime-gpu==1.16.3`

It is helpful indeed. 
But why?

**Comment by turbolego** [comment]
> Running the following commands worked:
> 
> `pip uninstall onnxruntime onnxruntime-gpu` `pip install onnxruntime-gpu==1.16.3`

Does not work on Intel based mac:

```
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.16.3 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.16.3
```
