### ISSUE TITLE
global obsensor_uvc_stream_channel.cpp:156 cv::obsensor::getStreamChannelGroup Camera index out of range

### ISSUE THREAD

**Issue by emremigh** [hacksider/Deep-Live-Cam#240]
![Screenshot_2](https://github.com/user-attachments/assets/5c22a2b9-535c-4f99-a6c5-19d742fd6a5c)

I am using python version 3.10 and installed in virtualenv.
I use my phone as a webcam so I need to use a virtual camera and I do this through obs.
With scrcpy I connect my phone via usb and transfer my image. Then I use nvidia broadcast for cool features. 
I guess the question here is that it does not see the virtual camera.

**Comment by lmst2** [comment]
I have the same issue, it does not recoginze the virtual camera, so bad cause my desktop does not have a camera
