### ISSUE TITLE
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.

### ISSUE THREAD

**Issue by Abhi6722** [hacksider/Deep-Live-Cam#249]
<img width="1552" alt="Screenshot 2024-08-13 at 2 06 03 PM" src="https://github.com/user-attachments/assets/a14ddd81-a291-47e8-bdb7-cab603326f88">

After installing all the requirements and running the application it is showing
`The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.`

I am on a mac m1 using python3.10 venv

**Comment by Zorlin** [comment]
Did you follow https://github.com/hacksider/Deep-Live-Cam?tab=readme-ov-file#coreml-execution-provider-apple-silicon the Apple Silicon instructions specifically?

**Comment by cuongn265** [comment]
> Did you follow https://github.com/hacksider/Deep-Live-Cam?tab=readme-ov-file#coreml-execution-provider-apple-silicon the Apple Silicon instructions specifically?

same here, I follow the instruction in the readme

**Comment by XADmc** [comment]
![1777501723608610_ pic_hd](https://github.com/user-attachments/assets/9bb67ff3-5409-45bc-b8c4-1d5ba50b8fcb)
I follow the Apple Silicon instructions
No matching distribution found for onnxruntime-coreml==1.13.1
