### ISSUE TITLE
NoneType' object has no attribute 'configure'

### ISSUE THREAD

**Issue by OnlyStopOnTop** [hacksider/Deep-Live-Cam#25]
File "C:\Users\user1\Downloads\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\ui.py", line 137, in update_status
    status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'

get this error message when starting the programm

**Comment by hacksider** [comment]
That means it can't detect any people in front of the camera or the camera isnt turned on.

**Comment by AlphaKh** [comment]
How do I know that the camera is open and working for the program @hacksider
