### ISSUE TITLE
face enhancer not found

### ISSUE THREAD

**Issue by vtjr001** [hacksider/Deep-Live-Cam#264]
I have installed every needed requirements but getting this error when I run the main file. I am running this on remote linux aws instance. Can you help me out here?

`2024-08-13 09:27:37.741628: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-13 09:27:37.765836: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-13 09:27:37.773128: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Frame processor face_enhancer not found`

**Comment by the-dino-enthusiast** [comment]
> @WhoAteDaCake
> 
> Try the following:
> 
> uninstall the current version of basicsr: `pip uninstall basicsr -y`
> 
> install basicsr directly from its GitHub repository: `pip install git+https://github.com/xinntao/BasicSR.git@master`
> 
> After installation is complete, also reinstall gfpgan: `pip uninstall gfpgan -y` `pip install git+https://github.com/TencentARC/GFPGAN.git@master`
> 
> This should resolve your issue.

This worked for me on macOS with m1 max chip, thanks!

**Comment by casyang** [comment]
> @WhoAteDaCake
> 
> Try the following:
> 
> uninstall the current version of basicsr: `pip uninstall basicsr -y`
> 
> install basicsr directly from its GitHub repository: `pip install git+https://github.com/xinntao/BasicSR.git@master`
> 
> After installation is complete, also reinstall gfpgan: `pip uninstall gfpgan -y` `pip install git+https://github.com/TencentARC/GFPGAN.git@master`
> 
> This should resolve your issue.

This method work for me on Windows 11.
A diffirent from this is, I get an error of "tb-nightly", so I install the gfpgan and basicsr requirements by their source requirements.txt file, change the ```tb-nightly``` to ```tensorboard```, then the install command like 
```
pip install git+https://github.com/xinntao/BasicSR.git@master --no-deps
pip install git+https://github.com/TencentARC/GFPGAN.git@master --no-deps 
```
