### ISSUE TITLE
face enhancer not found

### ISSUE THREAD

**Issue by vt57299** [hacksider/Deep-Live-Cam#266]
I have installed every needed requirements but getting this error when I run the main file. I am running this on remote linux aws instance without GPU. Can you help me out here?

`Frame processor face_enhancer not found`

**Comment by seniorforblockchain** [comment]
done

**Comment by vt57299** [comment]
@seniorforblockchain  Do you know how to solve this?

**Comment by vt57299** [comment]
> I used different versions for macos arm m1 chip.
> 
> numpy==1.26.4 opencv-python==4.8.1.78 onnx==1.16.0 insightface==0.7.3 psutil==5.9.8 tk==0.1.0 customtkinter==5.2.2 pillow==9.5.0 torch==2.4.0+cu118; sys_platform != 'darwin' torch==2.4.0; sys_platform == 'darwin' torchvision==0.19.0+cu118; sys_platform != 'darwin' torchvision==0.19; sys_platform == 'darwin' onnxruntime==1.18.0; sys_platform == 'darwin' and platform_machine != 'arm64' onnxruntime-silicon==1.16.3; sys_platform == 'darwin' and platform_machine == 'arm64' onnxruntime-gpu==1.18.0; sys_platform != 'darwin' tensorflow==2.17.0; sys_platform == 'darwin' tensorflow==2.16.2; sys_platform != 'darwin' opennsfw2==0.10.2 protobuf==4.23.2 tqdm==4.66.4

Didn't work. Still same thing.

**Comment by vt57299** [comment]
I figured it out. Now I have a different problem, I am using linux server and running the code with xvfb library but still It doesn't shows the window for camera and image after running the `run.py` file.

**Comment by Pashok111** [comment]
> I figured it out. Now I have a different problem, I am using linux server and running the code with xvfb library but still It doesn't shows the window for camera and image after running the `run.py` file.

How you fix this issue?

**Comment by vt57299** [comment]
@Pashok111 

Try the following:

uninstall the current version of basicsr:
`pip uninstall basicsr -y`

install basicsr directly from its GitHub repository:
`pip install git+https://github.com/xinntao/BasicSR.git@master`

After installation is complete, also reinstall gfpgan:
`pip uninstall gfpgan -y`
`pip install git+https://github.com/TencentARC/GFPGAN.git@master`


This should resolve your issue.

**Comment by BlackAIGuru** [comment]
@vt57299 please let me know how to solve #226 issue

**Comment by fucsleep** [comment]
> uninstall the current version of basicsr: `pip uninstall basicsr -y`
> 
> install basicsr directly from its GitHub repository: `pip install git+https://github.com/xinntao/BasicSR.git@master`
> 
> After installation is complete, also reinstall gfpgan: `pip uninstall gfpgan -y` `pip install git+https://github.com/TencentARC/GFPGAN.git@master`

WORKED PERFECTLY

**Comment by AsusClass** [comment]
> @Pashok111
> 
> Try the following:
> 
> uninstall the current version of basicsr: `pip uninstall basicsr -y`
> 
> install basicsr directly from its GitHub repository: `pip install git+https://github.com/xinntao/BasicSR.git@master`
> 
> After installation is complete, also reinstall gfpgan: `pip uninstall gfpgan -y` `pip install git+https://github.com/TencentARC/GFPGAN.git@master`
> 
> This should resolve your issue.

Worked!

**Comment by BigJago722** [comment]
Hi,

I'm trying to run the Deep-Live-Cam project, but I'm encountering a problem. The ui.py file is missing from the modules directory. I've tried the following:

*   Cloning the repository using git clone: `git clone https://github.com/hacksider/Deep-Live-Cam.git`
*   Cloning the repository using GitHub Desktop.
*   Downloading the repository as a ZIP file.

In all cases, the ui.py file is not present.  I've also checked the repository on GitHub.com directly in my browser, and the file is missing there as well.

The modules directory contains the following files: [List the files you see].

Could you please let me know how to obtain the ui.py file?  Is it intentionally missing, or is there a separate download/generation step required?

Thanks for your help!

**Comment by hacksider** [comment]
@BigJago722 ui.py is available on git as per checking.

**Comment by prometheus-alien** [comment]
谢谢，好人一生平安

**Comment by premhaske1109** [comment]
> [@Pashok111](https://github.com/Pashok111)
> 
> Try the following:
> 
> uninstall the current version of basicsr: `pip uninstall basicsr -y`
> 
> install basicsr directly from its GitHub repository: `pip install git+https://github.com/xinntao/BasicSR.git@master`
> 
> After installation is complete, also reinstall gfpgan: `pip uninstall gfpgan -y` `pip install git+https://github.com/TencentARC/GFPGAN.git@master`
> 
> This should resolve your issue.

worked!!

**Comment by SaraMadTX** [comment]
I'm not hard core technical, but I figured how to get the program to run. However, I'm not able to solve the "face_enhancer isn't found" error. 

Any ideas of what I could try?

**Comment by annng** [comment]
did it work for windows too?

**Comment by zengjie617789** [comment]
It should add these into readme.md.
```
uninstall the current version of basicsr:
pip uninstall basicsr -y

install basicsr directly from its GitHub repository:
pip install git+https://github.com/xinntao/BasicSR.git@master

After installation is complete, also reinstall gfpgan:
pip uninstall gfpgan -y
pip install git+https://github.com/TencentARC/GFPGAN.git@master
```

**Comment by Mumzkid4** [comment]
Just a Suggestion I am making - if anyone is using it perfectly without any lags or any issues the person can outline a detailed step on how it was done and if possible maybe screenshots to also show us the exact way to do it - because the way and steps to do this and after it lags and all that

**Comment by Mynameisfuse** [comment]
> Just a Suggestion I am making - if anyone is using it perfectly without any lags or any issues the person can outline a detailed step on how it was done and if possible maybe screenshots to also show us the exact way to do it - because the way and steps to do this and after it lags and all that 

It keep lagging when I go live

**Comment by Mumzkid4** [comment]
yes once you go live

**Comment by SiNaPsEr0x** [comment]
> [@Pashok111](https://github.com/Pashok111)
> 
> Try the following:
> 
> uninstall the current version of basicsr: `pip uninstall basicsr -y`
> 
> install basicsr directly from its GitHub repository: `pip install git+https://github.com/xinntao/BasicSR.git@master`
> 
> After installation is complete, also reinstall gfpgan: `pip uninstall gfpgan -y` `pip install git+https://github.com/TencentARC/GFPGAN.git@master`
> 
> This should resolve your issue.

work on windows with default installation guide!!! good

**Comment by mirjajens-creator** [comment]
Why does face enhancer moves slower ?

**Comment by hacksider** [comment]
Because it's extra processing and it's multiplying the pixels x4

**Comment by mirjajens-creator** [comment]
Ok, thank you but why can’t I download the 2.0 DeepLiveCam software from
your website? After subscription!
The only one there is 2.2

**Comment by hacksider** [comment]
Did you login to the website? You have to login to the site and you will see the download button in there. What error did you encounter?

**Comment by fred21-dev** [comment]
I subscribed but the camera is not starting after clicking live it's blank

**Comment by mirjajens-creator** [comment]
Yes, I have subscribed $30 and all I can see and download is the 2.2
version
No other old version and when I click on Previous, it just pops up Error
page.

**Comment by hacksider** [comment]
I think this isn't the right way to communicate. You can email me at hacksider@gmail.com if you're a subscriber with the email you used on your subscription.

**Comment by hacksider** [comment]
We usually remove the older version as we don't need to support it and is usually making things more confusing as the newer versions have fixes.

**Comment by mirjajens-creator** [comment]
Ok, but I’d like to try the 2.1 and 2.0 version. And also, can’t you do
something to fix the face enhanced and make it a bit faster? Or are there
specific specs that makes it faster?

**Comment by hacksider** [comment]
As of now, no. Face enhancer will always be very slow since you're processing the image multiple times before it appears.

The version 2.3 will make the face enhancer 5x faster (depending in your specs).

Also, there will be a new model that won't need face enhancer.

It will be available very soon ☺️

**Comment by mirjajens-creator** [comment]
Ok thank you, but if the next one won’t need face enhancer then it should
be smooth and faster.
Face Enhancer looks very good, but it’s just too slow.

I’ve seen people complain about WhatsApp Video calls displaying very small,
do you have any idea why or how it can be solved?

**Comment by hacksider** [comment]
It's not as good as the one with face enhancer but is way better than the current one. 😁

**Comment by mirjajens-creator** [comment]
Ok, so we should wait for it? How soon will it be available? Because I have
subscribed for 3 months

**Comment by hacksider** [comment]
It should be available this October unless we encountered some issues.

**Comment by mirjajens-creator** [comment]
Ok, I will look forward to it.

**Comment by Mumzkid4** [comment]
What are they key features we should be expecting?

**Comment by hacksider** [comment]
It will be listed upon release 😁

**Comment by mirjajens-creator** [comment]
Please, I have sent you an email to your email address
***@***.***, kindly check and resolve my issue. I subscribed for 3
months and it’s been just a few days and it has ended already. Kindly check
your email and get this resolved for me.

**Comment by hacksider** [comment]
As I have said, it is not expired yet. You can still download the files in
there.

Regards, Ken

**Comment by hacksider** [comment]
> Please, my subscription issues have not been resolved, I can’t download
> 
> anything, it still says I should subscribe again, meanwhile i subscribed it
> 
> for 3 months
> 
> 

Hi there, I believe we're already in contact via email. I already answered it on email as well.

**Comment by mirjajens-creator** [comment]
Please, I send you a message via your email and I have never received
anything from you until now and the problem is still there and has not been
resolved. I sent my username and screenshots are you asked, but never
received anything.

**Comment by mirjajens-creator** [comment]
Please screenshot of what exactly?

**Comment by obsidianocean** [comment]
if face_enhancer not loading/gafner access is denied it means you didn't run python as a admin. Took me forever just to figure this out
