### ISSUE TITLE
How to improve processing speed of "Live" mode

### ISSUE THREAD

**Issue by FMsunyh** [hacksider/Deep-Live-Cam#279]
Hello,
I would like to ask, where can I start to improve the processing speed?
Based on the test result of "Live" mode , it cannot achieve real-time performance, and I want to improve the speed.

CPU : i7-13700
GPU: 4090D
Memory: 48G

**Comment by cvaisnor** [comment]
Are you running the main script with cuda enabled? On my AMD Ryzen 9 7950x I get about 3 FPS using all the cores, and when I run it with Docker through my 4090 it is definitely close to 30FPS.

**Comment by FMsunyh** [comment]
> Are you running the main script with cuda enabled? On my AMD Ryzen 9 7950x I get about 3 FPS using all the cores, and when I run it with Docker through my 4090 it is definitely close to 30FPS.

What is the frame size of the video stream? I am Setting it to 640x360 can reach 25fps, but it will get stuck if it is larger(such as 960x540). I need clearer picture quality.

**Comment by FMsunyh** [comment]
> Are you running the main script with cuda enabled? On my AMD Ryzen 9 7950x I get about 3 FPS using all the cores, and when I run it with Docker through my 4090 it is definitely close to 30FPS.

Also, by pulling the stream through rtmp, it can currently achieve 1280x720p, without face enhancement, do you have a good solution to speed up face enhancement?

**Comment by cvaisnor** [comment]
I am running the stream in the default resolution. Using 'face enhancement' with cuda enabled did bring the frames down quite a bit. It runs at around 10FPS now. I'm not sure how to speed up that configuration.

**Comment by maxfrans** [comment]
Up, which gpu'll work best for this? considering a laptop or pc to buy within 2-3k

**Comment by FMsunyh** [comment]
> Up, which gpu'll work best for this? considering a laptop or pc to buy within 2-3k
CPU : i7-13700
GPU: 4090D
Memory: 48G

I modified the code and added multi-threaded processing. 1280x720p can be done in real time. The problem now is that I can't turn on enhanced processing.
