### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by pablo1794** [hacksider/Deep-Live-Cam#28]
The application doesn't run after running the start command. Can any anybody help ? I've done everything right but after the python run.py ----execution-provider cuda nothing happens the app doesn't get started

**Comment by hacksider** [comment]
Can you provide the error message?

**Comment by pablo1794** [comment]
there's no error message at all. When I run it stays and then go to a new line on anaconda but the cam app doesn't open like it's suppose to. Can you help me through AD ?

**Comment by hacksider** [comment]
`python run.py --execution-provider cuda`
Try the command on top. You have too many dashes
