### ISSUE TITLE
The app does not see camera if i use DroidCamX

### ISSUE THREAD

**Issue by Dimarom4** [hacksider/Deep-Live-Cam#280]
If i use my phone as a camera with DroidCamX I get an error
```
[ WARN:0@22.409] global cap.cpp:323 cv::VideoCapture::open VIDEOIO(DSHOW): raised unknown C++ exception!


[ERROR:0@22.412] global obsensor_uvc_stream_channel.cpp:158 cv::obsensor::getStreamChannelGroup Camera index out of range
```

**Comment by lulu3243** [comment]
i have the same error

**Comment by FabioFlorey** [comment]
Did you solve the error, @lulu3243 
I saw you opened a new issue with that same error and now it's closed.
If so, can you write down the steps?

**Comment by FabioFlorey** [comment]
solved on Windows laptop camera. Make sure your webcam is visibile and authorized.
![image](https://github.com/user-attachments/assets/f3bb1104-e4ad-47b7-9825-13f96a1bc9a7)

Not sure if it can help.
