### ISSUE TITLE
The hairstyle doesn't change

### ISSUE THREAD

**Issue by nyan00320** [hacksider/Deep-Live-Cam#298]
Hello.
I was successful in running the tool without using the GPU.
I used the model introduced in the following issue.
https://github.com/hacksider/Deep-Live-Cam/issues/133

I'm having trouble because when I run the tool, only the subject's face changes.
How can I change the hairstyle as well?
I'd appreciate some advice.
![image](https://github.com/user-attachments/assets/76470eed-872c-4a71-8c3c-9c09b89f2209)
![output](https://github.com/user-attachments/assets/03e95a3f-7706-4313-a10a-de6f11d2aacb)

**Comment by hacksider** [comment]
This is not part of any feature.
