### ISSUE TITLE
Face enhacement Lower FPS

### ISSUE THREAD

**Issue by aroca69** [hacksider/Deep-Live-Cam#3]
I´m using your repository with GPU. I have Nvidia geforce RTX 3070 with cuda installed.
The software is working great but when i use face enhacement, is awesome, lowers the FPS and is isposible to use. Any tips to avoid lowering FPS when using face enhacement?
Thanks in advance

**Comment by hacksider** [comment]
As of now there's no way to increase the FPS unless you have bigger buffer/VRAM as it is being preprocessed using GFPGAN. 

I just remembered, you can change the resolution (I suggest 480p) on ui.py to make more faster.

**Comment by aroca69** [comment]
Thanks a lot for your advice and also for the new model you updated yesterday, now is working fast with Cuda. Awesome software.

**Comment by hacksider** [comment]
Awesome! Great to hear that it's working fine on your end!

**Comment by mvthul** [comment]
Face enhancer on getting only 4-5 FPS on rtx 4090.

Also live resizable option not working for me. Need to edit code to set resolution.

Is there any way to fully use the gpu memory ?
