### ISSUE TITLE
No module named 'distutils' on ubuntu 24-04

### ISSUE THREAD

**Issue by esobreira** [hacksider/Deep-Live-Cam#304]
I get ModuleNotFoundError: No module named 'distutils' on Ubuntu 24-04. Any advice?

![image](https://github.com/user-attachments/assets/77958cb4-6d41-421d-b8b6-ee77b1695560)

**Comment by esobreira** [comment]
guys just use python 3.9.

**Comment by Mike-Medvedev** [comment]
Yes but you can also pip install setuptools which includes distutils, this is what i do when i get that error on anything > python 3.8

**Comment by esobreira** [comment]
> Yes but you can also pip install setuptools which includes distutils, this is what i do when i get that error on anything > python 3.8

thank you my man I have installed using python 3.9 and distutils. From what I know with python 3.12 distutils is deprecated, by downgrading I installed and ran this application quite well.

**Comment by Hopeyu** [comment]
> > Yes but you can also pip install setuptools which includes distutils, this is what i do when i get that error on anything > python 3.8
> 
> thank you my man I have installed using python 3.9 and distutils. From what I know with python 3.12 distutils is deprecated, by downgrading I installed and ran this application quite well.

Hey bro can you help me out I've been having  some installation issues 
![IMG-20240903-WA0008](https://github.com/user-attachments/assets/d9763bed-8cc4-4ddd-a6d1-10e32b4c001b)

**Comment by Mike-Medvedev** [comment]
> > > Yes but you can also pip install setuptools which includes distutils, this is what i do when i get that error on anything > python 3.8
> > 
> > 
> > thank you my man I have installed using python 3.9 and distutils. From what I know with python 3.12 distutils is deprecated, by downgrading I installed and ran this application quite well.
> 
> Hey bro can you help me out I've been having some installation issues ![IMG-20240903-WA0008](https://private-user-images.githubusercontent.com/90970442/364045718-d9763bed-8cc4-4ddd-a6d1-10e32b4c001b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzODY1NzgsIm5iZiI6MTcyNTM4NjI3OCwicGF0aCI6Ii85MDk3MDQ0Mi8zNjQwNDU3MTgtZDk3NjNiZWQtOGNjNC00ZGRkLWE2ZDEtMTBlMzJiNGMwMDFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE3NTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYzJjOWJmMWRmZDlkZjZiMTIwZGFkNWU4YjAyZDkxMWY2NzIwZDgzNDcyNGJhOTQ1NTg3MDYzOTQzMzRjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QBuDD29p-_nQedqhpHmSxzCEZsnA93SRNqMzPItIzng)

What Version of python are you using to run this repo?
