### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by MinhHanZo** [hacksider/Deep-Live-Cam#306]
ERROR: Could not install packages due to an OSError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Admin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\onnx\\backend\\test\\data\\node\\test_averagepool_3d_dilations_large_count_include_pad_is_0_ceil_mode_is_False\\test_data_set_0'

**Comment by Maxlee2704** [comment]
Same with you.
If you solved this issue, I would appreciate if you could show me how to do.
Thank you so much.

**Comment by cyba3r** [comment]
Same here, python 3.10 in venv

**Comment by cyba3r** [comment]
It was my vault, instead of using ".\.env\Scripts\Activate.ps1" I used ".\.env\Scripts\activate.bat". That doesnt work in Powershell ;-)
