### ISSUE TITLE
Frame processor face_enhancer not found

### ISSUE THREAD

**Issue by ZzQqXie** [hacksider/Deep-Live-Cam#309]
what can i do to slove this problem???
![联想截图_20240814135358](https://github.com/user-attachments/assets/6d65924b-3771-4cb8-af0d-f5e2139cf76b)

**Comment by aicools** [comment]
I also meet this problem, how do you make it

**Comment by aicools** [comment]
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3

It works.(By NV ENV)

**Comment by ZzQqXie** [comment]
> pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3
> 
> It works.(By NV ENV)

yes, it worked, thank you very much!!! 
now i have a new problem that the output is so blurry  and maybe i need to use GPU to run this program
