### ISSUE TITLE
Doesn't work on macOS on M1 Pro

### ISSUE THREAD

**Issue by rouol** [hacksider/Deep-Live-Cam#31]
I'm using MacBook Pro M1 Pro on macOS Sonoma 14.3.1 (23D60). Installed as stated in manual.

launched with a command
`python run.py --execution-provider coreml
`

Chose an image
<img width="626" alt="image" src="https://github.com/hacksider/Deep-Live-Cam/assets/69370969/b0b75911-90b3-479e-8ad8-5a1e3a8d3d8c">

When I'm trying to run LIVE, I get that error and black preview window:
`python run.py --execution-provider coreml
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/rouol/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/rouol/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/rouol/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/rouol/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/rouol/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py310tf/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/rouol/Code/WORK/Deep-Live-Cam/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_button.py", line 553, in _clicked
    self._command()
  File "/Users/rouol/Code/WORK/Deep-Live-Cam/modules/ui.py", line 104, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
  File "/Users/rouol/Code/WORK/Deep-Live-Cam/modules/ui.py", line 286, in webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
  File "/Users/rouol/Code/WORK/Deep-Live-Cam/modules/processors/frame/face_swapper.py", line 60, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "/Users/rouol/Code/WORK/Deep-Live-Cam/modules/processors/frame/face_swapper.py", line 48, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "/Users/rouol/Code/WORK/Deep-Live-Cam/venv/lib/python3.10/site-packages/insightface/model_zoo/inswapper.py", line 50, in get
    latent = source_face.normed_embedding.reshape((1,-1))
AttributeError: 'NoneType' object has no attribute 'normed_embedding'`

<img width="1728" alt="image" src="https://github.com/hacksider/Deep-Live-Cam/assets/69370969/a96c5eaf-ae2b-4575-a770-cd148d1032c9">

**Comment by Updatedme** [comment]
It works in macbook.

**Comment by zachary** [comment]
yes, I have the same issue on M1 pro
