### ISSUE TITLE
Leaked Semaphore Objects - Video Face Swap Issue

### ISSUE THREAD

**Issue by e-basaran** [hacksider/Deep-Live-Cam#311]
```
[DLC.CORE] Creating temp resources...
[DLC.CORE] Extracting frames...
[DLC.FACE-SWAPPER] Progressing...
Processing:   0%| | 2/1306 [00:01<16:09,  1.34frame/s, execution_providers=['CoreMLExecutionProvider'], execution_threads=8, max_memory=4Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Processing:  27%|██▋       | 359/1306 [02:04<05:59,  2.63frame/s, execution_providers=['CoreMLExecutionProvider'], execution_threads=8, max_memory=4]zsh: killed     python3 run.py --execution-provider coreml

/opt/miniconda3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
When I try to process a video, it gives the above error near 25%. I couldn't find a valid fix.

Regards.

**Comment by snacsnoc** [comment]
Trying lowering the maximum memory used with `--max-memory`, I ran into this same issue.

**Comment by Retha23** [comment]
Isn't it 4 by default, I tried to change but it said Python int too large
something.

**Comment by riddlegit** [comment]
It should be a coreml issue, I ran into the same problem on macos m1, try this and it works for me:
download a custom build onnxruntime_silicon from https://github.com/cansik/onnxruntime-silicon/releases/tag/v1.14.2
pip uninstall onnxruntime_silicon
pip install onnxruntime_silicon-1.14.2-cpxxx-cpxxx-macosx_12_0_arm64.whl (replace xxx with your version)

now you dont need to set max-memory and it wont leak again, have fun.
