### ISSUE TITLE
Sometimes the face of som frames are not modified

### ISSUE THREAD

**Issue by Zeelyne** [hacksider/Deep-Live-Cam#313]
Hi guys,
I uploaded a target video, in which the faces evolution in the frames is small. 
In the result, in most of the frames, the face is well modifed and adapted to the uploaded face image; yet in some frames, the face was not modified. The output faces of these frames are slightly retouched, I could see that they were rendered and were not the original ones, even though the difference was very very limited. I wonder why the magic didnt work on these frames, as, in these framesof the target video, the face was well exposed and defined, the eyes/noses/etc were not deformed. (But the mouth was actually  moving fast, as the person is speaking)

Would you please give me some suggetsions?
Thanks a lot!!

**Comment by hacksider** [comment]
They only render if the face is clear enough. Usually when it detects both eyes, nose and mouth. If it goes beyond that, then it will have a high chance it won't render properly (or if target gets covered).

**Comment by hacksider** [comment]
If you're planning on just doing videos, I suggest facefusion as it is way better when it comes to video processing. As of now we're focusing on real-time deep fake. ☺️
