### ISSUE TITLE
can't get rid of black square on face because of this

### ISSUE THREAD

**Issue by MotvUnknown** [hacksider/Deep-Live-Cam#314]
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.16.3 (from versions: 1.17.0, 1.17.1, 1.18.0, 1.18.1)
ERROR: No matching distribution found for onnxruntime-gpu==1.16.3

![help](https://github.com/user-attachments/assets/a9b68c79-c758-407b-9b6f-d90d50751573)

**Comment by iKroNN** [comment]
Did you manage to solve it?

**Comment by MotvUnknown** [comment]
> Did you manage to solve it?

I have not been able to solve it yet.

**Comment by iKroNN** [comment]
Eu consegui! tente substituir esse modelo aqui no lugar do que você tem! https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx @MotvUnknown
