### ISSUE TITLE
How to select the correct camera?

### ISSUE THREAD

**Issue by marco-qu** [hacksider/Deep-Live-Cam#315]
How to select the correct camera ? 
Is there any method to improve the output resolution of the camera?

**Comment by turbolego** [comment]
> How to select the correct camera ? Is there any method to improve the output resolution of the camera?

In the file `modules/ui.py`:

`    cap = cv2.VideoCapture(0)  # Use index for the webcam (adjust the index accordingly if necessary)`

I had to set mine to "3" not "0" for everything to work.
