### ISSUE TITLE
pip install -r requirements.txt error

### ISSUE THREAD

**Issue by ShadowSurferr** [hacksider/Deep-Live-Cam#318]
C:\Users\User\Desktop\Deep-Live-Cam-main>pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow: markers 'sys_platform == "darwin"' don't match your environment
Collecting numpy>=1.26.0 (from -r requirements.txt (line 3))
  Using cached numpy-2.0.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting opencv-python==4.8.1.78 (from -r requirements.txt (line 4))
  Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting onnx==1.16.0 (from -r requirements.txt (line 5))
  Using cached onnx-1.16.0-cp311-cp311-win_amd64.whl.metadata (16 kB)
Collecting insightface==0.7.3 (from -r requirements.txt (line 6))
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting psutil==5.9.8 (from -r requirements.txt (line 7))
  Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl.metadata (22 kB)
Collecting tk==0.1.0 (from -r requirements.txt (line 8))
  Using cached tk-0.1.0-py3-none-any.whl.metadata (693 bytes)
Collecting customtkinter==5.2.2 (from -r requirements.txt (line 9))
  Using cached customtkinter-5.2.2-py3-none-any.whl.metadata (677 bytes)
Collecting pillow==9.5.0 (from -r requirements.txt (line 10))
  Using cached Pillow-9.5.0-cp311-cp311-win_amd64.whl.metadata (9.7 kB)
Collecting torch==2.0.1+cu118 (from -r requirements.txt (line 11))
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp311-cp311-win_amd64.whl (2619.2 MB)
Collecting torchvision==0.15.2+cu118 (from -r requirements.txt (line 13))
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp311-cp311-win_amd64.whl (4.9 MB)
Collecting onnxruntime-gpu==1.18.0 (from -r requirements.txt (line 17))
  Using cached onnxruntime_gpu-1.18.0-cp311-cp311-win_amd64.whl.metadata (4.4 kB)
Collecting tensorflow==2.12.1 (from -r requirements.txt (line 19))
  Using cached tensorflow-2.12.1-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting opennsfw2==0.10.2 (from -r requirements.txt (line 20))
  Using cached opennsfw2-0.10.2-py3-none-any.whl.metadata (11 kB)
Collecting protobuf==4.23.2 (from -r requirements.txt (line 21))
  Using cached protobuf-4.23.2-cp310-abi3-win_amd64.whl.metadata (540 bytes)
Collecting tqdm==4.66.4 (from -r requirements.txt (line 22))
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
Collecting gfpgan==1.3.8 (from -r requirements.txt (line 23))
  Using cached gfpgan-1.3.8-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (2.31.0)
Collecting matplotlib (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached matplotlib-3.9.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting scipy (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached scipy-1.14.0-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting scikit-learn (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached scikit_learn-1.5.1-cp311-cp311-win_amd64.whl.metadata (12 kB)
Collecting scikit-image (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached scikit_image-0.24.0-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting easydict (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached easydict-1.13-py3-none-any.whl.metadata (4.2 kB)
Collecting cython (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached Cython-3.0.11-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
Collecting albumentations (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached albumentations-1.4.13-py3-none-any.whl.metadata (38 kB)
Collecting prettytable (from insightface==0.7.3->-r requirements.txt (line 6))
  Using cached prettytable-3.11.0-py3-none-any.whl.metadata (30 kB)
Collecting darkdetect (from customtkinter==5.2.2->-r requirements.txt (line 9))
  Using cached darkdetect-0.8.0-py3-none-any.whl.metadata (3.6 kB)
Collecting packaging (from customtkinter==5.2.2->-r requirements.txt (line 9))
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting filelock (from torch==2.0.1+cu118->-r requirements.txt (line 11))
  Using cached filelock-3.15.4-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from torch==2.0.1+cu118->-r requirements.txt (line 11)) (4.7.1)
Collecting sympy (from torch==2.0.1+cu118->-r requirements.txt (line 11))
  Using cached sympy-1.13.2-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.0.1+cu118->-r requirements.txt (line 11))
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Collecting jinja2 (from torch==2.0.1+cu118->-r requirements.txt (line 11))
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting coloredlogs (from onnxruntime-gpu==1.18.0->-r requirements.txt (line 17))
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting flatbuffers (from onnxruntime-gpu==1.18.0->-r requirements.txt (line 17))
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
Collecting tensorflow-intel==2.12.1 (from tensorflow==2.12.1->-r requirements.txt (line 19))
  Using cached tensorflow_intel-2.12.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting gdown>=4.2.0 (from opennsfw2==0.10.2->-r requirements.txt (line 20))
  Using cached gdown-5.2.0-py3-none-any.whl.metadata (5.8 kB)
Collecting colorama (from tqdm==4.66.4->-r requirements.txt (line 22))
  Using cached https://download.pytorch.org/whl/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting basicsr>=1.4.2 (from gfpgan==1.3.8->-r requirements.txt (line 23))
  Using cached basicsr-1.4.2-py3-none-any.whl
Collecting facexlib>=0.2.5 (from gfpgan==1.3.8->-r requirements.txt (line 23))
  Downloading facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)
Collecting lmdb (from gfpgan==1.3.8->-r requirements.txt (line 23))
  Downloading lmdb-1.5.1-cp311-cp311-win_amd64.whl.metadata (1.1 kB)
Requirement already satisfied: pyyaml in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from gfpgan==1.3.8->-r requirements.txt (line 23)) (6.0.1)
Collecting tb-nightly (from gfpgan==1.3.8->-r requirements.txt (line 23))
  Using cached tb_nightly-2.18.0a20240814-py3-none-any.whl.metadata (1.6 kB)
Collecting yapf (from gfpgan==1.3.8->-r requirements.txt (line 23))
  Downloading yapf-0.40.2-py3-none-any.whl.metadata (45 kB)
Collecting absl-py>=1.0.0 (from tensorflow-intel==2.12.1->tensorflow==2.12.1->-r requirements.txt (line 19))
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow-intel==2.12.1->tensorflow==2.12.1->-r requirements.txt (line 19))
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting gast<=0.4.0,>=0.2.1 (from tensorflow-intel==2.12.1->tensorflow==2.12.1->-r requirements.txt (line 19))
  Downloading gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
Collecting google-pasta>=0.1.1 (from tensorflow-intel==2.12.1->tensorflow==2.12.1->-r requirements.txt (line 19))
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting h5py>=2.9.0 (from tensorflow-intel==2.12.1->tensorflow==2.12.1->-r requirements.txt (line 19))
  Downloading h5py-3.11.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting jax>=0.3.15 (from tensorflow-intel==2.12.1->tensorflow==2.12.1->-r requirements.txt (line 19))
  Downloading jax-0.4.31-py3-none-any.whl.metadata (22 kB)
Collecting libclang>=13.0.0 (from tensorflow-intel==2.12.1->tensorflow==2.12.1->-r requirements.txt (line 19))
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
INFO: pip is looking at multiple versions of tensorflow-intel to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 13), -r requirements.txt (line 17), -r requirements.txt (line 20), -r requirements.txt (line 23), -r requirements.txt (line 4), -r requirements.txt (line 5), -r requirements.txt (line 6), numpy>=1.26.0 and tensorflow because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy>=1.26.0
    opencv-python 4.8.1.78 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python 4.8.1.78 depends on numpy>=1.23.5; python_version >= "3.11"
    opencv-python 4.8.1.78 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python 4.8.1.78 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python 4.8.1.78 depends on numpy>=1.19.3; python_version >= "3.9"
    onnx 1.16.0 depends on numpy>=1.20
    insightface 0.7.3 depends on numpy
    torchvision 0.15.2+cu118 depends on numpy
    onnxruntime-gpu 1.18.0 depends on numpy>=1.26.0
    opennsfw2 0.10.2 depends on numpy>=1.22.0
    gfpgan 1.3.8 depends on numpy
    tensorflow-intel 2.12.1 depends on numpy<=1.24.3 and >=1.22

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by krishansq** [comment]
What version of python are you using? I was having that error until I switched from 3.11 to 3.10.

**Comment by homegrownhrbs** [comment]
same, its works with 3.10 but not 3.11

**Comment by vladimir-pudding** [comment]
If you are planning to use it with an NVIDIA GPU, you can first change onnxruntime-gpu to version 1.16.3 (you would install the lower version further in the installation process anyway, as described in the guide). After that, it doesn't require numpy version 1.26.0 anymore. Then set numpy to 1.24.3; you can't go any higher than that because of tensorflow-intel. This worked perfectly for me with using Python 3.11

**Comment by homegrownhrbs** [comment]
> If you are planning to use it with an NVIDIA GPU, you can first change onnxruntime-gpu to version 1.16.3 (you would install the lower version further in the installation process anyway, as described in the guide). After that, it doesn't require numpy version 1.26.0 anymore. Then set numpy to 1.24.3; you can't go any higher than that because of tensorflow-intel. This worked perfectly for me while using Python 3.11

good shout! here is the requirements.txt that works for 3.11:

--extra-index-url https://download.pytorch.org/whl/cu118

numpy==1.24.3
opencv-python==4.8.1.78
onnx==1.16.0
insightface==0.7.3
psutil==5.9.8
tk==0.1.0
customtkinter==5.2.2
pillow==9.5.0
torch==2.0.1+cu118; sys_platform != 'darwin'
torch==2.0.1; sys_platform == 'darwin'
torchvision==0.15.2+cu118; sys_platform != 'darwin'
torchvision==0.15.2; sys_platform == 'darwin'
onnxruntime==1.18.0; sys_platform == 'darwin' and platform_machine != 'arm64'
onnxruntime-silicon==1.16.3; sys_platform == 'darwin' and platform_machine == 'arm64'
onnxruntime-gpu==1.16.3; sys_platform != 'darwin'
tensorflow==2.13.0rc1; sys_platform == 'darwin'
tensorflow==2.12.1; sys_platform != 'darwin'
opennsfw2==0.10.2
protobuf==4.23.2
tqdm==4.66.4
gfpgan==1.3.8

**Comment by curious-itauditor** [comment]
Anyone have the requirements.txt that works for Macbook Air M2?

**Comment by waterwsg** [comment]
> Anyone have the requirements.txt that works for Macbook Air M2?

Have you solved the same problem now?

**Comment by krishansq** [comment]
> > Anyone have the requirements.txt that works for Macbook Air M2?
> 
> Have you solved the same problem now?

Using python 3.10, this is my requirements.txt

--extra-index-url https://download.pytorch.org/whl/cu118

numpy>=1.22,<1.26
opencv-python==4.8.1.78
onnx==1.16.0
insightface==0.7.3
psutil==5.9.8
tk==0.1.0
customtkinter==5.2.2
pillow==9.5.0
torch==2.0.1+cu118; sys_platform != 'darwin'
torch==2.0.1; sys_platform == 'darwin'
torchvision==0.15.2+cu118; sys_platform != 'darwin'
torchvision==0.15.2; sys_platform == 'darwin'
onnxruntime==1.18.0; sys_platform == 'darwin' and platform_machine != 'arm64'
onnxruntime-silicon==1.16.3; sys_platform == 'darwin' and platform_machine == 'arm64'
onnxruntime-gpu==1.18.0; sys_platform != 'darwin'
tensorflow==2.13.0rc1; sys_platform == 'darwin'
tensorflow==2.12.1; sys_platform != 'darwin'
opennsfw2==0.10.2
protobuf==4.23.2
tqdm==4.66.4
gfpgan==1.3.8

**Comment by hacksider** [comment]
Check the discussion, there's an instruction there for macbook setup
