### ISSUE TITLE
Green pixels output

### ISSUE THREAD

**Issue by Tranks27** [hacksider/Deep-Live-Cam#320]
Hi, I can preview the output well but in the output video, it's all green and black pixels like it's corrupted. How can I solve this? Thanks

**Comment by Tranks27** [comment]
Update: 
The live feed is fine too. Only the output video is corrupted.

**Comment by rohitdash08** [comment]
how did you fix that? I'm still getting black patch on the face and the face is also not swapping.

**Comment by Tranks27** [comment]
> how did you fix that? I'm still getting black patch on the face and the face is also not swapping.

I followed the instructions on using GPU- CUDA

**Comment by mynp886** [comment]
where  it 
the instructions on using GPU- CUDA

**Comment by NkosenhleDuma** [comment]
Seeing the same green screen issue with my CUDA installation (same with the CPU execution target)

**Comment by rohitdash08** [comment]
@Tranks27, Thank you soo much it was helpful.
