### ISSUE TITLE
Feature Request: Add Support for AMD GPUs

### ISSUE THREAD

**Issue by TheRedCyclops** [hacksider/Deep-Live-Cam#333]
I know it's a big ask, but it would be great if support for AMD GPUs would be considered for this project.

**Comment by vodangtue** [comment]
I'm waiting for this too.

**Comment by solstice-gao** [comment]
I'm waiting for this too.

**Comment by yosr481** [comment]
I think the directML should work with AMD

**Comment by TiberiusMars** [comment]
Trying to use directml with AMD gives me this:

`python run.py --execution-provider directml

usage: run.py [-h] [-s SOURCE_PATH] [-t TARGET_PATH] [-o OUTPUT_PATH]
              [--frame-processor {face_swapper,face_enhancer} [{face_swapper,face_enhancer} ...]] [--keep-fps]
              [--keep-audio] [--keep-frames] [--many-faces] [--video-encoder {libx264,libx265,libvpx-vp9}]
              [--video-quality [0-51]] [--max-memory MAX_MEMORY] [--execution-provider {dml,cpu} [{dml,cpu} ...]]
              [--execution-threads EXECUTION_THREADS] [-v]
run.py: error: argument --execution-provider: invalid choice: 'directml' (choose from 'dml', 'cpu')`

Using `python run.py --execution-provider dml` works well and fast for "Preview" until you set everything up and press "Start" - it crashes right after this line:

`Processing:   0%| | 0/188 [00:00<?, ?frame/s, execution_providers=['DmlExecutionProvider'], execution_threads=8, max_me`

It never gets to 1%.

**Comment by laggggggg** [comment]
Identical issues to TiberiusMars with my RX 6650xt, including using dml.

**Comment by cjr60013255** [comment]
Waiting for this

**Comment by d1stru3t0r** [comment]
Waiting for this too.

**Comment by vodangtue** [comment]
I can use AMD GPU with directml. It work perfectly until face enhancer enabled, when face enhancer enabled it not use any GPU or CPU and it generate very slow.

**Comment by yosr481** [comment]
> Trying to use directml with AMD gives me this:
> 
> `python run.py --execution-provider directml
> 
> usage: run.py [-h] [-s SOURCE_PATH] [-t TARGET_PATH] [-o OUTPUT_PATH] [--frame-processor {face_swapper,face_enhancer} [{face_swapper,face_enhancer} ...]] [--keep-fps] [--keep-audio] [--keep-frames] [--many-faces] [--video-encoder {libx264,libx265,libvpx-vp9}] [--video-quality [0-51]] [--max-memory MAX_MEMORY] [--execution-provider {dml,cpu} [{dml,cpu} ...]] [--execution-threads EXECUTION_THREADS] [-v] run.py: error: argument --execution-provider: invalid choice: 'directml' (choose from 'dml', 'cpu')`
> 
> Using `python run.py --execution-provider dml` works well and fast for "Preview" until you set everything up and press "Start" - it crashes right after this line:
> 
> `Processing: 0%| | 0/188 [00:00<?, ?frame/s, execution_providers=['DmlExecutionProvider'], execution_threads=8, max_me`
> 
> It never gets to 1%.

Maybe try to play with other parameters, like video quality, or the encoder

**Comment by skrohit22087** [comment]
Try running with --execution-threads 1 and increase the value according to you gpu's vram usage

**Comment by skrohit22087** [comment]
it does work on my 6500m.

Try running with `python run.py --execution-provider dml --execution-threads 1 --max-memory 4` and increase the value of threads and max-memory according to you gpu's vram usage(for failsafe launch by set threads 1 and max memory lower than your vram first time). and if you are using nsfw content uncomment nsfw options from ui.py in  \Deep-Live-Cam\modules location(otherwise it may crash).
