### ISSUE TITLE
Mosaic on the face

### ISSUE THREAD

**Issue by mynp886** [hacksider/Deep-Live-Cam#334]
It works fine but there is a mosaic-like thing on the face. The models and modules are all imported normally.

**Comment by zandervs** [comment]
I also have this issue

**Comment by johnson7788** [comment]
https://github.com/user-attachments/assets/0ded92ea-7330-4586-9d36-5354ce774fec

I also have this issue, i use cuda on ubuntu.

**Comment by johnson7788** [comment]
Sovled by https://github.com/hacksider/Deep-Live-Cam/issues/382#issuecomment-2294827989
