### ISSUE TITLE
only shows black Square

### ISSUE THREAD

**Issue by Repulzer** [hacksider/Deep-Live-Cam#336]
The Live only shows a Black square on my Face... not really worth the effort/time to install it.

![Unbenannt](https://github.com/user-attachments/assets/d887a15f-cf4b-49ce-b1a7-9322c85a423c)

I even tried to use the same example image.
![config](https://github.com/user-attachments/assets/c24a04f9-8c5d-4d6d-b25d-12d839441285)

**Comment by Repulzer** [comment]
Solved by doing following:

`
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3
`

**Comment by FabioFlorey** [comment]
> Solved by doing following:
> 
> `pip uninstall onnxruntime onnxruntime-gpu` `pip install onnxruntime-gpu==1.16.3`

I have the following error:

```                                                               
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.16.3 (from versions: 1.17.0, 1.17.1, 1.18.0, 1.18.1, 1.19.0)
ERROR: No matching distribution found for onnxruntime-gpu==1.16.3
```

And I can't find a whl file to install. I'm on Windows 11 - Python 3.12.4

**Comment by Sscicada** [comment]
@Repulzer Useful, thanks
