### ISSUE TITLE
Preview blackscreen

### ISSUE THREAD

**Issue by CalvinKluk** [hacksider/Deep-Live-Cam#339]
If I try to use the webcam in live mode, the LED from my webcam turns on, but the preview screen is just black.

**Comment by liusome** [comment]
same, I use GoPro 10

**Comment by jasonlbx13** [comment]
same problem

**Comment by mikegazzaruso** [comment]
Most likely your input image is not suitable (i.e. too small or too big, or not clear enough)

**Comment by oliverban** [comment]
Same here, just black preview. No errors in cmd! What are the recommended resolutions? Anyone know?

**Comment by superaplicativos** [comment]
I was experiencing the same issue with Deep Live Cam, where the preview screen stayed black even though the LED on my webcam was on. In my case, I found out that there was another camera set as the default on my system, which was causing the problem.

Here’s what I did to fix it:

Checked the installed cameras: I went to the Device Manager and located the extra camera that was set as the default.
Uninstalled the extra camera: In the Device Manager, I right-clicked on the extra camera (in my case, "IdeaCamera") and selected "Uninstall device."
Set the correct webcam as default: I made sure that my main webcam was functioning correctly after removing the extra camera.

After doing this, Deep Live Cam started working correctly. However, I'm now facing a new problem: there's a black square over my face, and the face swap isn’t working properly. Has anyone encountered this issue and knows how to fix it?

**Comment by hacksider** [comment]
Make sure that your camera is the default camera. If you have a virtual camera, it might be the one set to default.

**Comment by Dyablopegasus** [comment]
No error during the installation process but my output brings out a black square over my video, how do I rectify

**Comment by hacksider** [comment]
Try checking the version of onnx runtime you're using if it is correct.

**Comment by Dyablopegasus** [comment]
Yes the version of onnx runtime is correct, but the black square still
covers my output

**Comment by Dyablopegasus** [comment]
Please how do I rectify it, that’s the only problem I’m having right now

**Comment by Spectre-SX** [comment]
I have my camera, and it enabled. When i use it through any other app, it works. I have it selected in the app, and when i click "Live" only a gray screen appears.

**Comment by dehumblePrince** [comment]
> Most likely your input image is not suitable (i.e. too small or too big, or not clear enough)

My deep live cam have been hanging Since I downloaded it and because of it I never use it. How do I resolve it pls
