### ISSUE TITLE
[Bug in Experimental] Cannot import windll on Linux

### ISSUE THREAD

**Issue by NXTler** [hacksider/Deep-Live-Cam#348]
Greeting,
as the name suggests, I get the following error when trying to start in experimental branch:
`ImportError: cannot import name 'windll' from 'ctypes' (/usr/lib/python3.10/ctypes/__init__.py)`

I suspect that either windll cannot be found as it is Windows specific or that a dependency is missing in requirements. I'm no developer, so I can't really tell.

**Comment by tostr7191** [comment]
same on macos, it seems `experimental` is currently windows-only (there is also some code that works with COM, which is also windows only afaik).
