### ISSUE TITLE
[Linux] Preview Window is not opening

### ISSUE THREAD

**Issue by cleptocat** [hacksider/Deep-Live-Cam#349]
There were no issues when installing the project. Similarly, the picture deepfaking works fine. The only issue I'm getting is when trying to get the live camera to work.
![image](https://github.com/user-attachments/assets/7eece2c3-127b-469d-a418-7ea9c997ef3c)

The thin rectangle that has been highlighted in red is the preview window I'm seeing. It can't be resized or altered in any way.
The PC still consumes a lot of CPU resources while the preview window is running, which would imply that the program is still working fine, but not showing the result on screen. 

This is the console output:
![image](https://github.com/user-attachments/assets/66b1a5b2-7d13-4103-8e29-e293e2b84492)

Please let me know if any other logs need to be provided.

**Comment by NkosenhleDuma** [comment]
I get the same issue. The slice does change colour when I move objects in front of the camera.

**Comment by wolkenschieber** [comment]
Also happens in my [dockerized version](https://github.com/wolkenschieber/deep-live-cam-docker).
