### ISSUE TITLE
When I use openvino for a laptop using an Intel Xe Graphic  GPU, it doesn't work  It shows onnxruntime loadlibrary failed with error 126

### ISSUE THREAD

**Issue by bravovn** [hacksider/Deep-Live-Cam#356]
This is all the output when i click on "Previews" or "Start" button :

PS C:\Deep-Live-Cam-main> python run.py --execution-provider openvino

EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\bravo\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\bravo/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\bravo\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\bravo/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\bravo\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\bravo/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\bravo\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\bravo/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\bravo\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\bravo/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\bravo\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]

![image](https://github.com/user-attachments/assets/fa41fbdf-9336-4953-ab90-536abaea38dd)

**Comment by rodrigolopezguerra** [comment]
Same here. This is kind of strange 

 **C:\Users\intel\Documents\saurabh\**onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1

**Comment by rodrigolopezguerra** [comment]
Same here . This path is strange (?) 

C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1

**Comment by nousernameavailable1** [comment]
Try running -

pip uninstall onnxruntime onnxruntime-openvino
pip install onnxruntime-openvino==1.15.0

It’s probably due to incorrect version of openvino, only 1.15.0 is likely supported so this should fix it (might be wrong about this though)

**Comment by lbethancourt-quantic** [comment]
I have this very same problem:
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\LuisBethancourt\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']

I installed openvino 1.15.0 is there anything else I should be installing?
