### ISSUE TITLE
Recognizing trackpad clicks on Macbook 

### ISSUE THREAD

**Issue by yyzguy** [hacksider/Deep-Live-Cam#359]
After launching Deep-Live-Cam it seems the program has a difficult time recognizing trackpad clicks on MacBook Air M3.

I have to click many, many times to get a button or toggle to respond.   The buttons light up properly when I put the pointer on them, they just hardly ever react to clicks.  Eventually they work.   No errors in the terminal window.

What am I doing wrong?

**Comment by yyzguy** [comment]
Oddly, buttons work find if I click and drag on them.

**Comment by zizake** [comment]
Same for me.
