### ISSUE TITLE
"Real-Time Face Swapping on Using Deep Live Monitor "

### ISSUE THREAD

**Issue by Mrkomiljon** [hacksider/Deep-Live-Cam#360]
You can see Deep_Live_Monitor using [monitor](https://github.com/Mrkomiljon/Deep-Live-Monitor)

https://github.com/user-attachments/assets/2f4d3b23-a8d4-4e88-9f11-508b72a87919

**Comment by hacksider** [comment]
That's actually awesome!

**Comment by hacksider** [comment]
Anyway, that's a good example. But you can do it already on the experimental by choosing a virtual camera.
