### ISSUE TITLE
Blurry Faces in Multi-GPU CUDA Environment

### ISSUE THREAD

**Issue by jinho-kim-osd** [hacksider/Deep-Live-Cam#364]
https://github.com/user-attachments/assets/7ce6f90c-c0cf-43c5-9d35-e17861c9e57f

When using 4 NVIDIA T4 GPUs in a CUDA environment, video outputs show blurry and patchy faces. Interestingly, this issue does not occur on Mac or when using a single GPU, suggesting a potential problem with multi-GPU processing in the CUDA setup.

**Comment by denrinm** [comment]
Got similar issue : Reinstall onxruntime will solve your issue

```
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3
```

**Comment by jinho-kim-osd** [comment]
I solved it. Thanks very much! @denrinm
