### ISSUE TITLE
CUDAExecutionProvider doesn't seem to be used, CPUExecutionProvider instead

### ISSUE THREAD

**Issue by cserpellZF** [hacksider/Deep-Live-Cam#37]
I am trying to use it with a GPU with cuda 12.2 in ubuntu 24.04. After starting it with `python run.py --execution-provider cuda`, it starts but it says

```
Processing:   0%|                                                                                   | 0/1789 [00:00<?, ?frame/s, execution_providers=['CUDAExecutionProvider'], execution_threads=8, max_memory=16]Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
```

I am not clear whether the GPU is being used at all, and it is very slow. Is this expected?

**Comment by hacksider** [comment]
It seems your just processing a video. Yes, it's using CUDA.

**Comment by thanhiart** [comment]
With CUDA , 12 Thread, 20 Memory, proccesing video very low. What's minium requirement for proccesing video with Many Faces and Keep FPS, Keep Frames ?. Thank you !

**Comment by thanhiart** [comment]
CPU and GPU use only 20% at all.

**Comment by cserpellZF** [comment]
Thanks.
