### ISSUE TITLE
Suggestions on: How to Achieve Better Face Quality Without Using Face Enhance?

### ISSUE THREAD

**Issue by thatnerdyaigirl** [hacksider/Deep-Live-Cam#370]
I have observed that the face quality is not optimal when the face enhancement module is not used. The current output is lacking in clarity and detail, which affects the overall quality of the faces in the output. I am using 1080p video for target along with 1080p image for source. The face enhance module just makes it look too "fake". Please someone suggest something.

**Comment by acwo** [comment]
You can always enhance it with some external tool like https://vmake.ai/video-enhancer/

**Comment by thatnerdyaigirl** [comment]
> You can always enhance it with some external tool like https://vmake.ai/video-enhancer/

Yeah but that also does exactly like face-enhance where it adds a "fakeness" to the face

**Comment by RainyZombie** [comment]
bump I'm also interested in this lmk if you found out anything please

**Comment by ANK789** [comment]
me too,hava any new feature tell me,thanks
