### ISSUE TITLE
What is minimum device requirements?

### ISSUE THREAD

**Issue by qccg** [hacksider/Deep-Live-Cam#375]
Hi, developers.
This is super awesome project that I have ever seen.
I am a full stack developer not AI developer so I am not sure my device can run this project.
So could you let me know the minimum requirements of this project?
I am using windows 10.

Thank you!

**Comment by hacksider** [comment]
I was using an 8700k before (so that's the lowest specs I have tested it). It can run with just cpu only as well. But a recommended is with nvidia gpu with at least 6gb vram.
