### ISSUE TITLE
Unable to select camera device through UI

### ISSUE THREAD

**Issue by cloudwitch** [hacksider/Deep-Live-Cam#376]
It would be nice to have a way to select which camera to use. I am on Ubuntu 22.04 with a Linux laptop. Since I use an external camera and keep my laptop closed, the program is defaulting to the on-board camera.

I was unable to find a quick/easy way to change the default camera in Ubuntu, so it would be nice if the program was able to allow a selection in the UI.

**Comment by cloudwitch** [comment]
I did find an issue suggesting editing `cap = cv2.VideoCapture` in `modules/ui.py`. Working on trying this. But it would be nice to have that able to be selectable in the UI.

**Comment by jayasafunctionofe** [comment]
a UI camera chooser was added in the experimental branch last week via commit 8d3072d

**Comment by hacksider** [comment]
This is already on the experimental build. Just testing it before releasing to public :)
