### ISSUE TITLE
Buttons not recognizing trackpad clicks, Macbook Air M3

### ISSUE THREAD

**Issue by yyzguy** [hacksider/Deep-Live-Cam#378]
Running Deep-Live-Cam on MacBook Air with M3.

The green buttons don't recognize trackpad clicks.   

Workaround:  click then drag on the buttons, then they respond.   Seems unusual, but this is the only way I can get the buttons to respond.

Initially opened, then closed here: https://github.com/hacksider/Deep-Live-Cam/issues/359#issue-2469504291

**Comment by bpafoshizle** [comment]
What version of python did you get it to run? Only version I can get to run is python 9.6 installed with xcode cli, but that doesn't work with tkinter, so buttons, etc don't render. I can get tkinter test UIs to run with python 3.11 and others, but then can't get the onnx-silicon installed, just get the following. Running `python run.py` on 3.11 by itself just hangs and cannot even be force killed. Running `python run.py --execution-provider coreml` results in `illegal hardware instruction`

```ERROR: No matching distribution found for onnxruntime-silicon==1.13.0```

**Comment by yyzguy** [comment]
I’m using python 3.10 but I read somewhere that 3.11 should also work.

I’m using onnxruntime 1.16.3 after reading this comment https://github.com/hacksider/Deep-Live-Cam/issues/357#issuecomment-229358690

**Comment by bpafoshizle** [comment]
> I’m using python 3.10 but I read somewhere that 3.11 should also work.
> 
> 
> 
> I’m using onnxruntime 1.16.3 after reading this comment https://github.com/hacksider/Deep-Live-Cam/issues/357#issuecomment-229358690 
> 
> 
> 
> prior to that I was using onnxruntime 1.13.1 which is what’s called for in the original instructions (not 1.13.0 as you have indicated)

Thanks, I figured out my issue. My Python was using Rosetta instead of apple silicon because my homebrew was migrated from my previous Intel Mac and then Python was installed through that it made it use Rosetta. Really tricky to figure that out as it's not obvious that was causing the issue. I reinstalled homebrew and all packages including Python with silicon and things work fine.

**Comment by yyzguy** [comment]
> My Python was using Rosetta instead of apple silicon because my homebrew was migrated from my previous Intel Mac and then Python was installed through that it made it use Rosetta.

That's brilliant!  Mine too was migrated from Intel Mac and that likely explains this issue and a handful of other quirks I have with other bits code installed.   That also explains why stuff I was expecting to find in /opt was located in /usr/local/opt.     I've been updating and migrating MacOS since  a very early intel version of OS X and have a ton of crud that's been coming along all these years.   ( I should probably do a fresh install, but that seems like alot of work).

**Comment by bpafoshizle** [comment]
Yeah I found something about it in one of the other issues in this repo, which also referenced this:

https://mattlehrer.com/blog/make-sure-youre-using-apple-silicon-brew
