### ISSUE TITLE
Empty window on MacBook m3 max

### ISSUE THREAD

**Issue by ImLoaD** [hacksider/Deep-Live-Cam#38]
Using python 3.10

Installed requirements, ffmpeg, onnxruntime-silicon 1.13.1

Run command and output: 
```
python run.py --execution-provider coreml
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
```
<img width="661" alt="image" src="https://github.com/hacksider/Deep-Live-Cam/assets/1041444/9e78be6c-149d-41d9-8665-d6ce1b3a69a3">

**Comment by ImLoaD** [comment]
Seems it's problem with python 3.10, and I need to install 3.11.

But with 3.11 - I cannot install onnxruntime-silicon 1.13.1 (I can install 1.14.1 at least)

This is what I understand so far

**Comment by hacksider** [comment]
Does 3.11 fixed your issue?

**Comment by hacksider** [comment]
> It seems there is an issue with Python 3.10, and I need to install version 3.11.
> 
> However, with Python 3.11, I cannot install onnxruntime-silicon version 1.13.1 (I can install version 1.14.1 at least).
> 
> This is what I understand so far.

Does 3.11 fix your issue? Sorry I don't have a mac now so this might help others as well :)

**Comment by tommyj8** [comment]
Had the same issue, fixed it by installing an updated version of tcl-tk. 

https://stackoverflow.com/a/61879759

**Comment by ngochoaitn** [comment]
Change python to 3.11.0 (use pyenv)
Change numpy==1.24.3 in requirements.txt
