### ISSUE TITLE
Face swap video outputs success, but no video is outputted.

### ISSUE THREAD

**Issue by AteebXYZ** [hacksider/Deep-Live-Cam#381]
By selecting a source image and target video, the program runs and this is outputted:

Processing: 100%|█████████████████| 451/451 [01:20<00:00,  5.62frame/s, execution_providers=['CUDAExecutionProvider'], execution_threads=11, max_memory=16]
[DLC.CORE] Creating video with 30.0 fps...
[DLC.CORE] Restoring audio might cause issues as fps are not kept...
[DLC.CORE] Processing to video succeed!

but when i check my output directory, there is no video.

OS: Fedora Linux 40
Cuda 11.8
cudnn 8.9.6
python3.10

**Comment by aijing1993** [comment]
Hello, do you find a solution for this?

**Comment by gibiee** [comment]
@AteebXYZ @aijing1993 
I have resolved the issue in the current version of the code. While the exact cause is unclear, it seems that an issue occurred with the .onnx file during internal processes.

Please check https://github.com/hacksider/Deep-Live-Cam/issues/395#issuecomment-2367267637
