### ISSUE TITLE
Merges a black square or nightmare's onto Target

### ISSUE THREAD

**Issue by JulianStiebler** [hacksider/Deep-Live-Cam#382]
- Windows 10 64bit
- NVidia GeForce RTX 3060 Mobile
- Intel(R) Core(TM) i7-10750H @2,60GHz | 6 Core 12 Threads

Using any picture it just merges a black square towards the specified target; 

- CPUExectuionProvider
- Either experimental or main branch

2 Stock images combined:
![grafik](https://github.com/user-attachments/assets/c38fea88-1aab-407a-a8dc-17404dc3d467)

When i run in CUDA; it produces nightmare fuel. 

- CUDA Execution Provider
- Either experimental or main branch

Same stock images used as above
![grafik](https://github.com/user-attachments/assets/794a7efa-39bc-4901-902b-98c70297eb9c)

I used main branch AND experimental and did the following on each:
- Different Virtual Environments
  - setup per hand for experimental and main separately
  - used setup-batch file for main aswell
- Reinstalled Python
- Reinstalled CUDA
- Used different options given in the application like Face Enhancer and such

Input and Target Images are definetly high quality enough; and its not related to those images specifically.
![grafik](https://github.com/user-attachments/assets/64bfa24b-377a-4cb2-a855-31ddf737e4a5)

**Comment by Rqmco** [comment]
@JulianStiebler , I had a similar issue, try the following commands.
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3

**Comment by CezarGab** [comment]
> @JulianStiebler , I had a similar issue, try the following commands. pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3

Same problem, and it worked here. Thank you.

**Comment by ezik117** [comment]
The same issue is with the black square. Running on Ubuntu with no GPU and with libraries installed by default. Executed as "python3 run.py". After uninstalling both libraries "onnxruntime" and "onnxruntime-gpu" and installing "onnxruntime-openvino==1.15.0"  it gives no black square, but the quality is dramatically decreased although the source/destination images are about 2000x1000 pixels. Any suggestion?
![output](https://github.com/user-attachments/assets/b74abc7e-0514-4e2d-92c6-ccda565d2c6d)

**Comment by TaosLezz** [comment]
@ezik117 I had the same problem as you with blurry image output

**Comment by imyideas** [comment]
> @JulianStiebler , I had a similar issue, try the following commands. pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3

The following error is being displayed. EERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.16.3 (from versions: 1.17.0, 1.17.1, 1.18.0, 1.18.1, 1.19.0)
ERROR: No matching distribution found for onnxruntime-gpu==1.16.3.
any solution ?

**Comment by d-sako** [comment]
@ezik117 same problem :/
did you find any solution?

**Comment by johnson7788** [comment]
> @JulianStiebler , I had a similar issue, try the following commands. pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3

Great Job

**Comment by zyxy3344** [comment]
> @JulianStiebler , I had a similar issue, try the following commands. pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3

niace  r that solves the problem of the black frame on the face.

**Comment by zyxy3344** [comment]
> > @JulianStiebler , I had a similar issue, try the following commands. pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3
> 
> niace r that solves the problem of the black frame on the face.

一定要用python3.10版本才有这个onnxruntime-gpu==1.16.3，

**Comment by chenxufenghz** [comment]
My laptop is MacBook-pro, no GPU, and has the same issue. 
seems onnxruntime-openvino is only for Linux and Window(reference https://pypi.org/project/onnxruntime-openvino/). I tried install it, and show errors below:
`
pip install onnxruntime-openvino==1.15.0
ERROR: Could not find a version that satisfies the requirement onnxruntime-openvino==1.15.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-openvino==1.15.0

pip install onnxruntime-openvino==1.18.0
ERROR: Could not find a version that satisfies the requirement onnxruntime-openvino==1.18.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-openvino==1.18.0
`

**Comment by tianli2005** [comment]
> ，我遇到了类似的问题，请尝试以下命令。
> pip uninstall onnxruntime onnxruntime-gpu
> pip install onnxruntime-gpu==1.16.3

Thank you for using the command you provided to solve it successfully
