### ISSUE TITLE
Media pipe and protobuf conflict 

### ISSUE THREAD

**Issue by Aikpo** [hacksider/Deep-Live-Cam#384]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mediapipe 0.10.11 requires protobuf<4,>=3.11, but you have protobuf 4.23.2 which is incompatible.

i tried everything can figure this out

**Comment by Rqmco** [comment]
Is your python version 3.10?

**Comment by Aikpo** [comment]
Yes

**Comment by Aikpo** [comment]
> Is your python version 3.10?

I have 2 versions of python 3.10 and 3.12 but I use 3.10 for this
