### ISSUE TITLE
Large square on the face on Windows 11 / Python 3.12

### ISSUE THREAD

**Issue by FabioFlorey** [hacksider/Deep-Live-Cam#386]
When I try to install onnxruntime==1.16.3 or onnxruntime-gpu==1.16.3

```                                                               
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.16.3 (from versions: 1.17.0, 1.17.1, 1.18.0, 1.18.1, 1.19.0)
ERROR: No matching distribution found for onnxruntime-gpu==1.16.3
```

And I can't find a whl file to install on the Internet. I'm working on Windows 11 with Python 3.12.4
Even moving to a new index (e.g. `pip install onnxruntime==1.16.3 -i https://pypi.tuna.tsinghua.edu.cn/simple`) doesn't work.

**Comment by Aikpo** [comment]
try using python 3.10.0 
it should help
