### ISSUE TITLE
No face in source path detected.

### ISSUE THREAD

**Issue by Torres9999** [hacksider/Deep-Live-Cam#392]
![image](https://github.com/user-attachments/assets/96072e89-99d4-48f1-ad12-f12aff700720)
iI followed the tutorial step by step，Please tell me how to find the problem

**Comment by Mazalucas** [comment]
hi! Same problem here:
"[DLC.FACE-SWAPPER] No face in source path detected."

Already reinstalled all requirements but can't make it work.

Hope to find some help here!
Thnaks.

**Comment by jocastrocUnal** [comment]
same here

**Comment by KRSHH** [comment]
Make sure that the face in source image is not zoomed in too much.
