### ISSUE TITLE
Face Swapper fails to load, causing Live preview to crash

### ISSUE THREAD

**Issue by hotlabs-technology** [hacksider/Deep-Live-Cam#400]
I'm experiencing an issue with the face swapping functionality in the Deep-Live-Cam project. The main window of the application loads correctly, but when I click on the "Live" button, a small empty window appears briefly before the application crashes.

Environment:
- Operating System: Windows
- GPU: Nvidia GeForce 4060
- Python version: 3.12.2

Steps to reproduce:
1. Launch the application using `python run.py --execution-provider cuda`
2. The main window loads successfully
3. Click on the "Live" button
4. A small empty window appears briefly
5. The application crashes with an error

Error message:
The application throws an exception when trying to load the face swapping model. The key part of the error is:

```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from [PATH]\models\inswapper_128_fp16.onnx failed:Protobuf parsing failed.
```

Full error traceback:
```
Frame processor face_enhancer not found
[TIMESTAMP] registry_win.h:57:GetProtoFromRegistryValue Opening registry key Software\Google\DriveFS\Share failed with 0x2
Frame processor face_enhancer not found
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: [PROVIDER OPTIONS OMITTED FOR BREVITY]
find model: [PATH]/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
[SIMILAR LINES FOR OTHER MODELS OMITTED]
set det-size: (640, 640)
Exception in Tkinter callback
Traceback (most recent call last):
  [INTERMEDIATE TRACEBACK LINES OMITTED]
  File "[PATH]\modules\processors\frame\face_swapper.py", line 43, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(model_path, providers=modules.globals.execution_providers)
  [INTERMEDIATE TRACEBACK LINES OMITTED]
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from [PATH]\models\inswapper_128_fp16.onnx failed:Protobuf parsing failed.
```

Additional observations:
- The error message mentions "Frame processor face_enhancer not found" at the beginning of the output.
- The application seems to successfully load several other models before encountering the error with the face swapper model.

**Comment by Simon-Str** [comment]
Got the same error

**Comment by vic4key** [comment]
@hotlabs-technology Make sure your `models` folder and `gfpgan\weights` folder look like this (file name, file size):

![image](https://github.com/user-attachments/assets/90f281e1-5c97-4899-967c-c93d60281855)

![image](https://github.com/user-attachments/assets/20000b5b-a901-474d-bf93-8264a7bcf1db)

**Comment by omer-re** [comment]
@vic4key what's the full path of `gfpgan\weight`? 
I am trying to make it works and got a similar problem, but I couldn't find that gfpgan folder

**Comment by vic4key** [comment]
@omer-re These files in the `weights` folder are auto download in the first run.

**Comment by omer-re** [comment]
@vic4key thanks, what can I do if it doesn't appear and I don't have them?

**Comment by hotlabs-technology** [comment]
I have downloaded the .pth file in the models folder but I cannot find `gfpgan\weights`

**Comment by omer-re** [comment]
@hotlabs-technology not sure it's the perfect one, but it workd for me (I found it online)
[download link from huggingface](https://cdn-lfs.huggingface.co/repos/eb/ff/ebffed61e77d28c48290e86a31f6bf5f50d224bc8fa2ff729475748a8f00325c/6d1de9c2944f2ccddca5f5e010ea5ae64a39845a86311af6fdf30841b0a5a16d?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27detection_Resnet50_Final.pth%3B+filename%3D%22detection_Resnet50_Final.pth%22%3B&Expires=1724750427&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyNDc1MDQyN319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy9lYi9mZi9lYmZmZWQ2MWU3N2QyOGM0ODI5MGU4NmEzMWY2YmY1ZjUwZDIyNGJjOGZhMmZmNzI5NDc1NzQ4YThmMDAzMjVjLzZkMWRlOWMyOTQ0ZjJjY2RkY2E1ZjVlMDEwZWE1YWU2NGEzOTg0NWE4NjMxMWFmNmZkZjMwODQxYjBhNWExNmQ%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=O2A1wndhLUlELtHsuCPsT56fLOy99sfJmq8TKInqAL9tKlOTYDFh-6B4qSE6A2u1gED1OtpCH5InpUNkzIT-EIeivC52DMj%7Eraem9pXon4Tp9O6PBjBfuafl%7EygP9HCODxpMlgjj3yCFjAGUnfkFBBZLcDREKJXvzJzd6PoZi2w-wmm9pQKQtXFkVEX28%7EOjTmB7gxk-LnRHSyZwRL7ks0Ub9JSJG1t8tzcl3foH%7EdsakC7VnnZ78hQR2WLWJPXR8lB0H5gLup7iyTF%7EKPSVFwv684rAkefJWHZDtPxqJPdQYWuR2%7EmnKSRQRpRSZA4XWJPB%7Eo2X38F9lUu2Ttax9Q__&Key-Pair-Id=K3ESJI6DHPFC7l)

**Comment by hotlabs-technology** [comment]
thanks @omer-re but when I click on the link I get this:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<script/>
<Code>InvalidKey</Code>
<Message>Unknown Key</Message>
</Error>
```

would you mind trying again?

**Comment by omer-re** [comment]
@hotlabs-technology sure!
https://huggingface.co/sinadi/aar/tree/main
scroll to the right file and download it

**Comment by Simon-Str** [comment]
I made it work.
Don't follow any old READMES.
Follow the instructions of the README of this Repo. The models are linked there. When the program starts I had to choose a face picture obviously but I also chose a Target Video, then the live mode worked. It needs 30 seconds to start. Just be patient.

Consider to make a fresh install so a fresh repo clone. I also used python venv.

**Comment by ElKaydan** [comment]
https://github.com/hacksider/Deep-Live-Cam/issues/464
Hey I opened this issue so I have all models in folder but no gfpgan\weights

**Comment by hotlabs-technology** [comment]
Thanks a lot @omer-re , I'm doing some progress but it still doesn't work:

- I created the folder `gfpgan\weight`
- I have downloaded the file `detection_Resnet50_final.pth`
- I could not find `parsing_parsenet.pth`

same error, not sure what am I missing

**Comment by vic4key** [comment]
It's `gfpgan\weights` not `gfpgan\weight`.

Try to manually get the file at https://huggingface.co/gmk123/GFPGAN/tree/main

**Comment by hotlabs-technology** [comment]
@vic4key sorry that was just my typo, the directory name was indeed correct. Thanks a lot for the link, I have downloaded the .pth files in the weights directory but I still have the following errors:

- "Frame processor face_enhancer not found"
- "Opening registry key Software\Google\DriveFS\Share failed with 0x2"
- The main error at the end of the log:
- `Copyonnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\GameDev\Desktop\Projects\DeepLiveCam\Deep-Live-Cam\models\inswapper_128_fp16.onnx failed:Protobuf parsing failed.`

This last error seems to be the most critical, indicating that there was a problem loading the ONNX model file for the face swapper functionality. 
In terms of output I still see the same small empty window when I click on "Live"
