### ISSUE TITLE
Face Enhancer using directML not utilizing GPU

### ISSUE THREAD

**Issue by Syntoxr** [hacksider/Deep-Live-Cam#405]
When using Face Enhance in live mode, only 2 cores of the CPU instead of the GPU (RX 7800 XT) are being used.

This has already been mentioned [here](https://github.com/hacksider/Deep-Live-Cam/issues/333#issuecomment-2295097298), but I thought it would be cleaner to open a new issue.

Also, when using non enhance live mode, only around 50% of the GPU are being utilized while the frame rate isn't reaching the original one.

CPU: R7 7700X
GPU: RX 7800 XT
OS: Win 11
Python: 3.10.11

**Comment by vodangtue** [comment]
Because of GFPGANer use CUDA or CPU so I think when use face enhancer it will load with cpu.
![image](https://github.com/user-attachments/assets/617ee161-98f4-4064-bfed-25c029dcd4c0)
![image](https://github.com/user-attachments/assets/3c0968f8-e16b-48c8-b828-3363fb852ff0)
