### ISSUE TITLE
M1 Problem 

### ISSUE THREAD

**Issue by kayed85** [hacksider/Deep-Live-Cam#406]
when run the cod this error, there any solve for this issue 

`Deep-Live-Cam % python3 run.py --execution-provider coreml

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/albumentations/check_version.py:49: UserWarning: Error fetching version info <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
  data = fetch_version_info()
[DLC.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "/Users/XX/AI Tools/Deep-Live-Cam/run.py", line 6, in <module>
    core.run()
  File "/Users/XX/AI Tools/Deep-Live-Cam/modules/core.py", line 236, in run
    if not pre_check():
           ^^^^^^^^^^^
  File "/Users/XX/AI Tools/Deep-Live-Cam/modules/core.py", line 158, in pre_check
    update_status('ffmpeg is not installed.')
  File "/Users/XX/AI Tools/Deep-Live-Cam/modules/core.py", line 166, in update_status
    ui.update_status(message)
  File "/Users/XX/AI Tools/Deep-Live-Cam/modules/ui.py", line 137, in update_status
    status_label.configure(text=text)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'configure'`

**Comment by vinhdevie** [comment]
You need install ffmpeg. 

`brew install ffmpeg`

**Comment by Updatedme** [comment]
Install ffmpeg 

Run this 


brew install ffmpeg

**Comment by maydersonmellops** [comment]
Performance was very poor on the M1 PRO, even using CoreML Execution Provider (Apple Silicon) for anyone else?

**Comment by briascoi** [comment]
> Performance was very poor on the M1 PRO, even using CoreML Execution Provider (Apple Silicon) for anyone else?

Same here, I tried everything and it's impossible to make it work smoothly
