### ISSUE TITLE
Application Not Appearing

### ISSUE THREAD

**Issue by Poordevv** [hacksider/Deep-Live-Cam#41]
Hello, I've completed all the steps and requirements when it came to installing the python file. 
However, when typing the command "python run.py --execution-provider=cuda" or even "python run.py", nothing appears. There's just a newline that's displayed to the console and that's all. Please help!

![image](https://github.com/hacksider/Deep-Live-Cam/assets/63006317/e1b89a22-c678-4e81-adf8-52e47cb9f75d)

**Comment by hacksider** [comment]
You don't really need to put the --models in the end unless you put it on separate drive.

**Comment by hellcezar** [comment]
I have the same, app will not appears
![image](https://github.com/hacksider/Deep-Live-Cam/assets/41210510/6a1c50dc-e9b2-43e6-9084-612ed8bbf14a)
Please help!

**Comment by victorhemsworth** [comment]
Yeah, it's not working me either. What's the issue?

**Comment by Poordevv** [comment]
Hello?

> You don't really need to put the --models in the end unless you put it on separate drive.

It's still not working, even with this part of the statement removed. Why is the app not appearing when I run it?

**Comment by hacksider** [comment]
Can you tell me more about what version of python are you using?

**Comment by hellcezar** [comment]
> Can you tell me more about what version of python are you using?

im using 3.12

**Comment by Poordevv** [comment]
Python 3.12 as well!

**Comment by hacksider** [comment]
Kindly use python 3.10

**Comment by Poordevv** [comment]
Still doesn't seem to work!

**Comment by hacksider** [comment]
> Still doesn't seem to work!

What error does it show when running on 3.10?

**Comment by victorhemsworth** [comment]
Atleast for me, it shows the exact same thing. Like no outputs similar to the one below.

> Quote reply

**Comment by radoman93** [comment]
Can confirm, same issue

**Comment by hacksider** [comment]
I have fixed the issue, seems like numpy goes 2.0 which breaks the installation

**Comment by aquawaves** [comment]
Solution:
`pip install numpy<1.24`
