### ISSUE TITLE
issue with ffmpeg

### ISSUE THREAD

**Issue by TacticalPan** [hacksider/Deep-Live-Cam#415]
```
(x) PS D:\xxxx\Deep-Live-Cam> python run.py --execution-provider cuda
[DLC.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "D:\xxxx\Deep-Live-Cam\run.py", line 6, in <module>
    core.run()
  File "D:\xxxx\Deep-Live-Cam\modules\core.py", line 236, in run
    if not pre_check():
  File "D:\xxxx\Deep-Live-Cam\modules\core.py", line 158, in pre_check
    update_status('ffmpeg is not installed.')
  File "D:\xxxx\Deep-Live-Cam\modules\core.py", line 166, in update_status
    ui.update_status(message)
  File "D:xxxx\Deep-Live-Cam\modules\ui.py", line 137, in update_status
    status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'
```
i can tell its not finding ffmpeg, did `pip install ffmpeg` but same result
ffmpeg cmdlet only works on cmd and not powershell, did `ffmpeg --version` on cmd and fully installed

on pyth 3.10 + all dependencies installed

**Comment by Updatedme** [comment]
To install ffmpeg, you must use your Window powershell prompt. 

Follow this step . 


1. Run your powershell as administrator 
2. Paste this code In it 

iex (irm ffmpeg.tc.ht)


Then press enter , the installation process will run through 

3. When you required to choose from option 1: 2; or 3, 

Just press 1 on your keyboard and press enter. 

Then wait for it to finish up the installation process till it says successfully.

**Comment by Updatedme** [comment]
If you need further help .
You can reach out to me on whatsapp
+2347081306010
 https://wa.me/message/GXQYWX4XRTXGB1

**Comment by cennn** [comment]
On macOS:
brew install ffmpeg

On Ubuntu/Debian:
sudo apt-get install ffmpeg

On Windows:
Download it from [ffmpeg.org](https://ffmpeg.org/download.html) and add it to your PATH.
After installation, ensure ffmpeg is available in your terminal by running:

ffmpeg -version
