### ISSUE TITLE
run.py: error: argument --execution-provider: invalid choice: 'directml' (choose from 'dml', 'cpu')

### ISSUE THREAD

**Issue by wentrue97** [hacksider/Deep-Live-Cam#416]
input python run.exe -- execution provider directml, there is an error when running it

`D:\Download\Deep-Live-Cam-main>python run.py --execution-provider directml
usage: run.py [-h] [-s SOURCE_PATH] [-t TARGET_PATH] [-o OUTPUT_PATH]
              [--frame-processor {face_swapper,face_enhancer} [{face_swapper,face_enhancer} ...]] [--keep-fps]
              [--keep-audio] [--keep-frames] [--many-faces] [--video-encoder {libx264,libx265,libvpx-vp9}]
              [--video-quality [0-51]] [--max-memory MAX_MEMORY] [--execution-provider {dml,cpu} [{dml,cpu} ...]]
              [--execution-threads EXECUTION_THREADS] [-v]
run.py: error: argument --execution-provider: invalid choice: 'directml' (choose from 'dml', 'cpu')`

**Comment by vodangtue** [comment]
use this command
``python run.py --execution-provider dml``

**Comment by leokovaski** [comment]
I have the same problem.
"run.py: error: argument --execution-provider: invalid choice: 'coreml' (choose from 'azure', 'cpu')"
Apple Intel

**Comment by Updatedme** [comment]
If you need help installating Deep-live-cam , reach out to me on whatsapp. +2347081306010
  https://wa.me/2347081306010
https://wa.me/message/GXQYWX4XRTXGB1
