### ISSUE TITLE
OpenVINO™ Execution Provider (Intel) doesn't utilizes GPU

### ISSUE THREAD

**Issue by needhelb** [hacksider/Deep-Live-Cam#42]
first of all we need to install additionaly 

pip.exe install openvino==2023.0 

---

then run app i see "Applied providers: ['**OpenVINOExecutionProvider**', '**_CPUExecutionProvider_**'], with options: {'OpenVINOExecutionProvider': {}, 'CPUExecutionProvider': {}}"

Processing: 100%|█| 245/245 [03:36<00:00,  **1.13frame/s,** execution_providers=['**OpenVINOExecutionProvide**r'], execution_th

 and CPU is 90% load, GPU 1% is load.

I have **Intel Arc GPU**

**Comment by hacksider** [comment]
did you also do this?

pip uninstall onnxruntime onnxruntime-openvino
pip install onnxruntime-openvino==1.15.0

**Comment by needhelb** [comment]
> did you also do this?
> 
> pip uninstall onnxruntime onnxruntime-openvino 
> pip install onnxruntime-openvino==1.15.0

yes, without onnxruntime-openvino it doesn,t works at all

-
in the same time "DirectML Execution Provider (Windows)" utilizes GPU, 
but when i try to save video ("start") i see error

_Processing:   0%| | 0/245 [00:00<?, ?frame/s, execution_providers=['DmlExecutionProvider'], execution_threads=60, max_m2024-06-24 21:02:50.2725589 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Transpose node. Name:'Transpose_218' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2565)\onnxruntime_pybind11_state.pyd!00007FFB141CCF66: (caller: 00007FFB14952E01) Exception(13) tid(2b80) 887A0005 ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤  GPU ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ . ¤ ¤ ¤  ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤  GetDeviceRemovedReason._

but "preview" works OK and utilizes GPU

-
i run facefusion-2.6.1-dml and it works flawless via DML
-
openvino is officially supported by Intel for its discrete ARC GPUs for AI computing, for SD, for example

**Comment by hacksider** [comment]
Oh! Are you trying to render a video instead of webcam? I totally forgot about that function as I am focusing more on the webcam/live function. If you plan on doing the video rendering face swap, then I suggest face fusion. It is hands down better than deep-live-cam on that part. But if it is on webcam mode, then I can say this one is better 😊

**Comment by needhelb** [comment]
[ERROR:0@16.059] global obsensor_uvc_stream_channel.cpp:156 cv::obsensor::getStreamChannelGroup Camera index out of range

i see 3 webcams in my system

1) Intel Virtual Cam (Intel ARC GPU software)
2) Virtual Cam 2
3) Real WebCam


how to select cam №3?

**Comment by needhelb** [comment]
deleted extra cams and
DML uses GPU and works OK with webcam, but slow framerate, how to adjust anything?

OpenVino still uses CPU only : (

**Comment by SanPatrick01** [comment]
Send dm to WhatsApp with the issues you're facing 

‪+234 811 513 3627‬

**Comment by Updatedme** [comment]
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by Updatedme** [comment]
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by DealsBeam** [comment]
> deleted extra cams and DML uses GPU and works OK with webcam, but slow framerate, how to adjust anything?
> 
> OpenVino still uses CPU only : (

Hey, did you get it to work?
