### ISSUE TITLE
Powershell Script Error  with: unrecognized arguments: --frame-processor face_swapper

### ISSUE THREAD

**Issue by ChangDLG** [hacksider/Deep-Live-Cam#420]
Iam trying to  execute  the  cmdlet  via  powershell script,  all arguments are working well (like --many-faces / --keep-fps etc..) but iam not able to put the  frace_enhancer  into the  command.
What  is the correct  way  to setup the command ?

--frame-processor face_swapper --frame-processor face_enhancer ?
this will bring up an error:
"Error  with: unrecognized arguments: --frame-processor face_swapper"
or
run.py: error: argument --frame-processor: invalid choice: 'FRAME_PROCESSOR' (choose from 'face_swapper', 'face_enhancer')

What  is the exact way to  use  bouth command so that it  will sapp faces and also use the enhancer ?

**Comment by Updatedme** [comment]
Have you considered executing these scripts on miniconda Prompt installed of using window powershell

**Comment by Updatedme** [comment]
If you  need help installating Deep-live-cam , reach out to me on whatsapp. +2347081306010
  https://wa.me/2347081306010
https://wa.me/message/GXQYWX4XRTXGB1

**Comment by ChangDLG** [comment]
> Have you considered executing these scripts on miniconda Prompt installed of using window powershell

Its not about the enviorment its about the command itself and how to use it.

Do i need to put in the two commands ?
--frame-processor face_swapper --frame-processor face_enhancer ?
is it  wrong  written ?
Help from the command line shows:
 --frame-processor FRAME_PROCESSOR [FRAME_PROCESSOR ...] 
 so its it  :
  --frame-processor FRAME_PROCESSOR [face_swapper]
or what is the  correct terminology?
