### ISSUE TITLE
Mac error during  pip installation of requirements.txt

### ISSUE THREAD

**Issue by curious-itauditor** [hacksider/Deep-Live-Cam#424]
ERROR: Could not find a version that satisfies the requirement pillow==9.5.0 (from versions: 9.3.0, 10.2.0)
ERROR: No matching distribution found for pillow==9.5.0

**Comment by Updatedme** [comment]
What version of miniconda did you install in your macbook ?

**Comment by curious-itauditor** [comment]
i'm not sure if i installed miniconda

**Comment by Updatedme** [comment]
You need miniconda installed in your macbook 

You can reach out to me on whatsapp if you need help for proper installation on Deep-live-cam ,
whatsapp. +2347081306010
  https://wa.me/2347081306010
https://wa.me/message/GXQYWX4XRTXGB1

**Comment by curious-itauditor** [comment]
I've already installed the requirements.txt, but encountered this error when running python run.py --execution-provider cuda

Traceback (most recent call last):
  File "/Users/xxx/Documents/Github/Deep-Live-Cam/run.py", line 3, in <module>
    from modules import core
  File "/Users/xxx/Documents/Github/Deep-Live-Cam/modules/core.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by Updatedme** [comment]
Are you running your terminal on miniconda 3.10 
Check to see that you running your terminal on minicond 3.10
 if not you need to install minicond 3.10 in Your terminal. 
Afterwards, run this again
 pip install -r requirements.txt

**Comment by Updatedme** [comment]
Use the recommended minicond 3.10 from the miniconda official website.
