### ISSUE TITLE
inswapper_128_fp16.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by Silhouteee** [hacksider/Deep-Live-Cam#425]
I really  do not have an idea of what to do. This issue comes up after selecting a picture for target face and cliclking going live i get this error message.

**Comment by LisandraMoura** [comment]
Try downloading the models from step 3. Download Models and put them in the "models" folder.

**Comment by vic4key** [comment]
@Silhouteee The answer of @LisandraMoura might resolve your issue. Feel free to re-open this issue if you’re still having trouble.

**Comment by Silhouteee** [comment]
I will appreciate you pointing to the models i am downloading.

**Comment by vic4key** [comment]
The download links are on the main page https://github.com/hacksider/Deep-Live-Cam?tab=readme-ov-file#3-download-models

And have a look at this https://github.com/hacksider/Deep-Live-Cam/issues/400#issuecomment-2302741123

**Comment by Silhouteee** [comment]
Thank you so much.  Missed that because i thought that was not neccesary for cuda excecution. This is my new issue after that.

atent = source_face.normed_embedding.reshape((1,-1))
AttributeError: 'NoneType' object has no attribute 'normed_embedding'

**Comment by sysonlai** [comment]
> Thank you so much. Missed that because i thought that was not neccesary for cuda excecution. This is my new issue after that.
> 
> atent = source_face.normed_embedding.reshape((1,-1)) AttributeError: 'NoneType' object has no attribute 'normed_embedding'

You can refer to the issue #87 . The face image couldn't find a face. Please find another one.

**Comment by China-natian** [comment]
<img width="1300" alt="image" src="https://github.com/user-attachments/assets/dec2ae06-a717-44e3-b9cf-3a5a697e8689">
I have download it ,  but It not working. And I tryed to restart ,also not working.

**Comment by Ch3r12h** [comment]
I am having the same issue. I downloaded both files in step 3 and placed in the "models" folder. Whenever I run the live cam, it generates a new file "inswapper_128_fp16.onnx" of 45kb and then the error message

**Comment by Ch3r12h** [comment]
> I am having the same issue. I downloaded both files in step 3 and placed in the "models" folder. Whenever I run the live cam, it generates a new file "inswapper_128_fp16.onnx" of 45kb and then the error message 

I was able to resolve this issue by renaming the "inswapper_128.onnx" after downloading and placing in \models. 
It works fine after 2 downloads but my CPU not built for this 🥲

**Comment by amirkenesbay** [comment]
Just rename module from `InSwapper 128 FP16.onnx` to `inswapper_128_fp16.onnx`. Because I got this message --> `/Deep-Live-Cam/models/inswapper_128_fp16.onnx should exist`
