### ISSUE TITLE
Output got a black square, didn't generate the deep-face

### ISSUE THREAD

**Issue by LisandraMoura** [hacksider/Deep-Live-Cam#427]
I don't have a GPU in my computer, and I have an AMR ryzen 5, with 12 gb of memory ram and ssh around the operating system.
I believe that it was not possible to generate the deep face due to the limitation of the machine, I even noticed a very high latency in the output in real time. 
I tried to generate the output without being live, but it didn't work either.

**Comment by michaelonken** [comment]
+1 (AMD Ryzen 7, no GPU, Ubuntu 24.04)

**Comment by coach1988** [comment]
I found this to help me with that:
https://github.com/hacksider/Deep-Live-Cam/issues/382#issuecomment-2294827989

**Comment by Suffton** [comment]
@coach1988  you are lucky. It doesn't work on my Mac

**Comment by omer-re** [comment]
+1 for `AMD Ryzen 5 4500U with Radeon Graphics` + Windows11.
Couldn't resolve yet.

**Comment by imyideas** [comment]
I am also facing the same issue. Black square is coming. any solutions

**Comment by 999946** [comment]
> @coach1988 你很幸运。它在我的 Mac 上失效了

pip install onnxruntime==1.16.3
