### ISSUE TITLE
pip install -r requirements.txt is error in Windows 11 Enterprise

### ISSUE THREAD

**Issue by HuJunnj** [hacksider/Deep-Live-Cam#436]
hi team,

pip install -r requirements.txt is error in Windows 11 Enterprise，my python verison is 3.6.3,  error information folllow:

(.venv) PS D:\GIT\Deep-Live-Cam> pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow: markers 'sys_platform == "darwin"' don't match your environment
ERROR: Could not find a version that satisfies the requirement numpy==1.23.5 (from versions: none)
ERROR: No matching distribution found for numpy==1.23.5
(.venv) PS D:\GIT\Deep-Live-Cam> 

please help me, thanks in advance.

Best Regards

**Comment by dssiqueira** [comment]
"numpy" is compatible with Python versions 3.7 to 3.10. Other libraries might cause issues, so I recommend updating to Python 3.10. This will help prevent future errors.

**Comment by gzzpsxsbrblmd** [comment]
I also got a lot of errors while trying to install dependencies. To solve those problems:
1. as said in readme file: **"python (3.10 recommended)"**, you will save a lot of troubles;
2. run pip install -r requirements.txt several times... sometimes the error will disappear magically;
3. If there are still errors, execute pip install on each line of the packages listed in requirements.txt manually, one line after another; 
4. download torch packages manually and run pip to install the wheel...

Good luck...

**Comment by HuJunnj** [comment]
> I also got a lot of errors while trying to install dependencies. To solve those problems:
> 
> 1. as said in readme file: **"python (3.10 recommended)"**, you will save a lot of troubles;
> 2. run pip install -r requirements.txt several times... sometimes the error will disappear magically;
> 3. If there are still errors, execute pip install on each line of the packages listed in requirements.txt manually, one line after another;
> 4. download torch packages manually and run pip to install the wheel...
> 
> Good luck...

PS D:\GIT\Deep-Live-Cam> pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow: markers 'sys_platform == "darwin"' don't match your environment
ERROR: Could not find a version that satisfies the requirement numpy==1.23.5 (from versions: 1.24.1, 1.26.3)
ERROR: No matching distribution found for numpy==1.23.5
WARNING: There was an error checking the latest version of pip.
PS D:\GIT\Deep-Live-Cam> python --version
Python 3.10.6
PS D:\GIT\Deep-Live-Cam>

My python version is 10 now, but error occured still.

thanks in advance.
Best Regard
Jun
