### ISSUE TITLE
    im_ratio = float(img.shape[0]) / img.shape[1] AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Kaykyfs** [hacksider/Deep-Live-Cam#437]
im_ratio = float(img.shape[0]) / img.shape[1] AttributeError: 'NoneType' object has no attribute 'shape'

How I can fix that? nothing works with me :')

**Comment by qyh540** [comment]
I have the same problem. Have you solved it?

**Comment by qyh540** [comment]
The file path or file name can not contain a Chinese name.
