### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF

### ISSUE THREAD

**Issue by Silhouteee** [hacksider/Deep-Live-Cam#438]
Done everything i think could be the solution but no head way yet. SOMEBODY PLEASE EXPLAIN WITHOUT THE AMBIGUITY TERMS. THANKS.

 sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\tHE\Deep-Live-Cam\models\inswapper_128_fp16.onnx failed:Protobuf parsing failed.

**Comment by coach1988** [comment]
I think this is what I ran into when my model files were corrupt. Try it with a freshly downloaded version.

**Comment by Silhouteee** [comment]
Fix it. Thanks.
