### ISSUE TITLE
low load on video memory

### ISSUE THREAD

**Issue by vladosik-gpu** [hacksider/Deep-Live-Cam#44]
Hello, thanks for the excellent program, I wanted to clarify why the load on my 3080 is so small, and it is only 1% load on video memory 4GB out of 10GB, how to increase the load, I have about 40 fps

**Comment by hacksider** [comment]
Did you follow the following instructions about the nvidia setup?

**Comment by vladosik-gpu** [comment]
do you mean the sequence for setting up cuda?
Of course, I assume I wouldn't run the program.
or are we talking about something else?

**Comment by hacksider** [comment]
> do you mean the sequence for setting up cuda? Of course, I assume I wouldn't run the program. or are we talking about something else?

`pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3
`

**Comment by vladosik-gpu** [comment]
Well, of course, all the steps were done, I tried changing the code and running it with different commands, but nothing changed at all except the window size, and I couldn’t solve the problem with a small load on the Nvidia card!(

**Comment by SanPatrick01** [comment]
send dm to my WhatsApp with a video of the issues you're facing ‪+234 811 513 3627‬

**Comment by Updatedme** [comment]
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010
