### ISSUE TITLE
missing advanced options guide

### ISSUE THREAD

**Issue by drhouse** [hacksider/Deep-Live-Cam#443]
from the readme:

> Additional command line arguments are given below. To learn out what they do, check [this guide](https://github.com/s0md3v/roop/wiki/Advanced-Options).

The link [https://github.com/s0md3v/roop/wiki/Advanced-Options](https://github.com/s0md3v/roop/wiki/Advanced-Options) redirects to the default wiki front page, I tried using archive.org (Wayback Machine), but they don't have a copy. Neither does Google have a cached copy. Although the readme gives tiny descriptions, in case anyone has a copy of the Advanced Options guide, it would be appreciated.

**Comment by hacksider** [comment]
The other options are for the web version, which this app didn't have.
