### ISSUE TITLE
after download and run python run.py a module cannot be found(no module named torch ,i use visual studio2022,same problem 3times i delete and do all thing again )

### ISSUE THREAD

**Issue by smile370** [hacksider/Deep-Live-Cam#444]

**Comment by smile370** [comment]
![Uploading 屏幕截图 2024-08-23 165847.png…]()

**Comment by smile370** [comment]
![屏幕截图 2024-08-23 165847](https://github.com/user-attachments/assets/cc019bdd-c66b-428d-a627-6cd995fc0f4d)

**Comment by Goulustis** [comment]
Did you follow the install guides? You need to install torch.

**Comment by Hopeyu** [comment]
![IMG-20240903-WA0008](https://github.com/user-attachments/assets/df92eab3-6d7f-4483-ae56-fb0da7f4f2ea)
Hey bro I keep getting this error,  can you please  help ?

**Comment by Goulustis** [comment]
install a numpy version less than 2
