### ISSUE TITLE
swap eyes only

### ISSUE THREAD

**Issue by leepalg** [hacksider/Deep-Live-Cam#445]
I want to swap only the eyes of a character onto a face, but if I use a picture showing only eyes as the input, the program still tries to render the whole face (rather than just the eyes) in the output, leading to weird artifacts and black spots in the nose/mouth/jaw area.  In short, it doesn't work.  Maybe there are settings that can be adjusted to change this?

**Comment by hacksider** [comment]
This is not an issue of the application as the main purpose of the app is to use the whole face and not just part of it.

**Comment by leepalg** [comment]
Okay... but is there anything in the code I can alter, to achieve the result I want?  Or would I need entirely different models/training data/a different program altogether?
