### ISSUE TITLE
i cant download Models

### ISSUE THREAD

**Issue by Luckyang5153** [hacksider/Deep-Live-Cam#448]
[GFPGANv1.4](https://huggingface.co/hacksider/deep-live-cam/resolve/main/GFPGANv1.4.pth)
[inswapper_128_fp16.onnx](https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128_fp16.onnx)
i cant open the link!

**Comment by johnson7788** [comment]
> [GFPGANv1.4](https://huggingface.co/hacksider/deep-live-cam/resolve/main/GFPGANv1.4.pth) [inswapper_128_fp16.onnx](https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128_fp16.onnx) i cant open the link!

You need use VPN if you can't visit huggingface

**Comment by Luckyang5153** [comment]
> > [GFPGANv1.4](https://huggingface.co/hacksider/deep-live-cam/resolve/main/GFPGANv1.4.pth) [inswapper_128_fp16.onnx](https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128_fp16.onnx) 我打不开链接！
> 
> 如果您无法访问 huggingface，则需要使用 VPN

thank u.

**Comment by budda** [comment]
> > > [GFPGANv1.4](https://huggingface.co/hacksider/deep-live-cam/resolve/main/GFPGANv1.4.pth) [inswapper_128_fp16.onnx](https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128_fp16.onnx) 我打不开链接！
> > 
> > 
> > 如果您无法访问 huggingface，则需要使用 VPN
> 
> thank u.

did it work @Luckyang5153  ?
