### ISSUE TITLE
global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638

### ISSUE THREAD

**Issue by EwoonGiT** [hacksider/Deep-Live-Cam#450]
how to fix error my camera not working how to fix someone?

**Comment by hacksider** [comment]
Make your camera the primary canera.

**Comment by EwoonGiT** [comment]
but im using a external camera on my pc

**Comment by EwoonGiT** [comment]
the external i use is the primary one :(

**Comment by wuanjunruc** [comment]
i have the same question, anyone can help me, please. My computer is a desktop, which does not have a built-in camera, so I used an external USB webcam.
