### ISSUE TITLE
Highly blurred faces

### ISSUE THREAD

**Issue by cyy-1234** [hacksider/Deep-Live-Cam#459]
Hi, author, I downloaded your code and ran it successfully, but the generated face was highly blurred.
![img_v3_02e4_7eab11b5-5e8e-4865-a80a-64fe27f8475g](https://github.com/user-attachments/assets/370998c9-1836-4041-8a62-6c409c5ade31)

**Comment by hacksider** [comment]
Default size without face enhancer is 128x128
