### ISSUE TITLE
failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by ElKaydan** [hacksider/Deep-Live-Cam#464]
![issue 3](https://github.com/user-attachments/assets/8b2c2741-c2af-4c13-a1f6-6a70c2552d2b)

![issue2](https://github.com/user-attachments/assets/df1fdf70-0092-4beb-89a6-f05f20bd6a2a)
check screenshots 
model don't load correctly
and models are in folder
gfpgan\weights folder don't exist

**Comment by Finalrykku** [comment]
Don't forget to download the models. Well.. I did. And that fixed this error.
