### ISSUE TITLE
Why I can't use the CUDA when I use this command:   python run.py --execution-provider cuda

### ISSUE THREAD

**Issue by viper3-2021-lol-champion** [hacksider/Deep-Live-Cam#466]
![屏幕截图 2024-08-26 214039](https://github.com/user-attachments/assets/13146683-6798-4e06-9671-e2c27106bd9e)
![屏幕截图 2024-08-26 214113](https://github.com/user-attachments/assets/682af662-5e46-4d27-92ec-8b8c056503ae)
![屏幕截图 2024-08-26 214141](https://github.com/user-attachments/assets/583bc1ce-b530-4b23-9726-2f150cba4d88)
My CUDA version is 11.8, and the cuDNN version is 8.5. When I installed CUDA and cuDNN, I tested them and found no issues. The tests included running the commands: set cuda, "deviceQuery.exe", and "bandwidthTest.exe". What's even stranger is that I could use CUDA around noon, but after I re-downloaded the two installation packages, I could no longer use CUDA. (Windows 11)

**Comment by hacksider** [comment]
did you also do this?
![image](https://github.com/user-attachments/assets/598915a2-7cd0-4b27-a9a2-a59c3644be57)

**Comment by hacksider** [comment]
Did you follow the full instruction? You have to do the next command as well which is to install the onnxruntime-gpu==1.16.3

**Comment by viper3-2021-lol-champion** [comment]
In my third image, you can see that I have installed onnxruntime-gpu 1.16.3. In fact, before our conversation, I had already installed both onnxruntime 1.18 and onnxruntime-gpu 1.16.3 in the library. After our first discussion, I uninstalled onnxruntime 1.18 and ran the program again, which resulted in an error. I have provided a screenshot of the error."
![屏幕截图 2024-08-26 232535](https://github.com/user-attachments/assets/993f45c1-9de7-4ac6-9392-22c9a546f5cc)
This photo is a screenshot of the packages that are currently installed in my virtual environment

**Comment by viper3-2021-lol-champion** [comment]
Just ran it again and encountered the same error: AttributeError: module 'onnxruntime' has no attribute 'InferenceSession'

**Comment by reahari** [comment]
> Did you follow the full instruction? You have to do the next command as well which is to install the onnxruntime-gpu==1.16.3

I tried to run this on Ubuntu 24.04 (python 3.12.3) and it can't be found:
```
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.16.3 (from versions: 1.17.0, 1.17.1, 1.18.0, 1.18.1, 1.19.0)
ERROR: No matching distribution found for onnxruntime-gpu==1.16.3
```

**Comment by hacksider** [comment]
Please check the recommended version of python on the readme ☺️
