### ISSUE TITLE
Nothing happens when starting

### ISSUE THREAD

**Issue by dekan02** [hacksider/Deep-Live-Cam#47]
I'm using a Mac M1 and when I run "python run.py", nothing happens. I have installed the requirements and tried re-installing it but nothing seems to work.
I'm using python 3.10.14 and I've checked previous issues and I still cant seem to fix this.

Update: I found the error "No module named 'gfpgan.archs.stylegan2_cleanonnx_arch'".

**Comment by hacksider** [comment]
try not including the face enhancer, I myself don't recommend using it especially on devices without dedicated GPU's
