### ISSUE TITLE
pip install -r requirements.txt ERROR

### ISSUE THREAD

**Issue by cellker00** [hacksider/Deep-Live-Cam#470]
PS C:\Users\jc678\Deep-Live-Cam> pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow: markers 'sys_platform == "darwin"' don't match your environment
Collecting numpy==1.23.5 (from -r requirements.txt (line 3))
Using cached numpy-1.23.5-cp310-cp310-win32.whl.metadata (2.3 kB)
Collecting opencv-python==4.8.1.78 (from -r requirements.txt (line 4))
Using cached opencv_python-4.8.1.78-cp37-abi3-win32.whl.metadata (20 kB)
Collecting onnx==1.16.0 (from -r requirements.txt (line 5))
Using cached onnx-1.16.0-cp310-cp310-win32.whl.metadata (16 kB)
Collecting insightface==0.7.3 (from -r requirements.txt (line 6))
Using cached insightface-0.7.3.tar.gz (439 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Collecting psutil==5.9.8 (from -r requirements.txt (line 7))
Using cached psutil-5.9.8-cp37-abi3-win32.whl.metadata (22 kB)
Collecting tk==0.1.0 (from -r requirements.txt (line 8))
Using cached tk-0.1.0-py3-none-any.whl.metadata (693 bytes)
Collecting customtkinter==5.2.2 (from -r requirements.txt (line 9))
Using cached customtkinter-5.2.2-py3-none-any.whl.metadata (677 bytes)
Collecting pillow==9.5.0 (from -r requirements.txt (line 10))
Using cached Pillow-9.5.0-cp310-cp310-win32.whl.metadata (9.7 kB)
ERROR: Could not find a version that satisfies the requirement torch==2.0.1+cu118 (from versions: none)
ERROR: No matching distribution found for torch==2.0.1+cu118

**Comment by cellker00** [comment]
HELP ME PLS, If you need to install something, send me the mega link, it's better for me

**Comment by wolverinex24** [comment]
pip install --use-pep517 -r requirements.txt

**Comment by AndreyViktor** [comment]
managed to fix it updating libs on requirements.txt

**Comment by diego-lipinski-de-castro** [comment]
@AndreyViktor can you paste your requirements.txt?

**Comment by cellker00** [comment]
> pip install --use-pep517 -r requisitos.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requisitos.txt'

**Comment by cellker00** [comment]
> conseguiu consertar atualizando as bibliotecas em requirements.txt

How do I do this?

**Comment by Updatedme** [comment]
Ok. I have  simple solution for you . 
I want you to delete the entire deep-live-cam folder then clone again from your miniconda with git clone 

You can deactivate your window defender during the process .

**Comment by kabeep** [comment]
Check python version
```shell
python -V
```
If not 3.10.x, Use `pyenv` to install version 3.10.x.
```shell
pyenv install -l
pyenv install 3.10.x
pyenv global 3.10.x
```
If use `miniconda`, upgrade it.
```shell
# .../Miniconda3/python.exe
python -c "import sys; print(sys.executable)"

conda search --full --name python
conda install python=3.10.x
```
Then,
```shell
pip install -r requirements.txt
```

**Comment by cellker00** [comment]
> ```shell
> pyenv install 3.10.x
> ```

my python version 3.10.0

choco version 2.3.0

**Comment by AndreyViktor** [comment]
> @AndreyViktor can you paste your requirements.txt?

`--extra-index-url https://download.pytorch.org/whl/cu118

numpy==2.1.0
opencv-python==4.10.0.84
onnx==1.16.2
insightface==0.7.3
psutil==6.0.0
tk==0.1.0
customtkinter==5.2.2
pillow==10.4.0
torch==2.4.0
torchvision==0.19.0
onnxruntime==1.19.0
onnxruntime-silicon==1.16.3; sys_platform == 'darwin' and platform_machine == 'arm64'
onnxruntime-gpu==1.19.0
tensorflow==2.17.0
opennsfw2==0.14.0
protobuf==5.27.3
tqdm==4.66.5
gfpgan==1.3.8
`
