### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'configure'

### ISSUE THREAD

**Issue by RwOnke** [hacksider/Deep-Live-Cam#476]
1. Install all modules successfully
2. Run python3 run.py --execution-provider cuda --execution-threads 60 --max-memory 60
3. Error made

Specs:
Windows 11 Pro 23H2
Galax RTX 3060
i5 10400F overclocked 
Secure boot off
ASUS B560m plus wifi motherboard
16GB of ram 3000mhz
Revi OS (Optimized for speed and gaming)

Err:
python3 run.py --execution-provider cuda --execution-threads 60 --max-memory 60
[DLC.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "C:\Users\swagmaster24\githubstuff\Deep-Live-Cam\run.py", line 6, in <module>
    core.run()
  File "C:\Users\swagmaster24\githubstuff\Deep-Live-Cam\modules\core.py", line 240, in run
    if not pre_check():
  File "C:\Users\swagmaster24\githubstuff\Deep-Live-Cam\modules\core.py", line 162, in pre_check
    update_status('ffmpeg is not installed.')
  File "C:\Users\swagmaster24\githubstuff\Deep-Live-Cam\modules\core.py", line 170, in update_status
    ui.update_status(message)
  File "C:\Users\swagmaster24\githubstuff\Deep-Live-Cam\modules\ui.py", line 142, in update_status
    status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'

**Comment by hacksider** [comment]
Error says there's no ffmpeg installed

**Comment by Updatedme** [comment]
Ffmpeg is not installed . 
Since this is a Windows

You can install ffmpeg from your window powershell prompt

**Comment by magisystem0408** [comment]
same error event happened to me.

**Comment by RwOnke** [comment]
Problem was in fact ffmpeg, I downloaded its files and placed them in the deepfakes folder and it ran, thanks everyone

**Comment by JackIRose** [comment]
> Problem was in fact ffmpeg, I downloaded its files and placed them in the deepfakes folder and it ran, thanks everyone

you dowload by youself? and put it in in which direatory?

**Comment by amirtabasi** [comment]
I got the same error in MacBook Pro m1. what I have to do?
