### ISSUE TITLE
Some problems with "onnxruntime_providers_cuda.dll"

### ISSUE THREAD

**Issue by Gary-404notfound** [hacksider/Deep-Live-Cam#477]
My "onnxruntime-gpu" version is **1.16.3**
"CUDA Toolkit" version is **11.8**
![Snipaste_2024-08-27_21-21-04](https://github.com/user-attachments/assets/28e1d6e8-664f-4b6d-800e-90332b134f3e)
But when i run(**python run.py --execution-provider cuda**), it output:
```2024-08-27 21:19:07.1822642 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_o
rt.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : 
FAIL : LoadLibrary failed with error 126 "" when trying to load "G:\python\IDE\Deep-Live-Cam-main\lib\sit
e-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"
```
I can use it normally, but it run only CPU. GPU usage is 0%.
```
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
```

**Comment by XL1125** [comment]
Have you solved this problem?

**Comment by Gary-404notfound** [comment]
> 你解决了这个问题吗？
Sorry, I haven't

**Comment by hacksider** [comment]
Did you also follow this instructions?
![image](https://github.com/user-attachments/assets/2fa0a91e-7bb0-4329-883d-89cbfc4fe2ab)

**Comment by Gary-404notfound** [comment]
> Did you also follow this instructions? ![image](https://private-user-images.githubusercontent.com/1267200/371858867-2fa0a91e-7bb0-4329-883d-89cbfc4fe2ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDQ3MTMsIm5iZiI6MTczMTQwNDQxMywicGF0aCI6Ii8xMjY3MjAwLzM3MTg1ODg2Ny0yZmEwYTkxZS03YmIwLTQzMjktODgzZC04OWNiZmM0ZmUyYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMDk0MDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg0ZDJkZTQzMTE3MTA1MGU2OWE1ZGJiNDM1NDdkZmZmZjJhZTMyOGY5MjUxMzk2OWUzMjhlMjI3MjEwOTQ4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rmMFJ-JAPu03OxYyp95U0o-_9NqTEBT5FnAqdQK1F2Y)

Yeah, but it didn't work
