### ISSUE TITLE
Black square on the head

### ISSUE THREAD

**Issue by xNterra** [hacksider/Deep-Live-Cam#48]
First of all, thank you for the project. I have completed the installation, but for your information, I am not using CUDA. I am unable to perform video swaps, but the most important issue is that when I perform an image swap, a black square appears instead of the new face. As you can see in the attached files.
![Capture d’écran 2024-07-11 235914](https://github.com/user-attachments/assets/c0379911-ae65-4646-b3bb-9657a5a483e5)

**Comment by hacksider** [comment]
It seems you have installed the latest version of insightface, please use the insightface version on requirements.txt

**Comment by Thankgod20** [comment]
experiencing this currently insightface version in requirements.txt is 0.7.3 but still getting black box over head

**Comment by Jamadoo** [comment]
@Thankgod20 any solutions? Im experiencing the same issue
