### ISSUE TITLE
Mac Studio M1 the main window is blank. 上项目启动-主窗口空白

### ISSUE THREAD

**Issue by imlx** [hacksider/Deep-Live-Cam#483]
I am encountering a peculiar issue with Deep-Live-Cam. All package dependencies and environment-related contents, including ffpeg, have been installed and configured according to the project’s Readme documentation without any errors. I am using the startup command “python run.py --execution-provider coreml”. However, the main window is blank. When I move the mouse to the position of the corresponding buttons, the mouse icon changes to a small hand, and it is clickable, but I am unable to verify the functionality as the main window is blank and nothing is visible. I seek assistance from the experts on this matter.
项目包依赖以及ffpeg等环境相关内容均按照项目Readme文档进行操作，未报错。 项目启动 命令使用 “python run.py --execution-provider coreml”，但是主窗口显示空白，鼠标移动到相应按钮位置，鼠标图标会变成小手指，并且可以点击，但是无法验证功能，因为主窗口空白什么也看不到，请求各位专家协助。

logs:  控制台 提示只有这些内容
(venv) ➜  Deep-Live-Cam git:(main) ✗ python run.py --execution-provider coreml
Frame processor face_enhancer not found

![Uploading WechatIMG2744.jpg…]()

**Comment by imlx** [comment]
![WechatIMG2744](https://github.com/user-attachments/assets/2719d58b-ad61-4b4c-b4a5-0e61f2651e98)

**Comment by globau** [comment]
See https://github.com/hacksider/Deep-Live-Cam/issues/119
