### ISSUE TITLE
invalid choice: 'openvino' (choose from 'azure', 'cpu') HELP ME PLEASE PLEASE PLEASE

### ISSUE THREAD

**Issue by c0mrad12** [hacksider/Deep-Live-Cam#486]
my error 
C:\Windows\System32\Deep-Live-Cam> python run.py --execution-provider openvino
usage: run.py [-h] [-s SOURCE_PATH] [-t TARGET_PATH] [-o OUTPUT_PATH]
              [--frame-processor {face_swapper,face_enhancer} [{face_swapper,face_enhancer} ...]] [--keep-fps]
              [--keep-audio] [--keep-frames] [--many-faces] [--nsfw-filter]
              [--video-encoder {libx264,libx265,libvpx-vp9}] [--video-quality [0-51]] [--live-mirror]
              [--live-resizable] [--max-memory MAX_MEMORY] [--execution-provider {azure,cpu} [{azure,cpu} ...]]
              [--execution-threads EXECUTION_THREADS] [-v]
run.py: error: argument --execution-provider: invalid choice: 'openvino' (choose from 'azure', 'cpu')

**Comment by AVGRadmin** [comment]
You need to respect the fact that this is people that uses their own private time to develop and maintain this repo. 
As you can see, this and other small/simple issues are usually easy to solve by following the instructions provided properly. (Pluss there are multiple duplicates if these issues).
Other than that i recommend that you have more patience in the future if you have any issues. 

People are likely to help whenever they have time. But personally, i would simply refuse to help anyone after they made the type of comment that you came with. Very disrespectful towards the people that maintain this.

**Comment by ToonWilson** [comment]
hello please what can i do to make my DEEP-LIVE-CAM pop up after completing all setups?
