### ISSUE TITLE
The program only uses the CPU for calculations on mac computers

### ISSUE THREAD

**Issue by teethandnail** [hacksider/Deep-Live-Cam#487]
<img width="790" alt="截屏2024-08-28 17 07 30" src="https://github.com/user-attachments/assets/7620e844-b6f1-49e5-9be9-8e647a1d6f5b">
How can I enable gpu on my mac ?

**Comment by teethandnail** [comment]
<img width="775" alt="image" src="https://github.com/user-attachments/assets/dad62e8b-d51b-403f-ab0b-cc905fdb29c9">
I installed the above libraries.

**Comment by teethandnail** [comment]
<img width="776" alt="image" src="https://github.com/user-attachments/assets/0e8fd89e-bf13-44fe-a2f6-05a72deed914">

I installed the above libraries.

**Comment by emiyalee1005** [comment]
I'm facing the same issue on my m3 max device too. I have following the steps and successfully run with `python run.py --execution-provider coreml`.  But the app only use my cpu and thus very laggy

**Comment by DaoDaoNoCode** [comment]
+1, is there a way to get better support on M3 chip? It's very laggy on my M3 macbook and I believe the GPU is not fully used.

**Comment by cchance27** [comment]
Same question i came here to ask, its attrocious on mac, like severe lag, also it always uses continuity cam instead of the builtin mac cam, don't see a flag to disable it.

**Comment by emiyalee1005** [comment]
> I'm facing the same issue on my m3 max device too. I have following the steps and successfully run with `python run.py --execution-provider coreml`. But the app only use my cpu and thus very laggy

Here is the monitor data
<img width="952" alt="image" src="https://github.com/user-attachments/assets/1bfe597b-2490-4c8f-8983-ad04dc2e9d73">

**Comment by cdrake118** [comment]
Same issue for me. M2 Max
<img width="891" alt="Screenshot 2024-08-28 at 9 33 25 PM" src="https://github.com/user-attachments/assets/4acea5ee-3727-42f1-b06e-5e5e113cc9ab">

**Comment by budda** [comment]
> Same question i came here to ask, its attrocious on mac, like severe lag, also it always uses continuity cam instead of the builtin mac cam, don't see a flag to disable it.

I changed the default camera by editing the ui.py file - look for ```camera = cv2.VideoCapture(0)``` and change the number. 0 was my iPhone, 1 was my monitor, I assume 2 will be my macbook built in one. Your numeration will vary.

**Comment by budda** [comment]
> <img alt="image" width="776" src="https://private-user-images.githubusercontent.com/8167849/362229529-0e8fd89e-bf13-44fe-a2f6-05a72deed914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjgwMDAsIm5iZiI6MTcyNTMyNzcwMCwicGF0aCI6Ii84MTY3ODQ5LzM2MjIyOTUyOS0wZThmZDg5ZS1iZjEzLTQ0ZmUtYTJmNi0wNWE3MmRlZWQ5MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDNUMDE0MTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE2MTRmM2Q4YTgwY2JjM2RjZjcwM2ZkMjhiZTMxNDNmZmZmNTgzNzRiNjUyMTcwMDU0OTg4OThiOTIwOWNkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LQIQm6tofNJ8T_xWBEWwWgmRsMeKYPvYwJ5mABeCrsY">
> I installed the above libraries.

How did you manage to get the onnxruntime-silicon package installed ?! I just get the error:
```
ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon (from versions: none)
ERROR: No matching distribution found for onnxruntime-silicon
````

**Comment by defertoexpertise** [comment]
> > <img alt="image" width="776" src="https://private-user-images.githubusercontent.com/8167849/362229529-0e8fd89e-bf13-44fe-a2f6-05a72deed914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjgwMDAsIm5iZiI6MTcyNTMyNzcwMCwicGF0aCI6Ii84MTY3ODQ5LzM2MjIyOTUyOS0wZThmZDg5ZS1iZjEzLTQ0ZmUtYTJmNi0wNWE3MmRlZWQ5MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDNUMDE0MTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE2MTRmM2Q4YTgwY2JjM2RjZjcwM2ZkMjhiZTMxNDNmZmZmNTgzNzRiNjUyMTcwMDU0OTg4OThiOTIwOWNkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LQIQm6tofNJ8T_xWBEWwWgmRsMeKYPvYwJ5mABeCrsY">
> > I installed the above libraries.
> 
> How did you manage to get the onnxruntime-silicon package installed ?! I just get the error:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon (from versions: none)
> ERROR: No matching distribution found for onnxruntime-silicon
> ```

wrong python version?

**Comment by solstice-gao** [comment]
Using a 32-bit ONNX model increases the inference speed to 15fps, primarily because onnxruntime doesn't yet fully support Apple's M-series chips.

1. You can refer to this repository: [Deep-Live-Cam](https://github.com/gongzhang/Deep-Live-Cam/blob/main/README.macos.md).
2. I am currently converting an ONNX model to a PyTorch model and utilizing MPS for acceleration, but I have encountered some issues during inference and am working to resolve them.

If you are interested, feel free to contact me via email: 17604515707@163.com.

**Comment by budda** [comment]
> > > <img alt="image" width="776" src="https://private-user-images.githubusercontent.com/8167849/362229529-0e8fd89e-bf13-44fe-a2f6-05a72deed914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjgwMDAsIm5iZiI6MTcyNTMyNzcwMCwicGF0aCI6Ii84MTY3ODQ5LzM2MjIyOTUyOS0wZThmZDg5ZS1iZjEzLTQ0ZmUtYTJmNi0wNWE3MmRlZWQ5MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDNUMDE0MTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE2MTRmM2Q4YTgwY2JjM2RjZjcwM2ZkMjhiZTMxNDNmZmZmNTgzNzRiNjUyMTcwMDU0OTg4OThiOTIwOWNkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LQIQm6tofNJ8T_xWBEWwWgmRsMeKYPvYwJ5mABeCrsY">
> > > I installed the above libraries.
> > 
> > 
> > How did you manage to get the onnxruntime-silicon package installed ?! I just get the error:
> > ```
> > ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon (from versions: none)
> > ERROR: No matching distribution found for onnxruntime-silicon
> > ```
> 
> wrong python version?

yeah is newer than 3.10
I tried to downgrade python but didn't seem to "work" for me. I'm new to the world of Python though...

**Comment by teethandnail** [comment]
> > <img alt="image" width="776" src="https://private-user-images.githubusercontent.com/8167849/362229529-0e8fd89e-bf13-44fe-a2f6-05a72deed914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjgwMDAsIm5iZiI6MTcyNTMyNzcwMCwicGF0aCI6Ii84MTY3ODQ5LzM2MjIyOTUyOS0wZThmZDg5ZS1iZjEzLTQ0ZmUtYTJmNi0wNWE3MmRlZWQ5MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDNUMDE0MTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE2MTRmM2Q4YTgwY2JjM2RjZjcwM2ZkMjhiZTMxNDNmZmZmNTgzNzRiNjUyMTcwMDU0OTg4OThiOTIwOWNkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LQIQm6tofNJ8T_xWBEWwWgmRsMeKYPvYwJ5mABeCrsY">
> > I installed the above libraries.
> 
> How did you manage to get the onnxruntime-silicon package installed ?! I just get the error:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon (from versions: none)
> ERROR: No matching distribution found for onnxruntime-silicon
> ```

I installed miniconda, then used miniconda to create a python virtual environment, installed python3.10.10 in the virtual environment, and then executed the commands according to the author's instructions.

**Comment by defertoexpertise** [comment]
Perhaps a silly question... but are you on an Arm based mac or an older intel mac?

**Comment by budda** [comment]
> Perhaps a silly question... but are you on an Arm based mac or an older intel mac?

yeah, M2 Max here.

**Comment by ChristianWeyer** [comment]
> Using a 32-bit ONNX model increases the inference speed to 15fps, primarily because onnxruntime doesn't yet fully support Apple's M-series chips.
> 
> 1. You can refer to this repository: [Deep-Live-Cam](https://github.com/gongzhang/Deep-Live-Cam/blob/main/README.macos.md).
> 2. I am currently converting an ONNX model to a PyTorch model and utilizing MPS for acceleration, but I have encountered some issues during inference and am working to resolve them.
> 
> If you are interested, feel free to contact me via email: [17604515707@163.com](mailto:17604515707@163.com).

Did you ever successfully finish your conversion @solstice-gao ?
