### ISSUE TITLE
I can`t use it for Zoom

### ISSUE THREAD

**Issue by Nor1m** [hacksider/Deep-Live-Cam#495]
My Zoom can't find the camera while using this application

![image](https://github.com/user-attachments/assets/29b7adce-e15f-4bcb-ab3e-03f6c9721f41)

If got errors in the terminal
[ WARN:1@206.703] global cap_msmf.cpp:471 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072875772
[ WARN:1@206.708] global cap_msmf.cpp:483 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072875772
[ WARN:0@206.712] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -1072875772

**Comment by hacksider** [comment]
Use OBS to stream on zoom

**Comment by Nor1m** [comment]
Thanks
