### ISSUE TITLE
The project encountered an exception during operation

### ISSUE THREAD

**Issue by zzy-123-ylr** [hacksider/Deep-Live-Cam#496]
Run it well and click on the live screen to display the black box of the face.
Error message:
UserWarning: Error fetching version info <urlopen error _ssl.c:980: The handshake operation timed out>
  data = fetch_version_info().
 RuntimeWarning: invalid value encountered in cast
  bgr_fake = np.clip(255 * img_fake, 0, 255).astype(np.uint8)[:,:,::-1]

**Comment by yShen868** [comment]
RuntimeWarning: invalid value encountered in cast
  bgr_fake = np.clip(255 * img_fake, 0, 255).astype(np.uint8)[:,:,::-1]
 same question

**Comment by yShen868** [comment]
https://github.com/hacksider/Deep-Live-Cam/issues/382

**Comment by zzy-123-ylr** [comment]
> #382

Thank you

**Comment by zzy-123-ylr** [comment]
> #382

The black box issue has been resolved. Do you know how to handle the problem of unsmooth live visuals? I hope the process and realism can be similar to the video demo in Deep Live Cam. Thank you
