### ISSUE TITLE
mac book pro M1 Max 64G执行:pip install -r requirements.txt 报错

### ISSUE THREAD

**Issue by FeedHedgehog** [hacksider/Deep-Live-Cam#497]
执行
(.venv) (base) mac@JayMBP Deep-Live-Cam % pip install -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform != "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform != "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-gpu: markers 'sys_platform != "darwin"' don't match your environment
Ignoring tensorflow: markers 'sys_platform != "darwin"' don't match your environment
ERROR: Could not find a version that satisfies the requirement numpy==1.23.5 (from versions: 1.24.1, 1.26.3)
ERROR: No matching distribution found for numpy==1.23.5

![e16e205405ddf74284f6d82fb150dab4](https://github.com/user-attachments/assets/d3069c0a-e308-4126-a3e8-277c8dcf1526)

**Comment by FeedHedgehog** [comment]
替换numpy版本为：numpy==1.24.1后，opencv-python 找不到对应版本！

![40e93cb7874b024f4e8d9035f6374857](https://github.com/user-attachments/assets/9cb86847-3175-4bab-88d6-24f4d748e584)

**Comment by budda** [comment]
I had the same today (running on M2 Max).
I got it working by manually pip install commands for each package.

I could not get ```pip install onnxruntime-silicon``` to install though.

Then I keprt running ```% python3 run.py --execution-provider coreml``` until no more missing package errors and the Tk UI sprung to life!

**Comment by JahnKhan** [comment]
it cannot find the onnxruntime-silicon version that is in the requirements.txt. So I changed it to the available one.
`onnxruntime-silicon==1.15.0;` that could be installed, but I have not figured out how to run it, because I just started installing.
I think Iam missing ffmpeg now.
