### ISSUE TITLE
INVALID PROTOBUF : Protobuf Parsing failed

### ISSUE THREAD

**Issue by AboudiMik** [hacksider/Deep-Live-Cam#498]
This error seems to be a recurring error, ive seen many threads and there is no clear solution, ive tried downloading inswapper_128_fp16.onnx from various sources including from the orginal Repo and it still hasnt worked. Can anyone explain the issue and provide a solution because ive tried everything and nothing has worked. 
![Screenshot 2024-08-29 141334](https://github.com/user-attachments/assets/ac8e0202-a37a-40a1-a99a-e8ea14b6a025)
![Screenshot 2024-08-29 141425](https://github.com/user-attachments/assets/233cffb9-9388-43c1-a561-b3071cc195bc)

This is what appears when i press live, a blank screen.

**Comment by NeuroDonu** [comment]
What is the weight of your inswapper_128_fp16.onnx and what is its hash in MD5?
my values (at which I have the program running)
inswapper_128_fp16.onnx - 277288649 bytes
MD5- C9525B85AC01AF04F7810CF81477518C (i use 7zip)
SHA2-256 - 32031DBE50398C1BEFFA9DAADAEC8DD7AE9529D8314A0307B45A4987497F8494

**Comment by NeuroDonu** [comment]
for compare hashs try this site https://www.textcompare.org/

**Comment by eointolster** [comment]
Hi man follow the instructions I have here in this video in the description.
https://www.youtube.com/watch?v=e07wc695y_o
Then after it is installed go to models in the deep-live-cam and delete the inswapper_128_fp16.onx
Then go here 
https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx and download from hugging face 
This worked for me

**Comment by AboudiMik** [comment]
> for compare hashs try this site https://www.textcompare.org/

Ive checked the hashs and they match the file i have downloaded. Does this issue maybe have to do with the instructions .txt file thats in the models folder?

**Comment by eointolster** [comment]
I am sorry you are still having problems AboutMilk, I did what i did in this video 
https://www.youtube.com/watch?v=5jZJnNE1kA0
and it worked for me. I do no think the txt file has any relation to the problem. I just downloaded the file that was in the huggingface and replaced what is there. 
Sorry I cant replicate the issue on my end

**Comment by budda** [comment]
The huggingface link sorted the same console error for me. Thanks @eointolster
