### ISSUE TITLE
App is up and running but nothing appears on preview

### ISSUE THREAD

**Issue by hodgezai** [hacksider/Deep-Live-Cam#499]
As the title says. The preview window pops up but I don't see anything there. I tried running on cuda and normally but same issue occured. Also I do not see anything on the opposite of the image I want to use, that if I am supposed to see any.

The light on my webcam turns on, working but I do not see it in action.
Error I get on cmd follows:     im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

![11](https://github.com/user-attachments/assets/a858d022-b718-4489-8cfc-6b01dc15894b)

**Comment by eointolster** [comment]
Hi man follow the instructions I have here in this video in the description.
https://www.youtube.com/watch?v=e07wc695y_o
Then after it is installed go to models in the deep-live-cam and delete the inswapper_128_fp16.onx
Then go here 
https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx and download from hugging face 
This worked for me

**Comment by hodgezai** [comment]
> Hi man follow the instructions I have here in this video in the description. https://www.youtube.com/watch?v=e07wc695y_o Then after it is installed go to models in the deep-live-cam and delete the inswapper_128_fp16.onx Then go here https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx and download from hugging face This worked for me

Hello thanks for the reply. I did make a clean install from the stratch but same thing persisted. Do you think it is related to pip not being the latest version or is it something else?

**Comment by eointolster** [comment]
It could be for many reasons but if you have it in the virtual environment like I have in the description it should work. Do a pip update but the reason I suggested the venv is because you want to keep your stuff encapsulated and not interferring with anything else.

I did a reinstall and found that the main issue for me was the model as I shown above. I will make another video in a few hours on my channel showing what I have done. 

Best of luck till then

**Comment by hodgezai** [comment]
> It could be for many reasons but if you have it in the virtual environment like I have in the description it should work. Do a pip update but the reason I suggested the venv is because you want to keep your stuff encapsulated and not interferring with anything else.
> 
> I did a reinstall and found that the main issue for me was the model as I shown above. I will make another video in a few hours on my channel showing what I have done.
> 
> Best of luck till then

Thank you. I did update pip and it wasn't the solution either oh and yes I had venv to avoid issues. Let me see if I can find anything else.

**Comment by hodgezai** [comment]
anyone can help?

**Comment by eointolster** [comment]
I made a new video and it goes through it all the way, it is not an entertaining video but the full process I went through, including errors and fixes 
https://youtu.be/OvjWOwUktxw
