### ISSUE TITLE
python run.py doesnt load or show any error 

### ISSUE THREAD

**Issue by Underdome132** [hacksider/Deep-Live-Cam#50]
(base) C:\Users\under\Deep-Live-Cam>python run.py

(base) C:\Users\under\Deep-Live-Cam>

**Comment by Updatedme** [comment]
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by Underdome132** [comment]
please drop video link

**Comment by Decassidyc** [comment]
> (base) C:\Users\under\Deep-Live-Cam>python run.py
> 
> (base) C:\Users\under\Deep-Live-Cam>

If you're using a virtual environment like anaconda or venv, first activate the environment before running python run.py

Anaconda
conda activate deeplivecam  (replace deeplivecam with your environment name)

venv windows
venv\scripts\activate  (replace venv with environment name u created)

venv Linux
venv/bin/activate  (replace venv with environment name u created)
