### ISSUE TITLE
run.py: error: argument --execution-provider: invalid choice: 'directml' (choose from 'tensorrt', 'cuda', 'cpu')

### ISSUE THREAD

**Issue by Atalaura48** [hacksider/Deep-Live-Cam#500]
I have an AMD video card. When I use the following command:

python run.py --execution-provider directml

I get an error like this:

run.py: error: argument --execution-provider: invalid choice: 'directml' (choose from 'tensorrt', 'cuda', 'cpu')

**Comment by DEVENDERMASTER** [comment]
I also have a AMD graphics card. I am using the 'python run.py --execution-provider dml' and it works just fine.

**Comment by Atalaura48** [comment]
> I also have a AMD graphics card. I am using the 'python run.py --execution-provider dml' and it works just fine.

I have the methods on the screen, no dml.

**Comment by Atalaura48** [comment]
I solved the problem: BY DELETING THE APP AND NEVER USING IT AGAIN.
