### ISSUE TITLE
cannot run the program because torch not installed

### ISSUE THREAD

**Issue by Abdul-coder-maker** [hacksider/Deep-Live-Cam#504]
When I run "python3 run.py" or "python run.py --execution-provider cuda", I see error:
  File "/Users/anasser/Desktop/Deep-Live-Cam/run.py", line 3, in <module>
    from modules import core
  File "/Deep-Live-Cam/modules/core.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by Updatedme** [comment]
Did you create an environment? 

I recommend you use miniconda 3.10 for this .

**Comment by Updatedme** [comment]
If you need further help .
You can reach out to me on whatsapp
+2347081306010
https://wa.me/message/GXQYWX4XRTXGB1

**Comment by hacksider** [comment]
try this command
pip install torch

**Comment by sikola123** [comment]
@Updatedme scammer

**Comment by sikola123** [comment]
> If you need further help .
> You can reach out to me on whatsapp
> +2347081306010
> https://wa.me/message/GXQYWX4XRTXGB1

He
Scammer!!!

**Comment by Akie555** [comment]
> 试试这个命令 `pip install torch`

下载到好慢，有什么其他办法吗
