### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==2.0.1+cu118 (from versions: 2.2.0, 2.2.0+cu118, 2.2.1, 2.2.1+cu118, 2.2.2, 2.2.2+cu118, 2.3.0, 2.3.0+cu118, 2.3.1, 2.3.1+cu118, 2.4.0, 2.4.0+cu118) ERROR: No matching distribution found for torch==2.0.1+cu118

### ISSUE THREAD

**Issue by taixiaojingyan** [hacksider/Deep-Live-Cam#508]
why

**Comment by Updatedme** [comment]
> why

Do you have your cuda tool kit 11.8  installed ?
Are you doing this on a Windows, macbook or Linux?

**Comment by taixiaojingyan** [comment]
> Windows

On Windows

**Comment by budda** [comment]
I just manually installed it using ```% pip install torch```

Works for me on macOS after that.

**Comment by Updatedme** [comment]
> > Windows
> 
> On Windows

Pip install torch

**Comment by esauvisky** [comment]
This happens because your Python version is too recent, namely, 3.11 or higher. You need Python 3.10 for this so use `pyenv` to install a different Python version or set up a conda environment.
