### ISSUE TITLE
Not running fast in cpu windows 

### ISSUE THREAD

**Issue by Updatedme** [hacksider/Deep-Live-Cam#51]
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by julywint007** [comment]
Run

**Comment by julywint007** [comment]
> You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

**Comment by julywint007** [comment]
> Run
