### ISSUE TITLE
Revert "Enable to choose a camera device in UI" 

### ISSUE THREAD

**Issue by Timi16** [hacksider/Deep-Live-Cam#511]
I'm facing this difficulty like I don't want Mary cam to be the default but not working on OBS studio to transmit video

**Comment by hacksider** [comment]
If you're on windows, you can use the experimental build

**Comment by pedrolZasx** [comment]
in ui.py added this line to get the camera id run the code get the result and remove it if you want
`def list_available_cameras(max_cameras=10):
    available_cameras = []
    for index in range(max_cameras):
        cap = cv2.VideoCapture(index)
        if cap.isOpened():
            available_cameras.append(index)
            cap.release()  # Release the camera after checking
    return available_cameras

# List available cameras
print("Available cameras:", list_available_cameras())`

after you get the result like 
`Available cameras: [0, 2, 3, 5, 6]`

now replace "def create_webcam_preview" line 975
and input the camera id in "(camera_index=0)"

`def create_webcam_preview(camera_index=0):  # Add camera_index as a parameter
    global preview_label, PREVIEW

    camera = cv2.VideoCapture(
        camera_index
    )  # Use index for the webcam (adjust the index accordingly if necessary)
    camera.set(
        cv2.CAP_PROP_FRAME_WIDTH, PREVIEW_DEFAULT_WIDTH
    )  # Set the width of the resolution
    camera.set(
        cv2.CAP_PROP_FRAME_HEIGHT, PREVIEW_DEFAULT_HEIGHT
    )  # Set the height of the resolution
    camera.set(cv2.CAP_PROP_FPS, 60)  # Set the frame rate of the webcam

    preview_label.configure(
        width=PREVIEW_DEFAULT_WIDTH, height=PREVIEW_DEFAULT_HEIGHT
    )  # Reset the preview image before startup

    PREVIEW.deiconify()  # Open preview window

    frame_processors = get_frame_processors_modules(modules.globals.frame_processors)

    source_image = None  # Initialize variable for the selected face image

    while camera:
        ret, frame = camera.read()
        if not ret:
            break

        temp_frame = frame.copy()  # Create a copy of the frame

        if modules.globals.live_mirror:
            temp_frame = cv2.flip(temp_frame, 1)  # horizontal flipping

        if modules.globals.live_resizable:
            temp_frame = fit_image_to_size(
                temp_frame, PREVIEW.winfo_width(), PREVIEW.winfo_height()
            )

        if not modules.globals.map_faces:
            # Select and save face image only once
            if source_image is None and modules.globals.source_path:
                source_image = get_one_face(cv2.imread(modules.globals.source_path))

            for frame_processor in frame_processors:
                temp_frame = frame_processor.process_frame(source_image, temp_frame)
        else:
            modules.globals.target_path = None

            for frame_processor in frame_processors:
                temp_frame = frame_processor.process_frame_v2(temp_frame)

        image = cv2.cvtColor(
            temp_frame, cv2.COLOR_BGR2RGB
        )  # Convert the image to RGB format to display it with Tkinter
        image = Image.fromarray(image)
        image = ImageOps.contain(
            image, (temp_frame.shape[1], temp_frame.shape[0]), Image.LANCZOS
        )
        image = ctk.CTkImage(image, size=image.size)
        preview_label.configure(image=image)
        ROOT.update()

        if PREVIEW.state() == "withdrawn":
            break

    camera.release()
    PREVIEW.withdraw()  # Close preview window when loop is finished`
