### ISSUE TITLE
deep-live-cam in uvc-gadget

### ISSUE THREAD

**Issue by frostworx** [hacksider/Deep-Live-Cam#514]
I just created an ugly [fork](https://github.com/frostworx/Deep-Live-Cam_uvc-gadget) with some uvc-gadget functionality and description. 
As the [README changes](https://github.com/frostworx/Deep-Live-Cam_uvc-gadget?tab=readme-ov-file#dirty-hack) suggests this is in no way ready for a pull request and likely never won't _(from my side)_,
but maybe at least it helps others with similar attempts or even motivates for a more straightforward and cleaner solution.

If you think this non-issue is unappropriated, please feel free to close it and accept my apologies.

**Comment by hacksider** [comment]
Everything is welcome here. I'm really happy other people are creating stuffs with this fork of roop as well ☺️
