### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by reahari** [hacksider/Deep-Live-Cam#515]
Can a feature be added for bath processing on a directory of images and videos?

**Comment by AVGRadmin** [comment]
I've added batch processing to the [fork](https://github.com/AVGRadmin/Deep-Live-Cam-Docker) i'm using for myself.


Args are `-sf` / `--source_folder` and  `-tf` / `--target_folder`

Just ignore all the docker stuff. It should work as normal for windows with the usual method.

**Comment by reahari** [comment]
Thanks

**Comment by reahari** [comment]
Will this be merged into main?

**Comment by AVGRadmin** [comment]
> Will this be merged into main?

I have no plans to merge it myself. It's just something i'm "messing around" with for personal use. 

I could probably add a commit/pull request, but I doubt that I could use it as it is now. I haven't focused too much on keeping all variables and functions friendly for future commits on the main branch. So there is probably some changes needed to be done to my version in that case.
