### ISSUE TITLE
Face enhancer slow with CUDA

### ISSUE THREAD

**Issue by fojenj** [hacksider/Deep-Live-Cam#517]
Is there any recommended settings for using face enhancer with CUDA? OR should I be using DML instead? My GPU is only at like 40% utilization and same with RAM is way under usage so I feel like it should be able to run better.

It also just looks terrible without face enhancer no matter the quality settings I have.

**Comment by NeuroDonu** [comment]
DML is suitable for cards that don't work with CUDA (older NVIDIA graphics cards as well as any AMD\ INTEL graphics cards). but it is slower than CUDA. to fix this, you can just use more threads.

**Comment by NXTler** [comment]
My system is far from being CPU or GPU bound, so increasing the number of threads via `--execution-threads` does nothing at all. This is a pure software issue on my end.

**Comment by RainyZombie** [comment]
Same here.. we don't have to install the requirements(e.g CUDA TOOLKIT) if we're using the provided release that has everything in the env right?

**Comment by NXTler** [comment]
No, otherwise the GPU wouldn't work at all. The release itself isn't the problem, as I have the issue with a complete manual install.

**Comment by lianglll** [comment]
My GPU, CPU, and RAM utilization are also low

**Comment by hacksider** [comment]
It can only process as much using the live video as of this moment. Usual usage is just 6gb GPU vram. I'm still finding ways on how to improve it.

**Comment by KiritoGuugk** [comment]
> This question doesn't really belong here. Anyway, 1440p is a large resolution for the Models so I would expect a significant slow down. Furthermore your GPU doesn't have a lot of VRAM, you might hit the limit with that resolution and some idle VRAM usage. You also didn't say how long the video is.

It can be finished in 1min without face enhancer

**Comment by NXTler** [comment]
I would bet that you are running into VRAM limit with Face Enhancer, did you checked usage?

**Comment by KiritoGuugk** [comment]
> I would bet that you are running into VRAM limit with Face Enhancer, did you checked usage?

windows task manager shows vram: 7.5/8GB
u r right, VRAM is the limit 😂
