### ISSUE TITLE
 Hey! I updated the portable version.

### ISSUE THREAD

**Issue by NeuroDonu** [hacksider/Deep-Live-Cam#518]
I am the author of the portable version you added to the [releases](https://github.com/hacksider/Deep-Live-Cam/releases/tag/cuda_deep-live-cam). And not too long ago I updated it to add tensorrt support and the ability to upgrade. Here are the links: cuda package ([in telegram](https://t.me/neuralchatik/1397/9979), need to download both versions, but I have been informed that they may not work if you download it on web version) or in my [cloud](https://derkarta.com/index.php/s/eCxzrqkH7SRWF9X) (single archive). directml version [there](https://t.me/neuralchatik/1397/9972).

**Comment by hacksider** [comment]
Awesome to hear that! Will link it again to your site as soon as possible. ☺️

**Comment by cannafodder** [comment]
I tried this an hour after it was posted, though it loads, the face when live looks garbled, with face enhance it switched between dozens of hallucinated hi res faces, also, the tensor and cuda .bat files are identical... RTX4060

**Comment by NeuroDonu** [comment]
That's weird! I asked my friend to test it too and he said and showed me that the faces are heavily distorted. I don't know what to do about it

**Comment by NeuroDonu** [comment]
https://derkarta.com/index.php/s/k3ckfy95PW2jmcd
I update it: remove old models, add models by FaceFusion. Idk, fix error, or no...

**Comment by cannafodder** [comment]
With this the face in live mode works, but face enhance freezes with this error;

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\deeplive_cuda\\Deep-Live-Cam\\models\\GFPGANv1.4.pth'

**Comment by NeuroDonu** [comment]
Oh, damn! I must have downloaded the .onnx version by mistake, not the .pth.

**Comment by NeuroDonu** [comment]
https://t.me/neuralchatik/1397/10730
i wish its a final fix

**Comment by NeuroDonu** [comment]
I'm glad it's working as it should, since I can't even test to see if it works.

**Comment by cannafodder** [comment]
I'm not used to telegram, i attempted to download, got a 7z.001 and 7z.002 both of 4GB size that won't uncompress using 7zip

**Comment by cannafodder** [comment]
"...and the final third part."  my bad lemme try again. I decided to use google translate qand figured i'm stupid lol "и финальная третья часть"

**Comment by cannafodder** [comment]
yes, i am stupid, i downloaded the wrong files. (Only installed Telegram to get this)

**Comment by NeuroDonu** [comment]
F

**Comment by lamb909** [comment]
please which should i download with fixed errors and no installation needed
