### ISSUE TITLE
Run prompt :AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by fengcanluoye** [hacksider/Deep-Live-Cam#520]
The following error message is displayed:
![image](https://github.com/user-attachments/assets/35e52265-dac4-47f7-b2f9-ef1eb50be803)

**Comment by jordanbardella** [comment]
@echo off
set pypath=home = %~dp0python
set appdata=%~dp0tmp
set userprofile=%~dp0tmp
set temp=%~dp0tmp
set PATH=%PATH%;ffmpeg;python\Lib\site-packages\torch\lib;models

set CUDA_MODULE_LOADING=LAZY
set CUDA_PATH=python\Lib\site-packages\torch\lib

.\python\python.exe run.py --execution-provider cuda --execution-threads 60 --max-memory 60
pause

run this in .bat

**Comment by NeuroDonu** [comment]
https://github.com/hacksider/Deep-Live-Cam/issues/509

**Comment by robji15** [comment]
搞定了，哈哈，原来是你导入的人脸图片路径不能包含中文
