### ISSUE TITLE
Why is the face in the generated picture black?

### ISSUE THREAD

**Issue by fengcanluoye** [hacksider/Deep-Live-Cam#521]
![output](https://github.com/user-attachments/assets/e091fc7c-682c-4ddf-8110-a99d2820f708)

**Comment by NXTler** [comment]
This happens for me when I'm using the onnxruntime-gpu by the requirements and not recommended version (1.16.3) for my NVIDIA GPU.

**Comment by xTunner1** [comment]
same problem

**Comment by naffan2014** [comment]
same problem

**Comment by noondood** [comment]
no GPU, same problem

**Comment by fengcanluoye** [comment]
> This happens for me when I'm using the onnxruntime-gpu by the requirements and not recommended version (1.16.3) for my NVIDIA GPU.

Yes, it won't work if you run the following code

`
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3

python run.py --execution-provider cuda
`

**Comment by zrd1314** [comment]
同样的问题

**Comment by 13837678992** [comment]
> > This happens for me when I'm using the onnxruntime-gpu by the requirements and not recommended version (1.16.3) for my NVIDIA GPU.
> 
> Yes, running the following code solves it.
> 
> ` pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3
> 
> python run.py --execution-provider cuda `

I tried your method, but it still doesn't work.
 pip uninstall onnxruntime onnxruntime-gpu
 
 pip install onnxruntime-gpu==1.19.2
 
  python run.py --execution-provider cuda

**Comment by atsedeweyn** [comment]
same problem. I am using cpu. anyone have fix for this?

**Comment by Deja09** [comment]
> same problem. I am using cpu. anyone have fix for this?

same problem also

**Comment by Deja09** [comment]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\wimdows 10/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\wimdows 10/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\wimdows 10/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\wimdows 10/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\wimdows 10/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
 and still showing black square

**Comment by chenyangjamie** [comment]
Using the replacement version of inswapper_128_fp16.onnx solves this issue for me (find link in readme "inswapper_128_fp16.onnx (Note: Use this replacement version if an issue occurs on your computer")

**Comment by algaeakama** [comment]
### PLEASE I NEED URGENT HELP ON THIS
When i use onnxruntime-gpu==1.19.2, the generated pictures or videos faces get blurred with black.  But when i use onnxruntime-gpu==1.16.3, the app only works perfectly with CPU but slow when i execute with **_python run.py_** . However i always gets error when i run with **_python run.py --execution-provider cuda_**
![dd](https://github.com/user-attachments/assets/38835090-0e8b-48e8-a6dc-738060cf7d0a)

**Comment by KRSHH** [comment]
Did you pull the latest version?

**Comment by algaeakama** [comment]
@KRSHH , Yes, I used the latest version. I **### clone the Deep Live Cam** while installing and didn't just download it. Please I want to know if you have successfully installed it on GPU and is working perfectly.
