### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by tianli2005** [hacksider/Deep-Live-Cam#524]
![11111](https://github.com/user-attachments/assets/ed15d6be-47a0-4502-a2dc-c8c07c261545)
I'm seeing the same error as me at #520, but I don't know if it's the same problem as him and I don't know how #520 solves it

**Comment by tianli2005** [comment]
I've been working for six hours to get this step, but I've been stuck in this step for a long time, please help me

**Comment by HC-miss** [comment]
I have the same problem

**Comment by HC-miss** [comment]
#520

**Comment by NeuroDonu** [comment]
https://github.com/hacksider/Deep-Live-Cam/issues/509
I left a decision in https://github.com/hacksider/Deep-Live-Cam/issues/520. it's supposed to help you, lol.

**Comment by tianli2005** [comment]
> #509 我在 #520 中留下了一个决定。它应该能帮到你，哈哈。

Answer to #520 I don't know how to do that

**Comment by NeuroDonu** [comment]
> > #509 我在 #520 中留下了一个决定。它应该能帮到你，哈哈。
> 
> Answer to #520 I don't know how to do that

just rename your files to English and that's it. (I mean the ones you use for swap)

**Comment by tianli2005** [comment]
> > > #509 我在 #520 中留下了一个决定。它应该能帮到你，哈哈。
> > 
> > 
> > 回答 #520 我不知道该怎么做
> 
> 只需将您的文件重命名为英文即可。（我是说你用来交换的那些）

Ok, I'll give it a try, thanks for the answer

**Comment by 9miaomiaomiao9** [comment]
if it is solved?

**Comment by 9miaomiaomiao9** [comment]
> > > > #509 我在 #520 中留下了一个决定。它应该能帮到你，哈哈。
> > > 
> > > 
> > > 回答 #520 我不知道该怎么做
> > 
> > 
> > 只需将您的文件重命名为英文即可。（我是说你用来交换的那些）
> 
> Ok, I'll give it a try, thanks for the answer

have you solved it ？

**Comment by tianli2005** [comment]
> > > > > #509 我在 #520 中留下了一个决定。它应该能帮到你，哈哈。
> > > > 
> > > > 
> > > > 回答 #520 我不知道该怎么做
> > > 
> > > 
> > > 只需将您的文件重命名为英文即可。（我是说你用来交换的那些）
> > 
> > 
> > 好的，我试一试，谢谢你的回答
> 
> 你解决了吗？

Solved

**Comment by tianli2005** [comment]
> > > #509 我在 #520 中留下了一个决定。它应该能帮到你，哈哈。
> > 
> > 
> > 回答 #520 我不知道该怎么做
> 
> 只需将您的文件重命名为英文即可。（我是说你用来交换的那些）

The face is mushy and there seems to be a box on the face

**Comment by davidGangGang** [comment]
I have the same problem

**Comment by NeuroDonu** [comment]
![image](https://github.com/user-attachments/assets/0180533c-8696-4378-895e-83a52bb9179e)
like this? try to delete models, which you have in models. and download facefusion model:
https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx

i think its will help you

**Comment by Updatedme** [comment]
You are getting this error because you are a gpu, which is less
> ![11111](https://github.com/user-attachments/assets/ed15d6be-47a0-4502-a2dc-c8c07c261545)
> I'm seeing the same error as me at #520, but I don't know if it's the same problem as him and I don't know how #520 solves it

**Comment by robji15** [comment]
搞定了，哈哈，原来是你导入的人脸图片路径不能包含中文
