### ISSUE TITLE
How to remove watermark 

### ISSUE THREAD

**Issue by solmyr118** [hacksider/Deep-Live-Cam#526]
How to remove watermark?

**Comment by budda** [comment]
Where are you seeing a watermark ?

**Comment by solmyr118** [comment]
In the lower right corner of the converted video, there
![111](https://github.com/user-attachments/assets/8a82b542-8135-496c-9798-4de791db08eb)
 is a text watermark:GoEnhance.Ai

**Comment by budda** [comment]
How is https://www.goenhance.ai/ related to Deep Live Cam project?

**Comment by solmyr118** [comment]
Sorry, I made a mistake. My source video has a watermark.No problem now
