### ISSUE TITLE
Some kind of error

### ISSUE THREAD

**Issue by geszat221** [hacksider/Deep-Live-Cam#527]
![изображение](https://github.com/user-attachments/assets/b8083792-a9c5-44cf-a347-2bb5cfdb828f)

1. I start the software
2. I insert the face (the file is in English).
3. turn on the virtual camera in OBS
4. press Live in the software.

After these actions errors appear in red text in the console

![изображение](https://github.com/user-attachments/assets/a03b439f-8293-4b83-828f-862da7d9fe60)

And after these errors in red color, AI gives an error, which was solved in the previous questions (file is not in English).

**Who knows how to solve this?**

**Comment by avgragmin** [comment]
Try renaming your input file (i.e: test.jpg) since it complains on the file name.

![image](https://github.com/user-attachments/assets/7cd0fef1-c79d-469e-8b27-651002ff366c)

**Comment by geszat221** [comment]
> Try renaming your input file (i.e: test.jpg) since it complains on the file name.
> 
> ![image](https://private-user-images.githubusercontent.com/173109805/363643313-7cd0fef1-c79d-469e-8b27-651002ff366c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzYzNDQsIm5iZiI6MTcyNTI3NjA0NCwicGF0aCI6Ii8xNzMxMDk4MDUvMzYzNjQzMzEzLTdjZDBmZWYxLWM3OWQtNDY5ZS04YjI3LTY1MTAwMmZmMzY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxMTIwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTI1Njk1YWZhY2M0ODViNDUyY2Q4M2FjNTRhZDUzYzU3NTEwNzkyMWUyOTczMWVlMTQxZDgwMzRjYWFlMzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D-QQ4kxiLEN17sFU9B4HgNYatSyMc4gvnLerqa6QJbo)
> 
> Edit: Duplicate of #523

![изображение](https://github.com/user-attachments/assets/d92cac06-3839-4895-bc47-51318ee687ee)

Still the same error

**Comment by NeuroDonu** [comment]
Apparently onnxruntime-gpu was installed without CUDA support. is this a portable version or did you install it yourself?

**Comment by geszat221** [comment]
> Apparently onnxruntime-gpu was installed without CUDA support. is this a portable version or did you install it yourself?

![изображение](https://github.com/user-attachments/assets/d88d03ee-f2fc-4690-a4cb-941eb27074a2)

I just wrote in cmd - pip uninstall onnxruntime-gpu

and reinstalled it and still the same error.


![изображение](https://github.com/user-attachments/assets/bf09d731-b5df-4df8-b9e9-1bc21d3c1c78)

**Comment by NeuroDonu** [comment]
did you install cuda 11.8 + cudnn?

**Comment by geszat221** [comment]
> did you install cuda 11.8 + cudnn?

![изображение](https://github.com/user-attachments/assets/a6fb1ee2-93f0-4f9e-84df-8eef60fa91dd)

Yes, I also added the files to the PATH.

**Comment by NeuroDonu** [comment]
> > вы установили cuda 11.8 + cudnn?
> 
> ![изображение](https://private-user-images.githubusercontent.com/180166747/363777028-a6fb1ee2-93f0-4f9e-84df-8eef60fa91dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMDQzOTUsIm5iZiI6MTcyNTMwNDA5NSwicGF0aCI6Ii8xODAxNjY3NDcvMzYzNzc3MDI4LWE2ZmIxZWUyLTkzZjAtNGY5ZS04NGRmLThlZWY2MGZhOTFkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxOTA4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTBhZmNlNzA5NDAxNWViZTZmMmUxNGY4NDhhYTExNThiZjA4MWJlNWI0ODE1N2ZlOGNiMDNjYThhZTdlM2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.30P_kyu1JRXnZIpw83xXQXVhc--WOk3GChXVWtsIANI)
> 
> Да, я также добавил файлы в PATH.

nccc --version напиши в терминал

**Comment by geszat221** [comment]
> nccc --version

![изображение](https://github.com/user-attachments/assets/5df7a1a4-84b2-40b9-83d7-17d3776d3f6b)

**Comment by NeuroDonu** [comment]
Стой, подожди, попробуй pip install onnxruntime==1.18.1, 1.19 лишь 12.1 или 12.4 поддерживает, надо в доки залезть

**Comment by geszat221** [comment]
> Стой, подожди, попробуй pip install onnxruntime==1.18.1, 1.19 лишь 12.1 или 12.4 поддерживает, надо в доки залезть

Можно у чат гпт спросить, но я по его гайду и устанавливал с разбором ошибок

**Comment by geszat221** [comment]
> Не, 1.18.1 просто попробуй поставить, мне помогло

![изображение](https://github.com/user-attachments/assets/d2cceb76-0206-40d5-82a5-17084f7cdd70)

вот что теперь

**Comment by NeuroDonu** [comment]
Хмм. Попробуй тогда 1.18.0 версию, если не поможет, то самый крайняк 1.16.3, она точно работает

**Comment by geszat221** [comment]
> Хмм. Попробуй тогда 1.18.0 версию, если не поможет, то самый крайняк 1.16.3, она точно работает

А как снести только что установленную?

**Comment by NeuroDonu** [comment]
Аргумент -U в конец докинб

**Comment by geszat221** [comment]
> Аргумент -U в конец докинь

![изображение](https://github.com/user-attachments/assets/d89c7814-157d-4a0c-8920-266bc6b24910)

Та же ошибка после установки

![изображение](https://github.com/user-attachments/assets/1c41b86f-b05c-45d8-bee6-22329e010925)

**Comment by NeuroDonu** [comment]
Так ты обычную версию ставишь, чёт я проступил.
pip uninstall onnxruntime onnxruntime-gpu -y

Если сработает, отпишись, после этого делай это:
pip install onnxruntime-gpu==1.18.0

**Comment by geszat221** [comment]
> Аргумент -U в конец докинь

Твоя portable версия не имеет таких проблем? Мб ее просто поставить

**Comment by geszat221** [comment]
![изображение](https://github.com/user-attachments/assets/898f0494-3559-43cc-ab14-73e4beaf278f)

![изображение](https://github.com/user-attachments/assets/d849bfe9-5503-4bc3-9748-46ec36910652)

![изображение](https://github.com/user-attachments/assets/3f7f1b2b-5fe0-46bb-be0f-1a4e2bb73537)


Теперь такие ошибки

**Comment by NeuroDonu** [comment]
Хм, во-первых какая у тебя видюха. Во вторых переставь куду, можешь из моей портативки взять

**Comment by geszat221** [comment]
> Хм, во-первых какая у тебя видюха. Во вторых переставь куду, можешь из моей портативки взять

RTX 3060, удалить старую и у тебя reqs скачать?

**Comment by NeuroDonu** [comment]
> > Хм, во-первых какая у тебя видюха. Во вторых переставь куду, можешь из моей портативки взять
> 
> RTX 3060, удалить старую и у тебя reqs скачать?

С 3060 выпал, у меня ошибка что не видит девайс лишь на mx130. Ладно, может дрова старые? И как ты ставил куду

**Comment by geszat221** [comment]
> > > Хм, во-первых какая у тебя видюха. Во вторых переставь куду, можешь из моей портативки взять
> > 
> > 
> > RTX 3060, удалить старую и у тебя reqs скачать?
> 
> С 3060 выпал, у меня ошибка что не видит девайс лишь на mx130. Ладно, может дрова старые? И как ты ставил куду

Дрова свежие, куду через cmd вроде бы, но точно не помню. Гпт вел меня

**Comment by geszat221** [comment]
> mx130

![изображение](https://github.com/user-attachments/assets/73102053-c9ed-4c29-9760-79df39af1f30)

**Comment by NeuroDonu** [comment]
Не доверяй гпт. Смари чё делать надо.
Вин нажимаешь, пишешь установка и удаление приложений. Сносишь все что связано с CUDA (можешь просто отсортировать) и Nsight. После этого действия идёшь сюда: https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_522.06_windows.exe, ставишь ее, ребутаешь комп. После этого скачиваешь это: https://developer.nvidia.com/downloads/compute/cudnn/secure/8.9.7/local_installers/11.x/cudnn-windows-x86_64-8.9.7.29_cuda11-archive.zip/
Этот архив дропаешь в папку куды, она обычно расположена в: C:\Program Files\ MVIDIA GPU TOOLKIT (или в этом роде), в ней папка CUDA, там v11.8. в нее дропаешь содержимое архива (как ты в него зайдешь тебя встретит подпапка с его названием, ее содержимое (в ней несколько папок, именно их!, не ее одну) дропаешь. Ребутаешь комп снова и ставишь по новой onnxruntime-gpu, предварительно удалив старую, как я показал. Если в чем-то будет сложности можешь мне написать в тг, а то тут не шибко удобно. Тг: donu4ai, если понадобится

**Comment by NeuroDonu** [comment]
Либо можешь не морочиться, просто скачай портативку в соседнем топике, проверили ее недавно, все работает как надо вродь

**Comment by geszat221** [comment]
> Либо можешь не морочиться, просто скачай портативку в соседнем топике, проверили ее недавно, все работает как надо вродь

Лучше этот вариант использую. Ща попробую

**Comment by NeuroDonu** [comment]
В соседнем топике есть, последний релиз бери, первый слегка багнутый

**Comment by geszat221** [comment]
> багнутый

А можешь линк дать? Найти не могу

**Comment by NeuroDonu** [comment]
https://derkarta.com/index.php/s/k3ckfy95PW2jmcd

**Comment by geszat221** [comment]
> https://derkarta.com/index.php/s/k3ckfy95PW2jmcd

![изображение](https://github.com/user-attachments/assets/077a659c-323f-4fea-9261-d77753cf5490)


Все запускается, ошибок нет, но превью не грузит и вылетает..

**Comment by NeuroDonu** [comment]
Нейм файла какой

**Comment by geszat221** [comment]
> Нейм файла какой
![изображение](https://github.com/user-attachments/assets/d313466b-efaf-44a8-988e-e168c6b079e0)

**Comment by NeuroDonu** [comment]
Я имею ввиду который ты заюзал для свапа, он на русском?

**Comment by geszat221** [comment]
> Я имею ввиду который ты заюзал для свапа, он на русском?

Не, на англ, как и пусть, в котором этот фаил

**Comment by NeuroDonu** [comment]
Тогда выстави потоков меньше в батнике, может у тебя крашится из-за малого количества озу / врам

**Comment by geszat221** [comment]
> Тогда выстави потоков меньше в батнике, может у тебя крашится из-за малого количества озу / врам

не, у меня 32 gb оперативы и проц топовый

**Comment by NeuroDonu** [comment]
Загляни в батник, там я вроде выставил 100 потоков, нолик убери и проверь работоспособность

**Comment by geszat221** [comment]
> Загляни в батник, там я вроде выставил 100 потоков, нолик убери и проверь работоспособность

![изображение](https://github.com/user-attachments/assets/6b60eb63-eb2b-4b98-89a8-cd324a6db669)

тоже самое

**Comment by NeuroDonu** [comment]
Ну хз, это странно. Можешь записать видео? Или фулл лог скинь

**Comment by geszat221** [comment]
> Ну хз, это странно. Можешь записать видео? Или фулл лог скинь

https://dropmefiles.com/41Jd4

**Comment by NeuroDonu** [comment]
> > Ну хз, это странно. Можешь записать видео? Или фулл лог скинь
> 
> https://dropmefiles.com/41Jd4

Хм. Осталось пара вариантов, совмести их: убери tensorrt и возьми диспетчер задач, смотри что он скажет. Ещё возможно проблема с вебкой. Но тут хз

**Comment by geszat221** [comment]
> > > Ну хз, это странно. Можешь записать видео? Или фулл лог скинь
> > 
> > 
> > https://dropmefiles.com/41Jd4
> 
> Хм. Осталось пара вариантов, совмести их: убери tensorrt и возьми диспетчер задач, смотри что он скажет. Ещё возможно проблема с вебкой. Но тут хз

Без tensorrt заработало, /thread

**Comment by NeuroDonu** [comment]
Видимо я забыл это убрать в батнике, завтра буду у компа - выкачу финальную обнову в группу, но и на сервак тоже залью

**Comment by geszat221** [comment]
аа
