### ISSUE TITLE
Portable Version Face Enhance CLI error?

### ISSUE THREAD

**Issue by RainyZombie** [hacksider/Deep-Live-Cam#528]
Steps to reproduce:

Running the following via the portable version:

`.\python\python.exe run.py -s "F:\ai\ex name.png" -t  "F:\mp4" -o "F:\ai\imgcore\Canny TT\outputquality1newfaceenh.mp4" --frame-processor face_enhancer --execution-provider tensorrt --execution-threads 40 --max-memory 16 --video-quality 1`

It runs for a bit then at 20-30% I get   

>   assert input_size is not None or self.input_size is not None
> AssertionError

![image](https://github.com/user-attachments/assets/594fc69e-fa79-4c08-8614-e295741fecef)

Anyone encountering a similar issue? P.S: I tried other provider, via GUI it works

Any input is greatly appreciated!

**Comment by missu263** [comment]
how to fix? I also got this error: 
assert input_size is not None or self.input_size is not None
AssertionError
