### ISSUE TITLE
error running using cuda 

### ISSUE THREAD

**Issue by VergilMorvx** [hacksider/Deep-Live-Cam#530]
C:\Users\Vergil\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Deep-Live-Cam\modules\core.py", line 16, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'

also when i try to 
pip install onnxruntime-gpu==1.16.3

i get 

ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.16.3 (from versions: 1.17.0, 1.17.1, 1.18.0, 1.18.1, 1.19.0)
ERROR: No matching distribution found for onnxruntime-gpu==1.16.3

**Comment by RainyZombie** [comment]
If you can't get your dependencies installed I'd recommend downloading the portal version as it's packed with everything needed

**Comment by NeuroDonu** [comment]
Which python you use? 3.10.9?

**Comment by hacksider** [comment]
Heads up, I just created a no installation file on the readme. It's a single package where you only need to install CUDA then just run it after you unzip it.
