### ISSUE TITLE
Autolaunch CLI Live 

### ISSUE THREAD

**Issue by Niutonian** [hacksider/Deep-Live-Cam#535]
Quick question, 
how can I autolaunch the "Live" face swap from CLI?
`python.exe run.py --execution-provider cuda --execution-threads 60 --max-memory 60 --many-faces --video-quality 50 --frame-processor face_swapper --live-mirror --live-resizable --frame-processor face_enhancer `

I imagine I must insert the source Image like this:
`(faceEnv) C:\AI_TEMP\REALTIME_FACESWAP\Deep-Live-Cam-cuda\DEEPLIVECAM_GITHUB\Deep-Live-Cam>python.exe run.py --execution-provider cuda --execution-threads 60 --max-memory 60 --many-faces --video-quality 50 --frame-processor face_swapper --frame-processor face_enhancer --live-mirror --live-resizable  -s "C:\Users\makeDays\Downloads\FACES_00026_-image.png"`

I get this error:
[DLC.FACE-ENHANCER] Select an image or video for target path.

--
what would be the correct command line combo?

**Comment by hacksider** [comment]
Check the run-cuda.bat (that's just the base example on windows) You don't need to include the face enhancer if you're planning on using it with your webcam (that's still is very slow even on the top of the line PC).

**Comment by Buvi07** [comment]
@Niutonian hey what you mean --execution-threads 60 --max-memory 60 are you using 60 percent of your threads and mem or actual number
