### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by manel00** [hacksider/Deep-Live-Cam#536]
Hello,

I needed to install `customtkinter, tensorflow, onnxruntime` libraries

Now i have this problem, how can i fix it? I could not

Thank you

p.s:

![image](https://github.com/user-attachments/assets/f2be38d7-8768-43d1-9869-3744f3ce2251)

**Comment by AVGRadmin** [comment]
Both of you need to follow the installation instructions properly. Use virtual environment for python to ensure no mix-ups with pip.

`no module named xxxx` means that package `xxxx` was not properly installed.

@Hopeyu , you have a different error. Wrong Numpy version. You should have a version lower than 2.x, while you're trying to run a version above that.

**Comment by manel00** [comment]
I did it, but it is not working

**Comment by dorianabdullahu** [comment]
Try "python3 -m tkinter"; it should open a small window; if not, it will display that error again. 
I installed python-tk manually, which did the trick for me.
If you have multiple python versions, try "-m tkinter" with each one and use the version that works.
