### ISSUE TITLE
Error in Line 3, Line 14, Line148 + fbgemndll

### ISSUE THREAD

**Issue by ok-maker** [hacksider/Deep-Live-Cam#537]
PS C:\Users\Agency work account\Deep-Live-Cam> python run.py
Traceback (most recent call last):
  File "C:\Users\Agency work account\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "C:\Users\Agency work account\Deep-Live-Cam\modules\core.py", line 14, in <module>
    import torch
  File "C:\Users\Agency work account\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Agency work account\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by Updatedme** [comment]
You definitely did not follow the instructions properly.  

What's your OS and computer  configuration ?

**Comment by ok-maker** [comment]
> You definitely did not follow the instructions properly.
> 
> What's your OS and computer configuration ?

I know i also had problem downloading torch until i downgraded python to 3.10.10 and then torch got downloaded i have a window 11 pc 64x

**Comment by ok-maker** [comment]
> You definitely did not follow the instructions properly.
> 
> What's your OS and computer configuration ?

   I also got  this in the endof the requirments
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by Updatedme** [comment]
> > You definitely did not follow the instructions properly.
> > 
> > What's your OS and computer configuration ?
> 
>    I also got  this in the endof the requirments
> note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for insightface
> Failed to build insightface
> ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects 

You will get an endless error if you don't follow the installation Introduction process. 
Refeer to the deep-live-cam setup installation and follow all steps listed according to your pc specification

**Comment by Updatedme** [comment]
If you need further assistance with deep-live-cam or help with full installation, reach out to me on whatsapp 
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010
