### ISSUE TITLE
Guidance on selecting a camera when using the software

### ISSUE THREAD

**Issue by huongvnn82** [hacksider/Deep-Live-Cam#551]
I am currently using the DeepLiveCam software and noticed that the software automatically selects one camera (CAM) for image processing. However, my computer has multiple cameras, and I would like to know how to choose one of these cameras to use with the software.

I would greatly appreciate your assistance and guidance on this matter.
Thanks

**Comment by hacksider** [comment]
You can use the experimental version as of this moment as it have that functionality already.

**Comment by huongvnn82** [comment]
Thank you. I am using Deep Live Cam 1.3.0. and i do not see this function. I will update now.
By the way, may I ask if the software has the capability to process input from livestream signals such as YouTube, Zoom, etc.?

**Comment by hacksider** [comment]
if you use OBS, then yes

**Comment by huongvnn82** [comment]
i am using NVIDIA P5000 and 2 x Xeon E5-2660. 
- With Swapper mode: The system runs almost 100% CPU and 100% HDD. The system processes images at ~ 10fps. 
- Switching to Face-Enhancer mode: the system only uses CPU ~ 3% and GPU ~ 18% (and CUDA ~ 70%) then the system processes at ~ 2fps. Can you guide me to use 100% GPU to increase system speed? I read the instructions and there are no detailed instructions. Thank you so much
