### ISSUE TITLE
IMKClient Stall detected, block performed very slowly

### ISSUE THREAD

**Issue by naffan2014** [hacksider/Deep-Live-Cam#554]
Python[77713:45389541] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_supportsProperty:reply:) block performed very slowly (2.67 secs).

python:3.12
platform: mac

**Comment by Updatedme** [comment]
🤷‍♂️

**Comment by Updatedme** [comment]
Basic python requirements 3.10

This will help

brew install python-tk@3.10
