### ISSUE TITLE
Install Issue 9/6/2024

### ISSUE THREAD

**Issue by DyNgPinasOfficial** [hacksider/Deep-Live-Cam#555]
D:\PROGRAMMING\PYTHON\Deep-Live-Cam> pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow: markers 'sys_platform == "darwin"' don't match your environment
Requirement already satisfied: numpy<2,>=1.23.5 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (1.26.4)
Collecting opencv-python==4.8.1.78
  Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl (38.1 MB)
Collecting onnx==1.16.0
  Using cached onnx-1.16.0-cp310-cp310-win_amd64.whl (14.4 MB)
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: psutil==5.9.8 in c:\users\dy\appdata\roaming\python\python310\site-packages (from -r requirements.txt (line 7)) (5.9.8) 
Collecting tk==0.1.0
  Using cached tk-0.1.0-py3-none-any.whl (3.9 kB)
Collecting customtkinter==5.2.2
  Using cached customtkinter-5.2.2-py3-none-any.whl (296 kB)
Collecting pillow==9.5.0
  Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting torch==2.0.1+cu118
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)
Collecting torchvision==0.15.2+cu118
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting onnxruntime-gpu==1.18.0
  Using cached onnxruntime_gpu-1.18.0-cp310-cp310-win_amd64.whl (157.7 MB)
Collecting tensorflow==2.12.1
  Using cached tensorflow-2.12.1-cp310-cp310-win_amd64.whl (1.9 kB)
Collecting opennsfw2==0.10.2
  Using cached opennsfw2-0.10.2-py3-none-any.whl (12 kB)
Collecting protobuf==4.23.2
  Using cached protobuf-4.23.2-cp310-abi3-win_amd64.whl (422 kB)
Collecting tqdm==4.66.4
  Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Collecting gfpgan==1.3.8
  Using cached gfpgan-1.3.8-py3-none-any.whl (52 kB)
Requirement already satisfied: matplotlib in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (3.8.4)
Collecting easydict
  Using cached easydict-1.13-py3-none-any.whl (6.8 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.5.1-cp310-cp310-win_amd64.whl (11.0 MB)
Requirement already satisfied: scipy in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (1.13.0)
Collecting prettytable
  Using cached prettytable-3.11.0-py3-none-any.whl (28 kB)
Collecting albumentations
  Using cached albumentations-1.4.14-py3-none-any.whl (177 kB)
Collecting cython
  Using cached Cython-3.0.11-cp310-cp310-win_amd64.whl (2.8 MB)
Requirement already satisfied: requests in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (2.32.3)
Collecting scikit-image
  Using cached scikit_image-0.24.0-cp310-cp310-win_amd64.whl (12.9 MB)
Collecting darkdetect
  Using cached darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Requirement already satisfied: packaging in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from customtkinter==5.2.2->-r requirements.txt (line 9)) (23.2)
Collecting filelock
  Using cached filelock-3.15.4-py3-none-any.whl (16 kB)
Requirement already satisfied: jinja2 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from torch==2.0.1+cu118->-r requirements.txt (line 11)) (3.1.4)
Collecting networkx
  Using cached networkx-3.3-py3-none-any.whl (1.7 MB)
Collecting sympy
  Using cached sympy-1.13.2-py3-none-any.whl (6.2 MB)
Requirement already satisfied: typing-extensions in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from torch==2.0.1+cu118->-r requirements.txt (line 11)) (4.12.1)
Collecting flatbuffers
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
Collecting coloredlogs
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting tensorflow-intel==2.12.1
  Using cached tensorflow_intel-2.12.1-cp310-cp310-win_amd64.whl (272.8 MB)
Collecting gdown>=4.2.0
  Using cached gdown-5.2.0-py3-none-any.whl (18 kB)
Requirement already satisfied: colorama in c:\users\dy\appdata\roaming\python\python310\site-packages (from tqdm==4.66.4->-r requirements.txt (line 22)) (0.4.6)
Collecting yapf
  Using cached yapf-0.40.2-py3-none-any.whl (254 kB)
Collecting facexlib>=0.2.5
  Using cached facexlib-0.3.0-py3-none-any.whl (59 kB)
Requirement already satisfied: pyyaml in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from gfpgan==1.3.8->-r requirements.txt (line 23)) (6.0.1)
Collecting basicsr>=1.4.2
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... done
Collecting tb-nightly
  Using cached tb_nightly-2.18.0a20240906-py3-none-any.whl (5.5 MB)
Collecting lmdb
  Using cached lmdb-1.5.1-cp310-cp310-win_amd64.whl (100 kB)
Requirement already satisfied: six>=1.12.0 in c:\users\dy\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.12.1->tensorflow==2.12.1->-r requirements.txt (line 19)) (1.16.0)
Requirement already satisfied: setuptools in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from tensorflow-intel==2.12.1->tensorflow==2.12.1->-r requirements.txt (line 19)) (65.5.0)
Collecting wrapt<1.15,>=1.11.0
  Using cached wrapt-1.14.1-cp310-cp310-win_amd64.whl (35 kB)
Collecting tensorflow-estimator<2.13,>=2.12.0
  Using cached tensorflow_estimator-2.12.0-py2.py3-none-any.whl (440 kB)
Collecting jax>=0.3.15
  Using cached jax-0.4.31-py3-none-any.whl (2.0 MB)
Collecting gast<=0.4.0,>=0.2.1
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting absl-py>=1.0.0
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
Collecting keras<2.13,>=2.12.0
  Using cached keras-2.12.0-py2.py3-none-any.whl (1.7 MB)
Collecting termcolor>=1.1.0
  Using cached termcolor-2.4.0-py3-none-any.whl (7.7 kB)
Collecting google-pasta>=0.1.1
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting grpcio<2.0,>=1.24.3
  Using cached grpcio-1.66.1-cp310-cp310-win_amd64.whl (4.3 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting tensorboard<2.13,>=2.12
  Using cached tensorboard-2.12.3-py3-none-any.whl (5.6 MB)
Collecting numpy<2,>=1.23.5
  Using cached numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting libclang>=13.0.0
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
Collecting h5py>=2.9.0
  Using cached h5py-3.11.0-cp310-cp310-win_amd64.whl (3.0 MB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Using cached tensorflow_io_gcs_filesystem-0.31.0-cp310-cp310-win_amd64.whl (1.5 MB)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting astunparse>=1.6.0
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting addict
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Requirement already satisfied: future in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from basicsr>=1.4.2->gfpgan==1.3.8->-r requirements.txt (line 23)) (1.0.0)
Collecting numba
  Using cached numba-0.60.0-cp310-cp310-win_amd64.whl (2.7 MB)
Collecting filterpy
  Using cached filterpy-1.4.5.zip (177 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from gdown>=4.2.0->opennsfw2==0.10.2->-r requirements.txt (line 20)) (4.12.3)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 6)) (4.51.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dy\appdata\roaming\python\python310\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 6)) (2.9.0)
Requirement already satisfied: cycler>=0.10 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 6)) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 6)) (3.1.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 6)) (1.2.1)
Collecting lazy-loader>=0.4
  Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)
Collecting imageio>=2.33
  Using cached imageio-2.35.1-py3-none-any.whl (315 kB)
Collecting tifffile>=2022.8.12
  Using cached tifffile-2024.8.30-py3-none-any.whl (227 kB)
Collecting opencv-python-headless>=4.9.0.80
  Using cached opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)
Collecting eval-type-backport
  Downloading eval_type_backport-0.2.0-py3-none-any.whl (5.9 kB)
Collecting albumentations
  Using cached albumentations-1.4.13-py3-none-any.whl (171 kB)
  Using cached albumentations-1.4.12-py3-none-any.whl (171 kB)
  Using cached albumentations-1.4.11-py3-none-any.whl (165 kB)
  Using cached albumentations-1.4.10-py3-none-any.whl (161 kB)
  Using cached albumentations-1.4.8-py3-none-any.whl (156 kB)
Collecting albucore>=0.0.4
  Using cached albucore-0.0.14-py3-none-any.whl (8.5 kB)
Collecting albumentations
  Using cached albumentations-1.4.7-py3-none-any.whl (155 kB)
  Using cached albumentations-1.4.6-py3-none-any.whl (153 kB)
  Using cached albumentations-1.4.4-py3-none-any.whl (150 kB)
  Using cached albumentations-1.4.3-py3-none-any.whl (137 kB)
  Using cached albumentations-1.4.2-py3-none-any.whl (133 kB)
  Using cached albumentations-1.4.1-py3-none-any.whl (130 kB)
  Using cached albumentations-1.4.0-py3-none-any.whl (123 kB)
  Using cached albumentations-1.3.1-py3-none-any.whl (125 kB)
Collecting qudida>=0.0.4
  Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
Collecting humanfriendly>=9.1
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch==2.0.1+cu118->-r requirements.txt (line 11)) (2.1.5)
Requirement already satisfied: wcwidth in c:\users\dy\appdata\roaming\python\python310\site-packages (from prettytable->insightface==0.7.3->-r requirements.txt (line 6)) (0.2.13)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 6)) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 6)) (2.2.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 6)) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 6)) (2024.6.2)
Collecting joblib>=1.2.0
  Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Collecting threadpoolctl>=3.1.0
  Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Collecting mpmath<1.4,>=1.1.0
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.7-py3-none-any.whl (106 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from tb-nightly->gfpgan==1.3.8->-r requirements.txt (line 23)) (3.0.3)
Requirement already satisfied: platformdirs>=3.5.1 in c:\users\dy\appdata\roaming\python\python310\site-packages (from yapf->gfpgan==1.3.8->-r requirements.txt (line 23)) (4.2.0)
Requirement already satisfied: tomli>=2.0.1 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from yapf->gfpgan==1.3.8->-r requirements.txt (line 23)) (2.0.1)
Collecting importlib-metadata>=6.6.0
  Using cached importlib_metadata-8.4.0-py3-none-any.whl (26 kB)
Collecting wheel<1.0,>=0.23.0
  Using cached wheel-0.44.0-py3-none-any.whl (67 kB)
Collecting pyreadline3
  Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Collecting zipp>=0.5
  Using cached zipp-3.20.1-py3-none-any.whl (9.0 kB)
Collecting jaxlib<=0.4.31,>=0.4.30
  Using cached jaxlib-0.4.31-cp310-cp310-win_amd64.whl (56.3 MB)
Collecting ml-dtypes>=0.2.0
  Using cached ml_dtypes-0.4.0-cp310-cp310-win_amd64.whl (126 kB)
Collecting google-auth<3,>=1.6.3
  Using cached google_auth-2.34.0-py2.py3-none-any.whl (200 kB)
Collecting google-auth-oauthlib<1.1,>=0.5
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\dy\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->gdown>=4.2.0->opennsfw2==0.10.2->-r requirements.txt (line 20)) (2.5)
Collecting llvmlite<0.44,>=0.43.0dev0
  Using cached llvmlite-0.43.0-cp310-cp310-win_amd64.whl (28.1 MB)
Collecting PySocks!=1.5.7,>=1.5.6
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.4.0-py3-none-any.whl (181 kB)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.5.0-py3-none-any.whl (9.5 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Collecting pyasn1<0.7.0,>=0.4.6
  Using cached pyasn1-0.6.0-py2.py3-none-any.whl (85 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for insightface (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [215 lines of output]
      WARNING: pandoc not enabled
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\insightface
      copying insightface\__init__.py -> build\lib.win-amd64-cpython-310\insightface
      creating build\lib.win-amd64-cpython-310\insightface\app
      copying insightface\app\common.py -> build\lib.win-amd64-cpython-310\insightface\app
      copying insightface\app\face_analysis.py -> build\lib.win-amd64-cpython-310\insightface\app
      copying insightface\app\mask_renderer.py -> build\lib.win-amd64-cpython-310\insightface\app
      copying insightface\app\__init__.py -> build\lib.win-amd64-cpython-310\insightface\app
      creating build\lib.win-amd64-cpython-310\insightface\commands
      copying insightface\commands\insightface_cli.py -> build\lib.win-amd64-cpython-310\insightface\commands
      copying insightface\commands\model_download.py -> build\lib.win-amd64-cpython-310\insightface\commands
      copying insightface\commands\rec_add_mask_param.py -> build\lib.win-amd64-cpython-310\insightface\commands
      copying insightface\commands\__init__.py -> build\lib.win-amd64-cpython-310\insightface\commands
      creating build\lib.win-amd64-cpython-310\insightface\data
      copying insightface\data\image.py -> build\lib.win-amd64-cpython-310\insightface\data
      copying insightface\data\pickle_object.py -> build\lib.win-amd64-cpython-310\insightface\data
      copying insightface\data\rec_builder.py -> build\lib.win-amd64-cpython-310\insightface\data
      copying insightface\data\__init__.py -> build\lib.win-amd64-cpython-310\insightface\data
      creating build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\arcface_onnx.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\attribute.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\inswapper.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\landmark.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\model_store.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\model_zoo.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\retinaface.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\scrfd.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\__init__.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty
      copying insightface\thirdparty\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty
      creating build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\constant.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\download.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\face_align.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\filesystem.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\storage.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\transform.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\__init__.py -> build\lib.win-amd64-cpython-310\insightface\utils
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d
      copying insightface\thirdparty\face3d\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\io.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\light.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\render.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\transform.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\vis.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\io.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\light.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\render.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\transform.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy        
      copying insightface\thirdparty\face3d\mesh_numpy\vis.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
      copying insightface\thirdparty\face3d\morphable_model\fit.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model    
      copying insightface\thirdparty\face3d\morphable_model\load.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model   
      copying insightface\thirdparty\face3d\morphable_model\morphabel_model.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
      copying insightface\thirdparty\face3d\morphable_model\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
      running egg_info
      writing insightface.egg-info\PKG-INFO
      writing dependency_links to insightface.egg-info\dependency_links.txt
      writing entry points to insightface.egg-info\entry_points.txt
      writing requirements to insightface.egg-info\requires.txt
      writing top-level names to insightface.egg-info\top_level.txt
      reading manifest file 'insightface.egg-info\SOURCES.txt'
      writing manifest file 'insightface.egg-info\SOURCES.txt'
      C:\Users\DY\AppData\Local\Temp\pip-build-env-kxqibcmh\overlay\Lib\site-packages\setuptools\command\build_py.py:218: _Warning: Package 'insightface.thirdparty.face3d.mesh.cython' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'insightface.thirdparty.face3d.mesh.cython' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'insightface.thirdparty.face3d.mesh.cython' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'insightface.thirdparty.face3d.mesh.cython' to be distributed and are
              already explicitly excluding 'insightface.thirdparty.face3d.mesh.cython' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      C:\Users\DY\AppData\Local\Temp\pip-build-env-kxqibcmh\overlay\Lib\site-packages\setuptools\command\build_py.py:218: _Warning: Package 'insightface.data.images' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'insightface.data.images' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'insightface.data.images' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'insightface.data.images' to be distributed and are
              already explicitly excluding 'insightface.data.images' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      C:\Users\DY\AppData\Local\Temp\pip-build-env-kxqibcmh\overlay\Lib\site-packages\setuptools\command\build_py.py:218: _Warning: Package 'insightface.data.objects' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'insightface.data.objects' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'insightface.data.objects' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'insightface.data.objects' to be distributed and are
              already explicitly excluding 'insightface.data.objects' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython     
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core.h -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython       
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      creating build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\Tom_Hanks_54745.png -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_black.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_blue.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_green.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_white.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\t1.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      creating build\lib.win-amd64-cpython-310\insightface\data\objects
      copying insightface\data\objects\meanshape_68.pkl -> build\lib.win-amd64-cpython-310\insightface\data\objects
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.c -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.pyx -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\setup.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by CHHuy** [comment]
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

on visual studio installer, install C++

**Comment by Updatedme** [comment]
>note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

Are you running on python 3.10

Install download visual studio https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&channel=Release&version=VS2022&source=VSLandingPage&cid=2030&passive=false

Install and select c++ Desktop

**Comment by Updatedme** [comment]
If you still have difficulty around it ,  here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010
