### ISSUE TITLE
Lose onnxruntime

### ISSUE THREAD

**Issue by Akie555** [hacksider/Deep-Live-Cam#561]
After I downloads the “torch” and start to run the exe, the next problems come, It seems to download another module. I could not found other guys solution. I will be thankful for someone who can help me!

E:\NDM-downloads\Compressed\Deep-Live-Cam-main\Deep-Live-Cam-main>python run.py
C:\Users\HSH\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
Traceback (most recent call last):
  File "E:\NDM-downloads\Compressed\Deep-Live-Cam-main\Deep-Live-Cam-main\run.py", line 3, in <module>
    from modules import core
  File "E:\NDM-downloads\Compressed\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 15, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

**Comment by AVGRadmin** [comment]
`No module named 'onnxruntime'` Means that onnxruntime is not installed (pip install onnxruntime==1.18.0). 
You need to make sure you follow the install instructions properly. 

And as mentioned in this [issue](https://github.com/hacksider/Deep-Live-Cam/issues/503#issuecomment-2322854152), try using a virtual enviroment to make sure no mixups with pip packages.
> `python3 -m venv my_venv` to create a virtual environment. Then: `source my_venv/bin/activate` to activate your virtual environment.
> 
> And then you can try to install using pip :)

**Comment by Updatedme** [comment]
> After I downloads the “torch” and start to run the exe, the next problems come, It seems to download another module. I could not found other guys solution. I will be thankful for someone who can help me!
> 
> E:\NDM-downloads\Compressed\Deep-Live-Cam-main\Deep-Live-Cam-main>python run.py
> C:\Users\HSH\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
>   cpu = _conversion_method_template(device=torch.device("cpu"))
> Traceback (most recent call last):
>   File "E:\NDM-downloads\Compressed\Deep-Live-Cam-main\Deep-Live-Cam-main\run.py", line 3, in <module>
>     from modules import core
>   File "E:\NDM-downloads\Compressed\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 15, in <module>
>     import onnxruntime
> ModuleNotFoundError: No module named 'onnxruntime'
> 

This is beyond using %pip install onnxruntime 
You should consider following the process as instructed.  
1. Check that you are using miniconda 3.10 S recommended 
2. Git
3. Visual studio
4. Create an Environment 
5. Run requirments
6. Uninstall onnxruntime 
7. Ffmpeg
8. Install onnxruntime 1.16
If you Don't have a dedicated gpu then proceed to 
9. python run.py
if you running on a dedicated graphic card 
10. Futher download cuda toolkit 11.8
11. python run.py --execution-provider cuda 

The Above list is just a summary brake down. Please refer to https://github.com/hacksider/Deep-Live-Cam the proper installation information

**Comment by Updatedme** [comment]
If you need further assistance, here's my whatsapp  
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

**Comment by Akie555** [comment]
I had solved it, thanks for you help



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 10, 2024 08:44 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hacksider/Deep-Live-Cam] Lose onnxruntime (Issue #561)




 
If you need further assistance, here's my whatsapp
 https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010
