### ISSUE TITLE
HTTPSConnectionPool

### ISSUE THREAD

**Issue by RoboCop-Gen** [hacksider/Deep-Live-Cam#565]
```
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /deepinsight/insightface/releases/download/v0.7/buffalo_l.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1122)')))
```

**Comment by Updatedme** [comment]
> ```
> raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /deepinsight/insightface/releases/download/v0.7/buffalo_l.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1122)')))
> ```


Turn off your window defender for network. Also, you can consider  deactivating  your antivirus.
Moreover you should verify that your Internet connection is strong and stable. Then try again .

**Comment by Updatedme** [comment]
If you need further assistance with deep-live-cam or help with full installation, reach out to me on whatsapp 
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010
