### ISSUE TITLE
How to run with GPU?

### ISSUE THREAD

**Issue by jatayumuw** [hacksider/Deep-Live-Cam#567]
Im Currently using pycharm and it work well, but its laggy and after checking the task manager it use cpu only. how do i run using GPU?

**Comment by hacksider** [comment]
check the readme
![image](https://github.com/user-attachments/assets/af881b69-af7e-4fc5-a83b-dc5251c73af0)

**Comment by annng** [comment]
hi @hacksider I have run by cuda but it just show cpu only

![Image](https://github.com/user-attachments/assets/a52680c2-02a2-4de0-8fd3-888d562e0991)

![Image](https://github.com/user-attachments/assets/34c47546-bbbe-4584-b0ba-5530da4fbde5)
