### ISSUE TITLE
Enhancer enable 

### ISSUE THREAD

**Issue by nguyensi22** [hacksider/Deep-Live-Cam#573]
When I turn on "enhancer", my computer is quite jerky. I'm using RTX 4060 but when I turn it on, there's motion delay. I've tried reducing the preview resolution and reducing the camera fps to 15fps but that phenomenon still persists. Can developers help me fix this error. Your software is very good and helps me a lot, thank you very much

**Comment by hacksider** [comment]
It will still be very slow as it works like this
camera frame -> face swapper -> face enhancer (this one is really slow as it process and enhances the face resolution)

Even at 4090 it will be very slow.

**Comment by nguyensi22** [comment]
Can I fix it so it looks smoother?

**Comment by moaeddy** [comment]
> It will still be very slow as it works like this camera frame -> face swapper -> face enhancer (this one is really slow as it process and enhances the face resolution)
> 
> Even at 4090 it will be very slow.

but what is the best fix for it, or it's a permanent situation bug?

**Comment by hacksider** [comment]
It's not a permanent bug. it will be available on the gumroad edition by next year (v2.0)
