### ISSUE TITLE
ONNXRuntimeError] : 1 : FAIL

### ISSUE THREAD

**Issue by Qubei13** [hacksider/Deep-Live-Cam#584]
Hi! Im trying to use deep live cam to switch faces in video. However, i get this error messages every time. Any fix?

Processing:  98%|▉| 1712/1744 [08:40<00:06,  4.69frame/s, execution_providers=['CUDAExecutionProvider'], execution_thre[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

Processing:  99%|▉| 1722/1744 [08:40<00:01, 14.02frame/s, execution_providers=['CUDAExecutionProvider'], execution_thre[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

Processing:  99%|▉| 1726/1744 [08:41<00:02,  7.71frame/s, execution_providers=['CUDAExecutionProvider'], execution_thre[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

Processing:  99%|▉| 1729/1744 [08:42<00:03,  4.62frame/s, execution_providers=['CUDAExecutionProvider'], execution_thre[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

Processing:  99%|▉| 1732/1744 [08:43<00:03,  3.79frame/s, execution_providers=['CUDAExecutionProvider'], execution_thre[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

Processing:  99%|▉| 1733/1744 [08:44<00:03,  3.27frame/s, execution_providers=['CUDAExecutionProvider'], execution_thre[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

Processing:  99%|▉| 1734/1744 [08:44<00:03,  3.13frame/s, execution_providers=['CUDAExecutionProvider'], execution_thre[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

Processing:  99%|▉| 1735/1744 [08:44<00:02,  3.42frame/s, execution_providers=['CUDAExecutionProvider'], execution_thre[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

Processing: 100%|▉| 1738/1744 [08:44<00:00,  6.26frame/s, execution_providers=['CUDAExecutionProvider'], execution_thre[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=175 ; expr=cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking);

Processing: 100%|▉| 1742/1744 [08:45<00:00,  3.31frame/s, execution_providers=['CUDAExecutionProvider'], execution_thre
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Downloads\1\python\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Downloads\1\python\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\Downloads\1\modules\ui.py", line 132, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: analyze_target(start, root))
  File "D:\Downloads\1\modules\ui.py", line 174, in analyze_target
    select_output_path(start)
  File "D:\Downloads\1\modules\ui.py", line 361, in select_output_path
    start()
  File "D:\Downloads\1\modules\core.py", line 209, in start
    frame_processor.process_video(modules.globals.source_path, temp_frame_paths)
  File "D:\Downloads\1\modules\processors\frame\face_swapper.py", line 174, in process_video
    modules.processors.frame.core.process_video(source_path, temp_frame_paths, process_frames)
  File "D:\Downloads\1\modules\processors\frame\core.py", line 73, in process_video
    multi_process_frame(source_path, frame_paths, process_frames, progress)
  File "D:\Downloads\1\modules\processors\frame\core.py", line 65, in multi_process_frame
    future.result()
  File "D:\Downloads\1\python\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\Downloads\1\python\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\Downloads\1\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Downloads\1\modules\processors\frame\face_swapper.py", line 133, in process_frames
    source_face = get_one_face(cv2.imread(source_path))
  File "D:\Downloads\1\modules\face_analyser.py", line 28, in get_one_face
    face = get_face_analyser().get(frame)
  File "D:\Downloads\1\python\lib\site-packages\insightface\app\face_analysis.py", line 75, in get
    model.get(img, face)
  File "D:\Downloads\1\python\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 67, in get
    face.embedding = self.get_feat(aimg).flatten()
  File "D:\Downloads\1\python\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 84, in get_feat
    net_out = self.session.run(self.output_names, {self.input_name: blob})[0]
  File "D:\Downloads\1\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node. Name:'Gemm_128' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED ; GPU=0 ; hostname=DESKTOP-QUBEI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=168 ; expr=cudnnCreate(&cudnn_handle_);

**Comment by hacksider** [comment]
It seems your issue is that you're overloading your GPU, I suggest lower the resolution of the Video or get a better GPU.

**Comment by KiritoGuugk** [comment]
> It seems your issue is that you're overloading your GPU, I suggest lower the resolution of the Video or get a better GPU.
how much vram can support convert a 1080p 5mins video？It failed on my rtx 4060 8G
