### ISSUE TITLE
how to improve the usage of gpu？

### ISSUE THREAD

**Issue by louzhu123** [hacksider/Deep-Live-Cam#586]
my gpu is gtx4060ti 16g.
Whether using enhancement or not, the GPU usage is only < 30%. It seems to be 15fps in normal mode and only 5fps in enhanced mode.
I have used cuda according to the documentation

Here are some running logs
![image](https://github.com/user-attachments/assets/6453ce66-c5e4-4d00-b19c-62ebf25ba572)

**Comment by thgpddl** [comment]
请问你是怎么看FPS的，我的增强模式也有明显的卡顿，你解决这个问题了吗

**Comment by louzhu123** [comment]
> 请问你是怎么看FPS的，我的增强模式也有明显的卡顿，你解决这个问题了吗

fps感觉出来的，我也不知道哪里看fps。没解决，貌似别人的4090，增强模式下也会卡

**Comment by GabriellaMS** [comment]
我看有人说是因为cuda版本跟insightface不匹配，所以cuda的加速效果没起作用
