### ISSUE TITLE
Slow fps, lagging. It doesn't run in real-time even though I've enabled keep fps.

### ISSUE THREAD

**Issue by Kimthanh27** [hacksider/Deep-Live-Cam#587]
Slow fps, lagging. It doesn't run in real-time even though I've enabled keep fps.

**Comment by hacksider** [comment]
What's your specs? You will need a good gpu to have it almost real time.

**Comment by renjithsasidharan** [comment]
@hacksider whats a good GPU to get 20 FPS?

**Comment by Kimthanh27** [comment]
4090 nvidia card. cpu I9, new brands just last for 6 months My friend. tried every way, updated the newest verison from yours.

**Comment by hacksider** [comment]
You can resize the window to improve performance (I wouldn't suggest face enhancer) but the best you can get is around 15 to 20fps. The reason of this is the post processing.

**Comment by Kimthanh27** [comment]
Do you mean reducing the size of the preview window when "live" is checked? I tried that, but it didn't change the FPS in real-time. Also, the example you posted on GitHub was very smooth. What PC configuration were you using at that time?
