### ISSUE TITLE
Errors in launching the run.py

### ISSUE THREAD

**Issue by TVikg** [hacksider/Deep-Live-Cam#590]
Hello,

I've a Macbook Pro with M1 pro CPU. I followed the instructions for the Mac OS installation but when I try to lunch run.py I get these errors:

Deep-Live-Cam/run.py", line 3, in <module>
    from modules import core
Deep-Live-Cam/modules/core.py", line 14, in <module>
    import torch

I've python 3.12.6 installed.

**Comment by AVGRadmin** [comment]
Looks like you didn't copy the complete error text. 
Either way, i suggest you go through the complete install instructions again.

Notes:
- You should use the [recommended](https://github.com/hacksider/Deep-Live-Cam#:~:text=python%20(3.10%20recommended)) python version
- If error was `no module named tourch` then you didn't install [tourch](https://github.com/hacksider/Deep-Live-Cam/blob/621c3f035e34e9ee2ea063261c41d9c7745d225e/requirements.txt#L12) properly.

**Comment by kkaung** [comment]
The same error I am getting

**Comment by TVikg** [comment]
This is the error:
Traceback (most recent call last):
  File "/Users/user/Desktop/Deep-Live-Cam/run.py", line 3, in <module>
    from modules import core
  File "/Users/user/Desktop/Deep-Live-Cam/modules/core.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by TVikg** [comment]
I can't use the recommended python version because I have to downgrade other projects.

**Comment by AVGRadmin** [comment]
I have 3 python version on my PC for the same reason
 
Use python virtual environment and set up a seperate environment for this project with python 10. See: https://docs.python.org/3/library/venv.html
You can have multiple python versions installed, just make sure your virtual environment is using python 3.10.
