### ISSUE TITLE
Error webcam mode

### ISSUE THREAD

**Issue by MrX0r** [hacksider/Deep-Live-Cam#593]
Everything done according to the instructions when running Select a face Click live the error

[ WARN:0@66.472] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638

Where is the error? Who can help me?

**Comment by hacksider** [comment]
it seems it wasnt able to get data from your webcam. Is you webcam the default webcam? Try getting the "old experimental" branch if you're using windows

**Comment by hacksider** [comment]
That means you didn't allow your OS to grab frames for your webcam.
