### ISSUE TITLE
macOS 15 unsupported?

### ISSUE THREAD

**Issue by sikhaman** [hacksider/Deep-Live-Cam#601]
did the guide step by step
after run script see few warnings in the console and do not see UI itself. might be new macOS issue? 

```
(deep-env) ╭─d@book-pro ~/Desktop/Deep-Live-Cam 
╰─$ /Users/d/Desktop/Deep-Live-Cam/deep-env/bin/python run.py --execution-provider coreml



DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
2024-09-17 14:56:16.157 python[11207:359466] +[IMKClient subclass]: chose IMKClient_Legacy
2024-09-17 14:56:16.158 python[11207:359466] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
2024-09-17 14:56:19.645 python[11207:359466] The class 'NSOpenPanel' overrides the method identifier.  This method is implemented by class 'NSWindow'
```

also question to the source image? what format what resolution and extension should be?

**Comment by Martin-SF** [comment]
that looks like the installation of the python-tk package didnt worked like it shoud. retry it. also ensure that you use python 3.10

**Comment by arifintajul4** [comment]
same issue

**Comment by lkraider** [comment]
Works here, macOS 15.0.1 (24A348) on a Mac mini 2018, only very slow in CPU mode, not sure if the integrated Intel UHD Graphics 630 could handle it in GPU mode.

```
% uname -a
Darwin <hostname> 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:30 PDT 2024; root:xnu-11215.1.12~1/RELEASE_X86_64 x86_64
```

**Comment by arifintajul4** [comment]
<img width="906" alt="Screenshot 2024-10-30 at 19 54 18" src="https://github.com/user-attachments/assets/6f84a721-1cd5-4898-bff5-99cb872b77dc">
help me

**Comment by arifintajul4** [comment]
another error, the preview is blank
<img width="1440" alt="Screenshot 2024-10-30 at 21 14 30" src="https://github.com/user-attachments/assets/4a77a501-0e68-4315-8de3-af826967563a">
