### ISSUE TITLE
tensorflow-intel 2.12.0 depends on numpy<1.24

### ISSUE THREAD

**Issue by gomgomi7** [hacksider/Deep-Live-Cam#61]
The conflict is caused by:
The user requested numpy==1.24.3

and,
albucore 0.0.12 requires numpy<2,>=1.24.4

How can I solve it?

**Comment by Nuclear6** [comment]
numpy>=1.24.3

**Comment by LuckyNES** [comment]
I had an error installing requirements until I changed them to use numpy>=1.24.3 as mentioned above. Is someone doing a pull request?
