### ISSUE TITLE
problema tecnico

### ISSUE THREAD

**Issue by minatori50** [hacksider/Deep-Live-Cam#619]
sto riscontrando un problema. apro la deep cam live con il seguente comando: python run.py
in condivisione con any desk la telecamera funziona. disconesso any desk , stesso comando,stesso procedimento si apre la finestra web della cam ma rimane in schermo bianco.
vedere i due file in allegato.
quando clicco su live non si apre la web. si apre solo in condivisone con any desk.
![Screenshot 2024-09-22 200107](https://github.com/user-attachments/assets/a1d87b2f-3bb1-41fa-aed2-02a3fc3fa985)
![Screenshot 2024-09-22 201456](https://github.com/user-attachments/assets/56e4c1e2-487e-4645-983e-f3ac66575818)

**Comment by danielecapuano-dev** [comment]
Prova a dare un occhio alla issue #613 
Io ho risolto seguendo quello che c’è scritto lì

**Comment by Updatedme** [comment]
download https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128.onnx and put it in the model folder

 If you need further assistance, here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010
