### ISSUE TITLE
app is really slow even upgrade to nvida 4080

### ISSUE THREAD

**Issue by prinzcala** [hacksider/Deep-Live-Cam#620]
i thought it was my pc bcos it has graphic card of 2060. i bought new pc with graphic card of rtx 4080 with 32gb ram. after i run it  python run.py --execution-provider cuda, To my surprise it was still slow. Can anybody pls help me.

**Comment by MMbundles** [comment]
Set up your cuda environment with cudnn and add to path , I’m definitely sure that the cause and what’s your Vram? Because 32gb can just be your CPU RAM and not your VRam

**Comment by vignesh1507** [comment]
The issue you're experiencing is likely due to the fact that the code is not optimized for parallel processing, and the GPU is not being utilized efficiently. 

Check the CUDA version: Make sure that the CUDA version installed on your system is compatible with the insightface library. You can check the CUDA version by running nvcc --version in your terminal.

**Comment by Updatedme** [comment]
> i thought it was my pc bcos it has graphic card of 2060. i bought new pc with graphic card of rtx 4080 with 32gb ram. after i run it  python run.py --execution-provider cuda, To my surprise it was still slow. Can anybody pls help me.

This is simply caused by the cuda version installed  incompatible with the Insightface.  

If you dont know your way around this , here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

Or you can just check for the cuda version and install the required

**Comment by GabriellaMS** [comment]
> > i thought it was my pc bcos it has graphic card of 2060. i bought new pc with graphic card of rtx 4080 with 32gb ram. after i run it  python run.py --execution-provider cuda, To my surprise it was still slow. Can anybody pls help me.
> 
> This is simply caused by the cuda version installed incompatible with the Insightface.
> 
> If you dont know your way around this , here's my whatsapp https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010
> 
> Or you can just check for the cuda version and install the required

My cuda version is 11.8. I installed it in the same environment as Readme. Why am I also slow? How to check the CUDA version corresponding to InsightFace?

**Comment by vipcafe** [comment]
I am also facing a similar issue when enabling the FACE-ENHANCER mode—it runs very slowly, and the GPU usage is almost negligible.

![image](https://github.com/user-attachments/assets/bfce6383-1788-4821-8ba9-eb167f700300)

**Comment by hacksider** [comment]
We're on the process of making it almost realtime. Making sure it is stable before we release it on public.
![face_enhancer](https://github.com/user-attachments/assets/3d49d0e4-00cf-446d-95c6-965fe27eca15)

The demo runs on 10GB GPU. We're still on the process of making it more stable before releasing.
