### ISSUE TITLE
I just download last one I face this issue the one before no problem

### ISSUE THREAD

**Issue by hlafmanta** [hacksider/Deep-Live-Cam#624]
there's also problem the first I had I use my phone cam by manycam or droidcam now is not working it staying orange

AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\asd\Deep-Live-Cam-main\Deep-Live-Cam-main\models\inswapper_128.onnx failed:Protobuf parsing failed.

**Comment by hacksider** [comment]
download the latest model on the readme
https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128.onnx
