### ISSUE TITLE
建立一个社区交流群，供大家讨论  A Community Group

### ISSUE THREAD

**Issue by sudo888samewick** [hacksider/Deep-Live-Cam#635]
I believe this is a very good project with highly impactful application scenarios. I think the community might benefit from a discussion group where everyone can engage in real-time conversations.

我认为这是一个非常好的项目，有非常强大的应用场景。我认为社区或许需要一个交流群，以供大家实时讨论。

Discord
https://discord.gg/ZJ4qSJM248

微信

![image](https://github.com/user-attachments/assets/3f8ba0a2-3239-48ae-9e5d-6f0476df3c0e)

**Comment by KRSHH** [comment]
Coming Soon...
