### ISSUE TITLE
cannot clone this 

### ISSUE THREAD

**Issue by ilxy2** [hacksider/Deep-Live-Cam#636]
Cloning into 'Deep-Live-Cam'...
remote: Enumerating objects: 777, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (63/63), done.
error: RPC failed; curl 56 OpenSSL SSL_read: OpenSSL/3.1.2: error:0A000119:SSL routines::decryption failed or bad record mac, errno 0
error: 5472 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by hacksider** [comment]
You can just download as zip if you cant clone it.
![image](https://github.com/user-attachments/assets/f30c1757-9e29-4fd9-b2d1-d8d1e5b50d9a)
