### ISSUE TITLE
New 1.5 UI causes issues when trying to map Faces

### ISSUE THREAD

**Issue by smilingjack10** [hacksider/Deep-Live-Cam#637]
When updating to the 1.5 release mapping faces causes the following error:

```batchfile
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\usr \anaconda3\envs\faceswap\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\usr\anaconda3\envs\faceswap\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\usr\Desktop\Deep-Live-Cam\modules\ui.py", line 533, in <lambda>
    command=lambda id=id: on_button_click(map, id),
  File "C:\Users\usr\Desktop\Deep-Live-Cam\modules\ui.py", line 516, in on_button_click
    update_popup_source(scrollable_frame, map, button_num)
  File "C:\Users\usr\Desktop\Deep-Live-Cam\modules\ui.py", line 642, in update_popup_source
    scrollable_frame.winfo_children()[button_num],
IndexError: list index out of range
```

Reproduce:
Fresh install of Deep-Live-Cam in a blank venv with python 3.10
follow installation instructions of windows with cuda support
Use a picture or movie with multiple faces and select face mapping
Wait for the faces to be extracted from the picture/video
Select source images when asked
Only the First source image can be selected, all subsequent images will result in this error.

This is probably a simple mistake in indexing in the new ui.py file. But I would have to reverse engineer a lot in order to fix it. So hopefully someone with some more knowledge of the program can fix this 😉.

**Comment by KRSHH** [comment]
Hi, can you clarify your steps to reproduce this error?, I tested it again on a fresh install with a video with two faces and it displayed two faces in the mapper after detection. and I could map the faces using two other images and render it, without facing any issue on the latest release... Am I missing something here?

**Comment by smilingjack10** [comment]
Hi,
Yes of course. I've included a screenshot with my settings and how the error occurs. I've selected an S-0. Which appears next to T-1 btw, and when I select S-1 the error occurs.

![Schermafbeelding 2024-09-26 114401](https://github.com/user-attachments/assets/475892de-3180-433b-ba11-a52862f98a28)

**Comment by smilingjack10** [comment]
I've temporarly fixed the issue by replacing 'button_num' by '0' in the index in ui.py line 642 and 652

```python
            source_image = ctk.CTkLabel(
                scrollable_frame.winfo_children()[0],
                text=f"S-{button_num}",
                width=MAPPER_PREVIEW_MAX_WIDTH,
                height=MAPPER_PREVIEW_MAX_HEIGHT,
                font=("Arial", 14, "bold"),
            )
            source_image.pack(
                side="left",
                padx=(0, 10),
                after=scrollable_frame.winfo_children()[0].winfo_children()[button_num],
            )
``` 
![Schermafbeelding 2024-09-26 120958](https://github.com/user-attachments/assets/9ad497b8-b772-4153-9c0b-816fe446b4bf)

**Comment by KRSHH** [comment]
Still working fine for me without any changes... 

https://streamable.com/hgmmfr
![2024-09-26 17-18-40](https://github.com/user-attachments/assets/a4678f44-fa91-42a4-8927-5df8b7176941)

**Comment by smilingjack10** [comment]
Sorry for not getting back to you sooner, but I wanted to try this on another PC.
I tried it on Python 3.9 and 3.10. Both in a fresh conda environment and a fresh venv environment, the behavior/error persists.
(Windows 10)

```
git clone https://github.com/hacksider/Deep-Live-Cam.git
cd Deep-Live-Cam
conda create -n DLC python=3.10
activate DLC
pip install -r requirements.txt
run-cuda.bat
```
