### ISSUE TITLE
DPI scaling issue when using multiple different resolution displays

### ISSUE THREAD

**Issue by UHDPass** [hacksider/Deep-Live-Cam#639]
Exception in Tkinter callback
Traceback (most recent call last):
\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
\Python\Python310\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

**Comment by KRSHH** [comment]
Already fixed - [https://github.com/hacksider/Deep-Live-Cam/issues/597](https://github.com/hacksider/Deep-Live-Cam/issues/597) .

**Comment by UHDPass** [comment]
> Already fixed - #597 .

Highly doubt it. Since I've cloned the repo today and the issue is still there.

**Comment by KRSHH** [comment]
How to reproduce it?

**Comment by KRSHH** [comment]
Try upgrading customtkinter - `pip install --upgrade customtkinter`

**Comment by UHDPass** [comment]
> Try upgrading customtkinter - `pip install --upgrade customtkinter`



> Try upgrading customtkinter - `pip install --upgrade customtkinter`

Requirement already satisfied: customtkinter in d:*\deep-live-cam\venv\lib\site-packages (5.2.2)
Requirement already satisfied: darkdetect in d:*\deep_live_cam\deep-live-cam\venv\lib\site-packages (from customtkinter) (0.8.0)
Requirement already satisfied: packaging in d:\*\deep-live-cam\venv\lib\site-packages (from customtkinter) (24.1)

Issue persists.

**Comment by UHDPass** [comment]
UI is shown after the error, but looks like this:
<img width="374" alt="DEEP_UI" src="https://github.com/user-attachments/assets/209c5029-d69f-4e09-86d5-6d6528740a2e">

**Comment by KRSHH** [comment]
> python run.py --execution-provider cuda --execution-threads 60 --max-memory 60
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "C:\Users*_**\AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 1921, in call return self.func(_args) File "C:\Users*_**\AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 839, in callit func(*args) File "d:*__\Deep-Live-Cam\venv\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling window.block_update_dimensions_event() File "C:\Users*_**\AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 2383, in **getattr**
> return getattr(self.tk, attr)
> AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'




> > Try upgrading customtkinter - `pip install --upgrade customtkinter`
> 
> > Try upgrading customtkinter - `pip install --upgrade customtkinter`
> 
> Requirement already satisfied: customtkinter in d:_\deep-live-cam\venv\lib\site-packages (5.2.2) Requirement already satisfied: darkdetect in d:_\deep_live_cam\deep-live-cam\venv\lib\site-packages (from customtkinter) (0.8.0) Requirement already satisfied: packaging in d:*\deep-live-cam\venv\lib\site-packages (from customtkinter) (24.1)
> 
> Issue persists.


Both of these are different envs

**Comment by UHDPass** [comment]
> > python run.py --execution-provider cuda --execution-threads 60 --max-memory 60
> > Exception in Tkinter callback
> > Traceback (most recent call last):
> > File "C:\Users*_**\AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 1921, in call return self.func(_args) File "C:\Users*_**\AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 839, in callit func(_args) File "d:___\Deep-Live-Cam\venv\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling window.block_update_dimensions_event() File "C:\Users*_**\AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 2383, in **getattr**
> > return getattr(self.tk, attr)
> > AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'
> 
> > > Try upgrading customtkinter - `pip install --upgrade customtkinter`
> > 
> > 
> > > Try upgrading customtkinter - `pip install --upgrade customtkinter`
> > 
> > 
> > Requirement already satisfied: customtkinter in d:_\deep-live-cam\venv\lib\site-packages (5.2.2) Requirement already satisfied: darkdetect in d:_\deep_live_cam\deep-live-cam\venv\lib\site-packages (from customtkinter) (0.8.0) Requirement already satisfied: packaging in d:*\deep-live-cam\venv\lib\site-packages (from customtkinter) (24.1)
> > Issue persists.
> 
> Both of these are different envs

same venv just edited the path not to display full path

**Comment by UHDPass** [comment]
Because my editing of the path caused some confusion, I've did a new clone to a different folder. Results are as followed:

(venv) d:\test\Deep-Live-Cam>pip install --upgrade customtkinter
Requirement already satisfied: customtkinter in d:\test\deep-live-cam\venv\lib\site-packages (5.2.2)
Requirement already satisfied: darkdetect in d:\test\deep-live-cam\venv\lib\site-packages (from customtkinter) (0.8.0)
Requirement already satisfied: packaging in d:\test\deep-live-cam\venv\lib\site-packages (from customtkinter) (24.1)

[notice] A new release of pip available: 22.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) d:\test\Deep-Live-Cam>run-cuda.bat

(venv) d:\test\Deep-Live-Cam>python run.py --execution-provider cuda --execution-threads 60 --max-memory 60
Downloading: 56.0kB [00:00, 160kB/s]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "d:\test\Deep-Live-Cam\venv\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

**Comment by KRSHH** [comment]
Hi, try installing this whl in the venv -

https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl

**Comment by KRSHH** [comment]
pip install https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl

**Comment by KRSHH** [comment]
Open terminal in Deep-Live-Cam folder, enter these two commands -

```
.\venv\Scripts\Activate
```

```
python -m pip install --force-reinstall https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl
```

**Comment by baron-ln** [comment]
That's useful!
