### ISSUE TITLE
Distorted Face swap output

### ISSUE THREAD

**Issue by kikomoth** [hacksider/Deep-Live-Cam#641]
No idea what happened or why it all of a sudden is doing this... 
![output](https://github.com/user-attachments/assets/061df8e2-e595-4461-a015-1d7dfe80ff7a)

**Comment by KRSHH** [comment]
uhmm... any Error messages?

**Comment by kikomoth** [comment]
> uhmm... any Error messages?

Not sure if errors or just info, but here's what I'm seeing when I process an image...
![image](https://github.com/user-attachments/assets/0a253b6c-9e2f-49ba-b1f6-7aa254b284f8)

**Comment by kikomoth** [comment]
Fixed the issue by uninstalling onnxruntime and reinstalling it.
