### ISSUE TITLE
Cuda execution Error

### ISSUE THREAD

**Issue by dskydiver** [hacksider/Deep-Live-Cam#642]
RuntimeError: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1594703432 ; hostname=DESKTOP-PQK28NQ ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);

**Comment by Yakilo** [comment]
how did you solve it?
