### ISSUE TITLE
The app UI looks almost transparent and invisible after starting

### ISSUE THREAD

**Issue by phpmooc** [hacksider/Deep-Live-Cam#643]
OS: windows11
Python Version: 3.10

I have searched the issues related to #597 ,  and  pulled the latest commit with `5845b9c48098d2d30cedaa26769626f1c2726aec`,  
but it not works for me, the app UI still looks transparent and almost invisible, what am I doing wrong?  or which commit should I get?thanks in advance.

**Comment by Flansi** [comment]
OS: windows11
Python Version: 3.10
GPU: 4090

I have the same issue,

![issue](https://github.com/user-attachments/assets/de3a3628-69e6-4b3b-b406-53e04ed0d896)

(venv) PS G:\App\Deep-Live-Cam - unchanged> .\run-cuda.bat

G:\App\Deep-Live-Cam - unchanged>python run.py --execution-provider cuda --execution-threads 60 --max-memory 60
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\hanne\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\hanne\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "G:\App\Deep-Live-Cam - unchanged\venv\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "C:\Users\hanne\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

**Comment by hacksider** [comment]
You can get the latest one and start from that :) If it still have an issue, please report it back here

**Comment by Flansi** [comment]
Still the same issue:

![issue](https://github.com/user-attachments/assets/14b3e4cc-b247-435b-9e7a-ed9cf29d14d3)

**Comment by phpmooc** [comment]
> You can get the latest one and start from that :) If it still have an issue, please report it back here

**The latest one still has the same issue**

* transparent screenshot
![invisible](https://github.com/user-attachments/assets/a790dd0c-b3c9-4b57-a531-7bcdabc847ba)

* git log1
```
5845b9c - (HEAD -> main, origin/main, origin/HEAD) Update README.md (2024-09-26 00:57:11) <KRSHH>
71cf39f - Update metadata.py (2024-09-26 00:57:45) <Kenneth Estanislao>
92db20e - (tag: Deep_Live_Cam_CUDA) Merge pull request #632 from KRSHH/main (2024-09-25 17:51:30) <KRSHH>
f1e3657 - Updated README, (Images - TBU) (2024-09-25 17:42:09) <KRSHH>
6d12382 - New Fixed UI (2024-09-25 17:36:50) <KRSHH>
92a0994 - Update README.md (2024-09-21 19:56:00) <Kenneth Estanislao>
cad40b2 - Update face_swapper.py (2024-09-19 21:00:29) <Kenneth Estanislao>
1b4c0ce - Update face_swapper.py (2024-09-19 17:43:05) <Kenneth Estanislao>
fd4e3f5 - reverted to the old version (2024-09-19 17:38:02) <Kenneth Estanislao>
5bcd6da - Update ui.py (2024-09-19 15:54:57) <Kenneth Estanislao>
3e1f333 - Revert "Merge pull request #594 from KRSHH/main" (2024-09-19 02:36:35) <Kenneth Estanislao>
1f71d27 - Revert "Merge pull request #599 from KRSHH/main" (2024-09-19 02:01:47) <Kenneth Estanislao>
bbfdf83 - Update requirements.txt (2024-09-19 00:38:41) <Kenneth Estanislao>
88254c3 - Merge pull request #604 from bkosowski/bugfix/fix_onnxruntime_version (2024-09-19 00:33:05) <Kenneth Estanislao>
069e9b4 - Downgrade onnxruntime version to 1.16.0 to fix requirements installation (2024-09-18 15:58:50) <bkosowski>
80de3dc - Merge pull request #599 from KRSHH/main (2024-09-17 21:47:44) <Kenneth Estanislao>
911148c - README.md Update (2024-09-17 19:03:06) <KRSHH>
b229545 - Update README.md (2024-09-17 18:24:43) <KRSHH>
375d4ae - Update README.md (2024-09-17 20:27:27) <Kenneth Estanislao>
bcfb9f2 - Merge pull request #598 from KRSHH/main (2024-09-17 20:25:33) <Kenneth Estanislao>
a905d16 - Add files via upload (2024-09-17 20:25:08) <KRSHH>
d78df54 - Fixed the Face Mapper issue on live cam (2024-09-17 20:20:14) <KRSHH>
4067d24 - Fix Popup Live width (2024-09-17 20:18:59) <KRSHH>
9c22e63 - Fix Popup Live width (2024-09-17 17:46:14) <KRSHH>
0350f23 - Fixed the Face Mapper issue on live cam (2024-09-17 16:51:28) <KRSHH>
d1ec0a1 - Minor Fixes (2024-09-16 21:58:24) <KRSHH>
bd8ed6e - Add files via upload (2024-09-16 21:48:13) <KRSHH>
ea7bbd4 - Revert "Merge pull request #592 from KRSHH/main" (2024-09-16 23:34:35) <Kenneth Estanislao>
```

* app start log
```
(myenv) PS D:\Deep-Live-Cam> python.exe .\run.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Program Files\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "D:\myenv\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "D:\Program Files\Python310\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'
```

**Comment by animemoeus** [comment]
Same problem here

![image](https://github.com/user-attachments/assets/6d6ab25a-7ce7-4a9d-b53f-cdc4cdaa4d82)

```bash
(venv)  arter@animemoeus        Deep-Live-Cam  main  python .\run.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\arter\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\arter\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "C:\Users\arter\Documents\Python\Deep-Live-Cam\venv\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "C:\Users\arter\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'
```

**Comment by WhoJoshi69** [comment]
i am also having the same issue

**Comment by Bhl0318** [comment]
you can comment out these two lines 
"window.block_update_dimensions_event()" and "window.unblock_update_dimensions_event()" in scaling_tracker.py

**Comment by WhoJoshi69** [comment]
> you can comment out these two lines "window.block_update_dimensions_event()" and "window.unblock_update_dimensions_event()" in scaling_tracker.py

thanks bro!!! this worked

**Comment by KRSHH** [comment]
@phpmooc try installing this in the venv - https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl

**Comment by KRSHH** [comment]
pip install https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl

**Comment by Flansi** [comment]
> you can comment out these two lines "window.block_update_dimensions_event()" and "window.unblock_update_dimensions_event()" in scaling_tracker.py

this works, thank you!

**Comment by phpmooc** [comment]
> pip install https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl

thanks,  but still not work.

then tried @Bhl0318 's solution, it worked.

**Comment by KRSHH** [comment]
> > pip install https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl
> 
> thanks, but still not work.
> 
> then tried @Bhl0318 's solution, it worked.

Did you do these steps before -


Open terminal in Deep-Live-Cam folder, enter these two commands -

```
.\venv\Scripts\Activate
```

```
python -m pip install https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl
```

**Comment by KRSHH** [comment]
I am asking to try this method, as it would make the fix easy for other users if they face it...

**Comment by phpmooc** [comment]
> > > pip install https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl
> > 
> > 
> > thanks, but still not work.
> > then tried @Bhl0318 's solution, it worked.
> 
> Did you do these steps before -
> 
> Open terminal in Deep-Live-Cam folder, enter these two commands -
> 
> ```
> .\venv\Scripts\Activate
> ```
> 
> ```
> python -m pip install --force-reinstall https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl
> ```

Yep, the terminal tells:
```
INFO: pip is looking at multiple versions of customtkinter to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement darkdetect (from customtkinter) (from versions: none)
ERROR: No matching distribution found for darkdetect
```

**Comment by phpmooc** [comment]
> > > pip install https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl
> > 
> > 
> > thanks, but still not work.
> > then tried @Bhl0318 's solution, it worked.
> 
> Did you do these steps before -
> 
> Open terminal in Deep-Live-Cam folder, enter these two commands -
> 
> ```
> .\venv\Scripts\Activate
> ```
> 
> ```
> python -m pip install --force-reinstall https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl
> ```

Yep, it works this time after executing `--force-reinstall`，thanks a lot.

**Comment by KRSHH** [comment]
Great.
