### ISSUE TITLE
obtain their consent and clearly label any output as a deepfake when sharing online

### ISSUE THREAD

**Issue by vandit2209** [hacksider/Deep-Live-Cam#647]
Did you really take Elon Musks consent ...?! Use his face as first example....

**Comment by KRSHH** [comment]
Come on man...

He is a free speech absolutist anyway, and Doesn't care about his AI pics on X.

**Comment by hacksider** [comment]
Just to add on this. It usually falls on creative commons. Also, he is a public figure and it is clearly written that the demo in front is a deepfake. In case there is a claim or issues on it, I will gladly take it down. ☺️
