### ISSUE TITLE
Can I make a stream through deep live cam ? 

### ISSUE THREAD

**Issue by Aivoice96** [hacksider/Deep-Live-Cam#648]
I tried several times to reach out and brought a softbox external lighting to clarify the image and the image appears pixelated, can it be adjusted or adjusted,, the image appears as follows ..
It was a normal job, but there were still a lot of pixels left in my time 
Any solution ?
![Untitled](https://github.com/user-attachments/assets/1b1013ee-1b07-4e62-80a5-2d3cfdd52420)

**Comment by Aivoice96** [comment]
up

**Comment by KRSHH** [comment]
Did you pull the latest commit?, what are your specs and are you using OBS virtual cam?

**Comment by hacksider** [comment]
https://github.com/hacksider/Deep-Live-Cam/wiki/Tips-on-how-to-improve-the-quality

**Comment by Aivoice96** [comment]
> Did you pull the latest commit?, what are your specs and are you using OBS virtual cam?

@KRSHH  how could i make the latest commit ? 
my specs 
![image](https://github.com/user-attachments/assets/3f3a294d-eab8-4301-adae-a01e183b239b)
![image](https://github.com/user-attachments/assets/160cb09e-dfdf-4b91-9587-43808dbc9a39)

i run in obs as a window capture not  obs virtual cam Because he doesn't show it like that 
![image](https://github.com/user-attachments/assets/5c9b52f4-2229-4eb2-a584-148f6c004dd8)

**Comment by Aivoice96** [comment]
> https://github.com/hacksider/Deep-Live-Cam/wiki/Tips-on-how-to-improve-the-quality

@hacksider  I tried the solution you said, but the image has pixels ,, Although I use soft box costume lighting equipment to improve the image quality ,, i used it in obs as window capture not obs virtual camera .. is this the problem ? 
![image](https://github.com/user-attachments/assets/43fe0a7d-faee-4a64-8b20-b995d4247870)
and there is a problem when in put my face down it's goes and my hand on my mouth like this photo 

i need to make it like this in the preview topic live 

![Uploading resizable.gif…]()


any help ?
