### ISSUE TITLE
App is finally open , but when preview blank

### ISSUE THREAD

**Issue by BerEZzzz** [hacksider/Deep-Live-Cam#649]
![Snipaste_2024-09-27_17-48-15](https://github.com/user-attachments/assets/34d3e5cf-ff59-473a-866b-2a3e8f362217)
![Snipaste_2024-09-27_17-47-57](https://github.com/user-attachments/assets/de6ffde7-3c38-42ea-ae5a-8af956616f7d)

no clue whats wrong 
help me guys !

**Comment by kushdongX** [comment]
https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original

1, download the inswapper_128.onnx manually
2, put this model to your_path/models

try this

**Comment by BerEZzzz** [comment]
> https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original
> 
> 1, download the inswapper_128.onnx manually 2, put this model to your_path/models
> 
> try this

still same , nothing change

**Comment by kushdongX** [comment]
did u followed the exact steps that are mentioned in the install guide? try this too " pip install --upgrade insightface "

**Comment by BerEZzzz** [comment]
> did u followed the exact steps that are mentioned in the install guide? try this too " pip install --upgrade insightface "

Thanks it is works fine already
but i am not that satisfied cause of the quality and the fps kinda slow
is there any minimum requirement to run it smoothly

quality is good , when i turn on the face enhancer but fps drop to 1 and start not responding

12th Gen Intel(R) Core(TM) i5-12400F (12 CPUs), ~2.5GHz
Memory: 16384MB RAM
Nvidia rtx 4060

**Comment by hacksider** [comment]
Have you tried resizing the preview window to smaller one?

**Comment by Updatedme** [comment]
I have encountered this problem several times when I run installed for my customers . 


 Solution .
1. Uninstall all virtual cam application present in you computer . 
2. Restart your computer 
3. download the inswapper_128.onnx and replace it with the existing one in the models folder . 
4. Run the deep-live-cam 
5. Then selcet face and click live . 
6. Once it's successful captures your camer . You can then reinstall the vitual camera of your choice. 

Usually, it's best advice to uninstall any available virtual cam in your computer before installing the deep-live-cam software.  

If you need further assistance, here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

**Comment by Updatedme** [comment]
> ![Snipaste_2024-09-27_17-48-15](https://github.com/user-attachments/assets/34d3e5cf-ff59-473a-866b-2a3e8f362217)
> ![Snipaste_2024-09-27_17-47-57](https://github.com/user-attachments/assets/de6ffde7-3c38-42ea-ae5a-8af956616f7d)
> 
> no clue whats wrong 
> help me guys !

I have encountered this problem several times when I run installed for my customers .

Solution .

Uninstall all virtual cam application present in you computer .
Restart your computer
download the inswapper_128.onnx and replace it with the existing one in the models folder .
Run the deep-live-cam
Then selcet face and click live .
Once it's successful captures your camer . You can then reinstall the vitual camera of your choice.
Usually, it's best advice to uninstall any available virtual cam in your computer before installing the deep-live-cam software.

If you need further assistance, here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

**Comment by Updatedme** [comment]
> ![Snipaste_2024-09-27_17-48-15](https://github.com/user-attachments/assets/34d3e5cf-ff59-473a-866b-2a3e8f362217)
> ![Snipaste_2024-09-27_17-47-57](https://github.com/user-attachments/assets/de6ffde7-3c38-42ea-ae5a-8af956616f7d)
> 
> no clue whats wrong 
> help me guys !

I have encountered this problem several times when I run installed for my customers .

Solution .

Uninstall all virtual cam application present in you computer .
Restart your computer
download the inswapper_128.onnx and replace it with the existing one in the models folder .
Run the deep-live-cam
Then selcet face and click live .
Once it's successful captures your camer . You can then reinstall the vitual camera of your choice.
Usually, it's best advice to uninstall any available virtual cam in your computer before installing the deep-live-cam software.

If you need further assistance, here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

**Comment by davidlorex** [comment]
> > ![Snipaste_2024-09-27_17-48-15](https://private-user-images.githubusercontent.com/183080363/371501368-34d3e5cf-ff59-473a-866b-2a3e8f362217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MjQ3ODEsIm5iZiI6MTcyNzYyNDQ4MSwicGF0aCI6Ii8xODMwODAzNjMvMzcxNTAxMzY4LTM0ZDNlNWNmLWZmNTktNDczYS04NjZiLTJhM2U4ZjM2MjIxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxNTQxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODQwMjFlMGVjNDBlOWExYjcwZjA4ZDYzOGQ3OTg1MDY5MmE4YzBkMjhhMWE2Mzg1MDBiNjkwNmU1ZmYxYjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xuthXBekmy3_ClXjcGzp0MAnO-CCPqCVXQXg-ecXh68)
> > ![Snipaste_2024-09-27_17-47-57](https://private-user-images.githubusercontent.com/183080363/371501374-de6ffde7-3c38-42ea-ae5a-8af956616f7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MjQ3ODEsIm5iZiI6MTcyNzYyNDQ4MSwicGF0aCI6Ii8xODMwODAzNjMvMzcxNTAxMzc0LWRlNmZmZGU3LTNjMzgtNDJlYS1hZTVhLThhZjk1NjYxNmY3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxNTQxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzZmMjc1NGJiOWU3YjgzMTMwOTlhNTQzZjA0MzNmZDkzZDQyNmI0ZjgzMmQ4MzgxOWI4NTEyZGU2YWU1NDdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fyufQ-PDyiR2G8Yv2lttSmx4WCZh6slaNYk29XaTZ5U)
> > no clue whats wrong
> > help me guys !
> 
> I have encountered this problem several times when I run installed for my customers .
> 
> Solution .
> 
> Uninstall all virtual cam application present in you computer . Restart your computer download the inswapper_128.onnx and replace it with the existing one in the models folder . Run the deep-live-cam Then selcet face and click live . Once it's successful captures your camer . You can then reinstall the vitual camera of your choice. Usually, it's best advice to uninstall any available virtual cam in your computer before installing the deep-live-cam software.
> 
> If you need further assistance, here's my whatsapp https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

It works. Following your method worked perfectly 
I got similer problem.  
When i click live it goes blank.  I tried your method it works perfect. Thank you .

**Comment by tttyne** [comment]
![image](https://github.com/user-attachments/assets/5d73ef98-7ed4-40d2-bd6f-741a9fa1cff2)
I followed the instructions above, but still have the same problem :(

**Comment by fuderoso1000** [comment]
Same thing is happening with my, already uninstalled all possible virtual camera applications, restarted computer, redownloaded the models and still blank preview

**Comment by KRSHH** [comment]
> Same thing is happening with me, already uninstalled all possible virtual camera applications, restarted computer, re downloaded the models and still blank preview

What is the error message?

**Comment by fuderoso1000** [comment]
> > Same thing is happening with me, already uninstalled all possible virtual camera applications, restarted computer, re downloaded the models and still blank preview
> 
> What is the error message?

![image](https://github.com/user-attachments/assets/320ce3bb-94df-4cde-9a81-440711e0658a)

**Comment by KRSHH** [comment]
Did you try #697 ?

**Comment by fuderoso1000** [comment]
> Did you try #697 ?

I had not tried that one, I did try downloading the one model a couple of comments up, but I see they're different, 
it works now, thanks friend, much appreciated.
