### ISSUE TITLE
Can I make a stream through deep live cam 

### ISSUE THREAD

**Issue by Aivoice96** [hacksider/Deep-Live-Cam#657]
i make an issue topic but it closed the link is https://github.com/hacksider/Deep-Live-Cam/issues/648
 the image has pixels ,, Although I use soft box costume lighting equipment to improve the image quality ,, i used it in obs as window capture not obs virtual camera .. is this the problem ?
image
and there is a problem when in put my face down it's goes and my hand on my mouth like this photo
![371792332-43fe0a7d-faee-4a64-8b20-b995d4247870](https://github.com/user-attachments/assets/df704dc5-e8ec-4fb4-969e-f47169009b45)

i need to make it like this in the preview topic live

https://github.com/hacksider/Deep-Live-Cam/blob/main/demo.gif?raw=true

any help ?

**Comment by hacksider** [comment]
Why in the world will you stream with your webcam on that angle and put your hand on your mouth? This features are not included on the demo.
