### ISSUE TITLE
Exception in Tkinter callback when using slider on live cam

### ISSUE THREAD

**Issue by markbland82** [hacksider/Deep-Live-Cam#664]
Error:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MJB\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\MJB\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_slider.py", line 330, in _clicked
    self._value = (self._output_value - self._from_) / (self._to - self._from_)
ZeroDivisionError: float division by zero

**Comment by yarodevuci** [comment]
same here

**Comment by Updatedme** [comment]
Try this solution.
Open the terminal in Deep-Live-Cam folder, enter these two commands -
Paste in this command one after the other 


. \venv\Scripts\Activate

python -m pip install --force-reinstall https://github.com/KRSHH/FileStorage/raw/refs/heads/main/customtkinter-5.2.2-py3-none-any.whl

**Comment by markbland82** [comment]
@Updatedme - This didn't work for me.

**Comment by KRSHH** [comment]
Pull again

**Comment by KRSHH** [comment]
or pull the ui branch if you want to use the same UI
