### ISSUE TITLE
[SUGGESTION] - Remember LAST states when EXIT the app

### ISSUE THREAD

**Issue by AlonDan** [hacksider/Deep-Live-Cam#688]
This is not a bug, but a Suggestion.

Currently when exiting the app, it doesn't SAVE the changes of the checkboxes:
"Keep fps"
"Keep frames"
"Face Enhancer"
etc..

Please consider to add a feature that it will "REMEMBER" the latest changes on next release 🙏

**EDIT:**
Please also consider to add the newest Inswapper **256** and **512** 
and GPEN model will be much more accurate results than GFPgan.

I hope you will consider these suggestions, thanks ahead! ❤

**Comment by KRSHH** [comment]
Thanks for the suggestion. and the 256 and 512 are not open because of "SAFETY reasons".
