### ISSUE TITLE
Face Enhancer Resolution

### ISSUE THREAD

**Issue by fraukepfeuffer** [hacksider/Deep-Live-Cam#692]
The Face Enhancer produces way too much resolution for it to look real. 
Is there any way to down the resolution to find a middle ground?

Some videos have very blurry faces with no reason, the source image is big enough and with Face Enhancer its good but unreal.

**Comment by fraukepfeuffer** [comment]
I saw on the experimental tree you can set " --enhancer-upscale-factor ", but how can I install the experimental version? Its the same download as the normal one...

**Comment by Martin-SF** [comment]
install (with conda) is acually standard procedure. create a virtual environment then install packages specified in requirements.txt

`conda create -n deeplive python=3.10`
`pip install -r requirements.txt`

**Comment by Martin-SF** [comment]
regarding the resolution:
you can try to lower the resolution of the target file.
i think you mean the strength of the face enhancer you want to lower

**Comment by Updatedme** [comment]
That will reduce the quality of the output in preview.

> regarding the resolution:
> you can try to lower the resolution of the target file.
> i think you mean the strength of the face enhancer you want to lower
