### ISSUE TITLE
Говнище не рабочее!

### ISSUE THREAD

**Issue by SergeiShapovalov** [hacksider/Deep-Live-Cam#695]
НЕ ПЛАТИТЕ ЗА ЭТО ДЕНЬГИ! Сотни человек пишут что не работает, я 3 часа потратил на эту херню и еще 12$ зачем то оплатил, а нихера не запускается. Разрабы долбаны

**Comment by KRSHH** [comment]
Can you specify your issue?

**Comment by nitinmukesh** [comment]
@SergeiShapovalov 

Please explain your issue. I tested on Windows, works fine. You installing on Windows or Linux?
