### ISSUE TITLE
Always get trackback error. whenever i try to run.py

### ISSUE THREAD

**Issue by Mrviktur** [hacksider/Deep-Live-Cam#698]
*  File "C:\Deep-Live-Cam-Improved-main\run.py", line 3, in <module>
    from modules import core
  File "C:\Deep-Live-Cam-Improved-main\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "C:\Deep-Live-Cam-Improved-main\modules\ui.py", line 6, in <module>
    from PIL import Image, ImageOps
  File "C:\Deep-Live-Cam-Improved-main\venv\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Deep-Live-Cam-Improved-main\venv\lib\site-packages\PIL\__init__.py)

**Comment by hacksider** [comment]
pip install Pillow

**Comment by Mrviktur** [comment]
> pip install Pillow

(venv) C:\Deep-Live-Cam-Improved-main>pip install pillow
Requirement already satisfied: pillow in c:\users\dell\downloads\deep-live-cam-improved-main\deep-live-cam-improved-main\venv\lib\site-packages (9.5.0)

(venv) C:\Deep-Live-Cam-Improved-main>python run.py
Traceback (most recent call last):
  File "C:\Deep-Live-Cam-Improved-main\run.py", line 3, in <module>
    from modules import core
  File "C:\Deep-Live-Cam-Improved-main\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "C:\Deep-Live-Cam-Improved-main\modules\ui.py", line 6, in <module>
    from PIL import Image, ImageOps
  File "C:\Deep-Live-Cam-Improved-main\venv\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Deep-Live-Cam-Improved-main\venv\lib\site-packages\PIL\__init__.py)

**Comment by KRSHH** [comment]
in venv - python -m pip install pillow

**Comment by AVGRadmin** [comment]
> A module that was compiled using NumPy 1.x cannot be run in NumPy 2.1.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

You need to install the [correct](https://github.com/hacksider/Deep-Live-Cam/blob/bbad5e08bb44743f92a0ecf97a8fb124e79473ec/requirements.txt#L3) numpy version. I suggest going through the install process again to make sure everything is installed correctly.

**Comment by Updatedme** [comment]
I recommend you 1stly uninstall the python, restar the computer , then go over the process again.  It's important you create a V environment.  .

I also recommend minicond 3.10  

If you need further assistance, here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

**Comment by Updatedme** [comment]
I recommend you 1stly uninstall the python, restar the computer , then go over the process again. It's important you create a V environment. .

I also recommend minicond 3.10

If you need further assistance, here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010
