### ISSUE TITLE
Can't get virtual cameras as input

### ISSUE THREAD

**Issue by leontheremin** [hacksider/Deep-Live-Cam#7]
I'm trying to use a virtual camera (OBS, Nvidia Broadcast...) as an input to Deep-Live-Cam. Not even getting an error that I could share here, it just freezes. I've tried to change the camera index on the code with no luck, on one of them I got som RGB weird noise and I'm looking into possibly transcoding the image to try again. But it would be awesome to have a camera selector in the GUI.

**Comment by hacksider** [comment]
It's more of an issue with CV2 driver. I believe there's already some fixes out there on the wild but the focus here is to work with hardware first then software.

**Comment by Cz1544252489** [comment]
If I want to use software such as obs first, how can I do?

**Comment by hacksider** [comment]
> If I want to use software such as obs first, how can I do?

You can just capture the window on OBS. Or if you have multiple camera, I suggest use the old_experimental branch
