### ISSUE TITLE
Black squares instead of faces when swapping

### ISSUE THREAD

**Issue by doomhead0040** [hacksider/Deep-Live-Cam#70]
Installations went through without much trouble in venv pip install -r -requimnets.txt shows I have all packages. I don't know how to deal with this and what the error is coming from. Don't judge me for face selection this is just to show the problem.
![02OTR-videoSixteenByNineJumbo1600-2865121445](https://github.com/user-attachments/assets/adb92712-f181-4ddc-b0e6-05ada60b2883)
![img_5075-3008947372](https://github.com/user-attachments/assets/6d7d1cc3-5394-47ee-897e-53a9bab084ef)
![output](https://github.com/user-attachments/assets/d0f32059-d628-483f-b97b-319de2e894ed)
![output1](https://github.com/user-attachments/assets/92748a2c-4000-4f55-a64e-9b70c046d0e3)

**Comment by ShuQiHere** [comment]
metoo

**Comment by ShuQiHere** [comment]
the model is broken, try to download it again

**Comment by doomhead0040** [comment]
which one model?

**Comment by moaeddy** [comment]
> the model is broken, try to download it again

didn't solve it

**Comment by ShuQiHere** [comment]
I solved this problem by downloading it again; you may try downloading these two models in some other website and replace it with your old model

**Comment by ShuQiHere** [comment]
or you may try some other alternative model...

**Comment by moaeddy** [comment]
> or you may try some other alternative model...

which other alternative models do you suggest, and which alternative website do you suggest the models can be downloaded aside from the instruction page?

I already re-downloaded and didn't work.

**Comment by inobyte** [comment]
solved this problem just by using GPU

**Comment by moaeddy** [comment]
> solved this problem just by using GPU

i am using Nvidia RTX 3060

**Comment by hacksider** [comment]
Your onnx runtime isnt compatible, onnxruntime==1.18.0
also try redownloading the models

**Comment by chenbuer** [comment]
> > or you may try some other alternative model...
> 
> which other alternative models do you suggest, and which alternative website do you suggest the models can be downloaded aside from the instruction page?
> 
> I already re-downloaded and didn't work.

I replace old model. 
[inswapper_128_fp16](https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx) 
[GFPGANv1.4.pth](https://huggingface.co/gmk123/GFPGAN/resolve/main/GFPGANv1.4.pth?download=true)

then, the problem solved!

**Comment by yizhangliu** [comment]
> > > or you may try some other alternative model...
> > 
> > 
> > which other alternative models do you suggest, and which alternative website do you suggest the models can be downloaded aside from the instruction page?
> > I already re-downloaded and didn't work.
> 
> I replace old model with: [inswapper_128_fp16.onnx](https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx) [GFPGANv1.4.pth](https://huggingface.co/gmk123/GFPGAN/resolve/main/GFPGANv1.4.pth?download=true)
> 
> then, the problem solved!

This is the correct answer. Thank you very much.
