### ISSUE TITLE
Error...pip install -r requirements.txt

### ISSUE THREAD

**Issue by DraganxXx1** [hacksider/Deep-Live-Cam#703]
![Screenshot_1](https://github.com/user-attachments/assets/d6416478-8755-4544-87c2-3ff198d53bb2)

**Comment by nitinmukesh** [comment]
Try

pip install Cython

and then install requirements

**Comment by DraganxXx1** [comment]
![Uploading Screenshot_2.png…]()

**Comment by DraganxXx1** [comment]
I did that, but there's still something wrong.
![image](https://github.com/user-attachments/assets/6fcfb473-b5ef-46dc-ada8-8e0a9c5e83b9)

**Comment by DraganxXx1** [comment]
> Попробовать
> 
> pip install Cython
> 
> а затем требования к установке

I did that, but there's still something wrong.
![image](https://github.com/user-attachments/assets/ea70f0dd-9c29-473b-968e-24a93b0f6078)

**Comment by Amin-Berjaoui-Tahmaz** [comment]
I have the same issue. If you have managed to fix this, would you mind sharing what the fix was?
