### ISSUE TITLE
Frame processor face_enhancer not found

### ISSUE THREAD

**Issue by ttvhipo** [hacksider/Deep-Live-Cam#705]
I have tried everything no luck, please help

**Comment by Updatedme** [comment]
Aside from the face ehnacment does everyother things run and check fine?

**Comment by Updatedme** [comment]
If you need further assistance, here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

**Comment by Updatedme** [comment]
> I have tried everything no luck, please help

Does everything else works fine for you with deeplivecam aside the face enhancer . If yes . Then I recommend you enjoy other futures on the deeplivecam for now.  
It's only getting better .

**Comment by KRSHH** [comment]
#266
