### ISSUE TITLE
Low FPS on a high-performance PC

### ISSUE THREAD

**Issue by mugidar** [hacksider/Deep-Live-Cam#708]
Hi. This app is really cool, but I have some problems. When I run the “Live” deepfake, I have 20 fps without face enhancer and 6 fps with face enhancer. The problem is that my GPU is only 1% loaded. How can I make it work more or at full capacity?

**I have installed
CUDA
CUDNN
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3
etc
**and ran the program using** python run.py --execution-provider cuda

**Computer specifications
RTX 4080 SUPER
I7 14700K 
64 GB OF RAM

**Comment by KRSHH** [comment]
I am getting avg 10 FPS with RTX 3060 12GB. we need benchmarks from more users to check if there's an issue.

**Comment by mugidar** [comment]
> I am getting avg 10 FPS with RTX 3060 12GB. we need benchmarks from more users to check if there's an issue.

What do you mean benchmarks? What do you mean by benchmarks? Is there anything I can do to help?

**Comment by KRSHH** [comment]
We need benchmarks from users with similar if not same specs to check if its an issue or just normal performance.

**Comment by hacksider** [comment]
My 3080 is getting 15fps, 4080 is around 18 to 20fps. Usually 15fps is good enough for any basic broadcast.

**Comment by mugidar** [comment]
> My 3080 is getting 15fps, 4080 is around 18 to 20fps. Usually 15fps is good enough for any basic broadcast.

I think that's not bad for this app quality, but probably you know others softwares where possible to get more fps

**Comment by KRSHH** [comment]
> I think that's not bad for this app quality, but probably you know others softwares where possible to get more fps

There are no alternatives which offer higher performance, as of now so, Deep-Live-Cam is probably your best bet. and we are working on it to improve it.

**Comment by hacksider** [comment]
> > My 3080 is getting 15fps, 4080 is around 18 to 20fps. Usually 15fps is good enough for any basic broadcast.
> 
> I think that's not bad for this app quality, but probably you know others softwares where possible to get more fps

You can actually use Augmented reality, but of course it all ends up on the way it is implemented. The problem with Augmented reality is it doesnt adapt to lighting.

**Comment by mugidar** [comment]
Augmented reality? What does it mean? How to use it?

**Comment by mugidar** [comment]
> I am getting avg 10 FPS with RTX 3060 12GB. we need benchmarks from more users to check if there's an issue.

Btw, is there any ways to make Deep Live Cam use more pc resources?

**Comment by ochristianlove** [comment]
i am in the same boat, my FPS is, also i notice is not using the capacity of my pc, there is 14 core, RTX 4080, 32GB RAM, 3T Space,
2024 PC,

IF you can make the software have control for FPS,  window size, camera fps 30-60fps config, there so much resource available but it not using it an it slow, when i stop face enhancer to improves while sacrificing the quality 


also i suspect it might be my default camera, because i have see someone with good frame rate (FPS) and i dont understand the magic 

I NEED SOLUTION THANKS

**Comment by hacksider** [comment]
If you're using it without face enhancer, 15 to 30 fps can be achieved. That is already good enough for streaming.

**Comment by ochristianlove** [comment]
Am getting 2.9 max fps without face hencener, what do i do

**Comment by ochristianlove** [comment]
I always tun on victual environment for it to work 

ven\Scripts\activate

Before running run.py cuda

Should i show you what it reading in my Pwershell after running run.py cuda

Because the FPS is slow 2.9 FPS

**Comment by hacksider** [comment]
Try python 3.11, using venv. Then no face enhancer. That's what I used on the demo.

**Comment by goldrohan** [comment]
Can we achieve more with 5090? Like over 30 fps with 5090?

**Comment by bellyjeans** [comment]
I use conda rather than venv , it should be no difference ?

> Try python 3.11, using venv. Then no face enhancer. That's what I used on the demo.
