### ISSUE TITLE
Error in "run.py"

### ISSUE THREAD

**Issue by adelorn08** [hacksider/Deep-Live-Cam#710]
When I run the command “python run.py --execution-provider cuda”, the following error occurs:

Traceback (most recent call last):
  File "C:\Users\maril\Deep-Live-Cam\Deep-Live-Cam\run.py", line 6, in <module>
    core.run()
  File "C:\Users\maril\Deep-Live-Cam\Deep-Live-Cam\modules\core.py", line 250, in run
    limit_resources()
  File "C:\Users\maril\Deep-Live-Cam\Deep-Live-Cam\modules\core.py", line 137, in limit_resources
    gpus = tensorflow.config.experimental.list_physical_devices('GPU')
AttributeError: module 'tensorflow' has no attribute 'config'

**Comment by Updatedme** [comment]
Try 

Pip install tensorflow

**Comment by Updatedme** [comment]
If you need further assistance, here's my whatsapp
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

**Comment by KRSHH** [comment]
> If you need further assistance, here's my whatsapp https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010

Hi, thanks for actively helping users with issues but, please solve it here itself as it would help others if they face the same issue in the future.

**Comment by Updatedme** [comment]
Noted .
