### ISSUE TITLE
Low FPS on program

### ISSUE THREAD

**Issue by MarisJ03** [hacksider/Deep-Live-Cam#716]
Im getting 6fps on the program on Live with non of the boxes ticked and with face enhancer i get 2fps. 
Im using the command "python run.py --execution-provider cuda" for the gpu optimization.  I get 8fps on OBS virtual camera.
my specs are 
64gb DDR4 
Ryzen 9 5950x
RTX 3070ti

comparing these specs to what others have i shouldnt be getting this low of an fps. 
Could i please get some help please and thank you in advance.

Apologies if this is not in the right section to post this.

**Comment by KRSHH** [comment]
Can you check whether your GPU is being utilised?

**Comment by hacksider** [comment]
I suggest making the preview screen 720p or lower. 520p is enough for any streaming platform. 480p is also tolerable. And dont make your face too big, sit back a bit like a normal person would do.

![image](https://github.com/user-attachments/assets/80f16e9b-9c64-4ed2-acaf-e8b179ca7d3f)
This face to screen ration would be sufficient enough 😄

**Comment by MarisJ03** [comment]
> Can you check whether your GPU is being utilised?
hm thats weird when i press live button and check performance of my gpu it says only 4% of it is being used. am i missing something?

**Comment by leihuayi** [comment]
Have you tried comparing to other deepface video programs which use the same model, for instance [Facefusion](https://docs.facefusion.io/) ? Like you, I was kind of disappointed as well by the performances of inswapper onnx, in both projets I have around 11fps although I run the code on quite a powerful GPU (RTX A6000). You can check [here](https://svi.nl/GPUCards#contentgpu_cards-4) how good is the GPU you use compared to mine.


Changing the input size will not have much effet in speeding up the process. Indeed, the process of the algorithm for swapping faces is:
1. on the target image, find the face to swap (size WxH)
2. resize face to fixed size (usually 128x128 or 256x256)
3. generate new face to this fixed size
4. upscale the generated face to WxH

Therefore the swapping operation, which is the most time-consuming, is always done at constant size.
This is explained [here in the section "understanding quality of results"](https://glucauze.github.io/sd-webui-faceswaplab/faq/)
