### ISSUE TITLE
Preview doesn't work HELP please

### ISSUE THREAD

**Issue by Montana7786** [hacksider/Deep-Live-Cam#725]
Hi,
When I click on the live button, the preview only shows a grey screen with nothing on it.

Maybe it's because of this error : 

Installing collected packages: typing-extensions
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.6.1
    Uninstalling typing_extensions-4.6.1:
      Successfully uninstalled typing_extensions-4.6.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pydantic 2.9.0 requires typing-extensions>=4.6.1; python_version < "3.13", but you have typing-extensions 4.5.0 which is incompatible.
pydantic-core 2.23.2 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
ipython 8.27.0 requires typing-extensions>=4.6; python_version < "3.12", but you have typing-extensions 4.5.0 which is incompatible.
Successfully installed typing-extensions-4.5.0

And I also get this, even after I used the replacement version:

onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\User\Deep-Live-Cam\models\inswapper_128_fp16.onnx failed:Protobuf parsing failed.

**Comment by KRSHH** [comment]
Check #717

**Comment by Montana7786** [comment]
I dont get the error anymore, thanks but do you know why my results are that bad ? 
![image](https://github.com/user-attachments/assets/d58713e3-2f1d-4e67-b214-be60a32e30a3)

**Comment by KRSHH** [comment]
Use Face Enhancer when using prerecorded high res target image/video.
