### ISSUE TITLE
Already installed all the required stuff but when I try to run it, it just exits without showing any error

### ISSUE THREAD

**Issue by great-dev1** [hacksider/Deep-Live-Cam#737]
**Describe the bug**
Hi,

I've already installed all the requirements like mentioned in ReadMe.md and it went smoothly without any error. But when I try to run it with this command (python run.py --execution-provider cuda), it does not show me anything but just exits without showing any error.

**Screenshots**
![Screenshot_1](https://github.com/user-attachments/assets/013fd07d-21ec-4763-bc67-afe0dee9aebb)

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by Updatedme** [comment]
If need personal assistant holla at me here https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010
