### ISSUE TITLE
"Map faces" not working on 1.6.0 when i tried to swap the faces in the JPG picture

### ISSUE THREAD

**Issue by KloseYao** [hacksider/Deep-Live-Cam#739]
**Describe the bug**
I tried to swap the multiple faces in the picture , but even I already mapping all the different source the target faces, it still swap all faces to S-0 face. Am I missing some steps?

**To Reproduce**
1. Check "Map faces" and "Many faces"
2. Select Source images for each face.
3. Submit
4. Start Run

**Screenshots**
![20241024085355](https://github.com/user-attachments/assets/1daebec5-6cb1-40e8-b3f5-c640e5291009)

**Desktop (please complete the following information):**
- Windows 10
- Python 3.10.11 (venv)
- D-L-C 1.6.0

**Comment by KloseYao** [comment]
![image](https://github.com/user-attachments/assets/b32b3640-fb1b-4ccf-a065-d3c8f8ff365a)
The log also shows " Using first source image", anything wrong of my steps?

**Comment by rotatorotator** [comment]
Where did you find an 1.6.0 version?

**Comment by hacksider** [comment]
The current version is 1.6 😅

**Comment by hacksider** [comment]
> Where did you find an 1.6.0 version?

The current version is 1.6

**Comment by KloseYao** [comment]
uncheck "Many faces" and problem resolved
