### ISSUE TITLE
preview is too zoom 

### ISSUE THREAD

**Issue by Aivoice96** [hacksider/Deep-Live-Cam#749]
When I step on the live button, the preview window shows a large size relative to the camera, there is too much zoom, and I don't find a solution to the problem in the photos,

![image](https://github.com/user-attachments/assets/d9897d4c-bd17-472f-9957-d9d01f2ed82a)

 does it have anything to do with the topic indicated by the arrow ?

![image](https://github.com/user-attachments/assets/4137d247-4aa8-464b-b8a2-c0322f443e7f)

**Comment by hacksider** [comment]
It just mirror on what it sees on the webcam. You can step back a bit while testing it.

**Comment by Aivoice96** [comment]
> It just mirror on what it sees on the webcam. You can step back a bit while testing it.

The image that appears on the web cam is smaller than the one displayed in the preview box,, the preview box has more zoom than necessary and not the size of a regular camera

**Comment by Aivoice96** [comment]
up

**Comment by hacksider** [comment]
Is your webcam vertical? The preview is supposedly horizontal.

**Comment by Aivoice96** [comment]
> Is your webcam vertical? The preview is supposedly horizont

The problem was solved on its own, I opened the daytime program and it worked normally
