### ISSUE TITLE
Skin Color Adjustment Feature

### ISSUE THREAD

**Issue by keindeezy** [hacksider/Deep-Live-Cam#751]
The program works well but a feature should be added. The skin color should be able to change. Example, I am white skin, but I changed to a black person picture. It should have a feature to change the skin color. But if it has that feature already, help me figure it out.

**Comment by hacksider** [comment]
It will adjust to your skin color. You can use filters on any software then just capture it with OBS then use that as the base of your deepfake.

**Comment by KRSHH** [comment]
If you really need it. Get a tan, and your skin will be dark enough after the faceswap to pass as a black guy.
