### ISSUE TITLE
Black Square When Face Is Shown

### ISSUE THREAD

**Issue by ProgKing** [hacksider/Deep-Live-Cam#754]
OS: Arch Linux
GPU: GTX 1050Ti 
CPU: Ryzen 7 1700x

Terminal info:
❯ python run.py
2024-10-30 16:04:36.425682: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1730293476.443451   37785 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730293476.448874   37785 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[ WARN:0@2.932] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@2.932] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/user/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/user/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/user/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/user/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/user/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]

**Comment by minatori50** [comment]
the same, my console log:

[ERROR:0@12.308] global cap.cpp:323 cv::VideoCapture::open VIDEOIO(DSHOW): raised unknown C++ exception!


[ WARN:0@12.315] global cap.cpp:344 cv::VideoCapture::open VIDEOIO(DSHOW): backend is generally available but can't be used to capture by index
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\minat/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\minat/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\minat/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\minat/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\minat/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]

**Comment by AliceAria** [comment]
the same as well

**Comment by KRSHH** [comment]
Make sure that your webcam is not being utilized in any other application.

**Comment by AliceAria** [comment]
of course. My webcam is activated by this program.

**Comment by Updatedme** [comment]
Change the inswapper 


Download this inswapper 
https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx
Replace with existing inswapper .

**Comment by lxlyjss** [comment]
> Change the inswapper
> 
> Download this inswapper https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx Replace with existing inswapper .

good

**Comment by Updatedme** [comment]
I am glad that helped 

> Change the inswapper
> 
> Download this inswapper https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx Replace with existing inswapper .
