### ISSUE TITLE
lag in preview Video 

### ISSUE THREAD

**Issue by Aivoice96** [hacksider/Deep-Live-Cam#758]
why there is lag when in picturing video with game or any program else like that video at the original way .. 

https://github.com/user-attachments/assets/e285f7e9-7b71-4aaa-b7fa-445272c8c57d

and when in activated face enhancer it's make too lag in video like below video 

https://github.com/user-attachments/assets/25669d10-6883-4565-ac3c-773ea39369e2

i need it to make streaming or recording videos with it  ,, but i need it to make without lag and good quality of photo like the demo below 

https://github.com/user-attachments/assets/2900bb58-7a6a-46d0-956d-0f7d81947351

any solution ? 
Knowing that I use external soft box lighting

my computer requirements at photo below 
![image](https://github.com/user-attachments/assets/05d2bb0a-a2a4-4d5a-99da-808390c5f0a6)

![image](https://github.com/user-attachments/assets/0d200b2d-cccd-453b-9cbf-6a3398c6b580)
![image](https://github.com/user-attachments/assets/196ca233-44ea-4c7b-bdeb-73f40344cfc2)

**Comment by KRSHH** [comment]
Face Enhancer is not for live faceswap. 11 FPS is as good as it gets with your rig without it.

**Comment by hacksider** [comment]
Please take note that you are sharing the GPU resource to your game and the application. The application itself takes around 6gb VRAM already.

**Comment by Aivoice96** [comment]
> Please take note that you are sharing the GPU resource to your game and the application. The application itself takes around 6gb VRAM already.

@hacksider  i know that but the program with the game it takes about 8.5 gb vram there is about 3.5 gb free

**Comment by Aivoice96** [comment]
> Face Enhancer is not for live faceswap. 11 FPS is as good as it gets with your rig without it.

okay ,, i won't use face enhancer bu the photo hasn't good quality ,, and there is a lag not like the demo i mentioned 

@KRSHH

**Comment by Aivoice96** [comment]
could you reopen the request or i need to contact 
@KRSHH

**Comment by KRSHH** [comment]
> > Face Enhancer is not for live faceswap. 11 FPS is as good as it gets with your rig without it.
> 
> okay ,, i won't use face enhancer bu the photo hasn't good quality ,, and there is a lag not like the demo i mentioned
> 
> @KRSHH

the GPU used in demo is not 3060, Here is an inference on 3060 - 




https://github.com/user-attachments/assets/b48e3a1d-9097-49d6-b734-dfc9e5bce9c0

**Comment by hacksider** [comment]
The demo is using 3080, if you have 3080 or 4070 or higher, then you will experience better frame rates. You don't need to contact anyone for that kind of problem.

**Comment by KRSHH** [comment]
> The demo is using 3080, if you have 3080 or 4070 or higher, then you will experience better frame rates. You don't need to contact anyone for that kind of problem.

I have updated the template.

**Comment by Aivoice96** [comment]
> > > Face Enhancer is not for live faceswap. 11 FPS is as good as it gets with your rig without it.
> > 
> > 
> > okay ,, i won't use face enhancer bu the photo hasn't good quality ,, and there is a lag not like the demo i mentioned
> > @KRSHH
> 
> the GPU used in demo is not 3060, Here is an inference on 3060 -
> e4g34e5tg4.2.mp4

@KRSHH  I understand what you say ,, but there is little lag in movement 
Is it possible for us to remove this lag ? because I need this to create content or make streaming with it , or is it not possible?
I hope you understand what I mean

**Comment by hacksider** [comment]
I suggest getting a better GPU. The application is hardware dependent. 4080 or higher so you can get 15fps or higher.

**Comment by hacksider** [comment]
I also suggest making the preview window smaller. That might increase the performance since you are just using it as a small overlay below.

**Comment by KRSHH** [comment]
> I suggest getting a better GPU. The application is hardware dependent. 4080 or higher so you can get 15fps or higher.

Or just wait for 5090.

**Comment by Aivoice96** [comment]
> I also suggest making the preview window smaller. That might increase the performance since you are just using it as a small overlay below.

@hacksider  I understand.. but the price of GPU 4080 is very expensive for me.. I hope there will be a solution to the this lag in the future to control FPS .. and I will try to work with what is available for my GPU
