### ISSUE TITLE
Face Enhancer Process Stalls When I Try to Process a Second Video

### ISSUE THREAD

**Issue by ConnoisseurProtege** [hacksider/Deep-Live-Cam#761]
When I try to process a second video, Face Enhancer process doesn't do anything except stay at 0 frames. It worked the first time when I had to download the weights, but when it didn't have to, the process would stall. Even after deleting the weights it wouldn't work unless I cloned the repository again. I also have mouth mask and map faces enabled if those would affect it. 

 - OS: Windows 11
 - Version 1.7.0

**Comment by KRSHH** [comment]
whats the error message?

**Comment by ConnoisseurProtege** [comment]
> whats the error message?

I don't get any error at all it just stops at 0 frames processed
