### ISSUE TITLE
Is DeepLiveCam usable on Linux?

### ISSUE THREAD

**Issue by yppeno** [hacksider/Deep-Live-Cam#763]
Hello, is DeepLiveCam usable on a Linux? 
If yes, how?
Thanks

**Comment by hacksider** [comment]
It is usable, just follow the instructions on the readme.

**Comment by hacksider** [comment]
You can, just using cpu and the console though.

**Comment by yppeno** [comment]
> You can, just using cpu and the console though.

How can i do that please? Also i've a GPU attached to my server that's the point of me using this cloud linux server
