### ISSUE TITLE
when on "Face Enhancer"  I get this error

### ISSUE THREAD

**Issue by vipcafe** [hacksider/Deep-Live-Cam#775]
I use Windows, and when I click "Face Enhancer," I get this error:
![image](https://github.com/user-attachments/assets/fd1cf8d3-d504-484f-8bdb-623cb7c6213d)

If I don't enable this feature, the program runs normally.
Is there a way to fix it?

**Comment by KRSHH** [comment]
go to models folder check the link for gfpgan model in instructions, download it and put it in the same folder.
also follow the template.

**Comment by vipcafe** [comment]
> go to models folder check the link for gfpgan model in instructions, download it and put it in the same folder.
> also follow the template.

I was able to fix it by downloading the replacement file from here
https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth
