### ISSUE TITLE
ONNXruntimeerror

### ISSUE THREAD

**Issue by jaswindersinghdhami** [hacksider/Deep-Live-Cam#777]
when selecting the camera the screen starts which is blank and this error onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/jazdhami/Documents/AI/deeplive/Deep-Live-Cam-main/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.

have tried both the models provided

**Comment by KRSHH** [comment]
Duplicate of #697
