### ISSUE TITLE
Lags on face enhancer,  GPU running 50%

### ISSUE THREAD

**Issue by sammyjank** [hacksider/Deep-Live-Cam#78]
Hello, I am experiencing extreme lags when using face enhancer with webcam, even when my 3090 running only  50%.

**Comment by hacksider** [comment]
Face enhancer using gfpgan is still very slow and I still cant find any ways to achieve it realtime. I suggest use the default, then enhance it with OBS plugins like
- sharpen
- nvidia super resolution

**Comment by sammyjank** [comment]
right, i will give those things a go thanks
