### ISSUE TITLE
OpenCV: out device of bound (0-0): 1

### ISSUE THREAD

**Issue by hehanjie** [hacksider/Deep-Live-Cam#780]
Hi everyone, I've been stuck on a problem for a few days and I'm not sure how to move forward. Is there anyone who can help me out? I'd really appreciate it!

Apple M3 Max
macos 14.6.1

penCV: out device of bound (0-0): 1
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-0): 2
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-0): 3
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-0): 4
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-0): 5
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-0): 6
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-0): 7
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-0): 8
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-0): 9
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-0): 10
OpenCV: camera failed to properly initialize!

[11/12 21:23:52.923271][info][86869][Context.cpp:77] 	- SDK version: 1.9.4
[11/12 21:23:52.923272][info][86869][Context.cpp:78] 	- SDK stage version: main
[11/12 21:23:52.923273][info][86869][Context.cpp:82] get config EnumerateNetDevice:false
[11/12 21:23:52.923273][info][86869][MacPal.cpp:36] createObPal: create MacPal!
[11/12 21:23:52.923330][info][86869][MacPal.cpp:104] Create PollingDeviceWatcher!
[11/12 21:23:52.923331][info][86869][DeviceManager.cpp:15] Current found device(s): (0)
[11/12 21:23:52.923332][info][86869][Pipeline.cpp:15] Try to create pipeline with default device.
[11/12 21:23:52.923333][warning][86869][ObException.cpp:5] No device found, fail to create pipeline!
[11/12 21:23:52.923398][info][86869][Context.cpp:90] Context destroyed
![20241112212850](https://github.com/user-attachments/assets/c141d698-8172-4581-a607-986995c476c9)

**Comment by riogesulgon** [comment]
I am experiencing the same issue using Apple M3 Pro.
It seems to be an issue when using `cv2_enumerate_cameras`
In `ui.py`:

```python
def get_available_cameras():
    """Returns a list of available camera names and indices."""
    camera_indices = []
    camera_names = []

    for camera in enumerate_cameras():
        cap = cv2.VideoCapture(camera.index)
        if cap.isOpened():
            camera_indices.append(camera.index)
            camera_names.append(camera.name)
            cap.release()
    return (camera_indices, camera_names)
```

**Comment by hehanjie** [comment]
Solved, thanks brother

**Comment by zcabbub** [comment]
M3 pro 15.0 sequoia

same problem here, the only difference is that my count of retries goes to 99 for some reason.
and I tried and changed the camera indexes from everywhere but it does not work, I put 0, 1, -1, etc. in different places. I will have to understand it more deeply for it to work. 

The camera starts for a bit in the beginning, no display though, just I can see the camera icon popping up and the green light next to the physical camera.
<img width="510" alt="Screenshot 2024-11-14 at 21 13 50" src="https://github.com/user-attachments/assets/25be3e5b-c45c-484f-890a-a691039306be">


But the problem still stands and if anyone knows how to solve it pls lmk

**Comment by yamil-abraham** [comment]
> M3 pro 15.0 sequoia
> 
> same problem here, the only difference is that my count of retries goes to 99 for some reason.
> 
> and I tried and changed the camera indexes from everywhere but it does not work, I put 0, 1, -1, etc. in different places. I will have to understand it more deeply for it to work.
> 
> The camera starts for a bit in the beginning, no display though, just I can see the camera icon popping up and the green light next to the physical camera. <img alt="Screenshot 2024-11-14 at 21 13 50" width="510" src="https://private-user-images.githubusercontent.com/56021461/386370487-25be3e5b-c45c-484f-890a-a691039306be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTYzMzUsIm5iZiI6MTczMzQxNjAzNSwicGF0aCI6Ii81NjAyMTQ2MS8zODYzNzA0ODctMjViZTNlNWItYzQ1Yy00ODRmLTg5MGEtYTY5MTAzOTMwNmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE2MjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNmNhYTVjYWIxZGZlOWYzYzU0NWUxMTU5MTgyNmYxYjI1YWZiYTk1Mjc2ODU3MTE4MjM3Y2NhY2EwMzM3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6ppo9EY5826TK8MRGamzkBmwbn1aJTiNzFReGVUikJo">
> 
> But the problem still stands and if anyone knows how to solve it pls lmk
> 
> <img alt="Screenshot 2024-11-14 at 21 15 07" width="589" src="https://private-user-images.githubusercontent.com/56021461/386370838-de92bf79-9529-4c46-aecf-7ba6727120bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTYzMzUsIm5iZiI6MTczMzQxNjAzNSwicGF0aCI6Ii81NjAyMTQ2MS8zODYzNzA4MzgtZGU5MmJmNzktOTUyOS00YzQ2LWFlY2YtN2JhNjcyNzEyMGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE2MjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMGE5NzU4MTQzY2UzZTk1OGZhNTYyZWFhZDNlNTY2MzBjMzM2OGM3YzY1MWZmZDg4ODgzMGNmMDFhMjVjZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hvUb6WMZq6j_uoDVQo5XQ2vcnMKMWxdmKFQYwTeBLkE">

I have the same issue...did you find a solution?
