### ISSUE TITLE
Self-extracting archive version: Preview is empty

### ISSUE THREAD

**Issue by hodgezai** [hacksider/Deep-Live-Cam#784]
Hey folks hope you have a good one.
I bought the "lazy ass" package on gumroad because I cannot be bothered. 
When I select an image and run live, my camera turns on (the light appears on my laptop) but there is nothing on the preview. 

The CMD screen has this:
```
im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'
```
I have CUDA installed. My GPU is RTX 4050, RAM is 16 GB, 13rd Gen Intel CPU

**Comment by hacksider** [comment]
That means it can't detect any face. Try changing the picture.

**Comment by Moondragon2** [comment]
> That means it can't detect any face. Try changing the picture.

Thank you for the answer. I tried with many faces but none of those worked. Is there a specific resolution I must follow?

**Comment by hacksider** [comment]
Anything below 1024px would be good. As well you have to ensure that the face is clear enough (as well as yours). It should just be a single face as well.

Make sure the image is using english characters as well.

Lastly, your face should also be visible enough (try to minimize the facial hairs as well)

**Comment by Moondragon2** [comment]
> Anything below 1024px would be good. As well you have to ensure that the face is clear enough (as well as yours). It should just be a single face as well.
> 
> Make sure the image is using english characters as well.
> 
> Lastly, your face should also be visible enough (try to minimize the facial hairs as well)

Sadly it did not work. I tried with many different pictures but sadly I cannot have anything better than white preview screen. I guess it does not work for me, unless there is another solution? I tried to switch the models too. Not worked.

**Comment by Moondragon2** [comment]
Hello,

It didn't work, sadly. I have tried everything.
I guess it does not work on my laptop. Where can I ask for a refund?


· · ────────────────────── · ·
[cid:c1394086-fe5d-435a-89a7-acf603c27a34]
________________________________
Gönderen: Kenneth Estanislao ***@***.***>
Gönderildi: 14 Kasım 2024 Perşembe 20:06
Kime: hacksider/Deep-Live-Cam ***@***.***>
Bilgi: Moondragon2 ***@***.***>; Comment ***@***.***>
Konu: Re: [hacksider/Deep-Live-Cam] Self-extracting archive version: Preview is empty (Issue #784)


Anything below 1024px would be good. As well you have to ensure that the face is clear enough (as well as yours). It should just be a single face as well.

Make sure the image is using english characters as well.

Lastly, your face should also be visible enough (try to minimize the facial hairs as well)
