### ISSUE TITLE
requests.exceptions.ProxyError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /deepinsight/insightface/releases/download/v0.7/buffalo_l.zip (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))

### ISSUE THREAD

**Issue by noeeka** [hacksider/Deep-Live-Cam#79]
Error: requests.exceptions.ProxyError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /deepinsight/insightface/releases/download/v0.7/buffalo_l.zip (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))
[https://[s21.aconvert.com/convert/p3r68-cdx67/6cn6t-zl8pw.mp4](https://s21.aconvert.com/convert/p3r68-cdx67/6cn6t-zl8pw.mp4)](url)

**Comment by hacksider** [comment]
You can download the models manually on the link provided on the instructions
