### ISSUE TITLE
I have a little bit fps (1-10)

### ISSUE THREAD

**Issue by teslarecords** [hacksider/Deep-Live-Cam#795]
I changes the inswapper to inswapper_128.onnx on the inswapper.py. I changes in the setup_deep_live_cam on the Cuda (GPU), 
and then i start the soft (Live) face spawed, but the fps is very low, what the problem, help me, please?

**Comment by hacksider** [comment]
Please follow the template when reporting an issue. It'll be hard for us to identify your problem if this is the only thing you will provide us (that's why we created the template...)
