### ISSUE TITLE
how to run on window

### ISSUE THREAD

**Issue by NguyendatGH** [hacksider/Deep-Live-Cam#799]
Hi guys,
I'm new to Python and currently trying to run this project. I followed all the instructions in the README.md file, and when I used the command python run.py to run the project in the cmd, it's raise this error:

![image](https://github.com/user-attachments/assets/885431fb-bb24-46a1-8ff8-e60189be35e8)
i try to download every requirement of this project and still not working at all.
Can someone help me figure out what the issue might be and how to run it correctly? I'm currently using Windows to test this repository.

**Comment by NeHa77A** [comment]
The error indicates that the torch module could not be loaded. Have you installed the torch library?

**Comment by NguyendatGH** [comment]
Thanks for give me a solution, after i re-install pytorch modules, the program run correctly. Have a good day 😄
