### ISSUE TITLE
CPUExecutionProvider runs at 1FPS in Windows 10

### ISSUE THREAD

**Issue by federico-digital** [hacksider/Deep-Live-Cam#806]
The LIVE runs at 1 FPS, I installed everything manually with no issues on Windows 10, I installed Visual Studio. 

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\New User/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\New User/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\New User/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\New User/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\New User/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5

CPU is not even maxing out, why does it run at 1 FPS?

Microsoft Windows 10 Pro
Version 10.0.19045 Build 19045
System Type x64-based PC
Processor AMD Ryzen 7 3800X 8-Core Processor, 3893 Mhz, 8 Core(s), 16 Logical Processor(s)
Installed Physical Memory (RAM) 32.0 GB
Total Physical Memory 31.9 GB
Available Physical Memory 9.84 GB
Total Virtual Memory 63.9 GB
Available Virtual Memory 30.8 GB
Graphic Card: Radeon RX 560 Series

**Comment by hacksider** [comment]
CPU is not powerful enough to process your frames. GPU is always reccomended
