### ISSUE TITLE
Hello developers! Can u add more fps function + gpen 1.4?

### ISSUE THREAD

**Issue by renzobac** [hacksider/Deep-Live-Cam#811]
Dear developers, is it possible to get more lag and frame prep but more fps, i have 4090 + sony cam, and i test default logi cam, but always have only 15 fps. And maybe u add gpen 1.4 enchance module, faster than gfpgan ?

**Comment by KRSHH** [comment]
We've fixed the performance issue, you can expect 20-30 FPS... but, Its still in testing. and we haven't planned including gpen 1.4 yet.

**Comment by renzobac** [comment]
its possible to be in test team?

**Comment by hacksider** [comment]
> its possible to be in test team?

There's no test team. It's basically an effort between the developers and the community.
