### ISSUE TITLE
 Low FPS and Blur Issue in Deep-Live-Cam with Underutilized GPU

### ISSUE THREAD

**Issue by nasirkhansayyad132** [hacksider/Deep-Live-Cam#814]
I am experiencing **blur** around the face while using Deep-Live-Cam in live mode. Although setting the camera slightly farther away reduces the blur, the face still appears blurry. Enabling the face-enhancer mode significantly improves the clarity, but only get **4–6 FPS**. Additionally, my GPU (Nvidia 3090 Ti, 24GB) is underutilized, with **only 3–5GB of VRAM** in use.

My setup:

- 64GB RAM
- Nvidia 3090 Ti (24GB)
- HD camera

How can I optimize the performance to reduce blur while maintaining a higher FPS and better GPU utilization?

**Comment by hacksider** [comment]
Please check the wiki for more details on this.
