### ISSUE TITLE
Enhance  README.md

### ISSUE THREAD

**Issue by NimaBakhtiyari** [hacksider/Deep-Live-Cam#818]
Add the following to README.md to run the app with a single-step
```
py -3.10 -m venv .venv 
.venv\Scripts\Activate 
pip install --upgrade pip 
pip install -r requirements.txt 
python run.py
```
or you can create the following bat file
```bat
# Create a virtual environment
python3.10 -m venv .venv

# Activate the virtual environment
source .venv/bin/activate

# Upgrade pip
pip install --upgrade pip

# Install packages from requirements.txt
pip install -r requirements.txt

# Run the Python script
python run.py
```
It took me a long time to figure out that the current version of the program only works with Python 3.10. Of course, sometimes, when connecting to a proxy, some libraries are not installed, and it is better to warn the user about this. Sometimes, it can take a long time to discover this problem because no relevant error is generated.

**Comment by KRSHH** [comment]
Its literally the thing mentioned in the Installation -


![image](https://github.com/user-attachments/assets/9f0b7383-061d-4be5-883d-a2fbb5162f0b)
