### ISSUE TITLE
[Bug] Model naming inconsistency: Rename inswapper_128.onnx to inswapper_128_fp16.onnx required for proper functionality

### ISSUE THREAD

**Issue by irowbin** [hacksider/Deep-Live-Cam#819]
It seems there is an issue when downloading the model and placing it in the `/model` folder. An error occurs stating: `AssertionError: model_file D:\Deep-Live-Cam\models\inswapper_128_fp16.onnx should exist`. The model expects the name `inswapper_128_fp16.onnx`, but the downloaded model does not have the suffix `_fp16`, which is necessary for it to work.

If anyone encounters this issue, please rename the model file to `inswapper_128_fp16.onnx`, and it should function correctly.

Thank you.

**Comment by reenagibson** [comment]
I had that issue and I did the same thing, renamed it and confirmed it worked.
