### ISSUE TITLE
subprocess-exited-with-error

### ISSUE THREAD

**Issue by irfanshidqi** [hacksider/Deep-Live-Cam#82]
im installing all requirements.txt inside venv .
and i get this error ?  :

 Downloading pyasn1-0.6.0-py2.py3-none-any.whl (85 kB)
     ---------------------------------------- 85.3/85.3 kB 5.0 MB/s eta 0:00:00
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for insightface (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [215 lines of output]
      WARNING: pandoc not enabled
      running bdist_wheel
      running build
      running build_py
      creating build
      
.
.
.bla bla bla ( Line too long )
.bla bla bla ( Line too long )
.
.

at the end of cmd :

 running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Any tought  ? thankyou

**Comment by hacksider** [comment]
i believe you havent installed Microsoft C++ Build Tools yet. You missed the part where you have to install it.
