### ISSUE TITLE
Compatibility Error When Running MSI File

### ISSUE THREAD

**Issue by mokaily** [hacksider/Deep-Live-Cam#828]
Operating System: Windows 11
RAM: 64GB
Graphics Card: RTX 3070
CUDA Tools Version: 11.8
Description:
When attempting to run the MSI file, the following error message appears:

"This version is not compatible with your graphics card. Please download a different version."

**Comment by hacksider** [comment]
We never released an msi file ☺️

**Comment by hacksider** [comment]
Where did you download it? I suggest deleting it as we haven't released an msi file since then.

**Comment by KRSHH** [comment]
1. It's not official, so there is a threat of viruses and malware.

2. Demand a refund from the seller, if you paid for it.
