### ISSUE TITLE
Blank screen on MacOS M3 14.6.1

### ISSUE THREAD

**Issue by siriuslan** [hacksider/Deep-Live-Cam#843]
I follow the steps to install on my MacOS M3(Sonoma 14.6.1) however I can only see a blank screen with below outputs( it does not matter I run - python run.py --execution-provider coreml or python run.py)
<img width="621" alt="image" src="https://github.com/user-attachments/assets/ea262f29-fc9b-42e0-8e6e-0e67f5e2a0fc" />

`(.venv) {21:27}~/projects/study/ai_video/Deep-Live-Cam:main ✗ ➭ python run.py --execution-provider coreml
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
OpenCV: out device of bound (0-1): 2
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 3
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 4
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 5
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 6
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 7
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 8
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 9
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 10
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 11
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 12
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 13
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 14
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 15
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 16
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 17
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 18
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 19
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 20
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 21
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 22
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 23
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 24
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 25
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 26
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 27
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 28
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 29
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 30
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 31
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 32
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 33
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 34
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 35
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 36
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 37
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 38
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 39
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 40
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 41
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 42
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 43
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 44
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 45
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 46
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 47
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 48
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 49
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 50
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 51
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 52
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 53
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 54
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 55
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 56
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 57
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 58
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 59
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 60
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 61
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 62
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 63
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 64
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 65
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 66
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 67
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 68
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 69
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 70
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 71
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 72
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 73
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 74
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 75
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 76
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 77
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 78
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 79
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 80
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 81
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 82
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 83
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 84
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 85
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 86
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 87
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 88
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 89
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 90
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 91
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 92
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 93
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 94
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 95
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 96
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 97
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 98
OpenCV: camera failed to properly initialize!
OpenCV: out device of bound (0-1): 99
OpenCV: camera failed to properly initialize!`

I followed suggestions(step by step to make tkinter work or modify code to change the camera_index) in below links but unfortunately the issue still there. 
https://github.com/hacksider/Deep-Live-Cam/issues/112
https://github.com/hacksider/Deep-Live-Cam/issues/780

**Comment by KRSHH** [comment]
Can you pull again and try?

**Comment by siriuslan** [comment]
pulled the latest code and run however hit new error
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/89a54c51-7836-46a5-ae04-df3a3cc491ea" />

**Comment by KRSHH** [comment]
Can you try macfix branch - https://github.com/hacksider/Deep-Live-Cam/tree/macfix

**Comment by siriuslan** [comment]
I do not have access to this branch, it gives me 404 @KRSHH

**Comment by KRSHH** [comment]
Check #119
