### ISSUE TITLE
MacOS 15.2 Run error after installation

### ISSUE THREAD

**Issue by CrusherStanley** [hacksider/Deep-Live-Cam#847]
Pull the project and use pip install --use-pep517 -r requirements.txt to install it, then run it and get an error. The following is a screenshot of the error. I checked ISSUES but didn't find a specific solution. I hope you can help.
<img width="1004" alt="截屏2024-12-23 22 15 30" src="https://github.com/user-attachments/assets/05f57f73-9bce-4279-81f4-40a629f47be1" />

**Comment by KRSHH** [comment]
Try macfix branch

**Comment by CrusherStanley** [comment]
> 尝试macfix分支

This works very well, thank you very much for your help

**Comment by CrusherStanley** [comment]
> Try macfix branch

This works very well, thank you very much for your help
