### ISSUE TITLE
Can't open tkinter

### ISSUE THREAD

**Issue by workerbto** [hacksider/Deep-Live-Cam#859]
Hi,

I'm trying to deploy deep-live-cam on linux but I get these errors (in requirments and pyhton.run) :

Thanks a lot

e/lib/python3.10/site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 7)) (2.9.0.post0)
Requirement already satisfied: imageio>=2.33 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (2.36.1)
Requirement already satisfied: tifffile>=2022.8.12 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (2024.12.12)
Requirement already satisfied: lazy-loader>=0.4 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (0.4)
Requirement already satisfied: google-auth<3,>=1.6.3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (2.37.0)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (3.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (2024.12.14)
Requirement already satisfied: qudida>=0.0.4 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from albumentations->insightface==0.7.3->-r requirements.txt (line 7)) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from albumentations->insightface==0.7.3->-r requirements.txt (line 7)) (4.10.0.84)
Requirement already satisfied: humanfriendly>=9.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from coloredlogs->onnxruntime-gpu==1.16.3->-r requirements.txt (line 17)) (10.0)
Requirement already satisfied: MarkupSafe>=2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from jinja2->torch==2.0.1+cu118->-r requirements.txt (line 12)) (3.0.2)
Requirement already satisfied: wcwidth in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from prettytable->insightface==0.7.3->-r requirements.txt (line 7)) (0.2.13)
Requirement already satisfied: joblib>=1.1.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from scikit-learn->insightface==0.7.3->-r requirements.txt (line 7)) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from scikit-learn->insightface==0.7.3->-r requirements.txt (line 7)) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from sympy->torch==2.0.1+cu118->-r requirements.txt (line 12)) (1.3.0)
Requirement already satisfied: platformdirs>=3.5.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from yapf->gfpgan==1.3.8->-r requirements.txt (line 22)) (4.3.6)
Requirement already satisfied: tomli>=2.0.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from yapf->gfpgan==1.3.8->-r requirements.txt (line 22)) (2.2.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from beautifulsoup4->gdown>=4.2.0->opennsfw2==0.10.2->-r requirements.txt (line 19)) (2.6)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from numba->facexlib>=0.2.5->gfpgan==1.3.8->-r requirements.txt (line 22)) (0.43.0)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests[socks]->gdown>=4.2.0->opennsfw2==0.10.2->-r requirements.txt (line 19)) (1.7.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow==2.12.1->-r requirements.txt (line 18)) (3.2.2)
Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Installing collected packages: typing-extensions, triton, torch
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.12.2
    Uninstalling typing_extensions-4.12.2:
      Successfully uninstalled typing_extensions-4.12.2
  Attempting uninstall: triton
    Found existing installation: triton 3.1.0
    Uninstalling triton-3.1.0:
      Successfully uninstalled triton-3.1.0
  Attempting uninstall: torch
    Found existing installation: torch 2.5.1
    Uninstalling torch-2.5.1:
      Successfully uninstalled torch-2.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.115.6 requires typing-extensions>=4.8.0, but you have typing-extensions 4.5.0 which is incompatible.
lightning 2.5.0rc0 requires torch<4.0,>=2.1.0, but you have torch 2.0.1+cu118 which is incompatible.
pydantic 2.10.4 requires typing-extensions>=4.12.2, but you have typing-extensions 4.5.0 which is incompatible.
pydantic-core 2.27.2 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
pytorch-lightning 2.5.0rc0 requires torch>=2.1.0, but you have torch 2.0.1+cu118 which is incompatible.
Successfully installed torch-2.0.1+cu118 triton-2.0.0 typing-extensions-4.5.0
⚡ main ~/Deep-Live-Cam python run.py
Downloading: 56.0kB [00:00, 793kB/s]                                                          
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/Deep-Live-Cam/run.py", line 6, in <module>
    core.run()
  File "/teamspace/studios/this_studio/Deep-Live-Cam/modules/core.py", line 256, in run
    window = ui.init(start, destroy)
  File "/teamspace/studios/this_studio/Deep-Live-Cam/modules/ui.py", line 83, in init
    ROOT = create_root(start, destroy)
  File "/teamspace/studios/this_studio/Deep-Live-Cam/modules/ui.py", line 142, in create_root
    root = ctk.CTk()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/customtkinter/windows/ctk_tk.py", line 40, in __init__
    CTK_PARENT_CLASS.__init__(self, **pop_from_dict_by_set(kwargs, self._valid_tk_constructor_arguments))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by KRSHH** [comment]
Follow the template, we can't solve without more info.
