### ISSUE TITLE
BLACK SQUARE

### ISSUE THREAD

**Issue by Loganius-II** [hacksider/Deep-Live-Cam#86]
My output is literally covered with a black square in the face. I followed installation steps, and models. And I didn't do the GPU acceleration, I just ran the run.py

![output](https://github.com/user-attachments/assets/6fa36b50-43ac-40ac-b7f3-151c9787bcf5)

**Comment by knewter** [comment]
same

**Comment by rafgonlop1** [comment]
same issue here!

**Comment by 0xtito** [comment]
had the same problem, I then use GPU acceleration with directml and it worked

**Comment by maxcurrent420** [comment]
So CPU unsupported?

**Comment by Loganius-II** [comment]
-takes out raspberry pi- "did somebody say linux"

**Comment by ANK789** [comment]
This problem should change onnxruntime version ,
if you without GPU ,run 
pip uninstall onnxruntime
pip uninstall onnxruntime-gpu
pip uninstall onnxruntime-directml
pip install onnxruntime-directml==1.15.1
python run.py --execution-provider cpu

**Comment by turbolego** [comment]
> This problem should change onnxruntime version , if you without GPU ,run pip uninstall onnxruntime pip uninstall onnxruntime-gpu pip uninstall onnxruntime-directml pip install onnxruntime-directml==1.15.1 python run.py --execution-provider cpu

Does not work on Intel based mac:

```
ERROR: Could not find a version that satisfies the requirement onnxruntime-directml==1.15.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime-directml==1.15.1
```

**Comment by Suffton** [comment]
> > This problem should change onnxruntime version , if you without GPU ,run pip uninstall onnxruntime pip uninstall onnxruntime-gpu pip uninstall onnxruntime-directml pip install onnxruntime-directml==1.15.1 python run.py --execution-provider cpu
> 
> Does not work on Intel based mac:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement onnxruntime-directml==1.15.1 (from versions: none)
> ERROR: No matching distribution found for onnxruntime-directml==1.15.1
> ```
> 
> This worked for me on Intel based MacOS:
> 
> ```
> pip uninstall onnxruntime
> pip install onnxruntime==1.16.3
> ```

you are my hero. It works.

**Comment by ozoc666** [comment]
> > > This problem should change onnxruntime version , if you without GPU ,run pip uninstall onnxruntime pip uninstall onnxruntime-gpu pip uninstall onnxruntime-directml pip install onnxruntime-directml==1.15.1 python run.py --execution-provider cpu
> > 
> > 
> > Does not work on Intel based mac:
> > ```
> > ERROR: Could not find a version that satisfies the requirement onnxruntime-directml==1.15.1 (from versions: none)
> > ERROR: No matching distribution found for onnxruntime-directml==1.15.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This worked for me on Intel based MacOS:
> > ```
> > pip uninstall onnxruntime
> > pip install onnxruntime==1.16.3
> > ```
> 
> you are my hero. It works.

Really? Did you succeed in the end? I have some problems, can you help me?  
i use ‘pip uninstall onnxruntime
pip install onnxruntime==1.16.3’   
then  i used ‘python3 run.py --execution-provider coreml  ’
but ‘run.py: error: argument --execution-provider: invalid choice: 'coreml' (choose from 'azure', 'cpu')’

**Comment by hman366** [comment]
youre goated

**Comment by 123zzw** [comment]
> onnxruntime-directml

I run this program in Ubuntu on Linux. I have a Tesla T4 graphics card. When onnxruntime-gpu==1.17.0, a black frame appears. When I update onnxruntime-gpu==1.21.0, the problem is solved.
