### ISSUE TITLE
q) whats a good camera for ubuntu?

### ISSUE THREAD

**Issue by johndpope** [hacksider/Deep-Live-Cam#89]

**Comment by loom4k** [comment]
Any standard webcam should be supported on Ubuntu? Simply make sure you install the necessary drivers (if applicable) and connect it correctly to your computer. Webcams are not restricted to a specific OS for usage.

**Comment by hacksider** [comment]
This is not an issue with the project so I'll be closing this down. Feel free to discuss anything on the discussion.
