### ISSUE TITLE
Support Python > 3.10

### ISSUE THREAD

**Issue by mohamedmansour** [hacksider/Deep-Live-Cam#90]
This is the error I got in `python 3.11.9`:

INFO: pip is looking at multiple versions of onnxruntime-gpu to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r .\requirements.txt (line 13), -r .\requirements.txt (line 17), -r .\requirements.txt (line 4), -r .\requirements.txt (line 5), -r .\requirements.txt (line 6) and numpy==1.23.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.23.5
    opencv-python 4.8.1.78 depends on numpy>=1.21.2; python_version >= "3.10"
    opencv-python 4.8.1.78 depends on numpy>=1.23.5; python_version >= "3.11"
    opencv-python 4.8.1.78 depends on numpy>=1.17.0; python_version >= "3.7"
    opencv-python 4.8.1.78 depends on numpy>=1.17.3; python_version >= "3.8"
    opencv-python 4.8.1.78 depends on numpy>=1.19.3; python_version >= "3.9"
    onnx 1.16.0 depends on numpy>=1.20
    insightface 0.7.3 depends on numpy
    torchvision 0.15.2+cu118 depends on numpy
    onnxruntime-gpu 1.18.0 depends on numpy>=1.26.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by mohamedmansour** [comment]
The fix is to bump `numpy` to `1.26.0`

**Comment by PlebeiusGaragicus** [comment]
Right - I can't get tkinter to work with python 3.10 but it works with 3.11.  Tkinter is such a pain to install for some reason.

```
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by matas0** [comment]
If you are on MacOS this worked for me: `brew install python-tk@3.10`.

**Comment by timothyjoh** [comment]
After the above brew install, I use `pyenv` and had to reinstall python with 

```shell
env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.10
```

That will get it to work with the brew installed modules

**Comment by matas0** [comment]
The issue was also discussed in here if you have any more problems: https://github.com/hacksider/Deep-Live-Cam/issues/38#issuecomment-2143474008

**Comment by astelmach01** [comment]
a PR should be opened for that

**Comment by sskorol** [comment]
If you use CUDA on Linux, the following versions worked for me:
```
--extra-index-url https://download.pytorch.org/whl/cu121

numpy
torch==2.1.2+cu121
torchvision==0.16.2+cu121
onnxruntime-gpu==1.16.3
tensorflow==2.12.1
```

**Comment by PlebeiusGaragicus** [comment]
> If you are on MacOS this worked for me: `brew install python-tk@3.10`.

worked!

**Comment by hacksider** [comment]
Thanks @sskorol , @matas0 , @timothyjoh  for helping!
