### ISSUE TITLE
Monetize this Repository 

### ISSUE THREAD

**Issue by repomarket** [hacksider/Deep-Live-Cam#91]
Hello, 

This repository is amazing and should be monetized. Use our platform RepoMarke.io if you wish to do so :) For any assistance reach out to us on Support@RepoMarket.io

**Comment by Laim** [comment]
You are scum of the earth

**Comment by QuartzWarrior** [comment]
love hour their website doesn't show

**Comment by hacksider** [comment]
Sorry, this is not an issue and I don't have any plans on doing it 😝
