### ISSUE TITLE
Can't find onnxruntime-silicon==1.13.1

### ISSUE THREAD

**Issue by 0xNoe** [hacksider/Deep-Live-Cam#94]
Hi,

Currently on MacOS (Silicon, M2 Max), it seems not possible to download (with pip at least) the 1.13.1 version of onnxruntime.

`ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon==1.13.1 (from versions: 1.14.1, 1.15.0, 1.16.0, 1.16.3)
ERROR: No matching distribution found for onnxruntime-silicon==1.13.1`

And, if I'm right, Deep-Live-Cam doesn't support more recent versions of onnxruntime, right ? So if that's the case, what could be a workaround ?

Thanks !

**Comment by matas0** [comment]
Which package is requiring `1.13.1`? As the requirements.txt specify `onnxruntime-silicon` as `1.16.3`.

**Comment by 0xNoe** [comment]
Well @matas0 I saw that on the repo, but you're right, on `requirements.txt ` itself it's written `1.16.3`, hence the confusion.

<img width="314" alt="image" src="https://github.com/user-attachments/assets/be255bd0-637f-47a8-ba27-4c7e3135a440">

But then I don't understand why I get this error when I click on the "Live" button :
`onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/noegiglio/Deep-Live-Cam/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.`

I thought it could've been because of the onnxruntime version, but I got confused then. Not the most technical guy here lmfao.

**Comment by 0xNoe** [comment]
It seems I'm just retarded, my browser rewrites the name of the files I download in a proper way, so it deleted the underscores in the file name of the model. For fuck sake.

**Comment by julywint007** [comment]
> Hi,
> 
> Currently on MacOS (Silicon, M2 Max), it seems not possible to download (with pip at least) the 1.13.1 version of onnxruntime.
> 
> `ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon==1.13.1 (from versions: 1.14.1, 1.15.0, 1.16.0, 1.16.3) ERROR: No matching distribution found for onnxruntime-silicon==1.13.1`
> 
> And, if I'm right, Deep-Live-Cam doesn't support more recent versions of onnxruntime, right ? So if that's the case, what could be a workaround ?
> 
> Thanks !

**Comment by julywint007** [comment]
> Run

**Comment by julywint007** [comment]
> Well @matas0 I saw that on the repo, but you're right, on `requirements.txt ` itself it's written `1.16.3`, hence the confusion.
> 
> <img alt="image" width="314" src="https://private-user-images.githubusercontent.com/69926570/356735180-be255bd0-637f-47a8-ba27-4c7e3135a440.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDQ4MTEsIm5iZiI6MTcyMzI0NDUxMSwicGF0aCI6Ii82OTkyNjU3MC8zNTY3MzUxODAtYmUyNTViZDAtNjM3Zi00N2E4LWJhMjctNGM3ZTMxMzVhNDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIzMDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZmRiYmIzMmU3Y2NiMWMyODdkMmE2YmU2NGMyMjAxODk2YTMwN2Y4YjNiZDVhOTEyMTVjNmQ5OTQ2ZDk5MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xhZXouiK15Gih8jHen2P_hY5ZczsrQebCgnvaXsQReo">
> But then I don't understand why I get this error when I click on the "Live" button : `onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/noegiglio/Deep-Live-Cam/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.`
> 
> I thought it could've been because of the onnxruntime version, but I got confused then. Not the most technical guy here lmfao.

**Comment by julywint007** [comment]
> Run

**Comment by julywint007** [comment]
> Well @matas0 I saw that on the repo, but you're right, on `requirements.txt ` itself it's written `1.16.3`, hence the confusion.
> 
> <img alt="image" width="314" src="https://private-user-images.githubusercontent.com/69926570/356735180-be255bd0-637f-47a8-ba27-4c7e3135a440.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDUxNDAsIm5iZiI6MTcyMzI0NDg0MCwicGF0aCI6Ii82OTkyNjU3MC8zNTY3MzUxODAtYmUyNTViZDAtNjM3Zi00N2E4LWJhMjctNGM3ZTMxMzVhNDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIzMDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OWEyMjEzMWM0NTA3ZWRiM2EwYTVlNWVlYTE1MTU4MmI4YzkyMWYzNDhhNGQyYzJjYjI1YTgxZTBjZDQ0YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MTgMOcT0R5ZBh9zjUIGHwC-6KJMwk2cO_gtdHGQVxn4">
> But then I don't understand why I get this error when I click on the "Live" button : `onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/noegiglio/Deep-Live-Cam/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.`
> 
> I thought it could've been because of the onnxruntime version, but I got confused then. Not the most technical guy here lmfao.

**Comment by julywint007** [comment]
> Run

**Comment by nwentling5** [comment]
> It seems I'm just retarded, my browser rewrites the name of the files I download in a proper way, so it deleted the underscores in the file name of the model. For fuck sake.

Ah. This was my issue! I am using the Arc Browser. Here is the output difference of the two:
![CleanShot 2024-08-17 at 11 55 21@2x](https://github.com/user-attachments/assets/640b20ef-ff4f-480a-ab78-4161d9d8abc1)

**Comment by Thilac13** [comment]
it mentions that only python 3.10 works and nothing else, when I tried in python 3.12 got the error, but when I moved to python 3.10 it worked
