### ISSUE TITLE
"dependencies..." kann syntaktisch an dieser Stelle nicht verarbeitet werden.

### ISSUE THREAD

**Issue by Outfluencer** [hacksider/Deep-Live-Cam#95]
C:\Users\Administrator\Desktop>setup_deep_live_cam.bat
Setting up your platform...
Installing Visual Studio 2022 Runtimes...
Es wurde kein Paket gefunden, das den Eingabekriterien entspricht.
Cloning into 'Deep-Live-Cam'...
remote: Enumerating objects: 190, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 190 (delta 45), reused 28 (delta 27), pack-reused 132
Receiving objects: 100% (190/190), 48.36 MiB | 12.72 MiB/s, done.
Resolving deltas: 100% (93/93), done.
Downloading models...
Ein Unterverzeichnis oder eine Datei mit dem Namen "models" existiert bereits.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: path.to.model
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: path.to.model
Creating a virtual environment...
Installing required Python packages...
Requirement already satisfied: pip in c:\users\administrator\desktop\deep-live-cam\venv\lib\site-packages (23.0.1)
Collecting pip
  Using cached pip-24.2-py3-none-any.whl (1.8 MB)
ERROR: To modify pip, please run the following command:
C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\Scripts\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow: markers 'sys_platform == "darwin"' don't match your environment
Collecting numpy==1.23.5
  Using cached numpy-1.23.5-cp310-cp310-win_amd64.whl (14.6 MB)
Collecting opencv-python==4.8.1.78
  Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl (38.1 MB)
Collecting onnx==1.16.0
  Using cached onnx-1.16.0-cp310-cp310-win_amd64.whl (14.4 MB)
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting psutil==5.9.8
  Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl (255 kB)
Collecting tk==0.1.0
  Using cached tk-0.1.0-py3-none-any.whl (3.9 kB)
Collecting customtkinter==5.2.2
  Using cached customtkinter-5.2.2-py3-none-any.whl (296 kB)
Collecting pillow==9.5.0
  Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting torch==2.0.1+cu118
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)
Collecting torchvision==0.15.2+cu118
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting onnxruntime-gpu==1.18.0
  Using cached onnxruntime_gpu-1.18.0-cp310-cp310-win_amd64.whl (157.7 MB)
Collecting tensorflow==2.12.1
  Using cached tensorflow-2.12.1-cp310-cp310-win_amd64.whl (1.9 kB)
Collecting opennsfw2==0.10.2
  Using cached opennsfw2-0.10.2-py3-none-any.whl (12 kB)
Collecting protobuf==4.23.2
  Using cached protobuf-4.23.2-cp310-abi3-win_amd64.whl (422 kB)
Collecting tqdm==4.66.4
  Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Collecting gfpgan==1.3.8
  Using cached gfpgan-1.3.8-py3-none-any.whl (52 kB)
Collecting prettytable
  Using cached prettytable-3.10.2-py3-none-any.whl (28 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.5.1-cp310-cp310-win_amd64.whl (11.0 MB)
Collecting albumentations
  Using cached albumentations-1.4.13-py3-none-any.whl (171 kB)
Collecting matplotlib
  Using cached matplotlib-3.9.1.post1-cp310-cp310-win_amd64.whl (8.0 MB)
Collecting scikit-image
  Using cached scikit_image-0.24.0-cp310-cp310-win_amd64.whl (12.9 MB)
Collecting requests
  Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Collecting easydict
  Using cached easydict-1.13-py3-none-any.whl (6.8 kB)
Collecting cython
  Using cached Cython-3.0.11-cp310-cp310-win_amd64.whl (2.8 MB)
Collecting scipy
  Using cached scipy-1.14.0-cp310-cp310-win_amd64.whl (44.8 MB)
Collecting darkdetect
  Using cached darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Collecting packaging
  Using cached packaging-24.1-py3-none-any.whl (53 kB)
Collecting jinja2
  Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Collecting filelock
  Using cached filelock-3.15.4-py3-none-any.whl (16 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting sympy
  Using cached sympy-1.13.1-py3-none-any.whl (6.2 MB)
Collecting networkx
  Using cached networkx-3.3-py3-none-any.whl (1.7 MB)
Collecting flatbuffers
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
Collecting coloredlogs
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting tensorflow-intel==2.12.1
  Using cached tensorflow_intel-2.12.1-cp310-cp310-win_amd64.whl (272.8 MB)
Collecting gdown>=4.2.0
  Using cached gdown-5.2.0-py3-none-any.whl (18 kB)
Collecting colorama
  Using cached https://download.pytorch.org/whl/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting facexlib>=0.2.5
  Downloading facexlib-0.3.0-py3-none-any.whl (59 kB)
     ---------------------------------------- 59.6/59.6 kB 3.3 MB/s eta 0:00:00
Collecting yapf
  Downloading yapf-0.40.2-py3-none-any.whl (254 kB)
     ---------------------------------------- 254.7/254.7 kB 16.3 MB/s eta 0:00:00
Collecting lmdb
  Downloading lmdb-1.5.1-cp310-cp310-win_amd64.whl (100 kB)
     ---------------------------------------- 100.3/100.3 kB ? eta 0:00:00
Collecting basicsr>=1.4.2
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-kvjrr61d\basicsr_721bae0e982c4546b38b7320f90c772d\setup.py", line 147, in <module>
          setup(
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\setuptools\__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
          return installer(requirement)
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\setuptools\installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\setuptools\wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\setuptools\wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\setuptools\wheel.py", line 139, in _convert_metadata
          _unpack_zipfile_obj(zf, destination_eggdir)
        File "C:\Users\Administrator\Desktop\Deep-Live-Cam\venv\lib\site-packages\setuptools\archive_util.py", line 129, in _unpack_zipfile_obj
          with open(target, 'wb') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-kvjrr61d\\basicsr_721bae0e982c4546b38b7320f90c772d\\.eggs\\torch-2.4.0-py3.10-win-amd64.egg\\torch\\include\\ATen\\ops\\_fake_quantize_per_tensor_affine_cachemask_tensor_qparams_compositeexplicitautograd_dispatch.h'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Setup complete. You can now run the application.

Choose the GPU Acceleration Option if applicable:
1. CUDA (Nvidia)
2. CoreML (Apple Silicon)
3. CoreML (Apple Legacy)
4. DirectML (Windows)
5. OpenVINO (Intel)
6. None
Enter your choice (1-6):
"dependencies..." kann syntaktisch an dieser Stelle nicht verarbeitet werden.

**Comment by kitty-elephant** [comment]
Same problem

**Comment by kitty-elephant** [comment]
Already solved by running commond in the powershell
 `New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force`
Details can see at [https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later](url)
