### ISSUE TITLE
ive been trying to get this running for 2 hours, this seems like its the last issue?

### ISSUE THREAD

**Issue by slyvenom1** [hacksider/Deep-Live-Cam#97]
i do have ffmpeg downloaded so i dont know what the issue is please help 

D:\Deep-Live-Cam-main\Deep-Live-Cam-main>python run.py
[DLC.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "D:\Deep-Live-Cam-main\Deep-Live-Cam-main\run.py", line 6, in <module>
    core.run()
  File "D:\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 237, in run
    if not pre_check():
  File "D:\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 158, in pre_check
    update_status('ffmpeg is not installed.')
  File "D:\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 166, in update_status
    ui.update_status(message)
  File "D:\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\ui.py", line 137, in update_status
    status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'

**Comment by anton-logiscale** [comment]
Do you have [ffmpeg](https://www.ffmpeg.org/download.html) installed? It's listed as a dependency in the readme.

**Comment by slyvenom1** [comment]
i installed it from a website and i did pip install ffmpeg , i also dont know the difference between dependency and installed im new

**Comment by anton-logiscale** [comment]
Dependencies are things that the application **depends** on, so it won't be able to run without it. If you read the README file you'll see that the dependencies are hyperlinks where you can see how to download them.

The only website you should be installing it from is [www.ffmpeg.org/download](https://www.ffmpeg.org/download.html). The only things that need to be installed via pip in python projects are the ones listed in the `requirements.txt` file. You do this automatically by opening the top-most folder of the project, called the root, in command prompt, and running `pip install -r requirements.txt`.

## If you installed ffmpeg from the official website and its still not working, try restarting your device before running the script again.

**Comment by slyvenom1** [comment]
i installed ffmpeg from the official site(even before but i did a reinstall) and still getting the same error its like it doesnt recognize the pathway tried reinstalling all the files re running alll the commands the steps just doesnt work for me idk 
ty for trying though 


\Deep-Live-Cam-main>python run.py


[DLC.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "C:\Users\anon\OneDrive\Desktop\Deep-Live-Cam-main\Deep-Live-Cam-main\run.py", line 6, in <module>
    core.run()
  File "C:\Users\anon\OneDrive\Desktop\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 237, in run
    if not pre_check():
  File "C:\Users\anon\OneDrive\Desktop\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 158, in pre_check
    update_status('ffmpeg is not installed.')
  File "C:\Users\anon\OneDrive\Desktop\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 166, in update_status
    ui.update_status(message)
  File "C:\Users\anon\OneDrive\Desktop\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\ui.py", line 137, in update_status
    status_label.configure(text=text)
AttributeError: 'NoneType' object has no attribute 'configure'

**Comment by julywint007** [comment]
> i do have ffmpeg downloaded so i dont know what the issue is please help
> 
> D:\Deep-Live-Cam-main\Deep-Live-Cam-main>python run.py [DLC.CORE] ffmpeg is not installed. Traceback (most recent call last): File "D:\Deep-Live-Cam-main\Deep-Live-Cam-main\run.py", line 6, in core.run() File "D:\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 237, in run if not pre_check(): File "D:\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 158, in pre_check update_status('ffmpeg is not installed.') File "D:\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\core.py", line 166, in update_status ui.update_status(message) File "D:\Deep-Live-Cam-main\Deep-Live-Cam-main\modules\ui.py", line 137, in update_status status_label.configure(text=text) AttributeError: 'NoneType' object has no attribute 'configure'
block

**Comment by julywint007** [comment]
block

**Comment by hacksider** [comment]
https://www.youtube.com/watch?v=OlNWCpFdVMA try that video instruction

**Comment by slyvenom1** [comment]
i did follow that tutorial last time, i tried again today and i get this error as shown below , how can i verify that the path is correct? also after retrying deep live cam still does not think i have ffmpeg installed

Which FFMPEG would you like to install?
- FFMPEG: 1
- FFMPEG-Shared: 2
- FFMPEG-Full [This has the most codecs]: 3
Enter a number: 3
Installing FFMPEG-Full...
choco : The term 'choco' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:78 char:9
+         choco upgrade ffmpeg-full -y
+         ~~~~~
    + CategoryInfo          : ObjectNotFound: (choco:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Done.
ffmpeg : The term 'ffmpeg' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:90 char:5
+     ffmpeg -version
+     ~~~~~~
    + CategoryInfo          : ObjectNotFound: (ffmpeg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


The above was returned after running 'ffmpeg -version'
You should now be able to use 'ffmpeg' anywhere on your computer.
To update in the future, run 'choco upgrade all -y'
PS C:\Windows\system32>

**Comment by slyvenom1** [comment]
ok it seems i have fixed it thanks everyone for the help, the issue was in my program data the "chocolatey" folder was empty, i deleted the folder and reinstalled choco and now the program runs. thanks ppl

**Comment by A-Monarch** [comment]
good day everyone. please i need help with my deeplivecam. i use Omen laptop corei9 RTX4070 GPU.
but its slow and lagging bc it runs with my CPU instead of my GPU... i've been at this for almost a week now. i need help to fix this guys please
