### ISSUE TITLE
White Screen on Apple Silicon - "Frame processor face_enhancer not found"

### ISSUE THREAD

**Issue by RealLukeMartin** [hacksider/Deep-Live-Cam#99]
**System**:
Chip: Apple M1
OS: Sonoma

**Python Version**: Python 3.10.14

**Logs**:
```
~/Development/Deep-Live-Cam (main) » python run.py --execution-provider coreml

Frame processor face_enhancer not found

DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
```

**Application**:

<img width="1166" alt="Screenshot 2024-08-09 at 5 56 23 PM" src="https://github.com/user-attachments/assets/86fc7526-81ea-42d0-a65d-6e7ce97ea6cd">

**Comment by RealLukeMartin** [comment]
Actually figured this out, had to install tcl-tk via brew, `brew install tcl-tk`

**Comment by ernoaapa** [comment]
Didn't help on Apple M2 :(

**Comment by mladendinev** [comment]
facing the same issue

**Comment by RealLukeMartin** [comment]
Unfortunately I had some more issues even after I got through this issue. The app started successfully but would the live view would black screen or wouldn't even pull up at times.

I saw this yesterday, which looks potentially promising for mac folks but haven't tried it out yet https://github.com/storizzi/Deep-Live-Cam-Mac-Installer
